### ISSUE TITLE
Support for non-random UI component ids for performance testing

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1001]
Now `jmix.ui.testMode` and `jmix.ui.performanceTestMode` are not used.

### Changes

`jmix.ui.performanceTestMode` - disables `xsrf-protection`, Vaadin generates the same ids for component connectors without considering current username and locale.

### QA

1. Download latest jmeter
2. According to the [article](https://forum.cuba-platform.com/t/performance-testing-for-web-ui-with-jmeter/5729) configure test plan. **Note** that latest Firefox does not proxy localhost. You can use your local IP when opening application in browser tab.
3. Record the simple test, e.g. login to app, open UserBrowse and logout.
4. Play test and make sure it works (you can add logging to screens).

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4664-213
IntelliJ version: IntelliJ IDEA 2021.3.3 (Ultimate Edition)
