### ISSUE TITLE
EntityLog isn't registered for objects that are modified in EntityChangedEvent

### ISSUE THREAD

**Issue by andreysubbotin** [jmix-framework/jmix#1004]
CUBA issue: https://github.com/cuba-platform/cuba/issues/3285

Minimal reproducible example

- Create `Company` entity with `name` and `description` attributes.
- Create listener for `EntityChangedEvent`
```
   @EventListener(phase = TransactionPhase.BEFORE_COMMIT)
    public void beforeCommit(EntityChangedEvent<Company> event) {

        Company company = dataManager.load(event.getEntityId())
                .fetchPlan(FetchPlan.BASE)
                .optional()
                .orElse(null);

        if (event.getType() == EntityChangedEvent.Type.CREATED) {
            if (company != null) {
                company.setDescription(company.getName());
                dataManager.save(company, companyLog);
            }
        }
    }
```
- Enable entity log for `Company` entity.
- Try to create `Company` entity. Fill only `name` attribute. 
- Check entity log for created entity.
- Expected behavior
The change log should contain `name` and `description` attributes.
- Actual behavior
The change log contain only `name` attribute.  The `description` attribute that was changed by listener, was not registered in EntityLog.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4687-222
IntelliJ version: IntelliJ IDEA 2022.2.3
