### ISSUE TITLE
User substitution views

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1006]

**Comment by KremnevDmitry** [comment]
Don't forget about https://github.com/jmix-framework/jmix/issues/2156

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5619-232
IntelliJ version: IntelliJ IDEA 2023.2.2 (Ultimate Edition)
