### ISSUE TITLE
Nested fetchPlan should include only explicitly specified properties

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix#1011]
Jmix version: 1.3.3
Jmix Studio plugin version: 1.3.6-213
IntelliJ version: IntelliJ IDEA 2022.2.1 (Ultimate Edition)

Project: 
[battleg.zip](https://github.com/jmix-framework/jmix/files/9585632/battleg.zip)

I have User and Department entities. User references Department.
Department has many attributes, I don't want to load them in the User browser, because I want to optimize my screen using accurate fetchPlan.

So I construct this:
![image](https://user-images.githubusercontent.com/6158807/190684057-c75daa65-4229-4ee3-b153-0fd46da77ed5.png)

But when I look at the SQL in the runtime, Department table is queried for all attributes:

```
SELECT LIMIT ? ?
t1.ID AS a1, t1.ACTIVE AS a2, t1.BIRTH_DATE AS a3, t1.EMAIL AS a4, t1.FIRST_NAME AS a5, t1.LAST_NAME AS a6, t1.TIME_ZONE_ID AS a7, t1.USERNAME AS a8, t1.VERSION AS a9, t1.DEPARTMENT_ID AS a10, 
t0.ID AS a11, t0.LOGO AS a12, t0.NAME AS a13, t0.PHONE_NUMBER AS a14, t0.SECURITY_LEVEL AS a15 
FROM USER_ t1 
LEFT OUTER JOIN DEPARTMENT t0 ON (t0.ID = t1.DEPARTMENT_ID)
ORDER BY t1.USERNAME
```

This is because the nested fetchPlan was constructed by the screen loader as "extends _base".

Workaround: specify "extends _instance_name" for the nested property.
So:
- I cannot construct nested view only with attributes that I want.
- And runtime behavior differs from what Studio's designer shows.

**Comment by knstvk** [comment]
Caused by jmix-projects/jmix-data#121
