### ISSUE TITLE
TwinColumn left and right column heights are different in Firefox

### ISSUE THREAD

**Issue by cad3nc3** [jmix-framework/jmix#1014]
If no item is selected heights are different in Firefox
![2022-09-19_15-43](https://user-images.githubusercontent.com/5371512/191011984-6f587fe7-85d9-4f26-9d54-da0a878d55ed.png)

... it is ok if we select any item
![2022-09-19_15-45](https://user-images.githubusercontent.com/5371512/191012011-66105941-4646-4c19-9f91-16db658fc697.png)

**Comment by glebfox** [comment]
No clear solution. Wait for a newer FireFox version.
