### ISSUE TITLE
PopupButton vertical positioning bug

### ISSUE THREAD

**Issue by fomich-artem** [jmix-framework/jmix#1015]
Popup calculates wrong vertical position (cuba/jmix behaviour):

https://demo.jmix.io/sampler/#main/1/sample?id=popupbutton-custom-layout

![изображение](https://user-images.githubusercontent.com/1716311/191044118-38b8a8d8-c710-4093-a38f-2735193c60d8.png)

![изображение](https://user-images.githubusercontent.com/1716311/191044216-064f309d-ac36-4089-901b-4985543be07e.png)

[cuba-jmix-popupbutton-positioning-bug.webm](https://user-images.githubusercontent.com/1716311/191044406-687ee8e7-300c-4731-a7ea-e2acb071ab47.webm)

**Comment by gorbunkov** [comment]
It's very difficult to solve this problem because it requires a reworking of Vaadin component client-side.
