### ISSUE TITLE
Current fetch plan generated for DataContext commit is not correct for new instance

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1026]
The following case leads to `IllegalStateException: Cannot get unfetched attribute ...` exception:
- Creating a new entity instance
- The entity has a reference which is null in the edit screen
- The reference is set by an entity listener when saving the root entity

In the test project, try to create "New entity" and not set the reference:
[IllegalStateException.zip](https://github.com/jmix-framework/jmix/files/9631553/IllegalStateException.zip)

The problem is gone if the fetch plan is specified explicitly:
```
@Install(target = Target.DATA_CONTEXT)
private Set<Object> commitDelegate(SaveContext saveContext) {
    saveContext.getFetchPlans().put(getEditedEntity(), getEditedEntityContainer().getFetchPlan());
    return dataManager.save(saveContext);
}
```

Originated from [forum](https://forum.jmix.ru/t/illegalstateexception-cannot-get-unfetched-attribute-name-from-detached-object/593).

**Comment by MaxKatyshev** [comment]
Jmix version: 1.3.999-SNAPSHOT - verified
