### ISSUE TITLE
FlowUI for Entity Log

### ISSUE THREAD

**Issue by GurSergey** [jmix-framework/jmix#1027]
audit UI port on FlowUI

**Comment by lovtsovaik** [comment]
Critical problems:

**Problem 1 - wrong table content**
Open View > Search > Look at the "Entity instance name" content
AR: entity names
ER: instance names


**Problem 2 - can't remove setup**
Open Setup > select record > Remove > Cancel
AR: There are two remove confirmation windows. Removing doesn't work if when using the first window.
ER: Remove works by one window


**Problem 3 - can't edit setup (sometimes)**
Open Setup > Create with selecting any attribute and mode > Save
Select created record > Edit with some changes > Save
AR: Unique constraint violation occured. Can't save setup
ER: Editing works

**Comment by GurSergey** [comment]
> Critical problems:
> 
> **Problem 1 - wrong table content** Open View > Search > Look at the "Entity instance name" content AR: entity names ER: instance names
> 
> **Problem 2 - can't remove setup** Open Setup > select record > Remove > Cancel AR: There are two remove confirmation windows. Removing doesn't work if when using the first window. ER: Remove works by one window
> 
> **Problem 3 - can't edit setup (sometimes)** Open Setup > Create with selecting any attribute and mode > Save Select created record > Edit with some changes > Save AR: Unique constraint violation occured. Can't save setup ER: Editing works

Fixed in tickets:
https://github.com/jmix-framework/jmix/issues/1127
https://github.com/jmix-framework/jmix/issues/1128
https://github.com/jmix-framework/jmix/issues/1129
