### ISSUE TITLE
DataGrid.select() should set item in connected data container

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1032]
See `data_components.CollectionContainerUsageTest#sort items`: now the code 

```
container.items = [order1, order2, order3]
dataGrid.select(order1)

then: "container's current item is the first"

container.items.indexOf(container.item) == 0
```

Leads to "java.lang.IllegalStateException: Current item is null"

After fixing, enable `CollectionContainerUsageTest` and `ContainerBindingTest#field and table with collection container`.

**Comment by glebfox** [comment]
Will be fixed in https://github.com/jmix-framework/jmix/issues/853
