### ISSUE TITLE
ExcelExportAction does not consider DataGrid columns visibility

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1043]
### Description

If DataGrid contains hidden columns, `ExcelExportAction` will export them too.

### Solution

~Rework export API and provide option for including/excluding hidden columns in Table and DataGrid. By default hidden columns should not be exported.~

The `ExcelExportAction` exports visible table/dataGrid as is. So it was decided to do not provide an option.

**Comment by lovtsovaik** [comment]
All type of tables was checked. 
ExcelExport action works correctly, but jsonExport still exports hidden columns
