### ISSUE TITLE
Implement MultiValueSelectAction

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#1044]
Same as io.jmix.ui.action.valuespicker.ValuesSelectAction

**Comment by KremnevDmitry** [comment]
For QA:
#1204 is required for `setUseComboBox(Boolean)` in MultiValueSelectActions (not working yet)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4944-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
