### ISSUE TITLE
Notification improvements

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1052]
### Closable

Too much padding between edge and close button

<img width="190" alt="Screenshot 2022-09-28 at 12 43 14" src="https://user-images.githubusercontent.com/6077149/192734825-4ede3dab-ea32-4a4d-8724-d0dc2eb5894e.png">
<img width="192" alt="Screenshot 2022-09-28 at 12 43 23" src="https://user-images.githubusercontent.com/6077149/192734836-43aae04f-ef04-4636-8f8a-2afbd1bcddb5.png">
<img width="1792" alt="Screenshot 2022-09-28 at 12 43 45" src="https://user-images.githubusercontent.com/6077149/192734840-dfa1a0ea-2441-42c1-8a1b-565c37c64ecd.png">
<img width="150" alt="Screenshot 2022-09-28 at 12 44 18" src="https://user-images.githubusercontent.com/6077149/192734841-22c3c00b-a574-48e0-9d52-e98061abb1af.png">
<img width="137" alt="Screenshot 2022-09-28 at 12 44 31" src="https://user-images.githubusercontent.com/6077149/192734831-a8593367-36b5-477f-9cab-cf1c3e28056e.png">
<img width="1792" alt="Screenshot 2022-09-28 at 12 44 26" src="https://user-images.githubusercontent.com/6077149/192734844-fe7687bc-ba3d-47ab-acb4-ceaa816d3b01.png">

### Contrast

`Notifications.Type.DEFAULT` notification with `NotificationVariant.LUMO_CONTRAST` is too big

<img width="1461" alt="Screenshot 2022-09-28 at 12 50 08" src="https://user-images.githubusercontent.com/6077149/192735090-e8096d9f-f812-40ee-9b23-7715b57d8a64.png">

### Primary

`Notifications.Type.DEFAULT` notification with `NotificationVariant.LUMO_PRIMARY` has incorrect title color

<img width="157" alt="Screenshot 2022-09-28 at 12 50 33" src="https://user-images.githubusercontent.com/6077149/192735443-14cbae77-0794-4fdf-a222-42e8b123f663.png">

**Comment by KremnevDmitry** [comment]
### Possible notification configurations for testing:

**By content:**
- With message
- With title and message

**By position:**
All from com.vaadin.flow.component.notification.Notification.Position

**By closeability:**
- Closeable
- Non closeable

**By type:**
- System
- Warning
- Other

**By theme variant:**
All from com.vaadin.flow.component.notification.NotificationVariant
