### ISSUE TITLE
Cannot give permissions on extended entity replacing parent

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1058]
- Create a composite project with add-on and app
- Create Foo entity in add-on
- Create ExtFoo entity in app, replacing Foo
- Create resource role which gives rights to all actions and attributes of Foo and ExtFoo

AR: a user with this role cannot access ExtFoo.

See the project attached:
[composite-project.zip](https://github.com/jmix-framework/jmix/files/9681653/composite-project.zip)

**Comment by gorbunkov** [comment]
For QA: 
Please check entity access and entity attribute access
Also it would be great to check how row-level policies work for extended entities. They seem to work fine, but let's ensure.

**Comment by MaxKatyshev** [comment]
Checked some cases, includes with row-level roles 
Examples from this project
[composite.zip](https://github.com/jmix-framework/jmix/files/9733248/composite.zip)

1.3.999-SNAPSHOT - verified
