### ISSUE TITLE
Refactor template snippets

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1072]
Move `jmix_flow_collectionAttributeTable.xml`, `jmix_flow_form.xml`, `jmix_flow_table.xml` to separate `snippet/flowui` directory and rename to `collectionAttributeTable.xml`, `form.xml`, `table.xml` respectively.

Make changes in Studio API for using these snippets from FlowUI templates.

**Comment by KremnevDmitry** [comment]
Related to Studio Issue: https://youtrack.haulmont.com/issue/JST-3294/Flow-UI-Refactor-template-snippets
