### ISSUE TITLE
Ability to use EntitySuggestionField in Filter and PropertyFilter components

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1076]

**Comment by tmalatinszki** [comment]
Is there any news around this one? CUBA does it pretty well using suggestion dropdown in the filter, it would be really nice to have the same possibility in JMIX.

**Comment by knstvk** [comment]
EntitySuggestionField could not be used in CUBA generic filter. Perhaps you mean usage of the EntityComboBox component with a dropdown. You can use it in Jmix filter by specifying the [jmix.ui.component.entity-field-type](https://docs.jmix.io/jmix/ui/app-properties.html#jmix.ui.component.entity-field-type) property for an entity.
