### ISSUE TITLE
project with MySQL and BPM failed with java.sql.SQLSyntaxErrorException: Table 'ACT_GE_PROPERTY' doesn't exist

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#1085]
Task bootRun failed when database type is MySQL and BPM addon added.

Tested on Jmix version 1.2.4 and 1.3.3 and SNAPSHOT with the same result.

1. Create new project with Jmix version 1.2.4
2. Change database type to MySQL (please use MySQL server mentioned here: https://youtrack.haulmont.com/articles/PLAT-A-27/Database-servers )
3. Recreate database using studio action
4. Add BPM addon from Marketplace
5. Update database using studio action (update will be successful)
6. Run the project

ER: The project started successfully

AR: projects fails with exception:
> Task :bootRun FAILED
> Caused by: org.flowable.common.engine.api.FlowableException: couldn't upgrade db schema: insert into ACT_GE_PROPERTY values ('common.schema.version', '6.2.0.0', 1)
> Caused by: java.sql.SQLSyntaxErrorException: Table 'ACT_GE_PROPERTY' doesn't exist

**Comment by konyashkina** [comment]
[Task bootRun FAILED.log](https://github.com/jmix-framework/jmix/files/9745382/Task.bootRun.FAILED.log)

**Comment by gorbunkov** [comment]
The problem is in the `nullDatabaseMeansCurrent` configuration property of MySQL connector.
If you add `&nullDatabaseMeansCurrent=true` to the connection params in Data Store settings window then everything should work.

See [Flowable forum](https://forum.flowable.org/t/unable-to-create-more-than-one-database-in-same-server-mysql/2911)

**Comment by konyashkina** [comment]
Re-tested on
Jmix version: 1.3.3
Jmix Studio plugin version: 1.3.7-213
IntelliJ version: IntelliJ IDEA 2021.3.3 (Community Edition)
with `&nullDatabaseMeansCurrent=true` the project started successfully.
