### ISSUE TITLE
"View route parameter" is empty when creating a view using "Entity detail view" template

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1086]
See studio ticket: https://youtrack.haulmont.com/issue/JST-3260/View-route-parameter-is-empty-when-creating-a-view-using-Entity-detail-view-template

The default value must be id.
The template has this property with valueTemplate="id" attribute:

<property caption="View route parameter"
          code="detailRouteParam"
          propertyType="STRING"
          advanced="true"
          required="true"
          valueTemplate="id"/>

Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4640-222
IntelliJ version: IntelliJ IDEA 2022.2 (Ultimate Edition)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4687-222
IntelliJ version: IntelliJ IDEA 2022.2.3 (Community Edition)

1. "Entity detail view" template - PASSED
2.  "Entity list and detail views" template - FAILED, the "Detail view route parameter" is empty: 
 
![template](https://user-images.githubusercontent.com/85500330/195345682-43bb4e84-6040-40bd-bf94-9c859a270f50.png)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4699-222
IntelliJ version: IntelliJ IDEA 2022.2.2 (Ultimate Edition)

 Detail view route parameter = "id"
