### ISSUE TITLE
DataGrid injected without generic

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1090]
Steps to reproduce:
1. Open any view controller
2. Click to "Inject" action
3. Select dataGrid
ER: DataGrid injected with generic
AR: DataGrid injected without generic

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4687-222
IntelliJ version: IntelliJ IDEA 2022.2.3 (Community Edition)
