### ISSUE TITLE
A large list of filters moves upward

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1094]
[forum.jmix.ru](https://forum.jmix.ru/t/ne-vidny-konfiguraczii-filtrov/630)

**env**: 
Jmix version: 1.3.3 and 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4685-222
IntelliJ version: IntelliJ IDEA 2022.2.2 (Community Edition)

**TC**: 
In the browse window, save multiple filters
not all filters fit in the screen

**AR**: The filter list is moved up

**ER**: The filter list should be expanded downward

![image](https://user-images.githubusercontent.com/114649487/195581061-8e3fd195-efe3-47ab-9a4c-4dbad52b1554.png)
![image](https://user-images.githubusercontent.com/114649487/195581890-c9cec1c9-115e-4998-95a3-2ee706a0b621.png)

**Comment by gorbunkov** [comment]
We can't do anything with long lists.
