### ISSUE TITLE
Get rid of hardcoded timezone in tests

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#1106]
#### Problem 
Some tests failed in the case of building Jmix on a computer with a timezone different from +04. 
E.g. `io.jmix.graphql.datafetcher.date.DateMutationTest#"should upsert time fields with seconds"`.
It happens because there are tests with hardcoded timezone, e.g. `12:21:10+04:00`.

#### Solution
Rework such tests to not use hardcoded timezone.

Please, check tests:
* `io.jmix.graphql.datafetcher.date.DateFilterTest`
* `io.jmix.graphql.datafetcher.date.DateMutationTest`
* `io.jmix.graphql.datafetcher.date.DateQueryTest`
* `io.jmix.graphql.schema.scalar.OffsetDateTimeScalarTest`
* `io.jmix.graphql.schema.scalar.OffsetTimeScalarTest`

Check also places where `+04` appears in string literals.

**Comment by MaxKatyshev** [comment]
I set **TZ=America/Sao_Paulo** in **Environment variables** and try to check tests, but I found another falling tests:
- io.jmix.graphql.datafetcher.date.DateMutationTest#should create entity with date types
Line problem:
`response.get('$.data.upsert_scr_DatatypesTestEntity.dateTimeAttr') == "2011-12-03T10:15:30"`

Other tests with timezone `+04` works is correctly

**Comment by MaxKatyshev** [comment]
All tests works is correctly
