### ISSUE TITLE
Alignment problem with valuepicker and entitypicker

### ISSUE THREAD

**Issue by GurSergey** [jmix-framework/jmix#1109]
Alignment problem with valuepicker and entitypicker. The problem is observed when using formlayout as parent container
<img width="1057" alt="Screenshot_20221018_120351" src="https://user-images.githubusercontent.com/17911008/196372597-df48b851-77fe-4b10-b157-eba4a8ec0e42.png">

**Comment by lovtsovaik** [comment]
For QA: on the screencast the Instance and Entity fields placed not on the one line
