### ISSUE TITLE
ClassCastException in PickerField.afterCommitOpenedEntity

### ISSUE THREAD

**Issue by fomich-artem** [jmix-framework/jmix#1114]
ClassCastException (class ...ListOptions cannot be cast to class ...EntityOptions) occurs in row:

https://github.com/jmix-framework/jmix/blob/280bee5371107da0ffde7aba3de099c220064e10/jmix-cuba/cuba/src/main/java/com/haulmont/cuba/gui/components/PickerField.java#L753

also reproduced in CUBA Platform 7.2

Required steps to reproduce:

- prepare field with call `pickerField.setOptionsList(<some-entity-list>);` for example: `employee.setOptionsList(Collections.singletonList(getItem().getEmployee()));`
- open an entity card thru the pickerField and save the card (Employee in the example above)

**Comment by Flaurite** [comment]
Hello, @fomich-artem!

For now, as a workaround you can use `setOptions()` method and pass `ListEntityOptions` object.

**Comment by lovtsovaik** [comment]
verified
