### ISSUE TITLE
SimplePagination doesn't adapt to RTL mode

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1115]
### Actual result
<img width="1525" alt="Screenshot 2022-10-19 at 13 36 44" src="https://user-images.githubusercontent.com/6077149/196659274-cd5edadc-f1dd-4115-b569-10fa16a3452a.png">

### Expected result
![image](https://user-images.githubusercontent.com/22093943/213973812-b205d3c2-28b1-41dc-a929-83769d7eb258.png)

### QA
To change RTL mode use the following code in the LoginView:
```
@Subscribe
public void onInit(InitEvent event) {
    initLocales();
    initDefaultCredentials();
    UI.getCurrent().setDirection(Direction.RIGHT_TO_LEFT);
}
```

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4903-223
IntelliJ version: IntelliJ IDEA 2022.3
