### ISSUE TITLE
Flowui Audit  wrong table content

### ISSUE THREAD

**Issue by GurSergey** [jmix-framework/jmix#1127]
Open View > Search > Look at the "Entity instance name" content
AR: entity names
ER: instance names
![image](https://user-images.githubusercontent.com/17911008/197499233-c4859901-63bc-4998-9ff8-5db56e02e039.png)

**Comment by lovtsovaik** [comment]
Basic case works (defined instance name on single attribute, or function using DATATYPE attributes). More complicated cases will be fixed later.
