### ISSUE TITLE
Refactor Quartz add-on to core and UI modules

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1130]
To be able to introduce FlowUI module.

**Comment by konyashkina** [comment]
ER: 
~~~ 
 implementation 'io.jmix.quartz:jmix-quartz-starter'
 implementation 'io.jmix.quartz:jmix-quartz-ui-starter'
~~~

Tested on 
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4920-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
