### ISSUE TITLE
Projects ViewControllersConfiguration must have precedence over addons

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1146]
It seems that currently there is no particular order, e.g. in the screenshot below the project configuration goes second to last:

<img width="641" alt="Screenshot 2022-10-28 at 18 32 00" src="https://user-images.githubusercontent.com/6077149/198647499-ba50b5d3-37fc-47a7-ae37-25f194d5d6ad.png">

**Comment by gorbunkov** [comment]
Probably relates to #1268
