### ISSUE TITLE
Extend BusinessCalendar API

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1151]
Consider adding the following methods to the `BusinessCalendar` interface:

* businessDayStartAfter
* businessDayStartBefore
* businessDayEndAfter
* businessDayEndBefore

See [forum topic](https://forum.jmix.io/t/business-calendar-expose-more-methods/1989)

**Comment by Gavrilov-Ivan** [comment]
Added new methods to io.jmix.businesscalendar.model.BusinessCalendar:

- `LocalDateTime getBusinessIntervalStartAfter(LocalDateTime dateTime)`: Returns a date-time of the next start of business interval relative to provided date-time. Always returns start-time of next interval.
- `LocalDateTime getBusinessIntervalStartBefore(LocalDateTime dateTime)`: Returns a date-time of the previous start of business interval relative to provided date-time. If initial date-time is within interval - returns start-time of this interval. If initial date-time is outside of interval or points exact at its start-time - returns start-time of previous interval.
- `LocalDateTime getBusinessIntervalEndAfter(LocalDateTime dateTime)`: Returns a date-time of the next end of business interval relative to provided date-time. If initial date-time is within interval - returns end-time of this interval. If initial date-time is outside of interval or points exact at its end-time - returns end-time of next interval.
- `LocalDateTime getBusinessIntervalEndBefore(LocalDateTime dateTime)`: Returns a date-time of the previous end of business interval relative to provided date-time. Always returns end-time of previous interval.

**Comment by MaxKatyshev** [comment]
_Jmix version: 1.5.0-RC2
Jmix Studio plugin version: 1.5.SNAPSHOT4965-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Community Edition)_

Incorrect display of dates when working schedule and holiday matches

sample project:
**[business-calendar-check.zip](https://github.com/jmix-framework/jmix/files/10834259/business-calendar-check.zip)**

**Steps:**
1. Create Business calendar where:
* Holidays = Type: Day of week, Value: Sunday (current day at the time of testing) 
* Working schedule = Day of week: Sunday, Business hours: 10:00 - 23:00 (current day at the time of testing)
2. Create entity with methods from current time (time of testing ≈ Sunday 21:00)

ER: 
<img width="509" alt="Снимок экрана 2023-02-26 в 21 09 18" src="https://user-images.githubusercontent.com/11402689/221425345-a0dcbf5c-0d3e-4c32-9364-1c97e363674d.png">

AR: 
<img width="519" alt="Снимок экрана 2023-02-26 в 21 07 53" src="https://user-images.githubusercontent.com/11402689/221425257-cf16ac71-b1e6-4902-b899-3a2812526bcb.png">

**Comment by Gavrilov-Ivan** [comment]
This case is exceptional and, actually, not correct - there are no working days at all.
So we can say this API works "correct" - it tries to find some working day utill it reaches emergency break on Quartz side.

This case should not be supported on configuration step - created new issue https://github.com/jmix-framework/jmix/issues/1461

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.0-RC2 - verified
