### ISSUE TITLE
Self field style "small" does not applied to the caption and icon

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1163]
### Steps to reproduce
1. Add textField with caption and icon to the screen, add "small" stylename:
```
<textField id="textField" caption="TextField" stylename="small" icon="GITHUB"/>
```
**ER**
![image](https://user-images.githubusercontent.com/22093943/199473191-a3f92058-7c1f-4289-ae31-105051dfcfa6.png)

**AR**
![image](https://user-images.githubusercontent.com/22093943/199473091-2047f3d8-ef0d-411a-87a5-40f12b09f016.png)

2. Second case with "inline-icon" style:
```
<textField id="textField" caption="TextField" icon="GITHUB" stylename="inline-icon small"/>
```
**ER**
![image](https://user-images.githubusercontent.com/22093943/199473965-c406bcde-b833-41ae-9d37-7005c81b6231.png)

**AR**
Icon is not aligned and caption does not change its font size.
![image](https://user-images.githubusercontent.com/22093943/199473722-2f8ca511-0af1-4245-8906-28e9dcab1fc1.png)

**Comment by gorbunkov** [comment]
Low priority
