### ISSUE TITLE
Specify column names more than once in entity designer

### ISSUE THREAD

**Issue by GoetzConsulting** [jmix-framework/jmix#1166]
Version 1.3.3, 1.4.0 (only these two were tested)

In the entity designer, only one relationship to another table can be created per column name. If a column name is specified more than once in the designer, the following errors occur.

From my point of view, it should be possible to reference columns more than once.

![grafik](https://user-images.githubusercontent.com/48909114/199652156-3e2ec2fe-8a40-4154-886d-f452c2390a39.png)

Where can I find the log mentioned?

**Comment by Gasloff** [comment]
Hi

Could you please provide small sample project with such relations?
