### ISSUE TITLE
Association between two entities without using primary key

### ISSUE THREAD

**Issue by GoetzConsulting** [jmix-framework/jmix#1167]
Version 1.3.3

In our project we want to create an association between two entities. In our case, none of the fields we want to connect is a primary key.

So we added the parameter `referencedColumnName `to the `@JoinColumn` annotation. The resulting Liquibase script includes a foreign key constraint but ignores the parameter `referencedColumnName `and still refers to the primary key of the table.

**Comment by Gasloff** [comment]
Hi

Thanks for your feedback.
The YouTrack [issue](https://youtrack.jmix.io/issue/JST-3486/Support-association-between-two-entities-without-using-primary-key) created for the problem described, so you can follow the progress.

I'm closing this issue as we use GitHub for framework related issues. And this one relates Jmix IntelliJ IDEA plugin.
