### ISSUE TITLE
User attribute of enum type cannot be used in JPQL policy

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1173]
- Create enum with string id, say UserGroup
- Add `userGroup` attribute of `UserGroup` type to `User` entity
- Create `Foo` entity with `createdByUser` attribute of `User` type
- Create a row-level role with JPQL policy for `Foo` like this:
    ```
    @JpqlRowLevelPolicy(entityClass = Foo.class, where = "{E}.createdByUser.userGroup = :current_user_userGroup")
    void foo();
    ```
- Assign the role to a user, login and open Foo browse.
- You will get the exception:
    ```
    IllegalArgumentException: You have attempted to set a value of type class com.company.demo.entity.UserGroup for parameter current_user_userGroup with expected type of class java.lang.String from query string select e from Foo e where e.createdByUser.userGroup = :current_user_userGroup.
    ```

The problem can be fixed if we extract enum id in `CurrentUserQueryParamValueProvider`:
```
Object value = ...
if (value instanceof EnumClass) {
    return ((EnumClass<?>) value).getId();
} else {
    return value;
}
```
But probably it should be done in io.jmix.eclipselink.impl.JmixEclipseLinkQuery#processParams for all providers.

**Comment by gorbunkov** [comment]
Spotbugs failed

**Comment by knstvk** [comment]
@GurSergey Why the issue is in the Done column but is not closed?
