### ISSUE TITLE
Wrong index column name for MTEN_TENANT table

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1178]
```java
@JmixEntity
@Table(name = "MTEN_TENANT", indexes = {
        @Index(name = "IDX_MTEN_TENANT_UNIQ_TENANT_ID", columnList = "USERNAME", unique = true),
        @Index(name = "IDX_MTEN_TENANT_UNIQ_NAME", columnList = "USERNAME", unique = true)
})
@Entity(name = "mten_Tenant")
public class Tenant {
```

Column  list is wrong. USERNAME column is defined twice.

**Comment by KremnevDmitry** [comment]
For QA: 
Index restriction for HSQLDB is not implemented at the DBMS level. Therefore, exclude HSQLDB from the test.

**Comment by rusiaikinat** [comment]
FlowUI
Index restriction for Oracle  is not implemented

**Comment by rusiaikinat** [comment]
env
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4954-223
IntelliJ version: IntelliJ IDEA 2022.3.1 (Ultimate Edition)

AR
1. Bug when creating a database

2. When deleting an addon, the entry remains in the changelog.xml
![image](https://user-images.githubusercontent.com/114649487/220163953-e4fa3e12-ead5-4d73-af00-20cf2d4fffae.png)

**Comment by KremnevDmitry** [comment]
Bug fixed for Oracle DB.

Verified:

- PostgreSQL
- MSSQL
- OracleDB
- ~~HSQLDB~~

**Comment by rusiaikinat** [comment]
Verified:

- MySql
- OracleDB
