### ISSUE TITLE
CurrentAuthentication.getUser() returns a user with empty authorities

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1183]
Caused by https://github.com/jmix-framework/jmix/issues/948

See [forum](https://forum.jmix.io/t/jmix-1-4-regression-on-method-getauthorities-of-userdetails/2138)

The workaround is to set the application property:

```
jmix.core.current-authentication-user-reload-enabled=false
```

**Comment by lovtsovaik** [comment]
verified
