### ISSUE TITLE
FlowUI Audit Addon Improvements

### ISSUE THREAD

**Issue by GurSergey** [jmix-framework/jmix#1189]
1. Add sorting by columns id, instance name (table 1); old value id, value id (table 2)
2. change the location of the Value ID column (3 in a row)
3. UUIDs do not fit in the table (make it possible to resize columns)
4. add seconds to date column (called when)
5. Some problem (null for empty attributes, the nested instance name is not displayed ) with composite Instance name, example like this:
`
@InstanceName 
@DependsOnProperties({"number", "owner", "year"}) 
public String getInstanceName() {
 return String.format("N: %s, %s year (%s)", number, year, owner); 
}`
6. False positives of the uniqueness constraint.
7. Apply changes button is not needed
8. Setup tab issue on mobile versions with sidebar for attrubutes of entity
9. (this works in the old UI as well) the case of creating two settings for one entity has not been processed.
10. On the View tab, large double values ​​are denoted by E, although they look normal on screens.
11. Add pagination for tables

**Comment by lovtsovaik** [comment]
The next fixes will be in #1292
