### ISSUE TITLE
Report index attributes are not saved when importing a report

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#1197]
From forum https://forum.jmix.ru/t/pri-importe-otcheta-ne-sohranyayutsya-indeksnye-atributy-otcheta/629/6 

Report index attributes are not saved when importing a report. 
If we open the imported report and save it, then it works fine.

[reports_import_export.zip](https://github.com/jmix-framework/jmix/files/10001164/reports_import_export.zip)

For QA:
Additionally check different report security scenarios - roles, screens, input parameters (https://github.com/jmix-projects/jmix-reports/issues/33).

**Comment by Gavrilov-Ivan** [comment]
Old way of filling index attributes is removed. They filled by ReportsPersistence API.
