### ISSUE TITLE
Implement Screen aware actions

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1198]
* Add `ScreenAction` interface
* Implement default screen actions like: **Commit**, **CommitAndClose**, **Close**, **Select**
* Still support legacy hard-coded handlers

**Comment by ikuchmin** [comment]
Add ability to control state of action during screen loading

**Comment by ikuchmin** [comment]
Actions on EditorScreen is defined by type doesn't support Action.AdjustWhenScreenReadOnly
