### ISSUE TITLE
Navigation isn't resumed after unsaved changes dialog action invoked

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1202]
Case:

1. Open a detail view, e.g. `UserDetailView`
2. Make changes
3. Click any menu item in the `SideMenu`
4. In the **unsaved changes** dialog choose either **Save** or **Don't save**, i.e. an option that assumes further navigation

AR:

Application doesn't navigate to the selected view form the side menu

ER:

Application navigates to the selected view form the side menu

**Comment by lovtsovaik** [comment]
Verified
Also, a little bug was found: #1290
