### ISSUE TITLE
Screen extension mechanism test request

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1203]
See: [doc](https://docs.jmix.io/jmix/modularity/extension.html#ui) for more detail (and probably this [doc](https://doc.cuba-platform.com/manual-7.2/screen_extension.html) for examples with `index`)
For QA:
Check that screen extension mechanism still works. Pay special attention to changing **Fetch Plans** using `index`.

**Comment by rusiaikinat** [comment]
Created issue: [Extended screen, when adding a new column, all the columns of the extended table are visible](https://youtrack.jmix.io/issue/JST-3476)
