### ISSUE TITLE
EntityComboBox with metaClass defined doesn't clear and select value by ClearAction and LookupAction

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1204]
Case:

1. Define an `entityComboBox` and define `metaClass` instead of `dataContainer` and `property`, e.g.:
```
<entityComboBox id="anotherCategoryField" metaClass="Category"
                itemsContainer="categoriesDc">
    <actions>
        <action id="entityLookup" type="entity_lookup"/>
        <action id="entityClear" type="entity_clear"/>
    </actions>
</entityComboBox>
```

2. Open a view
3. Select a value for `entityComboBox`
4. Invoke the Clear action

AR:

**Visually** a value is still selected (even though, java API returns `null`)

ER:

Value is cleared

**Comment by KremnevDmitry** [comment]
Can't reproduce on:
Vaadin: 23.3.0
Flow: 23.3.0
Java: Eclipse Adoptium 11.0.15
OS: amd64 Windows 10 10.0

Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT-223
IntelliJ version: IntelliJ IDEA 2022.3.1 (Community Edition)
