### ISSUE TITLE
Ability to choose data range in Grid Export Actions

### ISSUE THREAD

**Issue by devmix** [jmix-framework/jmix#1211]
From project to project, we are rewriting ExcelExportAction/ExcelExporter (classes for JMIX, same for Cuba 6.x, 7.x) action by adding the ability to export full data set, not only the visible data set on the screen. Exporting only the visible part of the data is often confusing for users, they expect all data (pages in a table/grid) to be exported.

The typical flow:
1. The user clicks the export button and sees a dialog box with next buttons [Visible] [All] [Cancel]
2. [Visible] - works as usually, exports only visible dataset
3. [All] - exports **all** dataset with next limitations:
   1. Uses current `LoadContext`, filter and sorting.
   2. Uses current columns set from the associated table/grid.
   3. _Optional_. Some columns can be expanded to a multiple columns, e.g. columns from the entity instance name `car:truck` (`{name: string, type: enum}`) can be expanded to two columns in the resulting Excel: `name`, `type`.
   4. The export operation is executed using batches with a series of database queries (`limit` parameter is configurable via application.properties):
      1. `offset` + `limit` - slow for PostgreSQL.
      2. filter by column (`where column > :prevValue`) + `limit` - fast for PostrreSQL.
   5. The maximum number of exported rows is limited by the Excel specification.
   6. Before JMIX, we used `org.apache.poi.xssf.streaming` to avoid storing the resulting Excel in memory. Not sure if this is possible for `docx4j`.

I believe that this behavior can be configurable via `application.properties` or via action options.

**Comment by gorbunkov** [comment]
The similar issue: https://github.com/jmix-framework/jmix/issues/363

**Comment by gorbunkov** [comment]
For QA: see the comment in [PR](https://github.com/jmix-framework/jmix/pull/1428)

**Comment by gorbunkov** [comment]
Application properties have been renamed. See https://github.com/jmix-framework/jmix/issues/1452
