### ISSUE TITLE
Support explicit property reference for data vector source for Maps add-on

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#1216]
Currently the way how the vector layer of the maps add-on is configured to use a particular property of an entity is by using the `io.jmix.maps.Geometry` annotation on the property. In the XML / `VectorLayer` UI class it is not possible to explicitly declare which property to use. 

```xml
                <maps:geoMap id="customersMap">
                    <maps:layers selectedLayer="tiles">
                        <maps:tile id="tiles" tileProvider="map_OpenStreetMap"/>
                        <maps:vector id="customersLayer" dataContainer="customersDc" />
                    </maps:layers>
                </maps:geoMap>
```

This approach is not very obvious since it is implicit and also it is different on how properties are bound to a UI component in other parts of Jmix like input fields: `<textField id="firstNameField" dataContainer="customerDc" property="firstName"/>`.

Also when referencing e.g. a property of an embedded entity, the way how it works is currently not documented and explicit. This is possible by using a transient property and putting the `@Geometry` annotation on the getter like this:

```java
@Entity
class Customer {

    @EmbeddedParameters(nullAllowed = false)
    @Embedded
    @AttributeOverrides({
            @AttributeOverride(name = "street", column = @Column(name = "ADDRESS_STREET")),
            @AttributeOverride(name = "postCode", column = @Column(name = "ADDRESS_POST_CODE")),
            @AttributeOverride(name = "city", column = @Column(name = "ADDRESS_CITY")),
            @AttributeOverride(name = "position", column = @Column(name = "ADDRESS_POSITION_"))
    })
    private Address address;
    
    @Geometry
    @JmixProperty
    public Point getGeometry() {
        return address != null? address.getPosition() : null;
    }
}
```

Proposal:

Additionally to the `@Geometry` annotation, it should be possible or even required (to enforce conformity with other areas in the Jmix UI data binding) to explicitly set the property on the vector layer as well:

`<maps:vector id="customersLayer" dataContainer="customersDc" property="position" />`

The property should also support a property path like `<maps:vector id="customersFromOrderLayer" dataContainer="ordersDc" property="customer.position" />` as well as transient properties.

**Comment by Flaurite** [comment]
### Changes
Added `property` attribute to the `dataVectorSource` element. The `property` can take both simple property and property path.
For instance:
```
<maps:vector id="vectorLayer">
    <maps:dataVectorSource dataContainer="shopsDc"
                           property="coordinate"/>
</maps:vector>
```
```
<maps:vector id="vectorLayer">
    <maps:dataVectorSource dataContainer="ordersDc"
                           property="customer.address.point"/>
</maps:vector>
```

Added `getMetaPropertyPath()` method to `DataVectorSourceItems`. It returns a meta property path of the specified geometry property from which will be displayed geo-objects.

### Deprecated
- `@Geometry` annotation is deprecated. Use `property` attribute in `dataVectorSource` element.
- `GeometryPropertiesResolver` and its implementation `GeometryPropertiesResolverImpl` are deprecated. There is no appropriate alternatives. Use `property` attribute in `dataVectorSource` element and `DataVectorSourceItems#getMetaPropertyPath()`
