### ISSUE TITLE
Capability to @Install DataGrid inline editor handlers

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1228]
* setDefaultComponentStatusHandler
* setValidationErrorsHandler
* ~~Generation of column editor components (setColumnEditorComponent)~~ (can't be implemented now)

**Comment by KremnevDmitry** [comment]
The new character `.@` will be used to assign the `@Install` method to an internal field in the DataGrid

Example: 
```
    @Install(to = "usersTable.@editor", subject = "defaultComponentStatusHandler")
    private void usersTableEditorDefaultComponentStatusHandler(SupportsStatusChangeHandler.StatusContext<?> context) {
        // do logic
    }
```

```
    @Install(to = "usersTable.@editor", subject = "validationErrorsHandler")
    private void usersTableEditorDefaultComponentStatusHandler(ValidationErrors context) {
        // do logic
    }
```

**Comment by KremnevDmitry** [comment]
Linked Studio `[Issue](https://youtrack.haulmont.com/issue/JST-3611/Add-ability-to-generate-DataGrids-editor-handlers-in-view-controller)`

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.0-RC1 - verified
