### ISSUE TITLE
Improve layout for long attribute names in the generic filter

### ISSUE THREAD

**Issue by devmix** [jmix-framework/jmix#1234]
The length of localized entity attribute names sometimes differs dramatically and breaks the filter fields layout. So we need some solution to show these attributes correctly even if they are too long.

One of the solutions is to use `maxLength` attribute on the filter to limit max displayed text (like this [Maximum Text Length](https://docs.jmix.io/jmix/ui/vcl/components/table.html#column-max-text-length)). May be as attribute for `<filter/>` tag.

**Example**
![image](https://user-images.githubusercontent.com/4885297/204279796-277fea83-68dc-4242-a841-5a38558c2ffa.png)

----

### Changes
Added new `captionWidth` attribute:
```
<filter id="filter"
        captionWidth="50px"
        ...>
```
If `captionWidth` attribute is set filter will add tooltip with description to a caption label.

### QA
1) Check property filter condition
2) Check JPQL filter condition
3) Check FTS filter condition. To use FTS condition in filter search dependencies to `build.gradle`:
```
implementation 'io.jmix.search:jmix-search-starter'
implementation 'io.jmix.search:jmix-search-ui-starter'
```
4) Also check that that tooltip is shown when the cursor is on a label.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.0-RC1
Jmix Studio plugin version: 1.5.SNAPSHOT4950-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
