### ISSUE TITLE
Generic service for user notifications sent from background processes

### ISSUE THREAD

**Issue by devmix** [jmix-framework/jmix#1235]
**Problem**
Often in different projects, we need to somehow notify the user about the events of background processes. This means that this is not a reactio on the user action (e.g. button click and commit notification), but a notification from a background process about a new email, password expiration, a BPMS task assigned, etc.
Now we implement such a service every time for the project, because we need to override the platform beans for different platform versions.

**Possible solution**
Implement some kind of global `@Subscribe` listener for the screen/view/fragment (e.g. main-screen), that can catch broadcast messages if that screen/view/fragment is visible in the browser and user session is active.

**Examples**
That can be found in the internal components project: `message-center`. We have use `@EventListener` for that instead `@Subscribe`.
- MessageEventsListener - catches background events and sends generic notifications, user events (background event can have recipient information - login) to the screens via UiEventsMulticaster.
- UserMessagesIconFragment - catches user events.

**Comment by yuriy-khrebtov** [comment]
New `ClusterApplicationEvent` and `ClusterApplicationEventPublisher` were introduced. The publisher allows to send custom application events derived from `ClusterApplicationEvent` to all app instances in a cluster. When an application is a single-instance one the events will be sent only to that instance.

Also new `public void publishEventForUsers(ApplicationEvent event, @Nullable Collection<String> usernames)` was implemented in `UiEventPublisher` bean which allows to publish any application events to UIs of users specified. It uses `ClusterApplicationEventPublisher` under the hood so publishing in a cluster is also supported. To subscribe to such events in a view we can add some event listener in the view:
```
    @EventListener
    public void onTestEvent(TestEvent testEvent) {
        notifications.show("Received test event");
    }
```

**Comment by rusiaikinat** [comment]
The changes do not affect the Notification addon
Jmix version: 2.2.999-SNAPSHOT
