### ISSUE TITLE
PopupButton with too many items don't fit on the screen

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1236]
If PopupButton contains too many items to display them below of the component, it displays them above, but in certain situations that makes worse:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/6077149/204301030-108dad80-e28f-4686-8081-89f092b51434.png)

Required back port to CUBA

**Comment by gorbunkov** [comment]
Relates to #1094

**Comment by gorbunkov** [comment]
Requires fixes in client side. We have no clear solution yet. Do not do long lists.
