### ISSUE TITLE
Attempting to save an entity in `BeforeInsertEntityListener` results in StackOverflowError

### ISSUE THREAD

**Issue by devmix** [jmix-framework/jmix#1238]
Problem description in the topic

Sample test in the attached  project: `com.company.listenerso.ListenerSOTest`

[ListenerSO.zip](https://github.com/jmix-framework/jmix/files/10109953/ListenerSO.zip)

**Comment by knstvk** [comment]
The test passes for me.

Anyway, some recommendations:
- Do not use old listeners from `io.jmix.data.listener` working with managed instances at all. They are not documented in Jmix and marked as `@Experimental`.
- If you absolutely need those listeners, do not use DataManager there, only EntityManager.
