### ISSUE TITLE
EntitySuggestionField does not show suggestions when Row-Level Role with Session attribute is used

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#1239]
**Scenario:**

Given we want to filter for Customers via a `EntitySuggestionField`. The customer entity has an attribute `associatedResion` which points to a `Region` entity. 
Additionally there is a row-level role in place that allows only to display the customers where the associated region is matching the associated region that is set via session attributes:

```java
@RowLevelRole(name = "Show Only Associated Regions Data", code = "show-only-associated-regions-data")
public interface ShowOnlyAssociatedRegionsDataRole {

    @JpqlRowLevelPolicy(entityClass = Customer.class, where = "{E}.associatedRegion in :session_associatedRegions")
    void customersFromAssociatedRegionsOfTheEmployee();
}
``` 

**Expected Result:**
When using the EntitySuggestionField in the UI for a user that has the role applied, the sub-list of users are shown where the associated region is matching the one from the session attribute.

**Actual Result:**
When using the EntitySuggestionField in the UI for a user that has the role applied, no results will be shown. Instead a warning message in the logs appears:
```
i.j.d.i.SessionQueryParamValueProvider   : Unable to get session attribute session_associatedRegions: org.springframework.beans.factory.support.ScopeNotActiveException: Error creating bean with name 'core_SessionData': Scope 'session' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
```

**Comment by gorbunkov** [comment]
The problem here is that current session attributes implementation stores values in HttpSession. The `EntitySuggestionField` component executes queries in a background task that starts a new thread. That new thread doesn't have access to web request and to HttpSession, so it can't get session attributes that are retrieved by session-scoped `SessionData` bean.
