### ISSUE TITLE
FlowUI for Quartz add-on

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1241]
The following starters must be added to the `build.gradle`:

```
implementation 'io.jmix.quartz:jmix-quartz-starter'
implementation 'io.jmix.quartz:jmix-quartz-flowui-starter'
```

**Comment by konyashkina** [comment]
Tested, **failed**
_Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4944-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)_

**Steps:** 
1. Add dependencies to build.gradle 
```
 implementation 'io.jmix.quartz:jmix-quartz-starter'
 implementation 'io.jmix.quartz:jmix-quartz-ui-starter'
```
2. Load gradle changes
3. Run app. 

**AR:** Application run failed  

[Application run failed-1241.log](https://github.com/jmix-framework/jmix/files/10753021/Application.run.failed-1241.log)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.0-RC1
Jmix Studio plugin version: 1.5.SNAPSHOT4950-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)

1. Quartz add-on works fine with dependencies 
 ```
   implementation 'io.jmix.quartz:jmix-quartz-starter'
   implementation 'io.jmix.quartz:jmix-quartz-flowui-starter'
```
2. The dialog window for new/edit Job is too large, extends beyond the application window.

![FlowUI-Q-newJob](https://user-images.githubusercontent.com/85500330/220290947-98b38cc3-b580-4278-b30a-ade5ce9d25ca.png)
![FlowUI-Q-Job](https://user-images.githubusercontent.com/85500330/220290972-e75f7a53-cba0-4094-a245-c1995be2416d.png)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.0-RC2 
PASSED
