### ISSUE TITLE
Optional notification about closing browser tab

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1243]
To prevent loss of entered data.

#### Flow UI

* In the project template the `frontend/index.html` file now contains `<script type="text/javascript">` in the page `head` that creates a  global function that can be used to prevent browser tab from closing. 
* Implemented `WebBrowserTools` - static helper that makes it easy to subscribe to the browser's 'onbeforeunload' event
* `StandardDetailView` by default prevent browser tab closing. This can be changes by `setPreventBrowserTabClosing()` (must be changed before `ReadyEvent` is fired)

#### Classic UI

* Implemented `BootstrapListener` that adds `<script type="text/javascript">` to the page `head`. This script creates a  global function that can be used to prevent browser tab from closing. 
* Added methods to `WebBrowserTools` bean that make it easy to subscribe to the browser's 'onbeforeunload' event
* No default usage

### For QA:

Add the following inside the `head` tag in the `index.html` file:
```
<script type="text/javascript">
  jmixBeforeUnloadListener = (event) => {
    event.preventDefault();
    return (event.returnValue = "");
  };
</script>
```

**Comment by lovtsovaik** [comment]
For QA: test only FlowUI part

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5160-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
