### ISSUE TITLE
Search in main menu

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1244]

**Comment by yuriy-khrebtov** [comment]
New MenuSearchField component was implemented. The component filters and expands menu items when its value is changed. We can add it in xml descriptor:
```
<menuSearchField id="menuSearchField" menu="menu" placeholder="Type here"/>
```
or using Java:
```
    @Subscribe
    private void onInit(InitEvent initEvent) {
        MenuSearchField searchField = uiComponents.create(MenuSearchField.class);

        searchField.setMenuItemProvider(menu.getMenuItemProvider());
        navigation.addComponentAsFirst(searchField);
    }
```
Also MenuItemProvider interface and its default implementation were introduced to facilitate menu item loading management.

**Comment by glebfox** [comment]
@yuriy-khrebtov if there is no existing suitable Studio icon for this component, please create a design issue and link here. This issue cannot be resolved until component is supported both by Studio and Framework.

**Comment by yuriy-khrebtov** [comment]
Created design issue for new component icon: https://youtrack.haulmont.com/issue/DESIGN-346/Ikonka-MenuSearchField-dlya-plagina-Jmix

**Comment by MaxKatyshev** [comment]
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6046-233
IntelliJ version: IntelliJ IDEA 2023.3.2 (Community Edition)
verified
