### ISSUE TITLE
LinkCellClickListener should throw EntityAccessException

### ISSUE THREAD

**Issue by Yarik2308** [jmix-framework/jmix#1255]
Table columns can have [link](https://docs.jmix.ru/jmix/ui/vcl/components/table.html#link-to-edit-screen) property = "true"
if user do not have access to entity then `java.lang.IllegalStateException: No results` is thrown 
perhaps [LinkCellClickListener#loadEntity](https://github.com/jmix-framework/jmix/blob/212b03171bdb552293602fa0a8e83e5c1a9b0006/jmix-ui/ui/src/main/java/io/jmix/ui/component/table/LinkCellClickListener.java#L113) should throw `EntityAccessException` if entity not found

**Comment by gorbunkov** [comment]
@Yarik2308 Could you please clarify what do you mean by "user do not have access to entity"? Row-level constraint? If so then how has the user seen the entity instance in the entities list when they clicked the link column?

**Comment by Yarik2308** [comment]
@gorbunkov well... the easiest way to reproduce the problem is to create 2 entities 
`Test1` and `Test2`, `Test2` assosiate to `Test1`. User has `ResourceLevel` access to **all** fields of `Test2`, so in table he can see all columns include `Test1`, but he do not have acess to read `Test1` (`ResourceLevel`).  So when user clicks link to `Test1` entity exeption falls.
