### ISSUE TITLE
DataGrid does not respect entity attribute policy

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1262]
- Create new app with FlowUI
- Create role:
    ```
    @ResourceRole(name = "test", code = "test")
    public interface TestRole {
        @EntityAttributePolicy(entityClass = User.class, attributes = {"id", "version", "username", "password", "firstName", "lastName", "active", "timeZoneId"}, action = EntityAttributePolicyAction.MODIFY)
        @EntityPolicy(entityClass = User.class, actions = EntityPolicyAction.ALL)
        void user();
    
        @MenuPolicy(menuIds = "User.list")
        @ViewPolicy(viewIds = {"User.list", "User.detail"})
        void screens();
    }
    ```
- Start the app, create a user, assign the role to the user
- Login with the user, open Users list view

ER: `email` column is not shown
AR: `email` column is shown

### QA

1. Check DataGrid
2. Check TreeDataGrid
3. Also check that `TreeDataGrid` has a hierarchy column when View is opened. Try to use attribute in XML `hierachyColumn`, it should work.

**Comment by rusiaikinat** [comment]
**env**
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4863-222
IntelliJ version: IntelliJ IDEA 2022.2.4 (Ultimate Edition)

**TC**
Open User list
Open screen for Role assignment for any user
Look at the button `Add+`

**AR**
The button is not active. There is no way to assign a role 

**ER**
When opening the screen `Role assignment`, the button must be active
