### ISSUE TITLE
Ability to sort by multiple columns in DataGrid

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1265]
### FlowUI:

**3 new XML attributes:**
multiSort (boolean): enable or disable sorting
multiSortOnShiftClickOnly (boolean): enables multiple sorting only when the shift key is pressed
multiSortPriority (enum): the logic for adding new columns to sorting

**Comment by KremnevDmitry** [comment]
### For QA:
**How to test**

1. FlowUI: 
    - Set the `multisort` attribute for the DataGrid in the XML
    - Open the entity-list view
    - Click on column headers
    Multi sorting should be added
    - Set the `multiSortPriority` attribute to APPEND for the DataGrid
    - The order in which columns are added to the sort should change
    - Set the `multiSortOnShiftClickOnly` attribute to `true`
    - Multi sorting should only be available with shift-click

2. ClassicUI:
    - Open the browser screen
    - Single sorting should be available by clicking on the column header.
    - Multi sorting should only be available with shift-click

**Comment by konyashkina** [comment]
Tested on

- [X] 2.1-SNAPSHOT
- [X] 1.6-SNAPSHOT
