### ISSUE TITLE
Incorrect sorting of dependencies when registering screens

### ISSUE THREAD

**Issue by Serega3611** [jmix-framework/jmix#1268]
Precondition: multimodule project

At the time of installing the list of controller configurations in io.sys.ui.WindowConfig#set Configuration the io.jmix.ui.sys.UiControllersConfigurationSorter#sort method is called, which outputs an incorrectly sorted list.

Example: there is a custom bpm module that depends on the standard bpm module.
As a result, after sorting the configurations, it happens that the base module is LOCATED AFTER the dependent -> all screens that are overridden in the dependent module are overwritten by the base ones.

Before sorting:
![изображение](https://user-images.githubusercontent.com/43417686/205842286-684086d4-afc1-409d-92e9-25f0bf4531e1.png)

After sorting:
![изображение](https://user-images.githubusercontent.com/43417686/205842629-36ba8fc4-36e4-4035-85fa-b9ec8451ed90.png)

Dependencies in the custom module:
build.gradle of the module
![изображение](https://user-images.githubusercontent.com/43417686/205843050-148c46bb-a413-4509-973d-86fb066adea9.png)

Availability 
**@JmixModule(depends On = {..., "BpmUiConfiguration.class "})**
in the configuration file of the custom module - does not play any role - the problem is reproduced both with the indication of this dependency and without it.

**Comment by knstvk** [comment]
Does it happen when the application starts or in tests?

**Comment by Serega3611** [comment]
At the start of the application. I didn 't check it in the tests
