### ISSUE TITLE
When forming a long row, the height of the cell is not recalculated

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1269]
[forum issue](https://forum.jmix.ru/t/problema-v-perenose-strok-v-sformirovannyh-otchetah/689)

**env**
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.1-223
IntelliJ version: IntelliJ IDEA 2022.3 (Community Edition)

**TC**
Create Entity and add string attribute
Add add-on Reports
Run project
Create new instance of the entity with a long string
Create report (xlsx) for Entity
Run report for Entity

**AR**

- The field in the report does not adjust to the length of the line

![image](https://user-images.githubusercontent.com/114649487/205853851-5d5a0acd-f91e-44df-b95c-b33bb65ab873.png)

**ER**
If the row does not fit into a single-line cell, then the cell must be multi-line. All text must appear in the cell.

### QA notes
To activate a row height calculation in manually created XLSX templates, it is required to add a named region with the name starting with `hint_rowAutoHeight` and set the range where a row height calculation should be applied. For XLSX reports created from the wizard, this named range is added automatically for each configured report region.

**Comment by fulviosuperga** [comment]
Hi all, 

any news about this issue?

Thanks.
F.

**Comment by knstvk** [comment]
Hi @fulviosuperga 
Unfortunately the problem has no simple solution.
It's on our todo list and we'll start working on it in the near future.

**Comment by rusiaikinat** [comment]
Libre office
![Image](https://github.com/jmix-framework/jmix/assets/114649487/1e14a246-4833-41cf-a0a9-bb4125bfc8ac)



Microsoft office
![Image](https://github.com/jmix-framework/jmix/assets/114649487/22d66dad-0671-4741-86da-f450dcc1e0f0)

**Comment by rusiaikinat** [comment]
Microsoft office 2019
![image](https://github.com/jmix-framework/jmix/assets/114649487/bc776852-0f76-4b66-9aad-6fedf1c5f07d)

**Comment by fulviosuperga** [comment]
Well done guys!

Do you think it will available with next JMix version 1.6 ?

Thanks.
F.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6407-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6409-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

Test excel reports on short cells and on more than 700 symbols cells. Cells' height were recalculated – Ok.

![image](https://github.com/jmix-framework/jmix/assets/158277660/208d1432-5813-43ec-82ec-d293d43b01fb)
