### ISSUE TITLE
Unnecessary exclude property and missing enable property for screenSettings component in Component Inspector

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1279]
**Steps:**

1. Open descriptor
2. Add screenSettings in facets-> add components and open Component Inspector

_ER: "exclude" is absent; "enable" is here
AR: "enable" is absent; "exclude" is here_

Also see studio ticket: https://youtrack.jmix.io/issue/JST-3335/Unnecessary-exclude-property-and-missing-enable-property-for-screenSettings-component-in-Component-Inspector

**Comment by MaxKatyshev** [comment]
Jmix version: 1.4.999-SNAPSHOT - verified
