### ISSUE TITLE
Buttons are not visible on the Dashboard editor screen

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1280]
**env**
Jmix version: 1.4.1
Jmix Studio plugin version: 1.4.SNAPSHOT7-223
IntelliJ version: IntelliJ IDEA 2022.3 (Community Edition)

**TC**
install dashboards addon
Run project
Open screen Dashboards - Dashboard editor

**AR**
![image](https://user-images.githubusercontent.com/114649487/207305062-97d1c739-2399-4f64-9e18-2278fb3d39d0.png)

**ER**
The buttons  must be visible

**Comment by KremnevDmitry** [comment]
The documentation notes that you need to extend the default theme in order to correctly install the addon.
[Link to Documentation](https://docs.jmix.io/jmix/dashboards/index.html#installation)
