### ISSUE TITLE
Move default admin/admin credentials to project template application.properties

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1289]
To make it easier to remove them. Now it needs to search through docs/forums.

**Comment by knstvk** [comment]
Let's do more.
Login screen/view in Jmix is completely on the project level and there is no point to provide default values for it by the framework. So my suggestions are:
- Keep `UiLoginProperties` and `FlowuiLoginProperties` as is for backward compatibility but deprecate them.
- In the project templates (both classic and flow UI), set properties:
  ```
  ui.login.defaultUsername = admin
  ui.login.defaultPassword = admin
  ```
- In login screen/view inject these properties with `@Value` and use them in such a way that simple removing them from application.properties or setting to empty values removes also from the UI. Make sure also that you can disable them by providing some values (ideally empty) by Java system properties on command line.

@glebfox , @gorbunkov - please review this spec and comment if disagree.

**Comment by KremnevDmitry** [comment]
For QA:
Create ClassicUI java / ClassicUI Kotlin / FlowUI

For each project:

- Run application (default credentinals should be admin/admin)
- Try to change default values in application.properties (change / remove / empty value)
- Build JAR file, provide ui.login.defaultUsername/ui.login.defaultPassword variables

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4944-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
