### ISSUE TITLE
Module Quartz localization

### ISSUE THREAD

**Issue by GurSergey** [jmix-framework/jmix#1297]
Add translations for module quartz

**Comment by lovtsovaik** [comment]
Not translated:

- column names in the jobs table
- column names in the trigger table
- fields names in job editor
- fields names in trigger editor
- Header of trigger editor ()
- calendar (it's common problem)
- help text for cron: "Cron expression is a sequence of six or seven fields, separated by spaces: second, minute, hour, day, month, day of a week and year(optionally). The month and the day of a week can be represented by the first three letters of their English names. Examples:"

Wrong translation
Header of jobs editor (en: Quartz job): Редактор задач -> Редактор задачи / Quartz задача
Tab "Job data parameters" Параметры заданий -> Параметры задачи
help text for cron: 
запускает каждые 5 минут  ->
 ->
 ->
 ->
 ->
 ->
0 0/5 * ? * * - запускает каждые 5 минут
0 0 0 ? * * - срабатывает в 00:00 каждый день
0 0 8-10 ? * * * - срабатывает в 8, 9 и 10 часов каждый день
0 0/30 8-10 ? * * * - срабатывает каждый день в 8:00, 8:30, 9:00, 9:30 и 10 часов
0 10,44 14 ? 3 WED - срабатывает в 14:10 и в 14:44 каждую среду в марте
0 15 10 ? * 6#3 - срабатывает в 10:15 в третью пятницу каждого месяца
0 11 11 11 11 ? - срабатывает каждое 11 ноября в 11:11
0 0 0 7 1 ? - запускается каждое Рождество в полночь

0 0/5 * ? * * - fires every 5 minutes
0 0 0 ? * * - fires at 00:00 AM every day
0 0 8-10 ? * * * - fires at 8, 9 and 10 o'clock every day
0 0/30 8-10 ? * * * - fires every day at 8:00, 8:30, 9:00, 9:30 and 10 o'clock
0 10,44 14 ? 3 WED - fires at 2:10 PM and at 2:44 PM every Wednesday in the month of March
0 15 10 ? * 6#3 - fires at 10:15 AM on the third Friday of every month
0 11 11 11 11 ? - fires every November 11th at 11:11 AM
0 0 0 25 12 ? - fires every Christmas at midnight

**Comment by Gavrilov-Ivan** [comment]
Looks like something wrong with build with actual changes.

**Comment by lovtsovaik** [comment]
Header of trigger editor:
![image](https://github.com/jmix-framework/jmix/assets/73226373/d46969df-762a-486a-94be-ee0a4d60abd2)

Hint for repeat modes:

> Режимы 'Ограниченное количество запусков' and 'Бесконечные запуски'

**Comment by lovtsovaik** [comment]
verified
