### ISSUE TITLE
Lists of enumerations in UI should include enumerations that are not used in entity attributes

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1306]
Jmix 1.4.1

1. Create new enum in the project
2. Do not make it any entity atribute
3. Run the application
4. In the modeler create an input dialog process form and and a form field with the Platform enum

AR:

The new enum is not displayed in the list.

If you create any entity attribute for this enum, the  enum will be displayed in the modeler.

See [forum](https://forum.cuba-platform.com/t/include-enum-class-into-platform-enum-list/16679)

See [BProc issue](https://youtrack.jmix.io/issue/BPM-347)

**Comment by knstvk** [comment]
See also this [forum topic](https://forum.jmix.io/t/jpql-custom-editor-missing-some-enum-case/2415).
Let's rewrite the enums discovery globally.

**Comment by knstvk** [comment]
The same problem is in Report parameters.
