### ISSUE TITLE
Upgrade to Flowable 6.8.0

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1307]
https://github.com/flowable/flowable-engine/releases/tag/flowable-6.8.0

**Comment by gorbunkov** [comment]
For QA: pls, make a quick test that after the migration to 1.5 all running process instances continue working and that processes can be start on new fresh 1.5 project.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.0-RC1
Jmix Studio plugin version: 1.5.SNAPSHOT4950-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
