### ISSUE TITLE
Support navigation to Detail views from Menu

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1308]
### Description
See support forum: [topic](https://forum.jmix.io/t/want-to-set-badge-text-to-menuitem-in-flowui/2311/3).

For now, `ViewMenuItem` does not support Detail view navigation.

**Comment by glebfox** [comment]
fixed in https://github.com/jmix-framework/jmix/issues/844

example:

```
<item view="User.detail" title="Admin">
    <routeParameters>
        <parameter name="id" value="60885987-1b61-4247-94c7-dff348347f93"/>
    </routeParameters>
</item>
```
