### ISSUE TITLE
Add ability to edit localization messages from code editor

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#1311]
When entity field has no localization message action is available:
![image](https://user-images.githubusercontent.com/13851473/209518397-46ffac56-20f7-4efa-8542-4a94eb027da8.png)

It will be convient to have similar action for editing commit messages.
 
When localization messages exists, action will be available: "Edit messages in the message bundle"
It opens localization editor dialog.

**Comment by knstvk** [comment]
See https://youtrack.jmix.io/issue/JST-3524/Add-ability-to-edit-localization-messages-from-code-editor
