### ISSUE TITLE
MappedSuperclass is not weaved properly if it has no inheritors

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#1312]
see forum [topic](https://forum.jmix.io/t/composite-project-lazy-loading-eclipselink-weave/2318).
 ValueHolders are not added when MappedSuperclass has no inheritors.
 
 #### Task
 ##### Investigation
 1. See whether it happens in our fork only
 2. Maybe it has been fixed in the next versions (update?)
 3. Report if it is not fixed yet in EclipseLink
##### Changes
Fix the problem or throw an exception from gradle plugin.

**Comment by knstvk** [comment]
Duplicates #317
