### ISSUE TITLE
XLSX report is corrupted if formula is used in the template

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1313]
Jmix: 1.4.1

When a report template contains a formula in each row then resulting document that is opened by the Excel with the error. The error says that the document is corrupted, however all formulas are calculated correctly.

Sample project: [reports_excel_formula.zip](https://github.com/jmix-framework/jmix/files/10303785/reports_excel_formula.zip)

Report template:  [Template for report _Report for entity _User__ (1)(1).xlsx](https://github.com/jmix-framework/jmix/files/10303788/Template.for.report._Report.for.entity._User__.1.1.xlsx)

See [forum topic](https://forum.jmix.ru/t/problema-ispolzovaniya-formuly-pri-generaczii-otcheta-v-xlsx/761)

**Comment by Gavrilov-Ivan** [comment]
Error occures when document with empty (without cell elements) calcChain.xml file is opened by the Excel.
Also calcChain generation was incorrect so it's disabled for now.
