### ISSUE TITLE
Update GSON to 2.10.1 to support Record type

### ISSUE THREAD

**Issue by BryanYin** [jmix-framework/jmix#1314]
In a service, use `Record` as parameter type:
```java
@Service("demo_testService")
public class TestService {
    public record TestRecord(String reader, Boolean isMain) {
    }

    public String testMethod(TestRecord reader) {
        return "Success";
    }
}
```

Install REST-API add-on, expose this method. Then, call this method, it will throw:
```
Caused by: java.lang.IllegalAccessException: Can not set final java.lang.String field com.tcx.coman.beans.services.TestService $TestRecord.reader to java.lang.String
```

After add `implementation 'com.google.code.gson:gson:2.10'` in `build.gradle`, the issue is gone. Please see also: https://github.com/google/gson/issues/1794

Since Jmix supports JDK 17, we need this upgrade.

**Comment by gorbunkov** [comment]
The current Spring Boot already brings GSON 2.10.1. So the dependency is already delivered, no need to do anything special.
