### ISSUE TITLE
Checkbox component in editor sends NULL instead of Boolean.FALSE when not interacted with

### ISSUE THREAD

**Issue by ket4z** [jmix-framework/jmix#1317]
# Environment:
* Jmix version: 1.4.2 (probably applies to previous jmix versions, at least 1.4.x versions)

# Steps to reproduce:
* create editor, place checkbox component connected to a data container on it, specify a bool type property
* try to add new record via jmix app, make sure NOT to interact with your checkbox (i.e. do not check and uncheck it), save
* check your data - value in that property/field will be null (alternative / faster way to check - make that bool property not-nullable, a db null-contraint exception will fire upon submitting editor screen)

# ER:
* editor sends Boolean.TRUE for checked checkbox and Boolean.FALSE for unchecked checkbox, never NULL

# AR:
* editor sends NULL for unchecked checkbox (or does not send any value) if the checkbox has not been previously interacted with, which is confusing as user expects the unchecked checkbox to represent FALSE value

**Comment by gorbunkov** [comment]
@ket4z You can set the initial `false` value for the field in the entity class, e.g.

```java
private Boolean myField = false;
```

**Comment by ket4z** [comment]
@gorbunkov Sure, I can work around this and I have. 

Still I consider this to be an usability issue (if not bug). If the checkbox component has only 2 states (checked/unchecked), it must represent `true` when checked and `false` when unchecked (not `null`). 

I'm not forcing any of the solutions, It is up to Jmix team to evaluate and decide but IMO there are only 3 viable options how to remove this non-deterministic behavior:
* stick with two states checkbox component but send `false` when unchecked
* introduce a third state for checkbox component representing null/undetermined value
* force user to set default value for bool fields (worst solution IMO)
