### ISSUE TITLE
Use Spring beans in report value formatter Groovy scripts

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1321]
It is possible to use Groovy scripts for value formatters in reports. The only argument we can use in groovy script is the "value". It would be useful to have Spring ApplicationContext context there. In this case we'll be able to use any spring bean for formatting the value.

See [forum topic](https://forum.jmix.ru/t/vyvod-lokalizovannyh-znachenij-dlya-enum-polej/771)

**Comment by NikitaShchienko** [comment]
Duplicate - https://github.com/jmix-framework/jmix/issues/2587
