### ISSUE TITLE
EditAction exception if entity is not stored in the database

### ISSUE THREAD

**Issue by GurSergey** [jmix-framework/jmix#1330]
With &lt;property name="openMode" value="DIALOG"&gt; the entity opens normally, otherwise an error occurs. The entity is not stored in the database
<img width="520" alt="Screenshot_20230109_112716" src="https://user-images.githubusercontent.com/17911008/211260970-9e1697b1-dcfd-4fb9-8cc1-96209861d4f2.png">
<img width="460" alt="Screenshot_20230109_112740" src="https://user-images.githubusercontent.com/17911008/211260993-5fdaf82e-de5a-4980-ac2a-ce223e6ca70c.png">
<img width="524" alt="Screenshot_20230109_112812" src="https://user-images.githubusercontent.com/17911008/211260996-5a52929f-a139-4eb2-8da1-bcb96bae9b28.png">
<img width="409" alt="Screenshot_20230109_112927" src="https://user-images.githubusercontent.com/17911008/211261005-23ba0827-ed98-486a-9767-243094705752.png">

### Changes
As suggested by @gorbunkov non JPA entities are always edited in the DIALOG mode.

**Comment by gorbunkov** [comment]
As a temporary solution we may always open DTO entities in Dialog mode (rework Edit action).

**Comment by glebfox** [comment]
Navigation to DTO Entity will be possible after https://github.com/jmix-framework/jmix/issues/892
