### ISSUE TITLE
Provide GlobalUiEventHandler

### ISSUE THREAD

**Issue by ZuperKeurZ** [jmix-framework/jmix#1340]
as discussed in 
https://forum.jmix.io/t/communication-between-core-application-and-backoffice-ui/226/9

In Cuba we had the [global events plugin](https://www.jmix.io/cuba-platform/marketplace/global-events/)  for sending events over application blocks and between vaadin sessions. 

the ticket above explains that it is missing in jmix and how to implement a similar approach. 

This is however quite low level code, it would be nice to have this in the framework.

**Comment by DREIZ3R** [comment]
Поднимаю.

**Comment by gorbunkov** [comment]
Implemented in https://github.com/jmix-framework/jmix/issues/1235#issuecomment-1820550454
