### ISSUE TITLE
Support Tooltip

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1342]
Since Vaadin 23.3 the `HasTooltip` interface has been introduced. Add support in XML and our custom components.
https://vaadin.com/docs/latest/components/tooltip

**Comment by KremnevDmitry** [comment]
### Supported components

- [ ] BigDecimalField
- [ ] JmixButton
- [ ] CheckboxGroup
- [ ] Checkbox
- [ ] ComboBox
- [ ] ComboBoxPicker
- [ ] ComboButton
- [ ] DatePicker
- [ ] DateTimePicker
- [ ] DrawerToggle
- [ ] DropdownButton
- [ ] EmailField
- [ ] EntityComboBox
- [ ] EntityPicker
- [ ] FileStorageUpload
- [ ] FileUploadField
- [ ] IntegerField
- [ ] ListBox
- [ ] MultiSelectComboBox
- [ ] MultiSelectListBox
- [ ] MultiSelectValuePicker
- [ ] NumberField
- [ ] PasswordField
- [ ] RadioButtonGroup
- [ ] Select
- [ ] TextArea
- [ ] TextField
- [ ] TimePicker
- [ ] UserIndicator
- [ ] ValuePicker

- [ ] Details
- [ ] AccordionPanel
- [ ] Tab
