### ISSUE TITLE
The column width showed up after reorder of DataGrid columns

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1345]
Steps:
1. Open list-view screen
2. Reorder of DataGrid columns by drag-n-drop in components hierarchy
3. 
See studio ticket: https://youtrack.jmix.io/issue/JST-3523/The-column-width-showed-up-after-reorder-of-DataGrid-columns

**Comment by rusiaikinat** [comment]
[The table does not fit in the viewport](https://youtrack.jmix.io/issue/JST-3562)
