### ISSUE TITLE
Cannot find value of screen param when select entity in reports parameter

### ISSUE THREAD

**Issue by evn9ln** [jmix-framework/jmix#1347]
An error occurs when defining an entity parameter when selecting an entity class. At the same time, screens are not added in field "Entity lookup screen"
![photo_2023-01-13_13-06-09](https://user-images.githubusercontent.com/57793250/212281295-df086aeb-c7aa-4d98-944e-bb53b44f1125.jpg)

During the debugging, found that an error occurs when iterating over screens, when the iteration reaches the sys$ScheduledTask.edit screen descriptor, which is declared in the web-screens.xml file 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/57793250/212281680-c0334c6d-91d8-4fef-9f9d-6eefd1ff87e3.png)

This screen contains a parameter that causes an error 
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/57793250/212281713-984061f7-9b07-426a-894b-221d24dedb3a.png)

The file with stacktrace is attached:
[error.txt](https://github.com/jmix-framework/jmix/files/10409946/error.txt)

**Comment by GurSergey** [comment]
Hi, @evn9ln! Сan you attach the archive with the project in the description to the ticket?
