### ISSUE TITLE
Not possible to add valid custom attributes to some elements of screen xml descriptor

### ISSUE THREAD

**Issue by khurry** [jmix-framework/jmix#1361]
Jmix 1.4.1.
Xsd schema for some screen descriptor elements doesn't allow to add extra attributes to them (in my case I need to add some attribute to <collection/> in <data/> to use it in specific loader) . So xml validator highlights these attributes as wrong.
Proposed solution is to add <xs:anyAttribute namespace="##other" processContents="lax"/> to xsd to make these elements extendable.

**Comment by glebfox** [comment]
We don't plan to all add possibility to define any attribute by adding `<xs:anyAttribute namespace="##other" processContents="lax"/>`

To provide custom attributes would be better to implement additional xsd schemas, e.g.:

* [view-ext.xsd](https://github.com/jmix-framework/jmix/blob/master/jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/view-ext.xsd) adds custom `index`attribute
* [fragment-data.xsd](https://github.com/jmix-framework/jmix/blob/master/jmix-flowui/flowui/src/main/resources/io/jmix/flowui/view/fragment-data.xsd) extends `view-data.xsd` to provide additional attributes for data elements
