### ISSUE TITLE
ExcelExporter maximum row number is fixed

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#1363]
At Apache POI maximum Excel row number depends on file format (64K or 1M):
https://svn.apache.org/viewvc/poi/tags/REL_4_1_2/src/java/org/apache/poi/hssf/usermodel/HSSFRow.java?view=markup#l231
https://svn.apache.org/viewvc/poi/tags/REL_4_1_2/src/ooxml/java/org/apache/poi/xssf/usermodel/XSSFRow.java?view=markup#l421
https://svn.apache.org/viewvc/poi/tags/REL_4_1_2/src/ooxml/java/org/apache/poi/xssf/streaming/SXSSFRow.java?view=markup#l151

JMIX has only one fixed limit for all file formats:
https://github.com/jmix-framework/jmix/blob/52137f980f05a2dd6082c498595bf1d5c474235a/jmix-ui/ui-export/src/main/java/io/jmix/uiexport/exporter/excel/ExcelExporter.java#L78

**Comment by gorbunkov** [comment]
XLS support has been removed from ExcelExporter. Maximum rows number is now 1M.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4950-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
