### ISSUE TITLE
Bean validation on persistence layer

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1368]
Currently bean validation is performed in different ways when you store entities from the editor screen and using REST API.

Editor screen only validates entity attributes that have corresponding fields in the screen. If in the editor screen you update some entity attribute programmatically and this attribute doesn't have corresponding UI field, then the entity will be saved with invalid value.

In REST API full entity validation is performed before save.

It seems that we may try to do the validation on the persistence layer. The first option is to do the validation using ORM. We explicitly turn the EclipseLink bean validation off in the `JmixEclipseLinkJpaVendorAdapter` class:

```java
map.put("javax.persistence.validation.mode", "NONE");
```

Maybe we should try yo turn it on.

The second option may be to invoke bean validation somewhere at DataManager after all entity listeners are invoked (because some entity attributes may be filled in listeners).

**Comment by Gavrilov-Ivan** [comment]
- Automatical bean validation on persistence layer is enabled
- Can be disabled by setting javax.persistence.validation.mode app property to NONE
- Validator groups can be configured by the following application properties (full class name required as value): jakarta.persistence.validation.group.pre-persist, jakarta.persistence.validation.group.pre-update, jakarta.persistence.validation.group.pre-remove. Default group by default.
- JmixLocalValidatorFactoryBean with Jmix-specific message interpolator is used as validation factory for auto validation (the same as for the manual validation on UI\REST side)

**Comment by lovtsovaik** [comment]
verified
- [x] bean validation enabled
- [x] jakarta.persistence.validation.mode=none
- [x] jakarta.persistence.validation.group.pre-persist, pre-update, pre-remove
- [x] Jmix-specific messages
