### ISSUE TITLE
Provide the ability to get the file size in FileStorage

### ISSUE THREAD

**Issue by fomich-artem** [jmix-framework/jmix#1369]
There is a need to get the file size from FileStorage without reading the entire file. For example, currently to get the size of a file, you need to execute something like this:
```
FileStorage fs = ...;
try (InputStream is = fs.openStream(fileRef)) {
// read and count bytes from the stream
}
```
But the code could look like this:
```
FileStorage fs = ...;
fs.getFileSize(fileRef);
```
This functionality is necessary, for example, to display the file size in the UI.

**Comment by knstvk** [comment]
We recommend storing file size and other meta-information in regular entity attributes next to FileRef.
