### ISSUE TITLE
The error dialog is not show when error occurs while navigating to a view

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1374]
### Steps to reproduce
1. Try to throw an exception while navigating to the view, e.g. change action in `createBtn` like this:
```
<button id="createBtn" action="usersTbl.create"/> <!-- incorrect id of table -->
```
2. Open "Users" view.

**ER**
Error dialog with stacktrace should be shown.
![image](https://user-images.githubusercontent.com/22093943/213433521-e2161a37-a362-4364-9476-4565c1085971.png)

**AR**
Nothing is shown. In the console we can find exception with stacktrace.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4924-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)

Error dialog with stacktrace is shown.
