### ISSUE TITLE
SideMenu menu displays limited number of nested menu items

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1381]
For some reason, the opened menu has `max-width=2000px` as a result not all nested items are displayed, see [forum](https://forum.jmix.io/t/sidemenu-stops-expanding/2417/3) for more detail.

[SideMenuScroll.zip](https://github.com/jmix-framework/jmix/files/10477730/SideMenuScroll.zip)

**Comment by KremnevDmitry** [comment]
### Notes:
The restriction has been lifted. 
Use with caution: large numbers of menu items may cause browser performance problems.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4972-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
