### ISSUE TITLE
Label component should not pass null value to the formatter

### ISSUE THREAD

**Issue by trx0eth7** [jmix-framework/jmix#1393]
Actual for jmix v. 1.3.5

Step reproduce:
1. Create custom formatter
2. Set custom formatter to label
3. Set null value to label
4. Formatter tries to handle null value

Potentionaly problem, here:
io.jmix.ui.component.impl.LabelImpl#convertToPresentation

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)

Formatter gets nullable value:
![image](https://github.com/jmix-framework/jmix/assets/158277660/41ed970b-620d-43f9-822e-381f16534145)
