### ISSUE TITLE
DataLoadCoordinator doesn't trigger reload if query contains a session attribute parameter

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1412]
Jmix version: 1.4.4

If a collection loader query contains a single query parameter related to a session attribute, e.g.

```xml
<loader id="customersDl">
     <query>
          <![CDATA[select e from Customer e where e.lastName = :session_customerLastName]]>
     </query>
</loader>
```

then data loader won't be automatically load on screen opening. It seems that `DataLoadCoordinator` doesn't process this case correctly.

The sample project: [session-param-data-loader.zip](https://github.com/jmix-framework/jmix/files/10664661/session-param-data-loader.zip)

We need to check this in both UI and FlowUI modules.

**Comment by natfirst** [comment]
Works fine for platform 2.1
Related issue for platform 1.6 has been reopen https://github.com/jmix-framework/jmix/issues/2326
