### ISSUE TITLE
WebDav cannot create new folder or copy file with cyrillic symbols in name

### ISSUE THREAD

**Issue by bad-decision** [jmix-framework/jmix#1413]
Environment:
Jmix version: 1.4.3
Jmix Studio plugin version: 1.4.3-233
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)

TC:

1. Open the attached project -> Start the app in docker
2. Open WebDav storage in Windows Explorer (Windows 10)
3. Create new folder or copy file with cyrillic symbols in name

AR:
error is displayed:
![error](https://user-images.githubusercontent.com/75641540/217165914-e977f17c-f2e8-4ea6-a66d-eb9b14994092.PNG)

[webdav_test.zip](https://github.com/jmix-framework/jmix/files/10672093/webdav_test.zip)
[webdav log.txt](https://github.com/jmix-framework/jmix/files/10672106/webdav.log.txt)

**Comment by Gavrilov-Ivan** [comment]
Case 2: Windows Explorer gets name of folders from response of `PROPFIND` request from 'href' element
`<D:href>/webdav/files/New+folder/</D:href>`
not 'displayname'
`<D:displayname>New folder</D:displayname>`

WinSCP has the same issue.

Case 3 goes from case 2

**Comment by Gavrilov-Ivan** [comment]
For Case 2\3 also created new issue - https://github.com/jmix-framework/jmix/issues/1540
It reproduces not only on names with cyrillic symbols, but on any names with spaces.

So it is not related to the current issue.
