### ISSUE TITLE
CategoryAxis does not contain labelFunction element in SerialChart

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1425]
### Description
Support forum: [topic](https://forum.jmix.ru/t/voprosy-po-grafiku-serialchart/867)
See AmCharts docs: https://www.amcharts.com/docs/v3/reference/categoryaxis/#labelFunction_property

### Steps to reproduce
1. In project: https://github.com/jmix-framework/jmix-ui-samples open `columnline-chart.xml`;
2. Add the following code:
```
<chart:categoryAxis axisAlpha="0"
                    gridPosition="START"
                    tickLength="0">
    <chart:labelFunction>
            function(valueText, serialDataItem, categoryAxis) {
                console.log('labelFunction');
                return valueText;
            }
    </chart:labelFunction>
</chart:categoryAxis>
```

**AR**

![image](https://user-images.githubusercontent.com/22093943/218395777-0d39dcc2-43ec-4913-a734-e75e2447a845.png)

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.999-SNAPSHOT - verified
