### ISSUE TITLE
Invalid double format message for Excel export action for some translations

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1431]
For example, German translation contains the following message:

```
excelExporter.doubleFormat=#.##0,00##############
```

But it should be:

```
excelExporter.doubleFormat=#,##0.00##############
```

See [Microsoft documentation](https://support.microsoft.com/en-us/office/review-guidelines-for-customizing-a-number-format-c0a1d1fa-d3f4-4018-96b7-9c9354dd99f5).

See [forum topic](https://forum.cuba-platform.com/t/jmix-excelexport-with-localdate-and-bigdecimal/16726)

While working in the issue we must find all other translations with the same problem (Greek, Dutch, ?)

**Comment by konyashkina** [comment]
Tesetd on
Jmix version: 1.5.0-RC3
Jmix Studio plugin version: 1.5.SNAPSHOT4968-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
