### ISSUE TITLE
[GenericFilter] Support URL query parameters

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1441]
### Solution

1. URL Query Parameters support for `PropertyFilter`.

XML definition:
```
<queryParameters>
    <propertyFilter component="usernameFilter"/>
</queryParameters>
```

As a result, every operation and value changes are reflected in the URL bar, e.g.:
<img width="426" alt="Screenshot 2023-02-22 at 15 45 31" src="https://user-images.githubusercontent.com/6077149/220611144-f8167fbc-b6ce-4aa4-ba01-77f9bcab9329.png">

Query parameter name can be configured using the `param` attribute (by default the related component id is used as param name), e.g.:
```
<queryParameters>
    <propertyFilter component="usernameFilter" param="username"/>
</queryParameters>
```
<img width="372" alt="Screenshot 2023-02-22 at 15 45 51" src="https://user-images.githubusercontent.com/6077149/220611443-e842a665-d680-4d36-a580-044af9cdab44.png">

2. URL Query Parameters support for `GenericFilter`.

XML definition:
```
<queryParameters>
    <genericFilter component="filter"/>
</queryParameters>
```
<img width="1135" alt="Screenshot 2023-03-01 at 11 20 29" src="https://user-images.githubusercontent.com/6077149/222070733-e2762d39-1c2a-406a-b945-addf9e3c9288.png">

As a result, every condition with its operation and value changes are reflected in the URL bar, e.g.:
Conditions query parameter name can be configured using the `conditionParam` attribute (by default `genericFilterCondition` is used), e.g.:
```
<queryParameters>
    <genericFilter component="filter" conditionParam="condition"/>
</queryParameters>
```
<img width="966" alt="Screenshot 2023-03-01 at 11 19 08" src="https://user-images.githubusercontent.com/6077149/222070513-dc41df8f-190e-41ba-ad92-ca7369ba9d6f.png">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4993-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
