### ISSUE TITLE
Implement IN and DATE_INTERVAL operations in PropertyFilter

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1442]

**Comment by Flaurite** [comment]
Consider to add permission to `DateIntervalDialog`, since it is not available even with Filter role. See: https://github.com/jmix-framework/jmix/issues/3121

**Comment by KremnevDmitry** [comment]
> Consider to add permission to `DateIntervalDialog`, since it is not available even with Filter role. See: #3121

Fixed with https://github.com/jmix-framework/jmix/commit/a673fab24ec11f9b2a8ee3bf2a288967f54259c6

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6329-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6332-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Operations are available in propertyFilter and in Filter.

**Comment by KremnevDmitry** [comment]
Doc issue linked: https://github.com/jmix-framework/jmix-docs/issues/785
