### ISSUE TITLE
[GenericFilter] Support custom conditions

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1444]
- [x] Property
- [x] Jpql
- [x] Group
- [x] Edit/Remove group condition
- [x] FlowUI Kit ([JST-3841](https://youtrack.haulmont.com/issue/JST-3841) Support ResponsiveSteps)

TODO:
- [ ] JpqlFilter condition studio support([JST-4051](https://youtrack.jmix.io/issue/JST-4051))
- [ ]  #1767
- [x] GenericFilter/GroupFilter responsiveSteps Studio support ([JST-3841](https://youtrack.haulmont.com/issue/JST-3841) Support ResponsiveSteps)

**Comment by rusiaikinat** [comment]
[JST-4051](https://youtrack.jmix.io/issue/JST-4051) genericFilter - configuration.  The condition tag is not generated for jpqlFilter

**Comment by rusiaikinat** [comment]
AR
![image](https://github.com/jmix-framework/jmix/assets/114649487/e6167cce-ba46-4c5e-8b3a-65f0ff79535b)

ER
Classic UI
![MicrosoftTeams-image (3)](https://github.com/jmix-framework/jmix/assets/114649487/d78b2364-99bb-4ccb-97a8-d950c42863ec)
