### ISSUE TITLE
[GenericFilter] Support configurations

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1445]
- [x] Runtime
- [x] Designtime
- [x] Configuration actions (todo: https://github.com/jmix-framework/jmix/issues/1584)
- [x] Tests
- [x] TODO: #1766

**Comment by KremnevDmitry** [comment]
For QA: 

You can use ClassicUI documentation examples for testing design-time configurations.

**Comment by rusiaikinat** [comment]
[JST-4051](https://youtrack.jmix.io/issue/JST-4051) genericFilter - configuration. The condition tag is not generated for jpqlFilter
