### ISSUE TITLE
Can't add class name to MenuItem, because add() is not supported.

### ISSUE THREAD

**Issue by klaus7** [jmix-framework/jmix#1448]
See https://github.com/jmix-framework/jmix/blob/152fa82cfa8600c00b59de459e9e6968163b83f4/jmix-flowui/flowui/src/main/java/io/jmix/flowui/menu/ListMenuBuilder.java#L124
(also on another line in the same file)

`Arrays.asList` will inherits from an AbstractList and doesn't support adding to it.

Stacktrace (important part) when trying to add another class name to the menu item: 
```
java.lang.UnsupportedOperationException: null
	at java.base/java.util.AbstractList.add(AbstractList.java:153) ~[na:na]
	at java.base/java.util.AbstractList.add(AbstractList.java:111) ~[na:na]
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:336) ~[na:na]
	at io.jmix.flowui.kit.component.main.ListMenu$MenuItem.addClassNames(ListMenu.java:501) ~[jmix-flowui-kit-1.4.999-SNAPSHOT.jar:na]
```

#### Steps to reproduce
1. Add to some menu `classNames` attribute:
```
<menu id="application" classNames="custom-selector" .../>
```
2. In `MainView` add the following code:
```
@ViewComponent
private JmixListMenu menu;

@Subscribe
public void onInit(InitEvent event) {
    menu.getMenuItem("application")
            .addClassNames("added-class-name");
}
```
3. Launch the application and you will get the above exception.

#### Test cases
1) Check that we can add `classNames` programmatically for all menu item types:
- To `MenuItemBar` like `<menu id="application".../>`
- To simple menu with View
- To menu item with Bean and its method

2) Also check in the dev-tools that menu item has programmatically added selector
![image](https://user-images.githubusercontent.com/22093943/226625917-22e40fb1-80c6-4a70-8686-f3a2052263ce.png)

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.999-SNAPSHOT - verified
