### ISSUE TITLE
InstanceNameProvider returns wrong instance name for extended entities

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#1454]
### Problem
[Forum topic](https://forum.jmix.ru/t/mappedsuperclass-x-2-instancename-inogda-cannot-get-unfetched-attribute/884)

see `io.jmix.core.impl.InstanceNameProviderImpl#parseNamePattern():194`
It returns the first found `@InstanceName` field instead of the one from the closest ancestor.

`@InstanceName` should be overridden in subclasses correctly.

### Steps:
1. Download the [project](https://github.com/jmix-framework/jmix/files/10796485/UnfetchedDemo.zip)
2. Put breakpoint on `io.jmix.core.impl.InstanceNameProviderImpl#parseNamePattern():194`
2. Debug project and open Demo Resource Classes screen.

### QA Notes
Please, check that `@InstanceName` annotation on field works in general cases.

Particular case is covered by autotest, manual checking of it is not needed.
(In case of manual checking, please use exactly the same entity structure because removing e.g. soft-delete, audit and version traits from entity affects metadata properties order and makes problem unreproducible)

**Comment by dtaimanov** [comment]
Can be a duplicate of https://github.com/jmix-framework/jmix/issues/245

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3
