### ISSUE TITLE
Circular reference when injecting SessionRegistry

### ISSUE THREAD

**Issue by khurry** [jmix-framework/jmix#1455]
Tested in jmix 1.4.1 and 1.4.4
Case:
1. Create a jmix fullstack project
2. Create a spring bean in "screen" package and inject SessionRegistry in it using constructor:

```
@Component
public class TestBean {
  private final SessionRegistry sessionRegistry;
  
  public TestBean(SessionRegistry sessionRegistry) {
    this.sessionRegistry = sessionRegistry
  }
}
```

3. Run @SpringBooTest-test, for example, default JmixTestApplicationTests.
4. Get an exception:

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'testBean'
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'io.jmix.security.SecurityConfiguration': Unsatisfied dependency expressed through field 'sessionRegistry'; nested exception is org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'sec_SessionRegistry': Requested bean is currently in creation: Is there an unresolvable circular reference?

Looks like SecurityConfiguration can't be instantiated because it contains sessionRegistry autowired itself.

**Comment by gorbunkov** [comment]
We need to check this after fixing the https://github.com/jmix-framework/jmix/issues/287

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6960-242
IntelliJ version: IntelliJ IDEA 2024.2.4 (Community Edition)
