### ISSUE TITLE
Support OR in combination of children roles

### ISSUE THREAD

**Issue by BryanYin** [jmix-framework/jmix#1457]
We have a case:
row-level role 1: `{E}.department.name = 'sales'` for sales employees.
row-level role 2: `{E}.department.name = 'marketing'` for marketing employees.

and we need to create a role for Manager of marketing and sales, who can see all data from role 1 and role 2.

Currently we have to create a new role3 using `or` in `where` clause.

Good to have:
Support `or` in row-level role designer, that can combine role1 and role2 with `or` relation.

**Comment by gorbunkov** [comment]
We don't have plans to implement this
