### ISSUE TITLE
Support for JUnit5 @Nested test classes for JmixUiTestExtension 

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#1460]
Currently, when annotating a UI integration test with `@UiTest` on a test class, when using `@Nested` inner classes to group together different test cases, the annotation is not correctly interpreted. E.g. the authenticated user is "system" in the inner class although the outer class defines "admin".

Example:

```
@UiTest(authenticatedUser = "admin")
@SpringBootTest
public class AuthenticatedUserTest  {

    @Autowired
    CurrentAuthentication currentAuthentication;

    @Test
    void currentAuthentication_isAdmin() {

        User user = (User) currentAuthentication.getUser();

        assertThat(user.getLogin())
                .isEqualTo("admin");
    }

    @Nested
    class NestedJunit5Class {

        @Test
        void currentAuthentication_isAdmin() {

            User user = (User) currentAuthentication.getUser();

            assertThat(user.getLogin())
                    .isEqualTo("admin");
        }
    }
}
```

The first test case succeeds, the second one fails.

One option is to annotate all inner classes with the `@UiTest` annotation, but this is quite cumbersome, when the inner test are just used as groups of tests that don't have a different setting for the annotation.

**Comment by Flaurite** [comment]
Changes are made from PR https://github.com/jmix-framework/jmix/pull/1463 with some additions.
