### ISSUE TITLE
REST: get enum for specific language not work

### ISSUE THREAD

**Issue by BryanYin** [jmix-framework/jmix#1472]
GET http://localhost:8080/rest
            /messages
            /enums
            /rest.sample.entity.CustomerType
Accept-Language: zh_CN

this doesn't work. 

ER:
If I put `zh_CN` to the 2nd place in `jmix.core.available-locales`, it should get `zh_CN` translations when I specify `Accept-Language` request header.

AR:
it always get localized messages in the first language set in `jmix.core.available-locales`.
<img width="653" alt="image" src="https://user-images.githubusercontent.com/25950822/222146904-55c210da-5749-4904-87fe-acc0ea221a7b.png">

Jmix version: 1.4.4
Jmix Studio plugin version: 1.4.3-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)

**Comment by trdeep** [comment]
"zh_CN" should be changed to "zh-CN".

**Comment by BryanYin** [comment]
I will update CN Jmix doc accordingly.
