### ISSUE TITLE
Vaadin Ecxeption: Addon Multitenancy + Application settings. Login form does not appear

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1479]
env
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4991-223
IntelliJ version: IntelliJ IDEA 2022.3.1 (Ultimate Edition)

TC
Install add-on Multitenancy + Application settings
Run project

AR
Login form does not appear

![image](https://user-images.githubusercontent.com/114649487/222644866-41a80b67-5465-4902-979a-c99e29e4e926.png)

**Comment by gorbunkov** [comment]
@rusiaikinat It works fine for me. Did you do any additional modifications in the project, or just created a new empty project, added two addons there and started it?

**Comment by lovtsovaik** [comment]
It is reproduced for me too at 1.5.0-RC3 Jmix version

**Comment by lovtsovaik** [comment]
My fresh case

- Create a new FlowUI project with postgres database
- Add Audit, run -> **ok**
- Add Quartz and Grid Export Actions together, run -> **error**
- Comment Quartz dependencies, call Reload Gradle Dependencies, run -> **ok**
- Add AppSettings, run -> **error**
- Comment GridExport dependencies, call Reload Gradle Dependencies, run -> **ok**

**Comment by lovtsovaik** [comment]
@glebfox have you any idea how to fix it?
This problem reduces the testing possibilities

**Comment by gorbunkov** [comment]
Probably relates to #1571

**Comment by Flaurite** [comment]
@lovtsovaik it is not a Jmix problem. See how to fix it in project: https://github.com/jmix-framework/jmix/issues/1571#issuecomment-1508673298
