### ISSUE TITLE
Fix menu id in FlowUi addon template

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#1491]
For the Studio [ticket](https://youtrack.jmix.io/issue/JST-3726)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5040-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
