### ISSUE TITLE
[CLASSIC UI] Use 100% width and height as the default values for a newly added Table like components

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1494]
See Jmix Studio ticket: https://youtrack.jmix.io/issue/JST-3428/Use-100-width-and-height-as-the-default-values-for-a-newly-added-Table-like-components

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5026-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
