### ISSUE TITLE
Auditable and Soft-Delete implementation

### ISSUE THREAD

**Issue by andreysubbotin** [jmix-framework/jmix#15]
https://www.cuba-platform.com/support/topic/the-state-field-path-this-deletets-cannot-be-resolved-to-a-valid-type
Original Issue: cuba-platform/cuba#514

* Move Creatable, Updatable, SoftDeletion, SoftDelete to CUBA module.
* Introduce annotations:
   - DeletedDate, DeletedBy
   - CreatedDate, CreatedBy, UpdatedDate, UpdatedBy - maybe use existing annotations from Spring Data 
Commons
* EntityEntry should contain information about soft deletion, audit info (create/update) and able to set/get that information in entity.
* Framework should use Entity entry or helper class EntityValues to set audit/soft deletion info
* Look at SpringData AuditingHandler, AuditingEntityListener
* Entity sample:
```
class SomeEntity {
    @Id
    Lond id
    
    @Column(name = "UUID", nullable = false)
    UUID uuid;

    @Version
    @Column(name = "VERSION", nullable = false)
    Integer version;

    @CreatedDate
    @Column(name = "CREATE_TS")
    Date createTs;

    @CreatedBy
    @Column(name = "CREATED_BY", length = 50)
    String createdBy;
    
    @LastModifiedDate
    @Column(name = "UPDATE_TS")
    Date updateTs;

    @LastModifiedBy
    @Column(name = "UPDATED_BY", length = 50)
    protected String updatedBy;

    @DeletedDate
    @Column(name = "DELETE_TS")
    Date deleteTs;

    @DeletedBy
    @Column(name = "DELETED_BY", length = 50)
    String deletedBy;

    @Column(name = "TEXT")
    String text;
}
```

**Comment by knstvk** [comment]
After #512 is merged, `HasUuid` replacement can be done without any special annotation: it's just a `@JmixGeneratedId` attribute of `UUID` type.

**Comment by dtaimanov** [comment]
`HasUuid` and `Versioned` part has been moved to #579
