### ISSUE TITLE
Reports: xlsx-report causes 'Index out of bounds' exception

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#1500]
Report based on xlsx-template failed with 'Index out of bounds' exception if template has named range for band with empty cells and non-rendered rows before this band.

1. Create xlsx-template with one named range for band started not from the begining of document (e.g. from B2). Last row(s) of this range should be empty.
2. Create simple report with horizontal band refered to this named range.
3. Run report.

Error occurs in `XlsxFormatter#copyCells(BandData band, Range templateRange, List<Row> resultSheetRows, Row firstRow, Worksheet resultSheet`) because of mismatch of row indexes between template and result sheet.

https://forum.jmix.io/t/xlsx-report-ranged-names-not-working/2650

**Comment by Gavrilov-Ivan** [comment]
Updated dependency: YARG 2.2.21

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.1-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
