### ISSUE TITLE
UPPER and LOWER properties do not work for attributes

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1507]
forum issue: [https://forum.jmix.io/t/entity-property-case-conversion/2668](https://forum.jmix.io/t/entity-property-case-conversion/2668)

Jmix version: 1.5.0
Jmix Studio plugin version: 1.5.0-223
IntelliJ version: IntelliJ IDEA 2022.3.1 (Ultimate Edition)

TC
Create string attribute Case conversion - UPPER
Create string attribute Case conversion - LOWER
Create list and detail view
Run project

AR
UPPER and LOWER properties do not work for attributes
![image](https://user-images.githubusercontent.com/114649487/225548735-78cedf75-3888-4c26-ad9e-0c9b54c45f16.png)

**Comment by glebfox** [comment]
Flow UI TextField has no `caseConversion` setting. Create a Studio issue to hide this property when creating an attribute for Flow UI app.
