### ISSUE TITLE
Prevent from creating filter configurations with the same name

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1514]
Now a user can save generic filter configuration with the same name.
See [forum topic](https://forum.jmix.io/t/unique-save-filter-name-configuration/2676).

**Comment by yuriy-khrebtov** [comment]
We implemented validation for uniqueness of filter configuration names when create or edit a configuration. Now, when a user tries to save a configuration with name that is already assigned to another configuration, save operation will fail with notification if the scope of configuration to save is equal to the scope of existing configuration. 
For example, if a user saves **global** configuration with name "conf1" and there is already **user** configuration with the same name then save operation will be successful. But if he will try to save another **user** configuration with the same name, save operation will fail.
Name validation can be enabled/disabled using `jmix.ui.component.filter-configuration-unique-names` (default is true).
Also, global configs in filter popup button are marked with * symbol to distinct them from user configs.
