### ISSUE TITLE
[FLOW UI] Export actions are not available in Add Action dialog

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1517]
Jmix Studio ticket: https://youtrack.jmix.io/issue/JST-3757/Export-actions-are-not-available-in-Add-Action-dialog

1. Create project with FlowUI
2. Add Grid Export Actions add-on
3. Open user-list-view.xml, select table actions and click Add in inspector

ER: export actions are in the list
AR: no export actions available

Also, there are no export actions in the dropdown of action's type attribute in the inspector.
It works in classic UI.

**Comment by MaxKatyshev** [comment]
_Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5048-223
IntelliJ version: IntelliJ IDEA 2022.3.3 (Community Edition)_

If remove Grid Export Actions add-on then export actions are available
![image](https://user-images.githubusercontent.com/11402689/227538775-c06b5ea2-e998-4432-b845-e2ac37fc794b.png)

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.999-SNAPSHOT - verified
