### ISSUE TITLE
Hot deploy support

### ISSUE THREAD

**Issue by web-devel** [jmix-framework/jmix#152]

**Comment by knstvk** [comment]
Consider using standard Spring dev tools mechanism.

**Comment by knstvk** [comment]
Probably we'll use our own mechanism, but will deploy only resources and compiled classes (no Java/Groovy source code). Ideally, we should move Scripting API to the compatibility module and use the standard ScriptEngine or something.

**Comment by knstvk** [comment]
Check out this: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-spring-boot-restart-vs-reload
