### ISSUE TITLE
Support PivotTable addon for Studio

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1520]
PitotTable isn't presented in the Add Component dialog.
Studio also doesn't know about their properties.
Jmix Studio ticket: https://youtrack.jmix.io/issue/JST-3758/Support-PivotTable-addon

**Comment by lovtsovaik** [comment]
*Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5062-223*

Basic support works
![image](https://user-images.githubusercontent.com/73226373/228747896-7704f671-b4f9-464d-8cb5-6971d4d4734c.png)
