### ISSUE TITLE
Can't set column width in pixels in Jmix UI Inspector

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1525]
Jmix UI Inspector shows "Invalid number value" when you set column width in px.
If you set column width in px through XML, the corresponding value in Inspector will be set to 0.
Jmix Studio ticket: https://youtrack.jmix.io/issue/JST-3756/Cant-set-column-width-in-pixels-in-Jmix-UI-Inspector

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.999-SNAPSHOT - verified
