### ISSUE TITLE
Actions created by class cannot be overridden

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1529]
Actions created using `io.jmix.ui.Actions#create(java.lang.Class<T>)` method cannot be overridden in the application. For example, `io.jmix.ui.component.filter.FilterSupport#createFilterAction` creates actions by their classes, so overriding of any filter action is impossible.

Perhaps we should only create actions by ID and deprecate `Actions#create(java.lang.Class<T>)` methods, or when creating by class search registered action types with the same id lower in the hierarchy.

Originates from [forum topic](https://forum.jmix.io/t/unique-save-filter-name-configuration/2676).
See also #420.

**Comment by gorbunkov** [comment]
Remove `Actions#create(java.lang.Class<T>)` in 2.0 and deprecate in 1.6
