### ISSUE TITLE
OffsetTime attributes processed incorrectly with DataManager

### ISSUE THREAD

**Issue by DeNZoL63** [jmix-framework/jmix#153]
**Steps to reproduce the bug:**
1. run test project from attachment [offset-time.zip](https://github.com/Haulmont/jmix-core/files/6426955/offset-time.zip)
2. open browser screen 'Entity with time offset property'
3. add filter condition for 'Offset time attr'

**Exxamples**

Choose condition `<= 11:11`
**ER:** displayed entities with `offsetTimeAttr` '11:11' and '03:03' 
**AR:** displayed entity with `offsetTimeAttr` '03:03' 

Choose condition `= 11:11`
**ER:** displayed entities with `offsetTimeAttr` '11:11'
**AR:** displayed no entity 

Choose condition `<> 11:11`
**ER:** displayed entities with `offsetTimeAttr` '22:22' and '03:03'
**AR:** displayed entities with `offsetTimeAttr` '11:11', '22:22', '03:03'

**Comment by DeNZoL63** [comment]
Also, it doesn't work with the OffsetDateTime type

**Comment by SergeiAksenov2** [comment]
Tested on:
1)  Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6364-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2)  Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6363-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

All cases from exaples are Ok.
