### ISSUE TITLE
Notifications: Show notifications for substituted user

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#1541]
Screen with users' In-app notifications should show notifications according to substituted (effective) user, not authenticated.
https://forum.jmix.io/t/notification-add-on-with-substitution-user-issue/2742

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.1-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
