### ISSUE TITLE
WebdavDocumentLink declaration issues

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#1546]
Declaration of `WebdavDocumentLink` in XML layout has the following issues:

**Namespace**
Currently webdav namespace suggests 'documentLink' component name but 'webdavDocumentLink' is expected.

**Implementation**
There is an NPE occurred in `WebdavDocumentLinkImpl`:
```
private void onItemChanged(EntityValueSource.InstanceChangeEvent<Object> event) {
    this.webdavDocument = EntityValues.getValueEx(event.getItem(), metaPropertyPath.getPath());
    refresh();
}
```
`metaPropertyPath` is never initialized.

Update: the same issue occurres with WebdavDocumentVersionLink

Blocks https://github.com/jmix-framework/jmix/issues/1549

**Comment by rusiaikinat** [comment]
[WebDav]  standard caption disappears #1569

**Comment by Gavrilov-Ivan** [comment]
Add do palette: https://youtrack.cuba-platform.com/issue/JST-3826/Webdav-components-are-not-available-in-the-component-palette
