### ISSUE TITLE
DataGrid IconRenderer does not reset icon if return value is null

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1550]
### Description
See discussion: [forum](https://forum.jmix.io/t/removing-an-existing-icon-form-a-treedatagrid-column-with-an-iconrenderer/2728).

### Steps to reproduce
1) Create some entity and Browser/Editor screens.
2) Add column with icon renderer. 
3) In the controller add column generator to the icon column. Return null or icon by some condition, e.g.:
```
@Install(to = "filesTable.icon", subject = "columnGenerator")
private Icons.Icon filesTableIconColumnGenerator(DataGrid.ColumnGeneratorEvent<File> event) {
    return Boolean.TRUE.equals(event.getItem().getIsDirrectory()) ? JmixIcon.FOLDER : null;
}
```
4) Launch the application
5) Create two instances of entity.
6) Try to sort rows by some column.

**ER**
Row with icon, row without icon.
**AR**
All rows have an icon.

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.999-SNAPSHOT - verified
