### ISSUE TITLE
Shortcuts don't work if screen is not focused

### ISSUE THREAD

**Issue by dgodlevskiy** [jmix-framework/jmix#1560]
When opening screen with no focusable components you need to click on it to make shortcuts work.

To reproduce it you can create a blank screen with an action that has a shortcut. When you just open the screen, the shortcut doesn't work, but after you click on the screen, the shortcut starts working.

**Comment by glebfox** [comment]
Unfortunately, neither layout nor screen has Server side API to focus it. In this case, a WA can be used:

```
@Subscribe
public void onInit(final InitEvent event) {
    JavaScript.eval("document.getElementsByClassName('v-verticallayout-jmix-window-layout')[1].focus()");
}
```

The code above uses JavaScript code to focus element.
