### ISSUE TITLE
Export/import functionality in roles screens

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1561]
In Flow UI resource roles screen and row-level roles screens must support import and export as it is implemented in classic UI

**Comment by m-shambarova** [comment]
### Reopened
**Env:**
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5184-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
Win

**Note:**

_1. After downloading the file, the attached file is shown_

**ТС:**
- Attached file shown when importing a file;
- Open scrin "Resourse Roles/Row-level roles";
- Import .json;
![image](https://github.com/jmix-framework/jmix/assets/99609936/5d3e036a-6614-480b-bda2-bc1f8eec2786)

**AR:** The attached file is displayed
**ER:** In the previous version, the uploaded file was not attached. Perhaps you should not show it.

_2. In the previous version, the notification showed the maximum size when uploading a large file_

**ТС:**

- Open scrin "Resourse Roles/Row-level roles";
- Import any large file;
![image](https://github.com/jmix-framework/jmix/assets/99609936/cb9c7a8b-c9dd-41d7-abf4-60ecebdb62a2)

**AR:** A notification is shown that the file is too large.
**ER:** In the previous version, the notification showed the maximum size. You may need to show the file limit in the notification.
