### ISSUE TITLE
DMN tables editor screen with FlowIU

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1566]
Features:

- [x] Add Decision Table Modeler
- [x] Add Decision Table Views
- [x] Add Decision Table support for Bpmn Modeler UI
- [x] Migrate translations for DMN
- [x] Add Test case sample demo for dmn

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5388-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
