### ISSUE TITLE
Catch Search button onClick event in Filter component

### ISSUE THREAD

**Issue by tmalatinszki** [jmix-framework/jmix#1568]
Hi All,

I have a simple page with a table and the built-in filter control, and I need to run some custom code when user clicks on Search button of the filter panel. Is there any way to catch this click event? Using data loader delegate is not an option in this case.

Thanks,
Tamás

**Comment by gorbunkov** [comment]
In Jmix 2.x this will be probably solved by https://github.com/jmix-framework/jmix/issues/1443
