### ISSUE TITLE
[WebDav] webdavDocumentVersionLink, useLastVersion="true",  standard caption disappears 

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1569]
env
Jmix version: 1.5.999-SNAPSHOT

TC
Open a project with addon Webdav in it
Create Entity with Association attribute (webdavDocument)
Create screens
Add whith edit screen 
` <webdav:webdavDocumentVersionLink id="versionLink" property="webdavDocument"  />`
run project
open edit screen
![image](https://user-images.githubusercontent.com/114649487/229997034-6b242b72-87db-4225-a7f1-87bfe4c58f59.png)
Update webdav:webdavDocumentVersionLink add property useLastVersion="true"
open edit screen

AR
Standard caption disappears. In place of the caption, the file name

ER 
Place the file name after the caption

**Comment by Gavrilov-Ivan** [comment]
Since `WebdavDocumentVersionLink` extends `io.jmix.ui.component.Link` it's imposible to add 'field' caption.
WA - use Label as caption on target layout.
