### ISSUE TITLE
ProgressBar and ProgressBarDialog don't show progress

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#1574]
ProgressBar doesn't show progress. It only updates when you click other elements on the page.

![progressbar](https://user-images.githubusercontent.com/128021710/230404859-8c7349e6-b463-491c-b8cc-bdaf09cd2b59.gif)

ProgressBarDialog doesn't show progress and doesn't disappear unless closed by the user. The progress may update at the moment the dialog is closed.
![backgrounddialog](https://user-images.githubusercontent.com/128021710/230404889-906c2404-a874-4746-a4e7-9aef717949ce.gif)

I used examples based on ones given here: https://docs.jmix.io/jmix/ui/background-tasks.html

**Comment by konyashkina** [comment]
Not reproduced. ProgressBar and ProgressBarDialog work as expected.
@iudaev please give an example project where the error occurs.

**Comment by iudaev** [comment]
Vaadin: 23.3.0
Flow: 23.3.0
Java: Eclipse Temurin 17.0.6
OS: macOS Ventura 13.2.1
Browsers: Firefox 112.0.1, Chrome 112.0.5615.137

Test project:
[progressbar-bug.zip](https://github.com/jmix-framework/jmix/files/11371068/progressbar-bug.zip)

Steps to view ProgressBar:
1. Run project
2. Open Application/progressBar

Steps to view ProgressBarDialog:
1. Run project
2. Open Application/Background tasks view
3. Select users and click **Send email**
