### ISSUE TITLE
Load entities by ids without throwing EntityAccessException

### ISSUE THREAD

**Issue by andreysubbotin** [jmix-framework/jmix#159]

**Comment by andreysubbotin** [comment]
https://github.com/Haulmont/jmix-core/issues/142#issuecomment-832550105

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7059-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)

**Comment by glebfox** [comment]
Entities in the result list have the same order as provided identifiers. If an instance from the list cannot be loaded for some reason, the whole operation fails with `EntityAccessException`
