### ISSUE TITLE
Standard RemoveAction doesn't work with custom DataStore and DTO entities

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1590]
Jmix version: 1.5.1

The problem can be reproduced in [Jmix External Data Store Sample](https://github.com/jmix-framework/jmix-samples/tree/main/external-data-sample).

Create a project, try to delete it. As a result the project won't be deleted.

The reason is that inside the `io.jmix.ui.RemoveOperation` DTO entities aren't passed for commiting into `DataManager`. See `io.jmix.ui.RemoveOperation#commitIfNeeded`:

```java
        List<?> entitiesToCommit = entitiesToRemove.stream()
                .filter(entity -> !entityStates.isNew(entity))
                .collect(Collectors.toList());
```

See [forum topic](https://forum.jmix.io/t/help-with-custom-datastore-removing-entity/2809)

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.999-SNAPSHOT - verified
