### ISSUE TITLE
Error on sequential entity removal from the dataGrid in FlowUI

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1595]
Jmix: 1.5.1

Create an entity with **Versioned** trait.
Generate views for it
Set the selectionMode="MULTI" for the DataGrid
Run the project, create several entity instances
Delete one instance
Try to delete the second instance

AR:
OptimisticLockException

![remove](https://user-images.githubusercontent.com/7888486/231707596-3ee41f91-03ab-4b83-a361-a1e481ae9a07.gif)

It seems that after removal the dataGrid continues to store the removed entity inside its collection of selected items. When the second entity is being removed, both "selected" entities (the current one and the removed one) come to the RemoveOperation.

The project: [flow-remove-2.zip](https://github.com/jmix-framework/jmix/files/11220190/flow-remove-2.zip)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5134-223
IntelliJ version: IntelliJ IDEA 2022.3 (Community Edition)
