### ISSUE TITLE
Hitting Enter on keyboard opens wrong screen when jmix.ui.component.main-tab-sheet-mode=MANAGED

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1598]
Jmix: 1.5.1

1. Create new project with two entities and screens for them (e.g. Order and Customer)
2. Set the [jmix.ui.component.main-tab-sheet-mode](https://docs.jmix.io/jmix/ui/app-properties.html#jmix.ui.component.main-tab-sheet-mode) property to MANAGED
3. Run the app, open Order browse and create an order instance. Select the instance in the browser
4. Open the Customer browse, click by the mouse somewhere, e.g. in the filter area
5. Hit "Enter" on the keyboard - as a result the Order instance editor will be opened, although we are on Customer browse screen

See [forum topic](https://forum.jmix.io/t/enter-key-selects-dormant-screen-selection/2815)

Sample project: 
[untitled4.zip](https://github.com/jmix-framework/jmix/files/11221871/untitled4.zip)

**Comment by FedorovVladislav** [comment]
@knstvk в версии jmix 1.6.2 данная проблема присутствует
