### ISSUE TITLE
The pageSize attribute doesn't work for comboBox

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#1599]
Jmix version '1.5.999-SNAPSHOT' 
IntelliJ IDEA 2023.1 (Community Edition)
io.jmix.studio (1.5.2-231)

1) Create a comboBox with items:

```
      <comboBox itemsEnum="io.jmix.security.model.RowLevelPolicyAction" 
                  pageSize="2" id="comboBox"/>
```
2) Launch the application and make sure that the count of items per page is not changed

**Comment by glebfox** [comment]
Not a bug. Flow UI `ComboBox` doesn't **display** items in pages like the Classic UI. It provides smooth scrolling. The JavaDoc of the `setPageSize` method clearly says that:

> Sets the page size, which is the number of items requested at a time from the data provider. This does not guarantee a maximum query size to the backend; when the overlay has room to render more new items than the page size, multiple "pages" will be requested at once.
The page size is also the largest number of items that can support client-side filtering. If you provide more items than the page size, the component has to fall back to server-side filtering.
