### ISSUE TITLE
Table UI settings should support column expandRatio

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1607]
### Description
See forum [discussion](https://forum.jmix.ru/t/teryaetsya-shirina-kolonok-pri-zakrytii-otkrytii-vkladki/1009).

For now, if table columns contain `expandRatio` attribute it does not saved as setting. Because of this, when we open screen again applied setting will reset `expandRatio`.

For instance. Table with the following columns:
```
<facets>
    <screenSettings id="settingsFacet" auto="true"/>
    ...
</facets>
<layout>
    <groupTable ...>
        <columns>
            <column id="name" expandRatio="4"/>
            <column id="isDirectory" expandRatio="3"/>
            <column id="parent" expandRatio="2"/>
            <column id="uri" expandRatio="1"/>
        </columns>
```
After the second opening:

**ER**
![image](https://user-images.githubusercontent.com/22093943/232401875-fed68ada-5598-4922-9df6-4ee0998f44f5.png)
**AR**
![image](https://user-images.githubusercontent.com/22093943/232401975-9447e0fa-c792-49c8-af4f-d4175035905c.png)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5134-223
IntelliJ version: IntelliJ IDEA 2022.3.3 (Ultimate Edition)
