### ISSUE TITLE
TagPicker does not hide selected items while opening screen

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1614]
### Steps to reproduce
1) Create entities with one-to-many relation and create screens (editor/browser)
2) In editor add `TagPicker` field in order to edit collection
3) Save entity instance with some related entities
4) Open editor again

**ER**
Options do not contain selected items

**AR**
Selected items are also available for selecting

**Comment by KremnevDmitry** [comment]
For QA: 
Reproduced only when the collection container is defined after the instance container:

Ex:
```
 <data>
        <instance id="superEntityDc"
                  class="com.company.bugfix3.entity.SuperEntity">
            <fetchPlan extends="_base">
                <property name="child" fetchPlan="_base"/>
            </fetchPlan>
            <loader/>
        </instance>
        <collection id="childEntitiesDc"
                    class="com.company.bugfix3.entity.ChildEntity">
            <fetchPlan extends="_base"/>
            <loader id="childEntitiesDl">
                <query>
                    <![CDATA[select e from ChildEntity e]]>
                </query>
            </loader>
        </collection>
    </data>
```

**Comment by KremnevDmitry** [comment]
For QA:
Test project attached
[test-project.zip](https://github.com/jmix-framework/jmix/files/11330001/test-project.zip)

Use `SuperEntity` for reproduce

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5134-223
IntelliJ version: IntelliJ IDEA 2022.3.3 (Ultimate Edition)
