### ISSUE TITLE
Unsupported tooltips

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#1615]
Components:

- [x] ComboButton
- [x] DropdownButton
- [x] JmixSimplePagination
- [x] SimplePagination
- [x] AbstractPagination
- [x] JmixUserIndicator
- [x] UserIndicator

Solution 1.5:
Mark as `@Deprecated`

Solution 2.0:
Related to: #1631 
Remove API

**Comment by MaxKatyshev** [comment]
Jmix version: 1.5.999-SNAPSHOT - verified
