### ISSUE TITLE
MultiSelectComboBoxPicker must not have itemsEnum API

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1619]
Picker components mostly work with Entities, that why whey require data binding. Entity doesn't support collection of Enums, so either remove mandatary data binding or remove itemsEnum API

**Comment by KremnevDmitry** [comment]
The accepted solution is to grant access to any method of data binding:
Possible variants:
![image](https://user-images.githubusercontent.com/75516667/236455747-a32bd80f-f347-4744-82d1-196d7a525e01.png)
