### ISSUE TITLE
There is no exportation of more than one parameter

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1629]
**env**
Jmix version: 2.0.999-SNAPSHOT

**TC**
Audit -> Entity log -> Setup
Export existing settings

**AR**
It is possible to select only 1 setting to save

**ER**
When exporting, show the standard download window (All rows, Current page, Select rows, Cancel)

**Discuss** : If one setting is loaded, the file name is equal to the selected entity

**Comment by gorbunkov** [comment]
Like in "Resource roles" screen, the export functionality here is not the same as standard "Excel export" action provides. So standard export action window should not be shown here.
