### ISSUE TITLE
Unsupported tooltips

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#1631]
Components:

- [x] ComboButton
- [x] DropdownButton
- [x] JmixSimplePagination
- [x] SimplePagination
- [x] AbstractPagination
- [x] JmixUserIndicator
- [x] UserIndicator

Solution 1.5:
Related to: #1615 
Mark as `@Deprecated`

Solution 2.0:
Remove API

**Comment by MaxKatyshev** [comment]
Jmix version: 2.0.999-SNAPSHOT - verified
