### ISSUE TITLE
The `name` attribute seems redundant for the datePicker component

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#1636]
See if any of the following needs to be fixed:

* datePicker is the only picker component with HTML attribute `name` in Jmix UI inspector. So may be it should not be present in the inspector.
* Jmix UI Inspector allows you to add a localized message for this attribute, which seems incorrect.
<img width="515" alt="Screenshot 2023-04-25 at 15 37 17" src="https://user-images.githubusercontent.com/128021710/234264931-5d30f5df-f795-4ac6-aa3f-2004e909bd36.png">

**Comment by KremnevDmitry** [comment]
The `name` attribute is needed for the consistency of the XML and Java APIs.
Developers can use it to send values from an input field from a Java script or something like this.

The generated localized message is generated correctly.
