### ISSUE TITLE
Templates for FlowUI views with DTO entity

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1648]
Currently there are no templates for FlowUI views with DTO entity

**Comment by KremnevDmitry** [comment]
Blocked by https://github.com/jmix-framework/jmix/issues/1357

**Comment by rusiaikinat** [comment]
[JST-4065](https://youtrack.jmix.io/issue/JST-4065)  NPE. Cannot invoke "com.haulmont.jmixstudio.model.Entity.isEmbeddable()" because "embeddableEntity" is null

**Comment by rusiaikinat** [comment]
- [x] Kotlin
- [x] Java
