### ISSUE TITLE
onReadyEvent fires multiple times

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#1651]
### After Vaadin 24.0 update.

Possible reason: changes in the logic of the Vaadin dialogs - multiple changes in the "open" state

Steps:
1. Open FlowUI project
2. Add code in the `UserDetailView`

```
    @Subscribe
    public void onReady(ReadyEvent event) {
        if (entityStates.isNew(getEditedEntity())) {
            usernameField.focus();
        }
        getContent().add(new Label("onReady runned"));
    }
```

3. Open ResourceRoleListView
4. Try to assign new user to any role
![regression1](https://user-images.githubusercontent.com/75516667/234801204-ecf5e4ac-64b9-4dba-81ad-69c6831f3537.gif)

Opening with navigation has no regression:
UserDetailView:
![image](https://user-images.githubusercontent.com/75516667/234801616-a9b1bdf0-3ebf-4b7e-b991-67ff191be1a5.png)

----

Caused by: https://github.com/vaadin/flow-components/issues/5103

**Temporal Solution**

Use flag to prevent multiple `ReadyEvent` propagation

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5231-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
