### ISSUE TITLE
Message key is shown instead of message text for validation massages

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1657]
*Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5142-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)*

**Case**

- Open flowui project
- Add quartz addon
- *Optional:*
    * Add new translation addon (e.g. French)
    * Add the same locale (Project properties > Locales > add new, save)
    * Add default message bundle (copy `messages_en.properties` file and delete _en postfix)
- Run project
- *Optional: Change locale to French*
- Login
- Open Quartz > Quartz jobs > Create

AR: message key instead of message text for default locale
![image](https://user-images.githubusercontent.com/73226373/235080945-8cada781-4144-4f25-8c74-7bdca561cda5.png)

**Comment by gorbunkov** [comment]
Duplicates #1749
