### ISSUE TITLE
Update FileTypesHelper initialExtToMIMEMap

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1664]
The following **fileStorageUpload** `accept` attribute definition doesn't allow to select `mp4` files:

```
<fileStorageUpload id="avatarField" property="avatar" accept="*.mp4"/>
```

The result HTML DOM Element:
```
<input type="file" name="files[]" title=" " tabindex="0" accept="application/octet-stream">
```

`application/octet-stream` is set instead of `video/mp4` for the `accept` attribute, because `FileTypesHelper` doesn't know about existing of `mp4` files and set the default value.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5220-223
IntelliJ version: IntelliJ IDEA 2022.3.3 (Ultimate Edition)
