### ISSUE TITLE
Incorrect notification after creating a new quartz job or trigger

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1667]
*Jmix version: 2.0.999-SNAPSHOT*

**Prepare project:**

- use flowui project with quartz addon
- create a simple job class as described in [documentation](https://docs.jmix.io/jmix/quartz/index.html#usage)

**Case 1**

- Open Quartz > Quartz jobs screen
- Create a new job (just set name and class) or edit an existed job > Save

**AR:** incorrect notification
![image](https://user-images.githubusercontent.com/73226373/235743593-71c15081-2a40-480b-99f5-60980b26e6f0.png)

**Case 2**
- Open Quartz > Quartz jobs screen
- Start creating a new job (just set name and class) 
- Create a new trigger > Save

**AR:** ![image](https://user-images.githubusercontent.com/73226373/235747661-c964688c-2ede-4bbe-8b40-d9e2429d96fd.png)

**Note** maybe there are other cases

**ER** smth like this
![image](https://user-images.githubusercontent.com/73226373/235744157-b78d3302-28ca-4f1e-89a4-28a623152246.png)

**Comment by gorbunkov** [comment]
Should be fixed in https://github.com/jmix-framework/jmix/issues/1886

**Comment by lovtsovaik** [comment]
After fix in 1886
saving job:
![image](https://github.com/jmix-framework/jmix/assets/73226373/37deb2c9-640f-4311-b39a-7e00a4bfd408)
saving trigger:
![image](https://github.com/jmix-framework/jmix/assets/73226373/a3ec55c3-7853-4f0b-b1b1-626218aafc00)

**Comment by lovtsovaik** [comment]
Not pretty anyway

**Comment by glebfox** [comment]
> Not pretty anyway

this is because of https://github.com/jmix-framework/jmix/issues/1926
