### ISSUE TITLE
Ability to remove Quartz jobs with invalid class name

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1669]
1. Create several job classes in your application.
1. Manually add several quartz jobs using the "Quartz jobs" screen.
1. Delete one of job classes.
1. Restart the app and open the Quartz Jobs screen

After fixes made in #1551 invalid quartz jobs won't be displayed, but valid jobs will. For invalid job we'll have a warning message in the log.

It would be great if we could see invalid jobs in the Jobs list with some marker indicating that these jobs are invalid. Also users should be able to remove such jobs.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6350-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

Failed - Unexpected error, NPE in entity.getJobState()

Job class is created. And after clicking in button Ok:

![image](https://github.com/jmix-framework/jmix/assets/158277660/8d86693d-c987-4bd7-9395-076bf2e611d0)

there is NPE

![image](https://github.com/jmix-framework/jmix/assets/158277660/aac2c589-830b-450c-b9d0-94b824d9084e)

In java code:

![image](https://github.com/jmix-framework/jmix/assets/158277660/14a3c22e-88b0-493b-97ec-a37df08bf774)

Logs:
[Job NPE log -create new job - JobModelListView_java.txt](https://github.com/jmix-framework/jmix/files/15128113/Job.NPE.log.-create.new.job.-.JobModelListView_java.txt)

**Comment by SergeiAksenov2** [comment]
![image](https://github.com/jmix-framework/jmix/assets/158277660/80e5c6d5-655d-4337-b41b-68be6676d5cd)
