### ISSUE TITLE
End date value is empty for saved trigger in trigger editor

### ISSUE THREAD

**Issue by m-orlova** [jmix-framework/jmix#1670]
**Jmix version:** 1.5.1
**Project:** [testquartz.zip](https://github.com/jmix-framework/jmix/files/11380380/testquartz.zip)

**Steps to reproduce:**
1. Open: Administration -> Quartz jobs
2. Click the "Create" button
3. Specify required fields for Quartz job: "Name" - any value, "Class" - `com.company.testquartz.TestJob`
4. Create trigger: click the "Create" button in the "Triggers" tab
5. Specify required fields in trigger editor and also set values for "Start date" and "End date"
![image](https://user-images.githubusercontent.com/71265042/235858561-3161c426-7e34-42a3-b23e-3f05938a5ed5.png)
6. Click "Ok" in trigger editor
7. Save job
8. Select created job in Job browser and click the "Edit" button
9. In the "Triggers" tab: select created trigger and click the "View" button
**ER:** "End date" contains a value specified in the 5th step.
**AR:** "End date" is empty.
![image](https://user-images.githubusercontent.com/71265042/235859567-eafbf2cb-0f67-48e6-890b-90f791f181ef.png)

**Comment by KremnevDmitry** [comment]
### For QA: 
Need to test on 1.5 (Classic UI) and 2.0 (FlowUI)

**Comment by lovtsovaik** [comment]
verified on 1.5.999-SNAPSHOT (Classic UI) and 2.0.999-SNAPSHOT (FlowUI)
for simple and cron expression, edit and view modes
