### ISSUE TITLE
Can not run the application with BPM addon

### ISSUE THREAD

**Issue by MaxKatyshev** [jmix-framework/jmix#1674]
_Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5151-231
IntelliJ version: IntelliJ IDEA 2023.1.1 (Community Edition)_

Sample project: [bpm.zip](https://github.com/jmix-framework/jmix/files/11383007/bpm.zip)

Steps:
1. Create new Jmix project
2. Install BPM Add-on
```
implementation 'io.jmix.bpm:jmix-bpm-ui-starter'
implementation 'io.jmix.bpm:jmix-bpm-starter'
```
4. Run application

**ER: Run the application**
**AR: Can not run the application**

![image](https://user-images.githubusercontent.com/11402689/235931227-f2d39527-c046-490d-8f84-4be6b67ec125.png)

**Comment by gorbunkov** [comment]
It seems to be fixed
