### ISSUE TITLE
Empty lines appear in the view-only list (multiSelectComboBox, multiSelectComboBoxPicker)

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1680]
Jmix version: 2.0.999-SNAPSHOT

TC
Set the readOnly="true" parameter for multiSelectComboBox or multiSelectComboBoxPicker

AR
It's got empty lines.
![image](https://user-images.githubusercontent.com/114649487/236473221-35453eb7-2805-48cc-83d0-c89cc31ca175.png)

[see project](https://github.com/jmix-framework/jmix/files/11407345/gitFL2.zip)

---

Caused by: https://github.com/vaadin/flow-components/issues/4533

**Comment by gorbunkov** [comment]
Test on pure vaadin and create issue for vaadin.

**Comment by glebfox** [comment]
Original Vaadin issue: https://github.com/vaadin/flow-components/issues/4533
