### ISSUE TITLE
Use dropdown with existing variables in service task

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1681]
When the parameter is clearly a variable, for example:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/5513878/236478709-5e2c2f06-ee5a-4364-8d9b-fc5272379d76.png">

Relates to https://youtrack.jmix.io/issue/JST-3913/Enable-process-variables-discovery-when-entering-the-variable-field-in-service-and-entity-tasks

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6063-233
IntelliJ version: IntelliJ IDEA 2023.3.4 RC
