### ISSUE TITLE
Soft-deleted records are not available in Entity Inspector

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1682]
*Jmix version: 2.0.999-SNAPSHOT*

**Preconditions**
* Use test project:  [flow20.zip](https://github.com/jmix-framework/jmix/files/11414097/flow20.zip)
  *Or create a new entity with all traits* 
* Run the app, login 

**Test Case**
* Open Data Tools > Entity Inspector 
* Select `Soft Deleted Entity`
* Create some instances
* Select one > Remove > Confirm
* Set Show mode = "Show all records" or "Show removed records only"

AR: soft-deleted entity is not shown. 
![image](https://user-images.githubusercontent.com/73226373/236662307-550d6fb4-8a07-4107-a789-f8dc5c8d747b.png)

In DB this record is marked as soft-deleted
![image](https://user-images.githubusercontent.com/73226373/236662563-83eb1192-1455-4eae-b7be-2758d73e24db.png)

ER: such records should be available in the Entity Inspector to have an ability to restore them ore wipe out

**Addition case**

- Set Show mode = "Show all records" or "Show removed records only"
- Select all records
- Call Excel (all rows, current page, selected rows), Export as ZIP, JSON

AR: soft-deleted entities are not present
(move to separate issue is it will not fixed here)

**Comment by yuriy-khrebtov** [comment]
I've fixed json export for removed entities. Other issues (UI, Excel) are not reproduced anymore.
