### ISSUE TITLE
Notes about UI for Entity Inspector

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1683]
*Jmix version: 2.0.999-SNAPSHOT*

**Preconditions**
* Use test project:  [flow20.zip](https://github.com/jmix-framework/jmix/files/11414097/flow20.zip)
  *Or create a new entity with many fields* 
* Run the app, login 
* Open Data Tools > Entity Inspector 
* Select `Soft Deleted Entity`
* Create some records
* Do Import

![image](https://user-images.githubusercontent.com/73226373/236663444-26078ec9-a377-46d1-9a8f-98afd399ff3b.png)

**Note 1 Table headers size**
Table headers are not fully visible. There is no tooltips, no ability to change width of the columns.

**Note 2 Cell content visibility**
The same as for table headers

**Note 3 `Restore` and `Wipe Out` buttons**
I think it will be better to move them together on a new line. In the screenshot, only `Wipe Out` is on the second line

**Note 4 Import file displaying**
File name is not fully visible (and no tooltip for it).
The layout of this element moves the underlying elements down and it looks not pretty. May be put this element to the right of the Import button?

**Comment by gorbunkov** [comment]
I guess we should make column reorderable and resizable.
Instead of setting table width 100% we should give each column a fixed size. In this case a horizontal scroll will appear in case of large columns number. But at least columns content will be readable.

**Comment by lovtsovaik** [comment]
For Note 4 need to decrease width of the window

Case from Note 4 probably was fixed in #1687
