### ISSUE TITLE
Fix localization in reports wizard

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1688]
See [forum topic](https://forum.jmix.ru/t/lokalizacziya-reportswizard/1052).

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.6-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
