### ISSUE TITLE
In-app notification viewer does not preserve newline for messages with Plain content type

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1691]
Try to send a multi-line notification with Plain content type:
```
- abc
- def
- qwe
```

In the viewer, you will see:
<img width="854" alt="image" src="https://github.com/jmix-framework/jmix/assets/5513878/45e58f96-c5c6-4049-87d7-c7c4518e3f58">

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT5221-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
