### ISSUE TITLE
Add Studio component property descriptions

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1701]
Some properties are currently not shown in the palette:

- `Details.opened`: exists in XSD but not in palette
- `DataGrid.multiSelect`: doesn't exist in XSD and in palette

**Comment by KremnevDmitry** [comment]
For `Details.opened`: **FIXED**

For `DataGrid.multiSelect`:

Multiple selection is set using the `selectionMode` attribute.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5210-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
