### ISSUE TITLE
Excel export actions should support exporting all records for KeyValueCollectionContainer

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1703]
It seems that KeyValueCollectionContainer is not supported and the exception is thrown when users try to "Export all":

```
RuntimeException: Cannot export all rows. Data loader must be an instance of CollectionLoader.
```

See [forum topic](https://forum.jmix.io/t/error-exporting-all-rows-to-excel-when-using-keyvaluecollectionloader/2999).

**Comment by jguthrie100** [comment]
@rusiaikinat @yuriy-khrebtov @gorbunkov is there any chance that this could be backported to 1.7? We are an enterprise-scale user and it would be very helpful to have this in 1.7!

**Comment by Flaurite** [comment]
Hello @jguthrie100! We created the issue https://github.com/jmix-framework/jmix/issues/4434 to port this fix to Jmix 1.x.
