### ISSUE TITLE
DeselectAll action in tables does not work correctly when column reordering is disabled

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#1709]
From [forum](https://forum.jmix.io/t/columncontrolvisibility-descriptor-settings-not-working-properly-when-global-configuration-is-applied-for-table-component/3019), sample provided

TC 1:

1. Create project with custom TableLoader, which globally hides Column Control.
2. Create browse screen with multiple columns, hide some of them (collapsed="true"), set columnControlVisible="true" for table.
3. Run project, open that browse screen, switch hidden columns on via Column Control.
4. Try to hide the columns back.

ER: Column is hidden.
AR: Nothing happens.

TC 2:

1) In `user-browse.xml` add to table: `reorderingAllowed="false"`
2) Launch the app and go to Users
3) Click on "Deselect All"

### QA

1) Check: Table, GroupTable, TreeTable

**Comment by rusiaikinat** [comment]
https://github.com/jmix-framework/jmix/assets/114649487/6fa68422-b9d1-4eff-9f3c-e0c8857d417b

```
<hbox caption="treeTable">
                        <treeTable id="checkEntitiesTable2" height="200px" hierarchyProperty="assAttr" width="500px"
                                   dataContainer="checkEntitiesDc" multiselect="true"
                                   columnControlVisible="true" reorderingAllowed="false">
                            <columns>
                                <column id="box1"/>
                                <column id="box2"/>
                                <column id="box3" collapsed="true"/>
                                <column id="assAttr"/>
                            </columns>
                        </treeTable>
                    </hbox>
```

**Comment by Flaurite** [comment]
Now the behavior is the following:
- if only one column is visible - "Deselect All" does nothing
- if 2+ columns are visible - "Deselect All" collapses all columns and makes first column not collapsed.
