### ISSUE TITLE
ComboBox clears value after setting items without options binding

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1710]
### Description
The case is the following.
```
<comboBox id="infoField" property="info"/>
```
`infoField` has a binding with some DataContainer and its property. `ComboBox` does not have options binding, but has manually configured list of items (e,g, with String type, etc) as options. in View controller.

For instance, we have to modify our items for `infoField`, e.g. add/remove some items. **The main thing** is the selected value in `infoField` the same in "old" items and in "new" items.

After setting "new" items, the ComboBox clears the value that produces ComponentValueChangeEvent and entity instance becomes "dirty". So we have false unsaved changes.

Demo project: [combobox-clears-value.zip](https://github.com/jmix-framework/jmix/files/11505723/combobox-clears-value.zip)

**Workaround**
The main idea is to manage manually setting value to field and to entity instance:
1) In `ComponentValueChangeEvent` set value to entity.
2) In `ItemPropertyChangeEvent` and `ItemChangeEvent` set value to the field.
3) When we need to set new items to field, remove `Registration` object of `ComponentValueChangeListener`. Set items, restore value then add listener again.

You can find code in `WaProjectDetailView` class from demo project.

**Comment by gorbunkov** [comment]
Test it and close if the problem cannot be reproduced any more.

**Comment by Flaurite** [comment]
Is not a bug but a misuse of component API.

**Description**
In the case above collection of options is set using `setItems(Collection)` that internally setting `ListDataProvider`. So when we add new item to collection and set it again using `setItems(Collection)` it sets new `ListDataProvider` and resets selected value.

The right way of adding new item is to use `ComboBoxListDataView`. It is returned by calling `setItems()`. For instance:
```
// Setting options to ComboBox
ComboBoxListDataView<String> dataView = comboBox.setItems(List.of("opt1", "op2"));

// Adding new item to options
dataView.addItem("opt3");
```
