### ISSUE TITLE
Save enum name instead of message in BPMN Entity Data Task

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#1715]
1. Create an Entity Data Task in modelerer.
2. Set "Create Entyty" task type, select an entity with an enum field.
3. Add enum attribute, select element.

AR: element saved in xml as a message (e.g. "value": "Not qualified")

Better save it as the element name ("value":"NOT_QUALIFIED") to avoid localization issues.
Implement backwards compatibility.

**Comment by gorbunkov** [comment]
This issue must be implemented both in runtime and Studio modelers

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.4.0-RC1
Jmix Studio plugin version: 2.4.SNAPSHOT6856-242
IntelliJ version: IntelliJ IDEA 2024.2.3
