### ISSUE TITLE
Define process instance listener with delegateExpression in the BPMN modeler

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1717]
We can define a process instance event listener by selecting a class.

Flowable also supports defining a listener using delegateExpression. This will allow to use Spring beans as listeners. See [Flowable documentation](https://www.flowable.com/open-source/docs/bpmn/ch03-Configuration/#listeners-executing-user-defined-logic).

We should add an option to select a delegateExpression for the listener to the BPMN modeler

These changes must be also implemented in Studio BPMN designer.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6060-233
IntelliJ version: IntelliJ IDEA 2023.3.4 RC
