### ISSUE TITLE
WebDav add-on with Flow UI

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1720]

**Comment by dtaimanov** [comment]
Incomplete:
- Fluent builders for Webdav...Links
- drop zones for Upload button, WebdavDocumentUploadField
- Minor bugs in Webdav Document Browser
- Javadocs
- several possible improvements to discuss

Pull requests: 
- https://github.com/jmix-framework/jmix/pull/2291
- https://github.com/jmix-framework/jmix-premium/pull/193
- https://github.com/jmix-framework/jmix-all/pull/6

**Comment by dtaimanov** [comment]
Demo project with hsql and hardcoded document ids for testing: [wd21999.zip](https://github.com/jmix-framework/jmix/files/13064614/wd21999.zip)
(see `contract-detail-view.xml`)
