### ISSUE TITLE
Unable to save data in Editor in one click: buttons are jumping

### ISSUE THREAD

**Issue by ovchinnikovsp** [jmix-framework/jmix#1726]
steps to reproduce: 
1. create a project on FlowUI 1.5.1
2. Create Entity with required attribute and generate details screen
3. Start application, open the entity creation screen
4. Fill out the fields with the valid data and press OK
ER: Data is saved, Details screen is closed 
AR: Just required value message disappeared, so it is necessary press OK again

![edit](https://github.com/jmix-framework/jmix/assets/24627909/f4d3e13c-dba3-4d21-a39f-d1a19e939888)

**Comment by glebfox** [comment]
That's not a bug. The components height is dynamic. In your case, when you try to click the button, the value change is fired and validation message is hidden, so the height of the component is reduced. This is the behaviour of Vaadin components and we don't plan to change it.


The easy solution is either to expand the form or to set `valueChangeMode` to `EAGER` or `TIMEOUT`, e.g.:

```
<layout expand="form">
```

```
<textField id="nameField" property="name" valueChangeMode="TIMEOUT"/>
```

We also plan to implement a view [footer](https://github.com/jmix-framework/jmix/issues/1760) which isn't resolve your issue directly, but can be used to avoid misexpectations.
