### ISSUE TITLE
Define process instance listener with delegateExpression in the BPMN modeler (release 1.6)

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1729]
See https://github.com/jmix-framework/jmix/issues/1717

**Comment by KartnDev** [comment]
UPD: 
commits above is mistake

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6230-241
IntelliJ version: IntelliJ IDEA 2024.1 RC
