### ISSUE TITLE
The user with the system-full-access role cannot open the screens

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1731]
Jmix version: 2.0.999-SNAPSHOT

TC

Open project
[jmix-flowui-oidc-test.zip](https://github.com/jmix-framework/jmix/files/11545574/jmix-flowui-oidc-test.zip)
Run keycloak `http://localhost:8180/auth/`
Create new user
Assign a system-full-access  role to the user
Open project  `http://localhost:8080/#main`

AR
Screens do not open for a user with the system-full-access role
![MicrosoftTeams-image](https://github.com/jmix-framework/jmix/assets/114649487/3acdafe6-a0fa-4895-b868-02ddbfe29b03)

**Comment by gorbunkov** [comment]
Can't reproduce the issue
