### ISSUE TITLE
Search doesn't work properly in attribute selection screen of report wizard

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#1735]
After #839 сheck the reproduction of the bug: https://github.com/jmix-framework/jmix/issues/1587

**Comment by breakingfox** [comment]
Fixed in https://github.com/jmix-framework/jmix/issues/839

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5377-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
