### ISSUE TITLE
Job is saved if incorrect Cron expression is specified for trigger

### ISSUE THREAD

**Issue by m-orlova** [jmix-framework/jmix#1737]
**Jmix version:** 1.5.2
**Sample project:** [testcron.zip](https://github.com/jmix-framework/jmix/files/11553713/testcron.zip)

**Steps to reproduce:**
1. Open menu: Administration -> Quartz jobs
2. Click the "Create" button
3. In opened editor: specify "Name", select "Class"
4. Click the Create button in the Triggers tab:
5. Specify an incorrect value for the Cron expression. For example:
![image](https://github.com/jmix-framework/jmix/assets/71265042/c3fa5196-dd94-4806-8bdf-799e50dcc0b8)
6. Click Ok in dialog
7. Save job
**ER:** Validation or error message is shown, job not saved.
**AR:** Exception is thrown, but job is saved without trigger.
![image](https://github.com/jmix-framework/jmix/assets/71265042/8ea2e4c7-23cc-4a61-8948-87dd54591080)

It would be helpful to have a validation for Cron expressions.

**Comment by lovtsovaik** [comment]
For QA: need to test on 1.5 (classic UI) and 2.0 (flow UI)

**Comment by lovtsovaik** [comment]
For classic (1.5.999-SNAPSHOT):
Notification
![image](https://github.com/jmix-framework/jmix/assets/73226373/4365b282-8ae0-47d7-aa91-741e6ca05b8e)
The record is not saved

**Comment by lovtsovaik** [comment]
ClassicUI - verified
FlowUI - testing blocked by #1804

**Comment by lovtsovaik** [comment]
verified for FlowUI
