### ISSUE TITLE
ORA-00932 (inconsistent datatypes) when running report on Oracle (port from 1.3)

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#1750]
See: #1698

Check reprodusion and fix if it nessesary.

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5303-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
