### ISSUE TITLE
Authorization server add-on with REST API

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1751]
In release 2.0 we're going to remove the security-oauth2 module. The `authorization-server` add-on is going to replace it. We must check all popular usage scenarios of combination authorization-server + rest-api, fix bugs and update the REST API documentation.

**Comment by lovtsovaik** [comment]
While queries from Postman work fine, can't get access using UI.

URLs http://localhost:8080/ and http://localhost:8080/logout redirect to http://localhost:8080/login
White screen
![image](https://github.com/jmix-framework/jmix/assets/73226373/88a0c7db-a3ff-445e-8343-67b82b85e6d9)

In logs:
DEBUG 17992 --- [nio-8080-exec-8] io.jmix.core.AccessLogger                : Denied access to [view: MainView] for user [anonymous] by io.jmix.securityflowui.constraint.FlowuiShowViewConstraint

**Comment by lovtsovaik** [comment]
verified
