### ISSUE TITLE
Filter in DataGrid column headers

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1752]
Like in this example: https://vaadin.com/docs/latest/components/grid/#filtering

**Comment by KremnevDmitry** [comment]
# How to:

To enable filtering in headers, you need to add the attribute `filterable = true` to the `<columns/>`  or `<column/>` tag.

So you can enable filters for all columns:
```
        <columns filterable="true">
            <column property="username"/>
            <column property="firstName"/>
            <column property="lastName"/>
            <column property="email"/>
            <column property="timeZoneId"/>
            <column property="active"/>
        </columns>
```

Or for all except email:
```
        <columns filterable="true">
            <column property="username"/>
            <column property="firstName"/>
            <column property="lastName"/>
            <column property="email" filterable="false"/>
            <column property="timeZoneId"/>
            <column property="active"/>
        </columns>
```

Or only for email:
```
            <columns>
                <column property="username"/>
                <column property="firstName"/>
                <column property="lastName"/>
                <column property="email" filterable="true"/>
                <column property="timeZoneId"/>
                <column property="active"/>
            </columns>
```

**Comment by knstvk** [comment]
Filter indicator must always be visible regardless of the column width, the same as sorting indicator.
```
<columns filterable="true">
    <column property="username"/>
    <column property="firstName"/>
    <column property="lastName"/>
    <column property="email"/>
    <column property="timeZoneId" filterable="false"/>
    <column property="active"/>
    <column property="onboardingStatus"/>
    <column property="department"/>
    <column property="joiningDate"/>
</columns>
```

<img width="1283" alt="image" src="https://github.com/jmix-framework/jmix/assets/5513878/1f10bf85-a393-484c-b254-b87df9031dc2">

**Comment by knstvk** [comment]
Define filterable="true" for a reference attribute. The filter will show entityPicker. Try to select an entity in the picker.
```
java.lang.IllegalStateException: A component 'EntityPicker' is not attached to a view
	at io.jmix.flowui.component.UiComponentUtils.getView(UiComponentUtils.java:268)
	at io.jmix.flowui.DialogWindows.lookup(DialogWindows.java:205)
	at io.jmix.flowui.action.entitypicker.EntityLookupAction.execute(EntityLookupAction.java:167)
	at io.jmix.flowui.action.valuepicker.PickerAction.actionPerform(PickerAction.java:75)
	at io.jmix.flowui.kit.component.valuepicker.ValuePickerButtonActionSupport.lambda$setAction$c6c19f47$1(ValuePickerButtonActionSupport.java:55)
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475)
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447)
	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
	at ...
```

**Comment by KremnevDmitry** [comment]
> Define filterable="true" for a reference attribute. The filter will show entityPicker. Try to select an entity in the picker.
> 
> ```
> java.lang.IllegalStateException: A component 'EntityPicker' is not attached to a view
> 	at io.jmix.flowui.component.UiComponentUtils.getView(UiComponentUtils.java:268)
> 	at io.jmix.flowui.DialogWindows.lookup(DialogWindows.java:205)
> 	at io.jmix.flowui.action.entitypicker.EntityLookupAction.execute(EntityLookupAction.java:167)
> 	at io.jmix.flowui.action.valuepicker.PickerAction.actionPerform(PickerAction.java:75)
> 	at io.jmix.flowui.kit.component.valuepicker.ValuePickerButtonActionSupport.lambda$setAction$c6c19f47$1(ValuePickerButtonActionSupport.java:55)
> 	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233)
> 	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475)
> 	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292)
> 	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447)
> 	at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62)
> 	at ...
> ```

Extracted to the separate issue: https://github.com/jmix-framework/jmix/issues/2369
