### ISSUE TITLE
Action executed by keyboard shortcut in detail view breaks back navigation

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1758]
- Create a detail view, add some shortcuts, for example:
    ```
    <actions>
        <action id="saveAction" type="detail_saveClose" shortcutCombination="META-ENTER"/>
        <action id="closeAction" type="detail_close" shortcutCombination="ESCAPE"/>
    </actions>
    ```
    
- Open the detail view from the list view
- Press the shortcut

ER: the detail view closes, the parent list view opens.
AR: the detail view closes and that's all.

**Reason**

Both `Button` and `View` subscribed to Action `shortcutCombination`

**Comment by glebfox** [comment]
## Breaking changes

The following components no longer take shortcut from actions:

* `Button`
* `ComboButton`
* `ValuePickerButton`

Actions' shortcut added to `HasActions` components and `View` no longer have global scope. Instead, the scope is limited by "actions holder". Below the list of actions holders:

- `View`
- `ValuePicker`
- `EntityPicker`
- `MultiValuePicker`
- `MultiSelectComboBoxPicker`
- `ComboBoxPicker`
- `EntityComboBox`
- `DataGrid`
- `TreeDatGrid`
- `GenericFilter`

**NOTE:**

Shortcuts added by Vaadin API, e.g. using `addClickShortcut()` or `Shortcuts.addShortcutListener()` works according to `ShortcutRegistration` settings, i.e. global by default.

**Comment by natfirst** [comment]
1. Add acrion with shortcutCombination="ENTER"
` <action id="showEntityInfo" type="datatl_showEntityInfo" shortcutCombination="ENTER"/>`
2. Run the app
3. Select some row in dataGrid and press Enter - action invoke
4. Click Add search condition and close dialog
5. Press Enter again 
*A.R.* Both actions invoke
![image](https://github.com/jmix-framework/jmix/assets/17950251/12767f6c-bb67-42d5-8bbb-f73a08e0bf77)
