### ISSUE TITLE
Incorrect header position when run report from a creation wizard

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1761]
Case:

1. Create a new XLSX report using wizard for list of entities
<img width="819" alt="Screenshot 2023-05-31 at 11 27 35" src="https://github.com/jmix-framework/jmix/assets/6077149/35f23015-6819-40be-a022-ff89731ae12a">
2. Run report from wizard:
<img width="821" alt="Screenshot 2023-05-31 at 11 28 47" src="https://github.com/jmix-framework/jmix/assets/6077149/a9c9134f-6fcc-4c4e-a317-824e79fab8fc">

AR:

Header is below of data
<img width="1330" alt="Screenshot 2023-05-31 at 11 28 21" src="https://github.com/jmix-framework/jmix/assets/6077149/a00b9e84-43c3-4612-96cb-5eb4be2eaaa8">

ER:
Header is above of data

Note: after a report is filly created, it works as expected.

**Comment by lovtsovaik** [comment]
Reproduced on 2.0.999-SNAPSHOT

Also, the name of the document is "Template", not "Report"

**Comment by gorbunkov** [comment]
Maybe we should remove the Run report button from the report wizard.

**Comment by NikitaShchienko** [comment]
The `Run` button has been removed.

**Comment by rusiaikinat** [comment]
![image](https://github.com/jmix-framework/jmix/assets/114649487/fb82aedd-b8e1-4e66-9db7-01b5f3bc2262)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6789-241
IntelliJ version: IntelliJ IDEA 2024.1.6 (Community Edition)

2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6790-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)

3) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6791-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

The title is displayed in the report on the first line - Ok.

![image](https://github.com/user-attachments/assets/4fb38da8-4925-4935-bdce-3a552bc3d448)
