### ISSUE TITLE
Content of Email History table is not fully visible

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1763]
2.0.999-SNAPSHOT

Create project with email and do setup
Send some emails 
Open Email History

AR: The columns are narrow, the text is cut off.
There is no way to view the contents of the column without opening a window with full information
![image](https://github.com/jmix-framework/jmix/assets/73226373/7ddaee53-fef1-4373-bdd7-07e3dd021ccf)

**Comment by gorbunkov** [comment]
We need to add columns resize, column collapsing and set autoSize

**Comment by MaxKatyshev** [comment]
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6061-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
verified
