### ISSUE TITLE
Remove "provided" property of data containers and loaders

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1765]
- Remove from XSD and Studio properties
- Remove `hostViewData` parameter of `ViewDataXmlLoader#load`

**Solution**

All data components (data containers and data loaders) no longer have `provided` attribute

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5243-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
