### ISSUE TITLE
Describe Studio properties of KeyValue containers and loaders

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1769]
- keyValueCollection.properties editor
- keyValueCollection.properties.idProperty
- keyValueCollection.loader.query with JPQL designer
- icon for loader

**Comment by KremnevDmitry** [comment]
Instead of the property editor use editing of elements in the Jmix UI Tree.

Old:
![image](https://github.com/jmix-framework/jmix/assets/75516667/1681c791-602a-4dcb-905b-0dfb88e36058)


New: 
![image](https://github.com/jmix-framework/jmix/assets/75516667/26ade59f-b3a6-49ad-bce9-cd0bf3cd3659)

**Comment by rusiaikinat** [comment]
can't add <query>. <properties> not defined

![Image](https://github.com/jmix-framework/jmix/assets/114649487/e68b2feb-3df2-4434-b036-9229395e927a)
