### ISSUE TITLE
rest.enabled specific policy is ignored when acccess token is issued by the authorization server add-on

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1773]
Jmix version: 2.0.999-SNAPSHOT

1. Create a new jmix application
2. Add **rest** and **authorization-server** add-ons
3. Issue access token for a user that has neither the **rest-minimal** nor any other role with **rest.enabled** specific policy
4. Try to access any endpoint of rest-api add-on, e.g. `/rest/entities/User`

ER: Access denied, because the user doesn't have a `rest.enabled` specific policy assigned
AR: User have access to rest api add-on endpoints

**Comment by lovtsovaik** [comment]
Verified with both grant type
