### ISSUE TITLE
Create bpmn-process-form template for Flow UI

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#1775]
[Problem](https://youtrack.haulmont.com/issue/JST-3911/Show-screen-after-creating-it-by-Create-Process-Form-action#focus=Comments-83-7974098.0-0) in Jmix Studio BPMN designer. Need to add Flow UI template for 2.0.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5260-231
IntelliJ version: IntelliJ IDEA 2023.1.2 (Ultimate Edition)
