### ISSUE TITLE
MasterDetails incorrectly enables Edit and Remove buttons for related collection attributes of edited entity

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1779]
Origin: https://forum.jmix.io/t/master-detail-page-table-on-the-right-edit-action-throw-exception-when-creating-new-entity/3083/2

![image](https://forum.jmix.io/uploads/default/original/2X/e/e2fcfb59a69fd1c3addd5a9161c633ef19b238b2.gif)

Run it, go to Cars->Create on the right side of the split panel, switch to Wheels tab, click Edit button.

[demo.zip](https://github.com/jmix-framework/jmix/files/11633906/demo.zip)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.6-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
