### ISSUE TITLE
Fix message.properties for German

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#1780]
**jmix-translations/content/io/jmix/businesscalendarflowui/messages_de.properties:**

<img width="861" alt="image" src="https://github.com/jmix-framework/jmix/assets/47520144/cfab16ad-0943-4b2c-a39f-edd9346768e0">

**Comment by gorbunkov** [comment]
We need to copy all messages from classic UI to FlowUI, replacing "ui" package name with "flowui"
