### ISSUE TITLE
Action `enabled` attribute is handled incorrectly

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1783]
The correct definition in XML:
```
<action id="sayHello" text="Say hello" enabled="false"/>
```

But the action loader expects `enable` instead of `enabled`, see `io.jmix.flowui.xml.layout.support.ActionLoaderSupport#initAction`

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5246-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
