### ISSUE TITLE
Add XML attributes for picker components

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#1787]
Some attributes of picker components can only be edited in the view controller. There should be a possibility to edit them in XML and in Jmix UI inspector. 

Here is the list of such attributes:

datePicker:
- `max` and `min` values (https://vaadin.com/docs/v23/components/date-picker/#min-and-max-value)
- `dateFormat` (https://vaadin.com/docs/v23/components/date-picker/#date-format)
- `weekNumbersVisible` (https://vaadin.com/docs/v23/components/date-picker/#week-numbers) (available in XML but missing in the UI inspector) 
- `helperText` (available in XML but missing in the UI inspector)

timePicker:
- `step` (https://vaadin.com/docs/v23/components/time-picker/#step)
- `max` and `min` values (https://vaadin.com/docs/v23/components/time-picker/#minimum-and-maximum-value)

dateTimePicker:
- `step` (https://vaadin.com/docs/v23/components/date-time-picker/#step)
- `max` and `min` values (https://vaadin.com/docs/v23/components/date-time-picker/#min-and-max-values)
- `dateFormat` (https://vaadin.com/docs/v23/components/date-picker/#date-format)

**Comment by rusiaikinat** [comment]
Descriptor:
```
 <layout>
        <datePicker id="i1" min="2023-07-25" max="2023-07-30"
                    dateFormat = "yyyy-MM-dd"
                    helperText="msg://timePicker.helperText" datatype="date" weekNumbersVisible="true" />
        <timePicker id="i2" label="Appointment time" min="08:00" max="12:00" step="450"/>
        <dateTimePicker id="i3" step="900"  dateFormat="yyyy-dd-MM HH:MM" />
    </layout>
```

Controller:

```
 @Subscribe
    protected void onInit(final InitEvent event) {
        i1.setI18n(new DatePicker.DatePickerI18n().setFirstDayOfWeek(1));

        i3.setMin(LocalDateTime.now());
        i3.setMax(LocalDateTime.now().plusDays(60));
    }
```
