### ISSUE TITLE
Long Class-Path may break the frontend

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#1790]
Port from: https://github.com/jmix-framework/jmix/issues/1571

### For QA:
Add-ons for testing 
BPM Add-on: https://github.com/jmix-framework/jmix/issues/1565
Reports Add-on: https://github.com/jmix-framework/jmix/issues/839

**Comment by lovtsovaik** [comment]
verified with reports, bpm, multitenancy
