### ISSUE TITLE
[port to 2.0] Jmix Quartz: Simple Trigger issues

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#1799]
Port #1624 to release 2.0

**Comment by lovtsovaik** [comment]
The names of modes are not equal in form and in hint
![image](https://github.com/jmix-framework/jmix/assets/73226373/9a5a793b-8aea-4114-8853-ba5e36242f96)

**Comment by lovtsovaik** [comment]
verified
