### ISSUE TITLE
View designer is unavailable on Windows/Linux

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#1801]
See Studio ticket: https://youtrack.jmix.io/issue/JST-3953/View-designer-is-unavailable-on-WindowsLinux

Description: 
On Jmix project 2.0+ with Jmix Studio 2.0+ View Designer is unavailable (or takes a very long time to load).

Cause:
Vite dev server configuration

For QA:
1. Create new Jmix project with Flow UI (with fresh Jmix Studio plugin).
2. Open any view descriptor.
3. Wait frontend build (open Console and see logs).
ER: The View Designer Preview should be displayed after an adequate time (after successful build of the frontend ~1-3 seconds)

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5246-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
