### ISSUE TITLE
Pessimistic locking - management UI

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#181]

**Comment by gorbunkov** [comment]
We need a screen that displays information about locked entity instances and allows to unlock them.

There is no documentation about pessimistic lock mechanism yet, but some keywords required for working on the issue may be found in the [documentation issue](https://github.com/jmix-framework/jmix-docs/issues/387).

Also, it may be useful to look at pessimistic locks screen in CUBA.
