### ISSUE TITLE
Not all elements are visible in the dialog window

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1812]
TC
Resource roles
Select role -> Assign to users

AR
![image](https://github.com/jmix-framework/jmix/assets/114649487/ad700fb0-dd6d-4638-b667-f23f2e4a4ffc)

Select and Close buttons are not visible

**Comment by glebfox** [comment]
Duplicates https://github.com/jmix-framework/jmix/issues/1858
