### ISSUE TITLE
Business calendar Add-on: some calendars are shown twice or more in the list 

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#1814]
**Steps to reproduce:** 
1. Run the app, log in, open Business calendars
2. Add a new calendar.
3. Add some records to the calendar (holidays, working hours).
4. Save the calendar.
5. Close the list.
6. Open the Business calendars list again. 

**ER:** The calendar is shown once in the list.
**AR:** The calendar is shown twice or more. 

![bc20_multi](https://github.com/jmix-framework/jmix/assets/85500330/289b8447-7b81-4446-9bda-f2b2e417e752)

![bc20_multi-new](https://github.com/jmix-framework/jmix/assets/85500330/12102576-4c82-475f-8b11-889fc9e9057f)

**Comment by NikitaShchienko** [comment]
The problem is related to https://github.com/jmix-framework/jmix/issues/1840

**Comment by NikitaShchienko** [comment]
Fixed to https://github.com/jmix-framework/jmix/issues/1815

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5295-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
