### ISSUE TITLE
Change settings in blank screen templates

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#1816]
Need to change some template settings for _Blank View_ and _Bpm Process Form_
See Studio ticket https://youtrack.jmix.io/issue/JST-3974

**Comment by m-shambarova** [comment]
Tested on:

Jmix version: 2.0.999-SNAPSHOT

Jmix Studio plugin version: 2.0.SNAPSHOT5258-231

IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
