### ISSUE TITLE
Token revocation doesn't work in authorization server add-on

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1818]
Jmix: 2.0.999-SNAPSHOT

1. Create new project with REST API and Authorization server add-ons
2. Obtain new access token as described in the authorization server add-on [README](https://github.com/jmix-framework/jmix/blob/master/jmix-authserver/README.md#obtaining-access-token).
3. Access any rest api controller, e.g. /entities/User using this token - you'll get the data
4. Revoke the token using the revocation endpoint: `/oauth2/revoke` (see [spec](https://datatracker.ietf.org/doc/html/rfc7009#section-2.1) for request parameters).
5. Try accessing the protected endpoint (`/entities/User`) using the revoked token

ER: you won't be able to get data, because the token has been revoked
AR: you get the data

**Comment by lovtsovaik** [comment]
Verified with Client Credentials Grant Type
