### ISSUE TITLE
Business calendar Add-on: sorting doesn't work for some fields

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#1835]
_Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5256-231
IntelliJ version: IntelliJ IDEA 2023.1.2 (Ultimate Edition)_

**Steps to reproduce**
Run the app, log in, open Business calendars.
Create or open a business calendar.
Go to Additional business days
Try to sort lines by:

- Start time
- End time

Go to Working schedule, try to sort lines by:

- Day of week
- Business hours

Holidays,  try to sort lines by:

- Type
- Value.

**Comment by NikitaShchienko** [comment]
Problem for nested fields (Start time, End time):
[FlowUI] Sorting not working for nested fields #1842

**Comment by NikitaShchienko** [comment]
**Result:**
Sorting by column is disabled for all tabs in the business calendar editor.

**Default sort:**

1. Holiday: Sort by **type**.
2. Working schedule: Sort by **days of the week**, as well as business hours are sorted by start time.
3. Additional business days: Sort by **date**.
