### ISSUE TITLE
[DataGrid] Sorting not working for columns if column key isn't equal to property

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#1842]
```
<dataGrid id="booksTable"
          width="100%"
          minHeight="20em"
          dataContainer="booksDc">
    <actions>
        <action id="create" type="list_create"/>
        <action id="edit" type="list_edit"/>
        <action id="remove" type="list_remove"/>
        <action id="refresh" type="list_refresh"/>
    </actions>
    <columns>
        <column key="bookName" property="name"/>
        <column property="author.name"/>
    </columns>
</dataGrid>
```

Sorting for `<column key="bookName" property="name"/>` doesn't work because `key != property`
Sorting for `<column property="author.name"/>` doesn't work because `key != property` (autogenerated `key` == `name`)

[twice-row-sample.zip](https://github.com/jmix-framework/jmix/files/11758879/twice-row-sample.zip)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5281-231
IntelliJ version: IntelliJ IDEA 2023.1.2 (Ultimate Edition)
