### ISSUE TITLE
Trigger description is not localized

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#1844]
Currently TriggerModel#getScheduleDescription (and JobModel#getTriggerDescription that collect descriptions from related triggers) generates value based on internal textual literals and this value is not localized.

Suggest to create generated table columns related to these properties and build result values at the screen side based on localized message template.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3
