### ISSUE TITLE
Rename authorization server artifact to jmix-authserver

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1846]
Currently the artifacts coordinates are:

* `io.jmix.authserver:jmix-authorization-server`
* `io.jmix.authserver:jmix-authorization-server-starter`

Artifact names should follow other jmix add-ons naming conventions and should be:

* `io.jmix.authserver:jmix-authserver`
* `io.jmix.authserver:jmix-authserver-starter`

Directory names and application properties names should also be renamed.

**Comment by lovtsovaik** [comment]
verified
