### ISSUE TITLE
Remove @DialogMode height attribute

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1858]
Currently, the default value: `@DialogMode(width = "50em", height = "37.5em")`, as the result, dialog window has scroll:

<img width="834" alt="Screenshot 2023-06-19 at 12 24 27" src="https://github.com/jmix-framework/jmix/assets/6077149/241928b9-f2d3-4b8c-9f4b-dfe4d7e54774">

Having `@DialogMode` without `height` resolves the issue:

<img width="850" alt="Screenshot 2023-06-19 at 12 25 32" src="https://github.com/jmix-framework/jmix/assets/6077149/4f9bd820-2259-49ef-9091-490757770c5f">

**For QA:** Check project template and list view templates (java, kotlin)

**Upd:** default `width` has been changed to `64em` (`1024px` with default font size) instead of `50em` (`800px`)

**Comment by MaxKatyshev** [comment]
width = 50em is too small. Testing on Mac 13 inches. Need to increase width
<img width="1190" alt="Screenshot 2023-06-26 at 16 40 28" src="https://github.com/jmix-framework/jmix/assets/11402689/2bdcd949-05ba-41fd-8c6a-87b36ae92066">

**Comment by glebfox** [comment]
default `width` has been changed to `64em` (`1024px` with default font size) instead of `50em` (`800px`)

**Comment by MaxKatyshev** [comment]
Jmix version: 2.0.999-SNAPSHOT - verified
