### ISSUE TITLE
[Bpmn modeler] Add translations for modeler views and models

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#1859]
For modeler feature and translations for new messages:

- [x] Modeler views messages translations
- [x] Modeler models messages translations

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5305-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
