### ISSUE TITLE
Business calendar Add-on: Entity is deleted on update

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#1868]
**Test case:**
- Create a business calendar with a holiday
- Close a creation dialog
- Open the business calendar and update the holiday entity
- Save the business calendar 

**ER:** Holiday entity updated
**AR:** Holiday entity removed

**Comment by NikitaShchienko** [comment]
Not reproduce, please retest.

**Comment by konyashkina** [comment]
_Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5295-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Ultimate Edition)_

Holiday entity updated successfully, exept https://github.com/jmix-framework/jmix/issues/1845
