### ISSUE TITLE
BPM: titles aren't shown in full and look the same on Process instances screen

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#1875]
BPM > Process instances
Some titles releated to process definition aren't shown in full and look the same.

_Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5281-231
IntelliJ version: IntelliJ IDEA 2023.1.2_ 

```
<column property="processDefinitionKey"/>
<column property="processDefinitionName"/>
<column property="processDefinitionVersion"/>
```
these titles are displayed confusingly similar: 

![bpm20-process-def-many-titiles](https://github.com/jmix-framework/jmix/assets/85500330/bfdbdf70-a352-4712-9772-24d6027bd9bf)

#### Solution:
Columns are resizable now

**Comment by dtaimanov** [comment]
1. Make columns resizable (+ flex grow?) on process instance list view
and/or 
2. Merge pd key and name

**Comment by dtaimanov** [comment]
Made columns resizable.
"Process definition key" and "Process Definitin name" are not merged in order to preserve ability to sort by key or name.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
