### ISSUE TITLE
Business calendar Add-on: redundant information in notifications

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#1879]
_Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5281-231
IntelliJ version: IntelliJ IDEA 2023.1.2 (Ultimate Edition)_

 **Steps to reproduce:**

1. Run the app, log in, open Business calendars
2. Add a new calendar.
3. Add some records to the calendar and  pay your attention to notifications on the top: 
 
- holidays 
-  working hours 
- additional days.
 

**AR:** Redundant information in notifications
![bc20_holiday-message](https://github.com/jmix-framework/jmix/assets/85500330/f9c40c64-b3b7-4cf5-ba1b-823100c8b682)

![bc20_why-its-shown](https://github.com/jmix-framework/jmix/assets/85500330/4736b2fb-660b-426a-b70f-52b1da0e3332)

![bc20_why-its-shown2](https://github.com/jmix-framework/jmix/assets/85500330/5960523d-2d18-4617-a54e-165dbe0e834c)

**ER:** Clear message like below: 
 
![bc20_clear-message](https://github.com/jmix-framework/jmix/assets/85500330/7d1eaa23-cc20-4e0a-b07f-1a68c5d2bc57)

**Comment by NikitaShchienko** [comment]
Related to https://github.com/jmix-framework/jmix/issues/1886

**Comment by lovtsovaik** [comment]
For Holiday - ok
![image](https://github.com/jmix-framework/jmix/assets/73226373/7b16ff71-a08a-4672-9b30-52902a1391c2)

For working hours and additional days - need to improve
![image](https://github.com/jmix-framework/jmix/assets/73226373/dd4efb69-1e4c-4e43-95b3-e3672463bfd2)
![image](https://github.com/jmix-framework/jmix/assets/73226373/02d39fe8-4d8c-43b2-859f-ee97dd7197e7)

**Comment by lovtsovaik** [comment]
verified
![image](https://github.com/jmix-framework/jmix/assets/73226373/002bb21c-88ef-4dae-ad03-f8c5fdd60db5)
![image](https://github.com/jmix-framework/jmix/assets/73226373/3fe756e1-ab99-4c93-8054-594d2162c0cd)
