### ISSUE TITLE
No notification about the mandatory filling of the "Report name" field

### ISSUE THREAD

**Issue by m-shambarova** [jmix-framework/jmix#1882]
**Env**
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5281-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
Win

**TC:**

- Report->Report
- Create->Using Wizard
- Fill in the required fields(step1)
- Clear value in the"Report name" and click on Next

**AR:** There is no notification about the mandatory filling of the "Report name" field. The system allows you to proceed to the next step without mandatory filling.
**ER:** The "Report name" field is required to be filled in and therefore there should be a notification if the field is not filled in (and without filling it out, do not allow you to proceed to the next step)

**Comment by breakingfox** [comment]
Fixed in https://github.com/jmix-framework/jmix/issues/1898

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5377-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
