### ISSUE TITLE
Move notification about closing browser tab functionality to View base class

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1885]
See: https://github.com/jmix-framework/jmix/issues/1243

### Solution

`View` base class contains public methods:

* `setPreventBrowserTabClosing(boolean)`
* `isPreventBrowserTabClosing()`

For QA:

1. Check that Detail views still by default have this setting enabled
2. Check that every other view can enable this setting, e.g.:

```
public class UserListView extends StandardListView<User> {
    @Subscribe
    public void onInit(final InitEvent event) {
        setPreventBrowserTabClosing(true);
    }
}
```

**Comment by lovtsovaik** [comment]
isPreventBrowserTabClosing() - works
setPreventBrowserTabClosing(true/false) - doesn't work
