### ISSUE TITLE
Improve display of object save message

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#1886]
When saving an entity without `@InstanceName` , the default name of the java object is displayed. 

**Example:**
<img width="926" alt="image" src="https://github.com/jmix-framework/jmix/assets/47520144/7cfc90c3-0ed2-4729-b70a-7ed8ec20efda">

**Method:**
`io.jmix.flowui.view.StandardDetailView#getSaveNotificationText`

```
return messages.formatMessage("", "info.EntitySaved",
messageTools.getEntityCaption(metaClass),
instanceNameProvider.getInstanceName(getEditedEntity()));
```

If `@InstanceName` occurs, outputs an empty string.

**Example:**
Holiday saved successfully!

## Solution

* `InstanceNameProvider` now contains a method to check if an entity class has `@IntanceName`. 
* Added a new message key: `info.EntitySaved.short`

**Comment by lovtsovaik** [comment]
verified
