### ISSUE TITLE
Use "small" theme variants for all components in BPM modeler

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1891]

**Comment by gorbunkov** [comment]
Also, we should consider having most of details boxes collapsed. For example, for the user task properties panel, the fields group for task id/name and assignee may be expanded, other panels may be collapsed. 
We may also consider storing collapsed stated for panels of the same type, e.g when we expanded the "Task listeners" panel for one user task, the panel should be dispay as expanded when we select any other user task element on the canvas.

**Comment by KartnDev** [comment]
Collapse variant feature will be added in https://github.com/jmix-framework/jmix/issues/2030

**Comment by KartnDev** [comment]
Small variant feature fixed in https://github.com/jmix-framework/jmix/issues/1992
