### ISSUE TITLE
Cosmetic changes in Reports UI

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#1892]
1. Fix menu order: it must be 1100.
2. Change all headers inside tabs to h4 (Cross parameters validation, Resource roles, Views).
3. Rename "Values formats" to "Value formats".
4. Rename "Multi Datasets" to "Multiple Datasets"
5. Rename "Visible for REST API" to "Available through REST API".
6. Rename "Script editor view" dialog to "Script" (or better remove header at all) and make the dialog resizable.

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5299-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
