### ISSUE TITLE
General remarks in Wizard

### ISSUE THREAD

**Issue by m-shambarova** [jmix-framework/jmix#1898]
**Env**
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5281-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
Win

- [x] 1. _Missing extra text in wizard_. Seen on pages: Step1,  Step 2 , Step 3 . The Report Region screen has additional text, but it mentions **charts**. This point needs to be clarified.
New
![image](https://github.com/jmix-framework/jmix/assets/99609936/3bffedfe-e3f2-4729-ab86-05b3f64332c6)
Old
![image](https://github.com/jmix-framework/jmix/assets/99609936/afd4b6b3-2e3b-4923-b5b2-c01fe11c0266)
---

- [ ] 2. _On the first screen of the wizard, a new field "Group" appeared, which was not in the previous version(see screenshot
in first paragraph)_
---

- [x] 3. _Wizard title text is different from the previous version. Seen on pages: Step1,  Step 2 , Step 3, Report Region_
New
![image](https://github.com/jmix-framework/jmix/assets/99609936/43dd3e80-b8b9-47bd-ab54-76a069076260)
Old
![image](https://github.com/jmix-framework/jmix/assets/99609936/6129cdc3-f448-4b5e-85a3-7257a6b5830f)
---

- [x] 4. _Buttons are not fully shown on the wizard screen(Report region). Tested on 1366*768._
![image](https://github.com/jmix-framework/jmix/assets/99609936/978326a2-e4a3-4317-b830-84278b3b84d8)
---

- [x] 5. The name of the attribute looks strange in the screen Report region (I selected the report entity)
New
![image](https://github.com/jmix-framework/jmix/assets/99609936/86f75cb0-8524-49ff-834a-ee5f9ab9a5ad)
Old
![image](https://github.com/jmix-framework/jmix/assets/99609936/5704ad11-6fa8-44f4-8340-23b140f98681)
---
- [x] 6. Screen(step 2) is different from the old one:
-the name of the column "Name"(should be"Region name")
-the order of the columns should be different
-when you click on the attribute, the report region screen opens
New
![image](https://github.com/jmix-framework/jmix/assets/99609936/8ef201e2-3494-4ecc-b40c-85e8cd7a9fcd)

Old
![image](https://github.com/jmix-framework/jmix/assets/99609936/d29083da-051a-4abb-a345-2600be10d31f)

---

- [x] 7. Sorting not working(Screen step 2)
![image](https://github.com/jmix-framework/jmix/assets/99609936/8276f1c9-c46c-43e5-8e51-63c561369555)
---

- [x] 8. Notifications about mandatory fields without localization (Screen step 3)
![image](https://github.com/jmix-framework/jmix/assets/99609936/47ff0a7a-275c-4667-b344-deb9cb99d0e4)
---

- [x] 9. The template download link looks like plain text (Screen step 3). Maybe we should make the template download option more understandable.
![image](https://github.com/jmix-framework/jmix/assets/99609936/9301e847-f08c-4186-9411-b6e767f8447b)
---
- [x] 10. In the old version on the last screen  of the wizard  "Default template, Group"fields were required
New
![image](https://github.com/jmix-framework/jmix/assets/99609936/9f6e394a-b050-49bb-889f-3b3834ea5356)
Old
![image](https://github.com/jmix-framework/jmix/assets/99609936/c346aea2-611d-4194-b00e-e0347e6c8772)

**Comment by breakingfox** [comment]
Group field is now required in wizard

**Comment by m-shambarova** [comment]
**Reopened**
11. I propose to remove the  "Report wizard" title and leave it at the top only  "Report creation.." (for other steps, do the same)
![image](https://github.com/jmix-framework/jmix/assets/99609936/95293d9b-0c0c-485f-9acc-9dd17d01c373)

**Comment by m-shambarova** [comment]
12. Zoom > 80% the horizontal stripes disappear.
![image](https://github.com/jmix-framework/jmix/assets/99609936/1f64a927-e57c-41e4-8073-0b851e09c63f)

**Comment by m-shambarova** [comment]
13.  Screen(step 2) perhaps it is worth highlighting the clickable attributes link with color (when you click on the attribute, the report region screen open)
![image](https://github.com/jmix-framework/jmix/assets/99609936/eb493e7a-8158-4540-bda2-b685b9b6fa87)

**Comment by m-shambarova** [comment]
14. Screen(step 3) Incorrect notifications about required empty fields (If a specific field is not specified, which must be filled in - show one general notification).
![image](https://github.com/jmix-framework/jmix/assets/99609936/4d00cd58-7823-426e-83fd-1fed93db034d)
