### ISSUE TITLE
Wrong focus on properties panel when an element is selected in BPMN modeler

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1906]
Jmix: 2.0.999-SNAPSHOT

1. Open the BPMN modeler
2. Add User Task
3. Click on it

AR:
The properties panel is scrolled to the middle and the Multi-instance type field is focused. The same thing happens for other elements as well (e.g. Call Activity)

<img width="1359" alt="image" src="https://github.com/jmix-framework/jmix/assets/7888486/daa15f61-435c-4800-ac72-7b189317b374">

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.0-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
