### ISSUE TITLE
Bad response when trying to get access to url without token

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1909]
jmix version 2.0.999-SNAPSHOT

1. create project with rest and authserver addons
2. run the app
3. try to send a request to http://localhost:8080/rest/entities/User without any authorization

ER: short error about required token. Code != 200
AR: [response.txt](https://github.com/jmix-framework/jmix/files/11835061/response.txt)
![image](https://github.com/jmix-framework/jmix/assets/73226373/267d573f-7f56-44ea-a23b-05f1eb4d5a10)

**Comment by knstvk** [comment]
Fixed in #3397
