### ISSUE TITLE
Reports Add-on:  Add translations for views and models

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#1912]
**Tasks:**
- [x] Views messages translations
- [x] Models messages translations

**Note:**
Added EN and RU messages.properties for FlowUI

**Comment by swarakaka** [comment]
Hello @NikitaShchienko , will the translations be different from those of classic ui? If yes, then I am ready to translate Kurdish Sorani texts immediately before version 2.0.

**Comment by NikitaShchienko** [comment]
Hello @swarakaka ,

Thank you. Yes, some names are different, the correct messages for English can be found in `jmix-reports/reports/src/main/resources/io/jmix/reports/messages.properties`. You can create a PR with a translation, after we check it, we will definitely add it to the project


Regards
Nikita
