### ISSUE TITLE
Bad scaling for upload component

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1916]
Jmix version: 2.0.999-SNAPSHOT

Add <upload uploadText="text"/> to any view
Change scale

AR:
![image](https://github.com/jmix-framework/jmix/assets/73226373/8c7e20f4-c02f-436f-a4ec-c357b7eb27b8)

![image](https://github.com/jmix-framework/jmix/assets/73226373/2eb9e7df-8999-40dc-9607-d5ffd0bab4b9)

![image](https://github.com/jmix-framework/jmix/assets/73226373/a78b6cf9-2611-4c6b-87a9-1c15a1456ac0)

**Comment by Flaurite** [comment]
This is Vaadin component - `Upload`. Jmix doesn't have CSS classes that can affect visual behavior of `Upload`. The responsiveness is provided by Vaadin and we won't change it.
