### ISSUE TITLE
DataGrid column visibility control

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1925]
Inspiration: https://vaadin.com/docs/latest/components/grid#column-visibility

**Comment by yuriy-khrebtov** [comment]
New GridColumnVisibility component has been implemented. It can be added
using xml:
![image](https://github.com/jmix-framework/jmix/assets/142792860/f60e8e77-f6d2-4ac4-b1ed-0c826b11d331)

or in view controller code:
![image](https://github.com/jmix-framework/jmix/assets/142792860/efbf8d6b-f2d6-46de-bde1-abc5a5fed456)

To make the component work we need to specify a grid which columns will be managed by the component using `dataGrid` attribute in xml or `columnVisibility.setGrid(detailsGrid)` in Java code.

By default item text is copied from column header. We can customize it using `<columnItemParam>` or in Java code using 
`columnVisibility.getColumnItem("name").setText("Name");`
Column items of column visibility component are created after view Init phase, tracking of column header changes in runtime is not supported.

Tracking of grid column set is also not supported, if we remove/add some columns in runtime we need to remove/add linked items from/to visibility component either.

**Comment by yuriy-khrebtov** [comment]
For the moment we get an exception on client side which doesn't affect component work. The issue is described here https://github.com/vaadin/flow-components/issues/5653
