### ISSUE TITLE
Add localization for Quartz entity names

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1926]
Non of quartz entities have localization for their names

* JobModel - `io.jmix.quartz.model/JobModel`
* TriggerModel - `io.jmix.quartz.model/TriggerModel`

## Solution 

Added en and ru localizations

For QA: check also #1667

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
