### ISSUE TITLE
Cosmetic changes for report screens

### ISSUE THREAD

**Issue by m-shambarova** [jmix-framework/jmix#1928]
Env
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5281-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
Win

1. _I propose to reduce the size of the table and the multi-line field on the Parameters tab, since they take up a lot of space on small screens( e.g. 1366*768). I also suggest move "Full screen" button closer to code editor_
New
![image](https://github.com/jmix-framework/jmix/assets/99609936/f930d758-0f6c-4c19-911b-29d48e373281)

Old
![image](https://github.com/jmix-framework/jmix/assets/99609936/e3438032-4306-4118-b9da-d9db57a31a92)

---
2. _On the "Bands" tab it might be worth:_
- add the heading "Script" to the code editor and think about how to save space. 
-  move "Full screen" button closer to code editor
- reduce the size of the "Dataset" table
![image](https://github.com/jmix-framework/jmix/assets/99609936/c0b7d0b4-a7d8-4a38-9517-39e076af6552)
![image](https://github.com/jmix-framework/jmix/assets/99609936/7783a94c-6534-4a53-a2a4-a3f71625ff19)

---
3. On the "Roles and views" button names are different. I propose to generalize.
![image](https://github.com/jmix-framework/jmix/assets/99609936/3a7ac09e-d109-4718-b1c6-72325b91c080)
---

4. On the 'Run report' screen add a formatter for the "Updated after" field.
![image](https://github.com/jmix-framework/jmix/assets/99609936/79e04e02-8a8f-4199-91e2-1f32c2e48136)
---

**Comment by sukhova** [comment]
The **Add** button is too close to the right edge of the screen. It is necessary to make an indent
<img width="1242" alt="MicrosoftTeams-imagedb4965068ac53bba5af0cb19713fc27906c13949725de198f447b31677e48489" src="https://github.com/jmix-framework/jmix/assets/40686909/8b2d75e2-8f8d-4994-88fe-29759b5efd0f">

**Comment by sukhova** [comment]
<img width="545" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/6debf32b-d030-458b-b84f-ebfe88938d29">

It should be "Entity selection view" here

**Comment by sukhova** [comment]
<img width="799" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/fc0d90d6-5acb-4501-9a12-32cb76228103">
I think, this message should be localized.

**Comment by sukhova** [comment]
<img width="799" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/6b8fe3ab-5ebc-426b-be2d-9100ba5b2963">
It should be "Format string" here

**Comment by breakingfox** [comment]
1. Full screen button stays as it is
2. Helper button near codeeditor can't be perfectly alligned with leabeled editor
3. Formatters for date field and component margin  with scroller should be implemented in jmix in general in future, not here

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5377-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
