### ISSUE TITLE
RuntimeException when download the report result in the Show report table view

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#1933]
1. Create a report with **Table** template via the Report Wizard
2. Open the **Reports → Show Report Table** view
3. Click on the **Excel** button and select the **All rows** item

**AR**:
RuntimeException: Cannot export all rows. Data loader must be an instance of CollectionLoader.
[log.txt](https://github.com/jmix-framework/jmix/files/11866599/log.txt)

**Comment by gorbunkov** [comment]
Probably caused by https://github.com/jmix-framework/jmix/issues/1570

**Comment by NikitaShchienko** [comment]
Fixed to #1570

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5377-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
