### ISSUE TITLE
BPM: Text markup is shown in dialog message 

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#1936]
Text markup is shown in a dialog message when we start BPM process.

_Jmix version: 2.0.999-SNAPSHOT_

BPM > Process definitions > Start process

**ER:**  Correct dialog message without markup  ("Do you want to start the process MyTestProcess?")
**AR:**  There are markup  tags like **b** and **div**.
 
![bpm20-markup-in-text](https://github.com/jmix-framework/jmix/assets/85500330/918c7c83-8f5d-47cc-8253-52f7a2555b4e)

**Comment by konyashkina** [comment]
Also in My tasks: 

![bpm20-markup-in-text2](https://github.com/jmix-framework/jmix/assets/85500330/01d3dd92-03b2-4b49-8435-e8afbe9255e7)

**Comment by dtaimanov** [comment]
+ other dialogs

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5349-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Ultimate Edition)
