### ISSUE TITLE
Add localization for RowLevelRoleModel and ResourceRoleModel 

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1937]
**Steps**
Create new role (resource or row-level)
Look at the notification

AR:
![image](https://github.com/jmix-framework/jmix/assets/73226373/231c8da8-6bd7-411b-9536-ede62f2972b3)
![image](https://github.com/jmix-framework/jmix/assets/73226373/1c46884d-3336-4eac-8885-746a87afd900)

ER: 
Resource role ...
Row-level role ...

**Comment by breakingfox** [comment]
Не воспроизводится в 2.0 и 2.1 версиях

![image](https://github.com/jmix-framework/jmix/assets/57682864/7be1a826-bfbe-44f8-bd18-167529e904dc)
