### ISSUE TITLE
ReportingException when applying parameter validation 

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#1943]
Jmix version: 2.0.0-RC2
Jmix Studio plugin version: 2.0.SNAPSHOT5289-231
IntelliJ version: IntelliJ IDEA 2023.1.3 (Community Edition)

1) Create a report via the report wizard with parameter, for example of number type:

<img width="1137" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/4703533a-1b18-4c32-94d8-f35a408835d8">

<img width="634" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/de5064cb-26b2-4fbd-ae0a-ba512f789465">

2) Set the validation script for this parameter:

<img width="633" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/8db322cf-6957-453d-a9f9-ff2e71bdc270">

Run the report

**AR**:
<img width="631" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/806112a3-564e-46b1-9e42-154fd878aca0">
[log2.txt](https://github.com/jmix-framework/jmix/files/11882833/log2.txt)

**Comment by m-shambarova** [comment]
**Reopened**
1. An error occurs when trying to run a report.

[stacktrace.txt](https://github.com/jmix-framework/jmix/files/12170251/stacktrace.txt)
_Note:_ I tried to create a similar report from the ticket description.  I used the project from the documentation [Jmix Samples](https://github.com/jmix-framework/jmix-samples-2)
[Report for entity _Book_.zip](https://github.com/jmix-framework/jmix/files/12170196/Report.for.entity._Book_.zip)

**Env:**
Jmix version: 2.0.0
Jmix Studio plugin version: 2.0.SNAPSHOT5377-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5377-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
