### ISSUE TITLE
Reports Add-on: Error with date type conversion in input parameters

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#1949]
Test case:

1 - Create Report for list of entities (For example, for the base Report entity)
2 - Create query
```
select e.createTs from report_Report e where e.createTs = :createTs
```
3 - Generate date input parameter for query
4 - Save report
5 - Run report

**AR:** Exception
```
ReportingException: An error occurred while loading data for band [Reports] and query [Dataset]. Report name [Date error report]
An error occurred while loading data for data set [Dataset]
You have attempted to set a value of type class java.time.LocalDateTime for parameter param_1 with expected type of class java.util.Date from query string select
e.createTs from report_Report e where e.createTs = :param_1.
```
**ER:** Report completed successfully

Report:
[Date error report.zip](https://github.com/jmix-framework/jmix/files/11892368/Date.error.report.zip)

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5377-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
