### ISSUE TITLE
Extract system screens from the flowui module

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1958]
Pessimistic lock management screen and upcoming JMX console screens are located inside the flowui module. We should consider extracting these screens with "business" functionality into another module. The flowui module should contain only UI components, screen API, etc.

**Comment by KremnevDmitry** [comment]
# Possible solutions:

Extract the `PessimisticLock` view from the FlowUI module is quite simple.
However, allocating a separate module for only one view seems to be an irrational solution.

It is possible to extract the pessimistic locking logic from the `core` module and create separate modules for the `core` and `ui` of the pessimistic locking functionality.

It remains to solve the problem of using the pessimistic locking API in standard flow view (e.g. `StandardDetailView`).

One implementable solution found: 

- Use non-required beans in standard view API
- Another way is to use a hook to call the API

A specific implementation needs to be discussed.

**Comment by KremnevDmitry** [comment]
Planned for future releases

**Comment by KremnevDmitry** [comment]
# Breaking changes:

##  APP PROPERTIES

| OLD | NEW |
| -------- | ------- |
| `jmix.core.pessimistic-lock.use-default-quartz-configuration`| `jmix.psmlock.use-default-quartz-configuration`   |
| `jmix.core.pessimistic-lock.expiration-cron` | `jmix.psmlock.expiration-cron`     |

## PACKAGES AND NAMING
| OLD| NEW |
| -------- | ------- |
|`io.jmix.core.pessimisticlocking.PessimisticLock`|`io.jmix.pessimisticlock.annotation.PessimisticLock`|
|`io.jmix.flowui.view.PessimisticLockStatus`|`io.jmix.flowui.view.LockStatus`|
|`DetailView#getPessimisticLockStatus`|`DetailView#getLockStatus`|
|`io.jmix.core.pessimisticlocking.LockDescriptorProvider`|`io.jmix.pessimisticlock.LockDescriptorProvider`|
|`io.jmix.core.pessimisticlocking.impl.AnnotationLockDescriptorProvider`|`io.jmix.pessimisticlock.impl.AnnotationLockDescriptorProvider`|
|`core_AnnotationLockDescriptorProvider`|`psmlock_AnnotationLockDescriptorProvider`|
|`io.jmix.core.pessimisticlocking.LockManager`|`io.jmix.pessimisticlock.LockManager`|
|`io.jmix.core.pessimisticlocking.impl.LockManagerImpl`|`io.jmix.pessimisticlock.impl.LockManagerImpl`|
|`core_LockManager`|`psmlock_LockManagerImpl`|
|`io.jmix.flowui.view.PessimisticLockSupport`|`io.jmix.pessimisticlockflowui.view.PessimisticLockSupport`|
|`flowui_PessimisticLockingSupport`|`psmlock_PessimisticLockSupport`|

Also, added new `StandardDetailView.SetupLockEvent` in Flowui module.

New modules: `io.jmix.pessimisticlock:jmix-pessimisticlock` and `io.jmix.pessimisticlock:jmix-pessimisticlock-flowui`

## Not affected probably (SystemLevel, Partly-Internal)
| OLD | NEW |
| -------- | ------- |
|`io.jmix.core.pessimisticlocking.LockDescriptor`|`io.jmix.pessimisticlock.entity.LockDescriptor`|
|`io.jmix.core.pessimisticlocking.LockInfo`|`io.jmix.pessimisticlock.entity.LockInfo`|
|`io.jmix.core.pessimisticlocking.LockNotSupported`|`io.jmix.pessimisticlock.entity.LockNotSupported`|

**Comment by KremnevDmitry** [comment]
Studio issue: https://youtrack.jmix.io/issue/JST-4463/Migrator-to-Jmix-30-should-update-pessimistic-lock-imports

**Comment by KremnevDmitry** [comment]
## For QA:
It is necessary to test the functionality of the DetailViews without including the pslock add-on.
And also check the functionality of pessimistic locking with the added add-on.
