### ISSUE TITLE
BPM Flowui localization

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#1962]
Add localization for all languages

##### Moved:
- io.jmix.bpmflowui.model/*
- io.jmix.bpmflowui.view.alltasks/*
- io.jmix.bpmflowui.view.defaultstartform/*
- io.jmix.bpmflowui.view.defaulttaskform/*
- io.jmix.bpmflowui.view.inputdialogform/*
- io.jmix.bpmflowui.view.job/*
- io.jmix.bpmflowui.view.mytasks/*
- io.jmix.bpmflowui.view.processdefinition/*
- io.jmix.bpmflowui.view.processinstance*
- io.jmix.bpmflowui.view.processinstancemigration/*
- io.jmix.bpmflowui.view.processvariable/*
- io.jmix.bpmflowui.view.startprocess/*
- io.jmix.bpmflowui.view.taskreassign/*
- io.jmix.bpmflowui.view.usergroup/*
 
##### Not moved (old key names):
 see #1967
 
#### Result:
Localization messages moved from classic ui for all currently existing languages: fr,ckb,de,el,it,nl,ro,zh_CN; 
En,ru - has been done in [#840](https://github.com/jmix-framework/jmix/issues/840)

There are some absent messages (in classic ui too).

**QA Notes:**
Compare classic ui and flow ui views:
- Start Process
- My tasks
- Process definitions
- Process instances
- User groups
- User tasks
 
Check also corresponding detail views and dialog windows (reassign task, migrate process/instances, etc.)

Languages to check: ru, fr, ckb, de, el, it, nl, ro, zh_CN.

Check briefly whether localized messages from classic ui are present in flowui views (classic ui was not fully localized in some languages).
Known absent localization (it's ok): 
- `io.jmix.bpmflowui.view.mytasks/tasks=Tasks` in tree header on "`My tasks" view

Modeler and content storage not needed to check, they will be localized in #1967

**Comment by konyashkina** [comment]
**Greek:** 
Add some elements in modeler, then try lo leave the page.
**AR:** Dialog window "Unsaved changes in modeler" is not transtated
Also "You have unsaved changes" dialog window: 
 
![bpm20-gr-unsaved-changes001](https://github.com/jmix-framework/jmix/assets/85500330/0da29596-5a4d-4bbf-97b7-504e370541f2)

and 
![bpm20-gr-unsaved-changes002](https://github.com/jmix-framework/jmix/assets/85500330/9c88948a-1e9a-4d0c-bc43-faa58790d260)

**Comment by konyashkina** [comment]
In some translations I see the same ui issue as https://github.com/jmix-framework/jmix/issues/1875 : titles aren't shown in full  
E.g. italian translation > Tasks utente  
 
![bpm20-it-tasks-utente](https://github.com/jmix-framework/jmix/assets/85500330/3ca70a18-4827-4eb8-adec-490dd25c8989)

and the same in french: 
 
![bpm20-fr-tasks-titles](https://github.com/jmix-framework/jmix/assets/85500330/efddae83-d168-4b5b-8f99-bf85ce3d0688)

**Comment by konyashkina** [comment]
![bpm20-fr-instances-de-processus](https://github.com/jmix-framework/jmix/assets/85500330/2a7276f7-d77f-4ffb-ba80-c76200c7eeb6)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)

Languages look fine: ru, fr, de, el, it, nl, ro, zh_CN
(some minor issues will be opened as new tickets).
**ckb translation is not full:** https://github.com/jmix-framework/jmix/issues/2080
