### ISSUE TITLE
Incorrect symbols in Composite Project Readme 

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#1973]
Jmix version: 2.0.0

Create composite project
![image](https://github.com/jmix-framework/jmix/assets/73226373/6dfc5e52-580f-462e-ae30-a0c715ed8dfc)

**Comment by konyashkina** [comment]
_Jmix version: 2.0.1
Jmix Studio plugin version: 2.1.SNAPSHOT5388-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
UTF-8_

Incorrect symbol is there.   @glebfox could you please check  it again? 
![compreadme](https://github.com/jmix-framework/jmix/assets/85500330/b09ea8f9-a311-4c33-9c47-851f3077a5b8)

**Comment by glebfox** [comment]
Still looks good for me. Please, attach a full window screenshot, as I did, so the used encoding is shown.

**Comment by konyashkina** [comment]
Сould it be a studio encoding issue?

![compreadme-full](https://github.com/jmix-framework/jmix/assets/85500330/5041d959-ba13-4e04-9402-7e29643e23c6)

**Comment by rusiaikinat** [comment]
Can't reproduce on:
ubuntu 22
Jmix version: 2.0.999-SNAPSHOT , 2.1.999-SNAPSHOT
![image](https://github.com/jmix-framework/jmix/assets/114649487/4f0dc624-5062-4931-a563-17b1d50924ea)

**Comment by rusiaikinat** [comment]
Jmix version: 2.1.999-SNAPSHOT
![image](https://github.com/jmix-framework/jmix/assets/114649487/0c42d970-f2ca-421c-b743-0e979866564e)

**Comment by rusiaikinat** [comment]
2.1.0-232

**Comment by glebfox** [comment]
Seems that it's Windows only problem

**Comment by rusiaikinat** [comment]
Jmix version: 2.3.0
Jmix Studio plugin version: 2.3.0-241

**Comment by gorbunkov** [comment]
Replace this character with **>**

**Comment by rusiaikinat** [comment]
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6713-242
IntelliJ version: IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
