### ISSUE TITLE
Support Html component in XML

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#1974]
`com.vaadin.flow.component.Html`

* `content` attribute - resource string
* nested html markup
* file content

## Solution

`<html>` support three possible ways of defining its content:

1. by direct `content` attribute: resource string that contains html markup
2. nested `<content>` element that wraps html markup
3. by direct `file` attribute: resource string that contains file path with html markup

```
<layout>
        <!-- 1 -->
        <html content="msg://html.content"/>
        <!-- 2 -->
        <html>
            <content>
                <![CDATA[
                <div>
                    <button>Button 11</button>
                    <button>Button 21</button>
                </div>
                ]]>
            </content>
        </html>
        <!-- 3 -->
        <html file="com/company/demo/view/sandbox/template.html"/>
    </layout>
```

**Note:** `Html` cannot be created using `UiComponents` bean, because it has no no-args constructor.
**Note2:** The html markup must have **exactly one** root element.

**Comment by knstvk** [comment]
Make `file` attribute instead of nested `file` element.

**Comment by knstvk** [comment]
@glebfox - Studio still enables adding anything inside <html> by drag-dropping from palette. Do we have a ticket for that?

**Comment by glebfox** [comment]
> @glebfox - Studio still enables adding anything inside `<html>` by drag-dropping from palette. Do we have a ticket for that?

As discussed with @Fedoseew, there is related Studio [issue](https://youtrack.haulmont.com/issue/JST-4344/Support-limiting-the-number-of-nested-elements#focus=Comments-83-8506653.0-0).

**Comment by MaxKatyshev** [comment]
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5648-231
IntelliJ version: IntelliJ IDEA 2023.2.3 (Ultimate Edition)
verified
