### ISSUE TITLE
Access to user sessions uses wrong security context

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#1984]
### Steps to reproduce
1. Download demo: [cl-master-notifications.zip](https://github.com/jmix-framework/jmix/files/11956936/cl-master-notifications.zip)
2. Open application in different browsers or use private tabs.
3. Log in by admin/admin, user1/1 user2/2
4. Under "admin" user create notification for: "admin, user1, user2"
5. Send it

**ER**
For every user should be shown notification with its username.

**AR**
For every user we can see notification with "admin".

**Comment by syncro** [comment]
fixed within the following merge: https://github.com/jmix-framework/jmix-premium/commit/2c0dd93d5859731a8c3aeceecdef50a7a9567c17

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
![02-result screen](https://github.com/jmix-framework/jmix/assets/158277660/4e0f6776-fed8-475b-aca0-d046c666f1d5)
