### ISSUE TITLE
Use the latest apache POI versions in BOM (Jmix 1.6)

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#1993]
In Jmix 2 we've [upgraded](https://github.com/jmix-framework/jmix/issues/1625) the POI version. However Jmix 1.x still uses the old POI version.  We should analyze whether it is possible to upgrade POI version in Jmix 1.6.

See [forum topic](https://forum.jmix.io/t/grid-export-and-poi-library-version/3231).

**Comment by SergeiAksenov2** [comment]
Tested on Java and Kotlin projects on:
1) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6282-233
IntelliJ version: IntelliJ IDEA 2023.3.4 (Community Edition)
2) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6281-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Addons: Reports and Grid Export Actions.
Reports and Excel export - Ok.
