### ISSUE TITLE
The behavior of Deselect All action is different for table and datagrid elements

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#1995]
Jmix version: 1.5.999-SNAPSHOT

Deselect All action for:
- dataGrid - removes all columns
- Table, GroupTable, TreeTable - removes all columns except one

https://github.com/jmix-framework/jmix/assets/114649487/690c5b83-56d5-4bab-86fa-f927bae3910e

#1709

**Comment by Flaurite** [comment]
It was decided to do not fix the issue. `Table` must contain at least one visible column, otherwise columns won't be visible again by "Select all" action.
