### ISSUE TITLE
When a process is deployed with an empty Class field, an error appears

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2001]
#1951

https://github.com/jmix-framework/jmix/assets/114649487/ce9d1773-700a-4342-afd2-9ad7683bc7c2

AR
When a process is deployed with an empty Class field, an error appears

ER
The Class field must be mandatory

**Comment by KartnDev** [comment]
This issue happens for `Execution listener` and `Task listener` elements

**Comment by KartnDev** [comment]
Fixed in `1.5` and `1.6` branches

**Comment by KartnDev** [comment]
Seems like this problem also appears in `Jmix 2.0`

**Comment by KartnDev** [comment]
Inside TaskListener and Execution Listener for any implementation require attribute mark are also necessary.
