### ISSUE TITLE
BpmSendNotificationExecutionListener is visible in the absence of an Notification addon 

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2002]
#1951
Jmix Version: 1.5
Not included Add-ons: Notification

TC
Create UserTask 
Open Executer Listener Editor 

AR
The Notification addon is not installed, but the `BpmSendNotificationExecutionListener` in the Class field is present

ER
BpmSendNotificationExecutionListener  should not be visible in the Class field when addon Notification is not installed

For QA check: 
- Execution Listener Editor
- Task Listener Editor

**Comment by rusiaikinat** [comment]
Reopened
![image](https://github.com/jmix-framework/jmix/assets/114649487/af8c0b57-c916-4383-a64b-1fdaf6f938de)

**Comment by KartnDev** [comment]
Check that your brach has this commit [`4918ef5`](https://github.com/jmix-framework/jmix-premium/blob/release_1_5/jmix-bpm/bpm/src/main/java/io/jmix/bpm/scanner/ClassPathScanner.java)
![image](https://github.com/jmix-framework/jmix/assets/43281522/0896f4d6-2745-424f-8f67-59e2d9d9ba2b)
![image](https://github.com/jmix-framework/jmix/assets/43281522/f22d9e1d-aed1-400a-bc0f-32420cfa6445)
