### ISSUE TITLE
Broken icon in popup menu for BPM actions and other places

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#2004]
From [forum](https://forum.jmix.ru/t/moi-zadachi-otsutstvuet-ikonka-v-kontekstnom-menyu/1186)

#### Problem 
1. Create project with the custom theme.
2. Set _jmix.ui.showIconsForPopupMenuActions=true_ to the theme properties.
3. Run project, create and start BPM process.
4. Go to the MyTasks screen, call popup menu from the assigned task item.

**AR:** Action appears with the broken icon.

Also there is no icon for the "Upload BPMN XML" button in the Process Definitions screen.

Test project to reproduce (just open "My tasks" and call popup menu):
[BpmIconTest.zip](https://github.com/jmix-framework/jmix/files/12464552/BpmIconTest.zip)

#### Solution:
Replace "icon/xyz.png" with font-icon name according to https://github.com/jmix-projects/jmix-old/issues/591

**QA Notes:**

Beside two icons mentioned in description, icons has been updated in screens:
* [cuba module] Scheduled execution browse
* [cuba module] Scheduled task browse
* [cuba module] Scheduled task edit
* Pivot table excel action
* Filter select and save actions
* Snapshot diff viewer compare button

**Comment by gorbunkov** [comment]
Probably we should replace icon file name with the icon name.
