### ISSUE TITLE
Issue with entity mapping on composite item creation

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#2008]
From forum [topic](https://forum.jmix.ru/t/jmix-2-0-ne-mapitsya-polzovatel-pri-sozdanii-ego-kompoziczii/1189/)

Jmix 2.0.0 [SampleCompositionIssue.zip](https://github.com/jmix-framework/jmix/files/12029481/SampleCompositionIssue.zip)

**TC1:**

1. Run attached project.
2. Open Users view -> Create.
3. Click DataGrid's Create button to open certificate-detail-view.

ER: User field is filled.
AR: User field is empty.

**TC2:**

1. Change openMode to DIALOG for create and edit actions in user-detail-view#certDataGrid -> redeploy views.
2. Repeat TC1 steps.
3. User field is filled now, fill Code field with "1", Data field with "ABC" -> Save -> Save User.
4. Edit new User -> Edit new Certificate -> Change Code field to "2", Data field to "XYZ" -> OK -> Success notification appears.
5. Do not save user details -> Edit new Certificate.

ER: Code field = "2", Data field = "XYZ".
AR: Code field = "1", Data field = "ABC".

**Comment by Flaurite** [comment]
The case with Composition and navigation is not valid. It is not possible to transfer an entity through navigation to init inverse attribute.

It is not recommended to use navigation mode for editing Composition. Studio automatically generates actions (Create, Edit) with openMode=DIALOG for one-to-many relation.
