### ISSUE TITLE
Authserver login form should use local CSS styles

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2013]
Currently, the `as-login.html` includes CSS styles from CDN. It should use local CSS styles.

```html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          crossorigin="anonymous">
<link href="https://getbootstrap.com/docs/4.0/examples/signin/signin.css" rel="stylesheet" crossorigin="anonymous"/>
```

**Comment by gorbunkov** [comment]
For QA: please check that login form is displayed correctly and works as expected

**Comment by rusiaikinat** [comment]
Tested in different browsers and Checked the form with incorrect authorization data
