### ISSUE TITLE
Can't save a field declared in a mapped superclass from an addon

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#2014]
From forum [topic](https://forum.jmix.io/t/jmix-2-0-entity-properties-cannot-be-persisted/3263) 

Jmix 2.0.0 [composite sample project](https://github.com/jmix-framework/jmix/files/12036981/test2.zip) with an addon, containing mapped superclass and an app with an entity.

**TC:**

1. Run attached project.
2. Open Test Entities view -> Create.
3. Fill p1 and p2 -> OK -> Success notification appears.

**ER:** Both columns in Test Entities detail screen are contain data.
**AR:** p1 is empty.

Also, if move id property to the mapped superclass then new item can't be saved.

**Comment by dtaimanov** [comment]
Caused by https://github.com/jmix-framework/jmix/issues/317
Temporal workaround: add some BaseEnitity inheritor to addon.
