### ISSUE TITLE
BPM: non-admin actor doesn't see any tasks in 'My tasks' tree

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#2021]
1. Create user 'Actor' with `BPM: process actor` role
2. Create some BPM process with user task
3. Start process and assign 'Actor' user
4. Login as 'Actor' and go to `BPM` -> `My tasks`

ER: Tasks tree with new assigned user task should be visible
AR: Tasks tree is completelly empty.

There is the same issue with Group tasks

Looks like security issue - no permissions for `MyTasksTreeItem` DTO.

Expected solution - provide read access to `MyTasksTreeItem` in `BPM: process actor` role:
```
@EntityPolicy(entityClass = MyTasksTreeItem.class, actions = EntityPolicyAction.READ)
@EntityAttributePolicy(entityClass = MyTasksTreeItem.class, attributes = "*", action = EntityAttributePolicyAction.VIEW)
```

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
