### ISSUE TITLE
BulkEditAction in FlowUI

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2025]
We need to re-implement an [existing action](https://docs.jmix.io/jmix/1.5/ui/actions/standard-actions/bulk-edit-action.html) from Classic UI.

See [forum topic](https://forum.jmix.io/t/jmix-2-0-flowui-bulk-edit/3259).

**Comment by rusiaikinat** [comment]
The enum field bound to the entity is not filled with data
![image](https://github.com/jmix-framework/jmix/assets/114649487/23411f8e-6097-426b-a989-ba1f697d2b14)
