### ISSUE TITLE
Adding themeNames to div breaks layout

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#2037]
<img width="577" alt="Screenshot 2023-07-17 at 19 21 10" src="https://github.com/jmix-framework/jmix/assets/128021710/f61336c1-98a2-48dc-8385-3d7172b5d02b">

**Comment by KremnevDmitry** [comment]
Now, to make a component a badge, you need to explicitly specify the themeName:

Old:
```
<div themeNames="success"/>
```

New:
```
<div themeNames="badge success"/>
```

**Comment by rusiaikinat** [comment]
variant spelling:
' <div themeNames="badge, success">'
