### ISSUE TITLE
Wrong sroll BPM decision dialog window (Russian localization)

### ISSUE THREAD

**Issue by dubenko** [jmix-framework/jmix#2045]
![Новый точечный рисунок](https://github.com/jmix-framework/jmix/assets/1576083/7bd45a61-97d3-4472-b950-9732de99ffc4)

#### QA Notes:
It is User task with input dialog form with candidate user group. Not assigned.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
