### ISSUE TITLE
[Bpm modeler] Combo box not supporting custom value in startEvent in Form details

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2048]
See more: https://forum.jmix.ru/t/oshibka-pri-naznachenii-biznes-klyucha-modulya-bpm-jmix-2-0/1206

**Comment by konyashkina** [comment]
_Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)_

Now there is no exception, 
but not able to save the value (Business key) selected from the list. 

**Steps:**  

1. Start element >  Form type = Input dialog 
2. Add Input dialog parameters. Save. 
3. In the Business key field select any value. 
4. Click any other element in the modeler.
5. Then go back to the Business key field. 

**AR:** Business key is empty.

**Comment by konyashkina** [comment]
Issue about Business key saving is https://github.com/jmix-framework/jmix/issues/2074
