### ISSUE TITLE
RichTextArea component

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2055]
### Description
Vaadin's `RichTextEditor` is not free: https://vaadin.com/docs/latest/components/rich-text-editor

**Comment by knstvk** [comment]
Can be helpful: https://github.com/JefMari/awesome-wysiwyg-editors

**Comment by konyashkina** [comment]
Tetsed on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6050-233
