### ISSUE TITLE
Decide which validators are needed for each component

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#2059]
1) **bigDecimalField**

![image](https://github.com/jmix-framework/jmix/assets/40686909/077ad4be-c31a-453a-867e-9d651bf3d14a)

Why are there
DoubleMax, DoubleMin, Email, Size, Regexp?

2) **codeEditor**
![image](https://github.com/jmix-framework/jmix/assets/40686909/32639f9e-6126-483f-a10c-7655428f4c56)

```
<xs:complexType name="constraintValidatorType">
        <xs:complexContent>
            <xs:extension base="stringValidatorType">
                <xs:sequence>
                    <xs:element name="digits" minOccurs="0" type="digitsValidatorType"/>
                    <xs:element name="decimalMin" minOccurs="0" type="decimalMaxMinValidatorType"/>
                    <xs:element name="decimalMax" minOccurs="0" type="decimalMaxMinValidatorType"/>
                    <xs:element name="doubleMin" minOccurs="0" type="decimalMaxMinValidatorType"/>
                    <xs:element name="doubleMax" minOccurs="0" type="decimalMaxMinValidatorType"/>
                    <xs:element name="negativeOrZero" minOccurs="0" type="messageValidatorType"/>
                    <xs:element name="negative" minOccurs="0" type="messageValidatorType"/>
                    <xs:element name="positiveOrZero" minOccurs="0" type="messageValidatorType"/>
                    <xs:element name="positive" minOccurs="0" type="messageValidatorType"/>
                    <xs:element name="max" minOccurs="0" type="maxMinValidatorType"/>
                    <xs:element name="min" minOccurs="0" type="maxMinValidatorType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
```

The list of available validators does not match the studio and the xml schema

Our `SourceCodeEditor` had the following predefined validators:

* CustomValidator
* EmailValidator
* NotBlankValidator
* NotEmptyValidator
* NotNullValidator
* RegexpValidator
* SizeValidator

2) **datePicker**
![image](https://github.com/jmix-framework/jmix/assets/40686909/10f46d3c-b024-4aba-b26e-a50c18241b62)

a) Please add `custom` validator to Studio

![image](https://github.com/jmix-framework/jmix/assets/40686909/2c768b9c-9f12-46fd-a19e-d478755c5ca6)

b) The `checkSeconds` attribute there is in the xml schema, but there is not in Studio

3) `emailField` has a lot of extra validators:
![image](https://github.com/jmix-framework/jmix/assets/40686909/8af068fe-caa6-4f0d-a5a4-8700e9ee5b21)

4) **entityComboBox** 
![image](https://github.com/jmix-framework/jmix/assets/40686909/3a5ea761-db27-4554-b28f-d3c6b40354c8)

The list of available validators does not match the studio and the xml schema

Our `entityComboBox` in 1.5 version had only `Custom` and `NotNull` validators

**Comment by sukhova** [comment]
`timePicker` has incorrect set of validators in Studio:
![image](https://github.com/jmix-framework/jmix/assets/40686909/9e234724-2020-44b0-90d4-de25e4f7cab0)

**Comment by KremnevDmitry** [comment]
# Changes:

## BigDecimalField
### Available: 
![image](https://github.com/jmix-framework/jmix/assets/75516667/7bfb0b3f-de49-4c49-a826-8ef2853f701b)
### Removed from XML and designer:

- `doubleMax` [unsupported]
- `doubleMin` [unsupported]
- `email` [unsupported]
- `notBlank` [unsupported]
- `notEmpty` [The use is not logical, use `notNull` instead]
- `regexp` [unsupported]
- `size` [unsupported]

## CodeEditor
### Available: 
![image](https://github.com/jmix-framework/jmix/assets/75516667/2810095b-9d95-4882-82d0-54a56ca5685e)
### Removed from XML and designer:

- `decimalMax`
- `decimalMin`
- `digits`
- `doubleMax`
- `doubleMin`
- `max`
- `min`
- `negative`
- `negativeOrZero`
- `positive`
- `positiveOrZero`

### Removed from designer:
- `future`
- `futureOrPresent`
- `past`
- `pastOrPresent`

## DatePicker/TimePicker/DateTimePicker

- `custom` validator added to designer
- `checkSeconds` attribute added to date-time validators
- The studio validator set for `timePicker` is now correct.

**Comment by rusiaikinat** [comment]
1.         <entityPicker id="er1"/>  in 1.5 CustomValidator и NotNUllValidator
2.         <integerField id="er2"/> -- remove unnecessary

3.         <multiSelectComboBoxPicker id="er3">  -- remove unnecessary
            <validators>
                <future checkSeconds="true" message="b"/>
                <futureOrPresent checkSeconds="true" message="w"/>
                <past checkSeconds="true" message="q"/>
            </validators>
        </multiSelectComboBoxPicker>

4.         <numberField id="er4"/> --remove unnecessary

5.        <passwordField  id="er5"/> -- remove unnecessary
6.        <propertyFilter id="er6" dataLoader="usersDl" operation="EQUAL" property="active">  -- there is no validator in 1.5
            <validators>
                <email/>
            </validators>      </propertyFilter>

7.        <textArea id="er7"/> -- add validators
8.       <valuePicker id="er8"/>   in 1.5 CustomValidator и NotNUllValidator

**Comment by KremnevDmitry** [comment]
# Fixed or verifyed:

- `entityPicker`
- `integerField`
- `multiSelectComboBoxPicker` + `multiSelectComboBox`
- `numberField`
- `passwordField`
- ~propertyFilter~ [not affected] 
    Validators for the `propertyFilter` will be added to its `valueComponent`
    The `propertyFilter` can have any component as its `valueComponent` in Flow, so any validators should be available.
- `textArea`
- ~valuePicker~ [not affected] 
    The `valuePicker` can have any type of data, so any validators should be available.
