### ISSUE TITLE
[Bpm modeler] Change h4 tags in modeler to compatibility cosmetic style fix style

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2061]
Problem: Right now we have small variant of ui components inside bpm modeler, but we used h4 tags so it didnt change into small variant.

FIx issue: replace h4 with spans with classname theme

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
