### ISSUE TITLE
Wrong sort order of UiControllersConfiguration

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2065]
Wrong sort order of UiControllersConfiguration causes bugs with add-on screen overriding.

See [forum topic](https://forum.jmix.ru/t/ne-rabotaet-pereopredelenie-ekranov-v-add-ons/1194). Test is attached there.

**Comment by daring2** [comment]
We use the following solution (kotlin version):
```
class UiControllersConfigurationSorter(...) {

    override fun sort(
        configurations: List<UiControllersConfiguration>
    ): List<UiControllersConfiguration> {
        val configMap = configurations.groupBy {
            evaluateJmixModule(it.basePackages)
        }
        return (jmixModules.all + null)
            .flatMap { configMap[it].orEmpty() }
    }

}
```

I can create a PR if this solutoin is acceptable.
