### ISSUE TITLE
Support meta annotations from addons

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2068]
**Situation:**
We need to describe a component for a Studio from premium add-ons. 

**What we do:**
We create a description from meta annotations and a special visual component to display in the Designer Preview. 

**What is the problem:**
The Studio uses an isolated classloader that stores only `jmix-dev-server` (from repository) and `jmix-themes` (from module dependencies) artifacts - this means that the visual component class will not be found in the Studio classloader and cannot be created.

**Solution:**
We can add the `studioClassloaderDependecies` attribute to the `@StudioUiKit` annotation, which is an array of strings of the form: <dependency_group>:<dependency_name>. The Studio will load the specified dependencies from module dependencies into the classloader and will use them.

Also see Studio ticket: https://youtrack.jmix.io/issue/JST-4159/Support-meta-annotations-from-addons

**Comment by Fedoseew** [comment]
@Flaurite, you can use that for Notifications addon (this will only work in the Studio from version 2.1)
Just add @StudioUiKit(studioClassloaderDependencies = "io.jmix.notifications:jmix-notifications-flowui") on ui kit class.

**Comment by Flaurite** [comment]
Fixed. Component from add-on is shown in View Components tree and in Component Inspector
