### ISSUE TITLE
Lazy loading state merged incorrectly into child context

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2073]
see https://forum.jmix.ru/t/nekorrektnoe-otobrazhenie-neskolko-kollekczij-na-ekrane/1212/3

### Steps (see forum topic for more details):
1. Run [project](https://forum.jmix.ru/uploads/short-url/hFSabH6BOXJhHzxDicTOJh3cCI8.zip) from the topic.
2. Open Root browser and edit "Root 1" entity
3. Add new "Foo" entity.
**ER:** New entity added to bottom of list of other already existed entities.
**AR:** Already existed entities disappeared. Only new entity appears.

### Cause 
Second merging of the same entity into another (child) data context leads to lazy collection loss. 

### QA Notes 
[optional] In addition to the described case it make sense to test some complex several time nested dialog screens with not sufficient fetch plans in order to make sure that nothing is broken and no similar issues occurs.

**Comment by gorbunkov** [comment]
We need to check if it is relevant for Jmix 2.x
