### ISSUE TITLE
BPM modeler: not able to save custom value in startEvent 

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#2074]
_Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5366-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)_

After https://github.com/jmix-framework/jmix/issues/2048
Now there is no exception,
but not able to save the value (Business key) selected from the list.

**Steps:**
1. Start element > Form type = Input dialog
2. Add Input dialog parameters. Save.
3. In the Business key field select any value.
4. Click any other element in the modeler.
5. Go back to the Business key field.

**ER:** Business key saved successfully. 
**AR:** Business key is empty.

**Comment by KartnDev** [comment]
seems like fixed in commit [7aca6e8057d8e065a0c00b349bca873a1a5c2c9a](https://github.com/jmix-framework/jmix-premium/pull/179)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5432-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
