### ISSUE TITLE
BPM Flowui localization: Kurdish translation is not full 

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#2080]
After https://github.com/jmix-framework/jmix/issues/1962 

Kurdish translation (ckb)  is not full.

**Comment by gorbunkov** [comment]
@dtaimanov Please check whether all messages that were present in 1.x were transferred to 2.0. If so, then close the issue because we can't add this localization ourselves.

**Comment by dtaimanov** [comment]
All messages that where present in 1.x were transferred 2.0
