### ISSUE TITLE
BPM Modeler - Error on Save draft

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#2084]
Jmix version: 1.5.3

Steps to reproduce the problem:
1. Open the "Modeler" screen.
2. Save process draft.
3. Open drafts screen using "Open draft" button.
4. Delete the process draft and close the screen.
5. Try to save draft.

Result: Error "Unable to save the 'Content storage' object changes".

![image](https://github.com/jmix-framework/jmix/assets/11490702/bc964b2b-16e9-4365-b929-272d3be8754d)

**Comment by gorbunkov** [comment]
@yuriy-khrebtov Please review and merge the linked PR. Also merge the changes into the `release_1_6` branch.

**Comment by yuriy-khrebtov** [comment]
Also fix same issue in Decision table modeler

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5504-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
