### ISSUE TITLE
FlowableObjectNotFoundException on View process instance

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#2087]
Jmix version: 1.5.3

Steps to reproduce the problem:
1. Create a process with an user task
2. Start an instance of the created process.
3. Open the "Process definitions" screen.
4. Select a process instance and click the "View process instance" button.
5. Delete the process instance using the "Delete" button.

Result:
The "Process instance editor" screen is closed but "Process definition editor" screen shows the deleted process instance. If a user clicks "View process instance" button a FlowableObjectNotFoundException error is shown.

![image](https://github.com/jmix-framework/jmix/assets/11490702/c620e650-30a8-4c80-8713-c9bb2348cbde)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5504-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
