### ISSUE TITLE
File name column of Templates is not fully visible

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2090]
2.0.999-SNAPSHOT

Create project with reports add-on
Open Reports -> Report -> Templates 

**AR**
The column are narrow, the text is cut off
There is no way to view the contents of the column
![image](https://github.com/jmix-framework/jmix/assets/114649487/cd40238b-12d3-49d4-a635-1ea1b66dab63)

**Comment by gorbunkov** [comment]
We should make all columns resizable. This should solve the issue
