### ISSUE TITLE
OpenSearch support

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#2094]
Support [OpenSearch](https://opensearch.org/) in Search addon in addition to current Elasticsearch.

Index structures in ES and OS are identical. Client API is similar.
Some classes in Search addon use classes from ES client - they must be changed.

# Index Management
## Index metadata building

It's required to redesign building index metadata - mapping and settings.

- `IndexConfiguration` - contains `Settings` from ES client. Possible solution - store them as `Map`.
- `IndexSettingsConfigurationContext `- uses `Settings.Builder` from ES client as API to build `Settings` object. Should be unified. This will be **breaking changes**.
- `AnalysisElementConfiguration `- contains `Settings` from ES client. Actually, it's not required to store it there as a `Settings` - can be stored as `ObjectNode` and be used outside later.
- `AnnotatedIndexDefinitionProcessor` - it's a central point of index metadata creation, should be refactored together with the previous ones.

## Operations with index

- `ESIndexManager` - create client-specific implementations. Rename or deprecate and create new one (e.g. just `IndexManager`) to get rid of reference to ES in interface.
- API method `getIndex()` returns `GetIndexResponse` from ES client. Need to unify. It's used to get index metadata and check if it's up-to-date. **Breaking changes**.

# Index Documents

- `EntityIndexer` - create client-specific implementations.
- `IndexResult` - uses `BulkResponse` and `BulkItemResponse` from ES client. Move client-specific logic (`create` method) to `EntityIndexer` implementations.

# Search Documents

- `EntitySearcher` - create client-specific implementations.
- `Search Strategy`
   - Issues
      - Uses `SearchRequest` from ES client as input parameter (**breaking changes**).
      - Uses query builder from ES. Hard to unify.
   - Possible solution
      - Create different interfaces\base classes and implementations for each Search strategy for each client.
      - Add provider for Search strategues with client-specific implementations. It provides strategy by unique name.
      - `EntitySearcher#search(SearchContext searchContext, SearchStrategy searchStrategy)` should accept strategy name instead of object (**breaking changes**).

# Common
### SearchProperties

- Naming: there are group of properties "jmix.search.elasticsearch.xxx". Need to unify (**breaking changes**).
- `jmix.search.elasticsearch.bulkRequestRefreshPolicy` property uses `RefreshPolicy` enum from ES client as values. OS client has analogue - `Refresh` enum - with different item names, but with the same internal values. There are 3 possible values - currently we use ES set, but it's required to create the unified ENUM on addon level. **Breaking changes**. Preferable values set is internal\OS-like): 
   - `false` (internal) - `NONE` (ES) - `False` (OS) - no additional refresh after request.
   - `true` (internal) - `IMMEDIATE` (ES) - `True` (OS) - perform refresh after request.
   - `wait_for` (internal) - `WAIT_UNTIL` (ES) - `WaitFor` (OS) - wait until refresh is performed by another "source".

### Filters
`FullTextFilterConverter`, `FullTextFilterImpl`, `FullTextFilterConditionEdit`: remove usage of `org.elasticsearch.common.Strings` and add analogue.

### Tests
Many tests use classes from ES client. Maybe we should add the same set of test for the OS.

Most of the difficulties and changes are expected in the context of Index metadata building and search strategy. The rest fo the changes should be simple - reimplementing the same logic using API of OS client.

Rough estimation - about 1-2 weeks.

**Comment by knstvk** [comment]
See considerations about licensing on the [forum](https://forum.jmix.io/t/search-add-on-in-v-2-1/3939/5).

**Comment by Gavrilov-Ivan** [comment]
## Changes
### Modules
Introduced 4 new modules

- `search-elasticsearch`
- `search-elasticsearch-starter`
- `search-opensearch`
- `search-opensearch-starter`

One (only) platform-specific starter must be added to project in addition to existing `search-starter`.

### API

#### General
- `ESIndexManager` was renamed to `IndexManager`
- `EntitySearcher#search(SearchContext, SearchStrategy)` -> `EntitySearcher#search(SearchContext, String)`
- `SearchResult#getSearchStrategy` now returns `String` (strategy name) instead of `SearchStrategy`
- `SearchStrategy#configureRequest` was removed
  - `configureRequest` method is available in platform-specific interfaces - `ElasticsearchSearchStrategy` and `OpenSearchSearchStrategy`
    - To create custom search strategy you have to implement one of these platform-specific interfaces
    - There are 2 sets of built-in strategies - for both platform
- `SearchStrategyManager` was removed
- It was split into platform-specific `ElasticsearchSearchStrategyProvider `and `OpenSearchSearchStrategyProvider`

#### Settings configuration
Configuration of index settings and analysis has been reworked:

- Separate `IndexSettingsConfigurer` and `IndexAnalysisConfigurer` are no longer available
- Platform specific `ElasticsearchIndexSettingsConfigurer` or `OpenSearchIndexSettingsConfigurer` should be used instead
  - They allow to configure both - generic settings and analysis.
  - Java Client API builder is used to configure
  - Settings for all indexes and settings for some specific indexes will not be merged anymore - if you need some configuration for specific index you have to specify whole set of settings you want to be applied

### Properties

- Properties `jmix.search.elasticsearch.*` were renamed to `jmix.search.server.*`
- Property `jmix.search.server.bulk-request-refresh-policy` now accepts values: `TRUE` (ex `IMMEDIATE`), `FALSE` (ex `NONE`), `WAIT_FOR` (ex `WAIT_UNTIL`)
- Property `jmix.search.rest-high-level-client-api-compatibility-mode-enabled` was removed

**Comment by Gavrilov-Ivan** [comment]
Need to test all scenarios related to Search addon using both OpenSearch and Elasticsearch modules.
ES module now uses actual Java APi client instead of High Level Rest Client - minimal version of ES is 7.17.x and 8.x
