### ISSUE TITLE
Support CSS attribute in XML

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2095]
Like in classic UI: https://doc.cuba-platform.com/manual-7.2/gui_attributes.html#gui_attr_css

**Comment by rusiaikinat** [comment]
_Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5419-232
IntelliJ version: IntelliJ IDEA 2023.2 (Ultimate Edition)_

`<checkbox id="activeField" property="active"  css="font-size: 120%; font-family: Verdana, Arial, Helvetica, sans-serif; color: #f5f" />`
![image](https://github.com/jmix-framework/jmix/assets/114649487/a4f926e6-dd59-4511-8013-2843f69a10a1)
