### ISSUE TITLE
Ability to define prefix and suffix components in XML

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2096]
E.g.
```
<textField id="nameField" property="name">
    <prefix>
        <icon icon="QUESTION"/>
    </prefix>
    <suffix>
        <button icon="PENCIL"/>
    </suffix>
</textField>
```

Plan: 

- [x] Component research
- [x] layout.xsd
- [x] Loader support
- [x] XML load test
- [x] ViewControllerDependencyInjector support  (perfomance issue: to be discussed???)
- [x] Create Jmix Studio issue MetaAnnotations support ([JST-4191](https://youtrack.jmix.io/issue/JST-4191/Support-prefixsuffix-elements-in-XML))
    - [x] + add kit meta annotations (probably need to changed)
- [x] Manual test in runtime

### To be discussed:
DrawerToggle has an interesting behavior
Do we really need it?

XML:
```
        <drawerToggle icon="SUN_RISE">
            <prefix>
                <button id="prefixButton3" themeNames="tertiary-inline" icon="VAADIN_H"/>
            </prefix>
            <suffix>
                <button id="suffixButton3" themeNames="tertiary-inline" icon="VAADIN_V"/>
            </suffix>
        </drawerToggle>
```

Runtime:
![image](https://github.com/jmix-framework/jmix/assets/75516667/5f4b0830-566a-44ba-a967-20826f56268d)

DOM:
![image](https://github.com/jmix-framework/jmix/assets/75516667/0af245dc-cb3b-4feb-b06a-b1c3f4809735)

Solution: remove drawerToggle support

**Comment by rusiaikinat** [comment]
Jmix version: 2.1.999-SNAPSHOT (Kotlin, Java)
Jmix Studio plugin version: 2.1.SNAPSHOT5430-232
IntelliJ version: IntelliJ IDEA 2023.2 (Ultimate Edition)
