### ISSUE TITLE
Increase dialog width

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2099]
AR:
<img width="424" alt="Screenshot 2023-07-28 at 18 55 36" src="https://github.com/jmix-framework/jmix/assets/6077149/47123bbd-95e9-43f9-9e46-8b0b2b7c7cce">

Seems that `minWidth` must be used instead of `width.

For QA: 
Option Dialog, Message Dialog and Background Task Dialog need testing

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5388-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
