### ISSUE TITLE
[DataGrid] Column sorting not working in custom rendered columns

### ISSUE THREAD

**Issue by Arty26** [jmix-framework/jmix#2101]
I have added a custom-rendered column as per this sample ([https://demo.jmix.io/ui-samples/sample/data-grid-custom-renderer]). Set sortable to true as per the documentation to enable the sorting. But sorting doesn't work.

@Subscribe
    protected void onInit(InitEvent event) {
        customersDataGrid.addColumn(createStatusComponentRenderer())
                .setHeader(messageTools.getPropertyCaption(metadata.getClass(Customer.class), "grade"));
                .setSortable(true);
    }

**Comment by Flaurite** [comment]
Hello @Arty26 !

Jmix implementation of `Grid` does not support column's sort if it's added by renderer. The column with renderer does not provide information about which property should be used in sorting. 

We have an issue https://github.com/jmix-framework/jmix/issues/2093 to provide some convenient way for adding sorting for such columns.

For now, you can add Sort Listener to Grid and perform sorting manually, for instance:
```
@Autowired
private Metadata metadata;

Grid.Column<Entity> customColumn = entitiesDataGrid.addColumn(creteRenderer())
        .setKey("customColumn")
        .setHeader("Custom column")
        .setSortable(true);
        
entitiesDataGrid.addSortListener(sortEvent -> {
    List<GridSortOrder<Entity>> sortOrders = sortEvent.getSortOrder();
    if (sortOrders.isEmpty()) {
        return;
    }
    
    Grid.Column<Entity> column = sortOrders.get(0).getSorted();
    if (column != null
            && "customColumn".equals(column.getKey())) {
        MetaPropertyPath mpp = metadata.getClass(Entity.class).getPropertyPath("myPropertyToSort");
        boolean ascending = SortDirection.ASCENDING.equals(sortOrders.get(0).getDirection());
        
        ((DataGridItems.Sortable<Entity>) entitiesDataGrid.getItems())
                .sort(new Object[]{mpp}, new boolean[]{ascending});
    }
});
```
