### ISSUE TITLE
Cosmetic note for the template download link in the report generation window

### ISSUE THREAD

**Issue by m-shambarova** [jmix-framework/jmix#2104]
**Env:**
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5377-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)

TC:

- Report->Report
- Create->Using Wizard
- Fill in the required fields(step1) and click on Next
- Select attributes(step 2) and click on Next

**AR:** The template download link looks weird.
![image](https://github.com/jmix-framework/jmix/assets/99609936/75f20067-1602-4125-82c2-ec2056681c9d)
![image](https://github.com/jmix-framework/jmix/assets/99609936/44b1185f-0d77-4ece-8c76-d01a208a45b6)

**ER:** Change template download link location or add a title as it was in the previous version(needs to be clarified).

**Comment by gorbunkov** [comment]
We may add the "Download template" link on the bottom of the screen.

**Comment by breakingfox** [comment]
Fixed in #2545 among other issues
