### ISSUE TITLE
Implement Timer facet

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2106]
### Description
See support forum [discussion](https://forum.jmix.io/t/alternative-to-timer-java-class-of-cuba-in-jmix-2-0/3360)

Jmix 1.x version has facet that enables calling methods by interval.

**Comment by yuriy-khrebtov** [comment]
It's now possible to add timer facet in view xml descriptor:
```
    <facets>
        <timer delay="1000" repeating="true" autostart="true" id="timer"/>
    </facets>
```
Or directly using
`facets.create(Timer.class)`

**Comment by knstvk** [comment]
A timer does not start after refreshing the web page. 
- Open a view with this timer:
  ```
  <facets>
      <timer id="timer" delay="2000" autostart="true" repeating="true"/>
  ```
- The timer starts ticking.
- Reload the page. The timer doesn't start.

**Comment by konyashkina** [comment]
Tested on  
Jmix version: 2.1.999-SNAPSHOT
