### ISSUE TITLE
AppSettings add-on breaks input dialog

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2107]
**Steps:** 

1. Add AppSettings add-on
2. Add dialog with input parameters to the view
3. Try to open it

ER: Dialog is opened
AR: 
```
NullPointerException: Cannot invoke "io.jmix.core.metamodel.model.MetaClass.getJavaClass()" because the return value of 
"io.jmix.flowui.component.ComponentGenerationContext.getMetaClass()" is null
```

Cause: `AppSettingsComponentGenerationStrategy` has a higher priority than `InputDialogGenerationStrategy`.
In the input dialog creation context, the metaclass can be empty.

Forum Topic:
https://forum.jmix.io/t/input-dialog-exception/3364/5

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5432-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
