### ISSUE TITLE
BPM open modeler button

### ISSUE THREAD

**Issue by dubenko** [jmix-framework/jmix#2110]
![image](https://github.com/jmix-framework/jmix/assets/1576083/5acd2f08-49b6-4f70-97f0-3d1655c57c19)
Active open modeler button if no selected items. When click on button throw exception.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5432-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)
