### ISSUE TITLE
Support autoLoad property in SimplePagination

### ISSUE THREAD

**Issue by Arty26** [jmix-framework/jmix#2111]
The pagination total item count is only showing when clicking on the "?" button. I need to display the total count by default on the initial load. Tried this [https://docs.jmix.io/jmix/flow-ui/vc/components/simplePagination.html#totalCountDelegate](url). 

@Subscribe("pagination")
public void onPaginationAttach(final AttachEvent event) {
        pagination.setTotalCountDelegate(this::paginationTotalCountDelegate);
}

@Install(to = "pagination", subject = "totalCountDelegate")
private Integer paginationTotalCountDelegate(final LoadContext<Organization> loadContext) {
        return dataManager.loadValue("select count(e) from Organization e", Integer.class).one();
}

**Comment by Arty26** [comment]
@knstvk @Flaurite

**Comment by Flaurite** [comment]
Hello @Arty26,

Take a look at `autoLoad` property: https://docs.jmix.io/jmix/1.5/ui/vcl/components/simple-pagination.html#auto-load It will show the total count in the UI. The `totalCountDelegate` commonly used when you have custom loading of entities to the container. 

If you have other questions please feel free to ask them in our forum: https://forum.jmix.io/. There you can find solutions for various problems and help from the community.

**Comment by Arty26** [comment]
Hi @Flaurite ,

Thanks for the reply & sharing the forum channel. 

Regarding the `autoLoad` property, I used this in the **v1.5** but recently I have migrated to the latest **v2.0.1**. Seems the property has not been exposed in the latest version.

**Comment by Flaurite** [comment]
Yes, it seems that `autoLoad` property is not fully migrated to Flow UI 2.0. I think, it will be fixed in this issue. Thank you for reporting the problem!
