### ISSUE TITLE
Performance issue with saving of many entities in data context

### ISSUE THREAD

**Issue by klaus7** [jmix-framework/jmix#2129]
https://github.com/jmix-framework/jmix/blob/afe3ad0ec3b8b18738bf94144872eb9e955729b4/jmix-flowui/flowui/src/main/java/io/jmix/flowui/model/impl/DataContextImpl.java#L701C11-L701C11

A significant performance issue if we want to save many entities via the data context. 

If we don't care about the reloading of the saved entities (or most of them) and have a large count of entities in the save context, the recursive calls to updateFetchPlans method are superfluous, but still requires a lot of CPU time.

Example for this would be an import entity with lots of related "import entry entities".

**Comment by gorbunkov** [comment]
Implemented here: https://github.com/jmix-framework/jmix/issues/1725#issuecomment-1818270822
