### ISSUE TITLE
Implement fetchPlan selection when saving entity to JmixDataRepository

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#2131]
Add the ability to customize `fetchPlan` to the `JmixDataRepository.save()` method.

**Forum**: https://forum.jmix.io/t/repository-fetch-plan/3413

**QA Notes:**
Covered by autotest

**Comment by dtaimanov** [comment]
Pull request: https://github.com/jmix-framework/jmix/pull/2876
