### ISSUE TITLE
Support UI validation from UI integration test

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#2132]
Oftentimes it is required to trigger UI validation in an UI integration test. In Classic UI it was possible via a hack of overriding the visibility setting of `StandardEditor::validateScreen` from protected to public and with that call it from within the tests (see https://github.com/jmix-framework/jmix/blob/v1.5.3/jmix-ui/ui/src/main/java/io/jmix/ui/screen/StandardEditor.java#L536). 

With FlowUI this option is not present anymore, as the method is private (see: https://github.com/jmix-framework/jmix/blob/master/jmix-flowui/flowui/src/main/java/io/jmix/flowui/view/StandardDetailView.java#L224)
which makes it currently almost impossible to trigger UI validation via an integration test. It is possible to copy the whole logic from StandardDetailView into the subclass, but this does not sound very sustainable.

Request:
Come up with a Test helper method class that performs validation of a StandardDetailView and returns the ValidationErrors.

**Comment by Flaurite** [comment]
After Mario's request created new issue: https://github.com/jmix-framework/jmix/issues/2777 which makes `validateView()` accessible from inheritors.

Within current issue added new method to `UiTestUtils`: `validateView()` that calls validation from the provided `StandardDetailsView`.
