### ISSUE TITLE
Opening and navigating to Views by controller class does not consider view overriding

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2136]
### Description
Let's say we have add-on with some `AddonView`. In this add-on `ViewD` opens `AddonView` as dialog by class and `ViewN` navigates to `AddonView` by class.
The application includes this add-on and overrides `AddonView` - `ExtAddonView`. For instance `ExtAddonView` adds button to the layout.

In the launched app `ViewD` opens `AddonView` by class, but it is expected that will be opened `ExtAddonView`. And the same with navigation. `ViewN` navigates to `AddonView` by class, but it is expected that will be opened `ExtAddonView`.

**AR**
 `ViewD` opens `AddonView` and `ExtAddonView` is ignored.
 Navigation does not work due to exception:
 ```
 com.vaadin.flow.router.NotFoundException: No route found for the given navigation target
 ```
 
The reason of this behavior is that `DialogWindows` and `ViewNavigators` do not try to find overriding for controller class, only for view Id (see `getViewInfo(String)`).

**Comment by rusiaikinat** [comment]
for QA:
Won't work for extension, works only for overriding. 
@ViewController view=extView
