### ISSUE TITLE
MainView with horizontal menu template

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2137]

**Comment by yuriy-khrebtov** [comment]
Now we can generate main view with top menu: "Right click on project tree -> New -> View... -> Main view with top menu". For the moment we should manually remove or comment out `@Route` annotation in previously used MainView view and manually change value of `jmix.ui.main-view-id` application property.
The issue for extended support by Jmix plugin has been created: https://youtrack.haulmont.com/issue/JST-4516/Main-view-with-top-menu-template

**Comment by MaxKatyshev** [comment]
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6033-233
IntelliJ version: IntelliJ IDEA 2023.3.2 (Ultimate Edition)
**verified**
