### ISSUE TITLE
[Port to v2] User should see filters of substituted user

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2156]
Source issue: User should see filters of substituted user #2007

Was ported to the 2.0 branch

Testing blocked by: User substitution views #1006
Coming in release Jmix 2.1

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5619-232
IntelliJ version: IntelliJ IDEA 2023.2.2 (Ultimate Edition)
