### ISSUE TITLE
genericFilter has repeated menu items in UI Inspector 

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#2158]
Configuration and Properties appear twice.

<img width="407" alt="Screenshot 2023-08-18 at 14 03 10" src="https://github.com/jmix-framework/jmix/assets/128021710/ac49213b-eb73-499b-adf5-511775532f67">

**Comment by KremnevDmitry** [comment]
Can't be reproduced:
![image](https://github.com/jmix-framework/jmix/assets/75516667/618a4782-c8cb-458a-ba71-e494773556ff)

More feedback needed.

**Comment by KremnevDmitry** [comment]
Can't reproduce by 3 developers.
Closed.
