### ISSUE TITLE
Support custom icons in ListMenu component

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2170]
### Description
Methods for adding icon takes `VaadinIcon` type. We can replace it by `IconFactory` interface to support custom icons.

**Comment by gorbunkov** [comment]
Will be implemented in https://github.com/jmix-framework/jmix/issues/1870

**Comment by Flaurite** [comment]
Duplicates: https://github.com/jmix-framework/jmix/issues/2170

### Solution
Since https://github.com/jmix-framework/jmix/issues/2170 `ListMenu` component takes any icon from custom icon-set.

In `menu.xml` you can specify the icon using the format `icon_collection_name:icon_id`. For instance:
```
<menu id="application" icon="my-icons:leaves-2-svgrepo-com"/>
```

In Java code, you can use `setPrefixComponent()` method from `MenuItem`:
```
@ViewComponent
private JmixListMenu menu;

@Subscribe
protected void onInit(final InitEvent event) {
    menu.getMenuItem("User.list")
            .setPrefixComponent(MyIcons.BUSHES_OF_LEAVES_SVGREPO_COM.create());
}
```
You can see full example in demo project: [f-icons.zip](https://github.com/jmix-framework/jmix/files/14645792/f-icons.zip)
