### ISSUE TITLE
Simplified API for background/asynchronous code

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2174]
## **Main goal**
To simplify the work with `asynchronous/background` calls.

## **Description**
At the moment we have a [BackgroundTask mechanism](https://docs.jmix.io/jmix/flow-ui/background-tasks.html). This mechanism is in some cases too redundant and looks too complicated. 
For example, if we need to load some data and then process the result (on UI thread), then we will have to write a lot of code to achieve the desired result and so on every time, for every such call. This may scare off novice developers a little and annoy others.

## **Suggestion**
It would be convenient to use something like `AsyncUtil.executeInBackground(currentView, dataFetchingSupplier, resultHandlerConsumer)`.
You can also see an example of this approach in the [Async Manager addon](https://github.com/fluorumlabs/async-manager?tab=readme-ov-file#async-manager-for-vaadin-flow) .

I attach an approximate implementation ([UiUtils.txt](https://github.com/jmix-framework/jmix/files/12455615/UiUtils.txt)) that was used on one of the projects, together with the above addon (may be it will be useful).

**Comment by glebfox** [comment]
Vaadin has a [Debouncer](https://github.com/vaadin/web-components/blob/main/packages/component-base/src/debounce.js) for JS code that is used to collapse multiple callbacks into one invocation after a timer. For example:

```
this.__debounceSetValue = Debouncer.debounce(this.__debounceSetValue, timeOut.after(timeout), () => {
    this.value = JSON.stringify(this._editor.getContents().ops);
});

...

if (this.__debounceSetValue && this.__debounceSetValue.isActive()) {
    lastCommittedChange = this.value;
    this.__debounceSetValue.flush();
}
```
