### ISSUE TITLE
BPMN modeler: input dialog parameter type should be localized

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2175]
Jmix version: 2.0.1
In the runtime BPMN modeler create an input dialog process form
Add input dialog parameter

AR: in the Type dropdown list we see "system" names of types
<img width="790" alt="Screenshot 2023-08-29 at 12 29 57" src="https://github.com/jmix-framework/jmix/assets/7888486/75bbd96a-4bef-4a4a-b6b1-cc305419e942">

ER: human readable type names as it was in Jmix 1.5:
<img width="668" alt="Screenshot 2023-08-29 at 12 29 42" src="https://github.com/jmix-framework/jmix/assets/7888486/ccd915df-ea03-4e25-9ff7-4c9ee537e432">

**Comment by KartnDev** [comment]
## Cannot reproduce / already fixed
Jmix version: 2.1.1
Jmix Studio plugin version: 2.1.SNAPSHOT5675-232
IntelliJ version: IntelliJ IDEA 2023.2 (Ultimate Edition)

![image](https://github.com/jmix-framework/jmix/assets/43281522/992b9635-ac5d-4839-bfc5-b74f0445816b)
![image](https://github.com/jmix-framework/jmix/assets/43281522/2c9e1cfd-5908-4503-8595-919ec28c2b74)
![image](https://github.com/jmix-framework/jmix/assets/43281522/c46703cc-d92c-4365-9b17-aea5cf0db45e)


Jmix version: 3.0.999-SNAPSHOT (master)
Jmix Studio plugin version: 2.1.SNAPSHOT5675-232
IntelliJ version: IntelliJ IDEA 2023.2 (Ultimate Edition)
![image](https://github.com/jmix-framework/jmix/assets/43281522/b1299d34-7983-4398-bbf3-5e7841303d55)
