### ISSUE TITLE
The alignment of the header in the form is broken

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2190]
Jmix version: 2.1.999-SNAPSHOT

BPM User task
![image](https://github.com/jmix-framework/jmix/assets/114649487/47c4156c-1fc7-4b68-abe5-f59ddeb2c62e)

Entity

https://github.com/jmix-framework/jmix/assets/114649487/5408c5e9-4634-4f1b-b53a-24b5213ac39c

**Comment by KartnDev** [comment]
Additional, if field is hidden, field's label is still visible:
![image](https://github.com/jmix-framework/jmix/assets/43281522/46ff72e0-d1a1-496d-8687-65d3d85d84bc)

**Comment by KremnevDmitry** [comment]
Should be fixed after: #2201
