### ISSUE TITLE
Cannot use SimplePagination with keyValueCollection and paginationTotalCountDelegate handler

### ISSUE THREAD

**Issue by ig0rix** [jmix-framework/jmix#2192]
Hi, everyone!

Jmix 2.0.1

I try to use SimplePagination with keyValueCollection and paginationTotalCountDelegate handler.
Click on pagination button "Go to Last page" raises an exception:
`java.lang.ClassCastException: class io.jmix.flowui.model.impl.KeyValueCollectionLoaderImpl cannot be cast to class io.jmix.flowui.model.CollectionLoader (io.jmix.flowui.model.impl.KeyValueCollectionLoaderImpl and io.jmix.flowui.model.CollectionLoader are in unnamed module of loader 'app')
	at io.jmix.flowui.data.pagination.PaginationDataLoaderImpl.getCount(PaginationDataLoaderImpl.java:100) ~[jmix-flowui-2.0.1.jar:na]
	at io.jmix.flowui.component.pagination.SimplePagination.getTotalCount(SimplePagination.java:572) ~[jmix-flowui-2.0.1.jar:na]
	at io.jmix.flowui.component.pagination.SimplePagination.onLastClick(SimplePagination.java:358) ~[jmix-flowui-2.0.1.jar:na]
	at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:233) ~[flow-server-24.0.9.jar:24.0.9]
	at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:475) ~[flow-server-24.0.9.jar:24.0.9]
	at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:292) ~[flow-server-24.0.9.jar:24.0.9]
.....`

**Comment by Flaurite** [comment]
Hello @ig0rix , I've reproduced the issue. Thank you for reporting the problem!

**Comment by Flaurite** [comment]
### Breaking changes
Changed generic type in Function.

Before:
```
PaginationComponent#setTotalCountDelegate(@Nullable Function<LoadContext, Integer> totalCountDelegate);
```
After
```
PaginationComponent#setTotalCountDelegate(@Nullable Function<DataLoadContext, Integer> totalCountDelegate);
```
I.e. `LoadContext` -> `DataLoadContext`

Changes can affect explicitly usage of this method, for instance:
```
@Autowired
private DataManager dataManager;
@ViewComponent
private SimplePagination pagination;

@Subscribe
public void onInit(final InitEvent event) {
   pagination.setTotalCountDelegate(loadContext -> {
       return ((Long) dataManager.getCount(loadContext)).intValue(); // Here is an error, loadContext is DataLoadContext
   });
}
```
If you use `totalCountDelegate` via `@Install` annotation, it should be fine. Because the `LoadContext` that is defined in method parameters the same type that is passed to this method. The following code still works for CollectionLoader:
```
@Install(to = "pagination", subject = "totalCountDelegate")
private Integer paginationTotalCountDelegate(final LoadContext loadContext) {
    return ((Long) dataManager.getCount(loadContext)).intValue();
}
```
Now the `@Install` method looks the following:
```
@Install(to = "pagination", subject = "totalCountDelegate")
private Integer paginationTotalCountDelegate(final DataLoadContext dataLoadContext) {
    if (dataLoadContext instanceof LoadContext<?> loadContext) {
        return ((Long) dataManager.getCount(loadContext)).intValue();
    }
    return 0;
}
```
