### ISSUE TITLE
Unclear time unit for `step` attribute

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#2199]
To set a correct interval, the value of `step` needs to be multiplied by 10.

**AR**: 
* `<timePicker step="150"/>` declares a `timePicker` component with 15 minutes interval between values.
*  `<dateTimePicker step="900"/>` declares a `dateTimePicker` component with 90 minutes interval between values.

**ER**: 
* `<timePicker step="15"/>` declares a `timePicker` component with 15 minutes interval between values.
* `<dateTimePicker step="90"/>` declares a `dateTimePicker` component with 90 minutes interval between values.

**Comment by konyashkina** [comment]
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5617-232
IntelliJ version: IntelliJ IDEA 2023.2.2
