### ISSUE TITLE
Update formLayout components in the framework views

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2212]
After: https://github.com/jmix-framework/jmix/issues/2201

It is required to find views where `labelPosition=ASIDE` is used and update them.

**Comment by KremnevDmitry** [comment]
View to fix:

BPM:
- [ ] ProcessInstanceMigrationView
- [ ] MyTaskListView

**Comment by konyashkina** [comment]
Tested on  
Jmix version: 2.1.999-SNAPSHOT and 2.1.0-RC1
