### ISSUE TITLE
Calendar component

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2216]
Free part of https://fullcalendar.io/demos looks promising, but further research is needed.

**Comment by Flaurite** [comment]
Other options:
- https://ui.toast.com/tui-calendar
- https://github.com/vkurko/calendar

**Comment by glebfox** [comment]
* When using `io.jmix.flowui.model.CollectionContainer#replaceItem`: old version of related calendar event is also displayed.

* Fix event hover background color and cursor - uses hardcoded color instead of theme dependant

* Fix focus color - uses browser default color

<img width="128" alt="Screenshot 2024-09-23 at 18 04 48" src="https://github.com/user-attachments/assets/8e04f70c-5bc1-4ae7-a19c-7efbbc14f817">

**Comment by rusiaikinat** [comment]
there is no description of actions for the calendar in the descriptor

![image](https://github.com/user-attachments/assets/78b725dc-a841-4314-8a96-0b24acaba6ae)

![image](https://github.com/user-attachments/assets/7c42da18-ed53-4666-acf7-697e2a5b6273)

**Comment by rusiaikinat** [comment]
```
<valuePicker id="recurringDaysOfWeekField" property="recurringDaysOfWeek">
                <actions>
                    <action id="daysOfWeekEdit" type="fcalen_daysOfWeekEdit"/>
                    <action id="clear" type="value_clear"/>
                </actions>
</valuePicker>
```

![image](https://github.com/user-attachments/assets/2020df30-488a-41ba-af29-092baf58efcc)
