### ISSUE TITLE
Typo in inspector for tab element

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#2217]
flewGrow -> flexGrow
<img width="301" alt="Screenshot 2023-09-11 at 12 48 48" src="https://github.com/jmix-framework/jmix/assets/128021710/f2711202-1ce2-49b9-9faf-3d720f1d7893">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5617-232
IntelliJ version: IntelliJ IDEA 2023.2.2 (Ultimate Edition)
