### ISSUE TITLE
Some of `tabs` component's themes work incorrectly

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#2218]
* `equal-width-tabs` theme stretches the component across the entire page.
![Screenshot 2023-09-11 at 13 06 14](https://github.com/jmix-framework/jmix/assets/128021710/3e0e5aea-1e37-45b7-93ca-53c32fe5d9fb)
```
<tabs themeNames="equal-width-tabs">
...
</tabs>
```

* `icon-on-top` applied to `tabs` has no effect on the icon position. However, it works for individual `tab` element.
![Screenshot 2023-09-11 at 13 09 35](https://github.com/jmix-framework/jmix/assets/128021710/968eddd7-889d-4c7d-b46b-7ac5b82b6110)

```
        <tabs themeNames="icon-on-top">
            <tab id="tab1">
                <icon icon="INFO_CIRCLE"/>
                <span text="Tab One"/>

            </tab>
            <tab id="tab2" themeNames="icon-on-top">
                <icon icon="HOME"/>
                <span text="Tab Two"/>
            </tab>
        </tabs>
```

* `fixed` theme doesn't seem to have any effect at all in standard application. May be it's part of Material theme, not Lumo.

**Comment by KremnevDmitry** [comment]
> - equal-width-tabs theme stretches the component across the entire page.
> - icon-on-top applied to tabs has no effect on the icon position. However, it works for individual tab element.

This is the Vaadin's features, see: https://github.com/vaadin/flow-components/issues/5541

> - fixed theme doesn't seem to have any effect at all in standard application. May be it's part of Material theme, not Lumo.

The `fixed` value, actually, belongs to the **meterial** theme-set. The value has been removed from suggestions.
