### ISSUE TITLE
BpmModeler: reuse properties of exising form fields

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#2223]
Reuse properties of exising form fields in FormFieldEdit screen.

Discussion - https://forum.jmix.io/t/bpm/3346.

Jmix version: 1.5.3

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.1.2-233
IntelliJ version: IntelliJ IDEA 2023.3.2 (Ultimate Edition)
