### ISSUE TITLE
BpmModeler: add support of external worker tasks

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#2227]
Add support of external worker tasks.

Description:
- https://www.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs#external-worker-task
- https://docs.camunda.org/manual/7.19/user-guide/process-engine/external-tasks/

Discussion:
- https://forum.jmix.io/t/bpm/3347

Jmix version: 1.5.3

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.1.2-233
IntelliJ version: IntelliJ IDEA 2023.3.2 (Ultimate Edition)
