### ISSUE TITLE
Skip enhancing of entities if entities weren't changed

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2245]
Enhancing in large projects significantly slows down the project build, because it's triggered on each change even in UI code.
See for example [forum topic](https://forum.jmix.io/t/how-to-make-enhance-process-quickly-when-we-start-it/3606).

Maybe we need to introduce a multi-module project structure with entities in separate module.

**Comment by knstvk** [comment]
See also https://forum.jmix.io/t/compilation-takes-too-long-for-a-converted-to-jmix-application/3825

**Comment by gorbunkov** [comment]
See implementation details in pull request description: https://github.com/jmix-framework/jmix/pull/2848

For QA, you may find the information whether entities enhancing happened or not in the build log of the application. Please also test that config property explain in the PR description works as expected.
