### ISSUE TITLE
User Settings

### ISSUE THREAD

**Issue by web-devel** [jmix-framework/jmix#226]

**Comment by aleksey-stukalov** [comment]
Currently, screen settings provide unclear API:
- unclear lifecycle, e.g. when they get loaded, applied stored. In other words what events to subscribe to manipulate with them.
- unclear API to write/read saved elements.
- unclear what exactly it stores and applies (depends on the `settingsEnabled` property of external components)

**Proposition**

Extract this functionality in a facet:
```
  <screenSettings includeAll="true"/>

  <screenSettings>
        <include componentId="idx1"/>
        <include componentId="idx2"/>
        <exclude componentId="idx3"/>
  </screenSettings>
```

To make lifecycle transparent provide install delegates/events for:
- loading screen settings
- applying screen settings
- saving screen settings

Simplify API for reading and writing elements:
```
   settings.put(String componentId, String property, Object valueInAnyFormat)
   String value = settings.get(String componentId, String property)
```

Centralize logic for capturing settings from objects and applying them back. E.g. register `SettingsWorker` classes for a specific component type (Table.class, Filter.class, ...), which will gather all required properties for a component and will be able to apply them.
