### ISSUE TITLE
BpmModeler - add support of external worker tasks (port from 1.6)

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2260]
See https://github.com/jmix-framework/jmix/issues/2227

PRs: 
* https://github.com/jmix-framework/jmix-premium/pull/190
* https://github.com/jmix-framework/jmix/pull/2248

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5619-232
IntelliJ version: IntelliJ IDEA 2023.2.2 (Ultimate Edition)
