### ISSUE TITLE
Signal selection is broken for Signal Intermediate Catch event

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2261]
Jmix version: 2.0.2

In the BPMN runtime modeler add a Signal Intermediate Catch Event to the modeler.
Try to select a signal definition from a combo-box in a properties panel

Expected result: a list with existing signal definitions with an option to create a new one. Like it was in 1.x version:

<img width="671" alt="Screenshot 2023-09-20 at 18 52 23" src="https://github.com/jmix-framework/jmix/assets/7888486/61270a59-4450-4ca3-b519-be0ffe70f88d">

Actual result: cannot open the list

The same problem is with Message Intermediate Catch Event.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.0-RC1
Jmix Studio plugin version: 2.1.SNAPSHOT5666-232
IntelliJ version: IntelliJ IDEA 2023.2.2 (Ultimate Edition)
