### ISSUE TITLE
Cannot edit BPMN model element name by a double-click on the element

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2271]
Jmix: 2.0.2

1. Open the runtime BPMN modeler.
2. Add a UserTask or any other element.
3. Double-click on the element.

Expected behavior: cursor is set inside the element on the canvas and user can change the element name (see how it should work [here](https://demo.bpmn.io/new)).

Actual behavior: Property panel blinks and there is no cursor inside the element.

**Comment by KartnDev** [comment]
![image](https://github.com/jmix-framework/jmix/assets/43281522/ebd96f5a-a943-42bf-b5c7-fa8a828cdec6)
![image](https://github.com/jmix-framework/jmix/assets/43281522/5a523d4c-ca76-472b-82bc-4a9d19218c62)
Cannot reproduce...

**Comment by gorbunkov** [comment]
The problem is that when we double-click the element on the canvas, the focus goes on the "id" field of the element properties panel on the right, but the cursor should remain inside the editable element on the canvas

**Comment by KartnDev** [comment]
Solution found, wait for other issue

**Comment by gorbunkov** [comment]
Studio issue: https://youtrack.jmix.io/issue/JST-4556
