### ISSUE TITLE
"strategyClass" missing in properties for aggregation

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2272]
_Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5509-231
IntelliJ version: IntelliJ IDEA 2023.1.5 (Ultimate Edition)_

![image](https://github.com/jmix-framework/jmix/assets/114649487/a65609c7-feba-43ac-95f2-9b641df1033b)

**Comment by KremnevDmitry** [comment]
Fixed in https://github.com/jmix-framework/jmix/issues/1754

![image](https://github.com/jmix-framework/jmix/assets/75516667/cdff711c-c844-4c57-9c16-4febdb90a6ca)
