### ISSUE TITLE
Entity Inspector doesn't show removed records

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#2276]
The bug looks like as https://github.com/jmix-framework/jmix/issues/1682

_Reproduced on_ 
Jmix version: 1.5.4 (nexus repo)
Jmix Studio plugin version: 2.0.SNAPSHOT5504-231
IntelliJ version: IntelliJ IDEA 2023.1.4 (Ultimate Edition)

both cases: FlowUI ans Classic UI.

_Steps to reproduce:_ 
Run Jmix app, login as admin.
Open Users and create a new user. Then delete the new user. 
Go to Entity Inspector (in FlowUI: Data Tools > Entity Inspector ) and set filter: 
- Show all records
- Show removed records only

_ER:_ Removed records are shown in the table below. 
_AR:_ Removed records aren't shown.

**Comment by yuriy-khrebtov** [comment]
Can't reproduce
