### ISSUE TITLE
genericFilter should have decent layout on screen of any width

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2277]
Example problems:

---

<img width="460" alt="image" src="https://github.com/jmix-framework/jmix/assets/5513878/a5d86123-385e-4a47-b5e0-3968df1b662c">

---

<img width="635" alt="image" src="https://github.com/jmix-framework/jmix/assets/5513878/82779ece-a6c7-4235-a692-2be187c22667">

---

**Comment by KremnevDmitry** [comment]
The reason: https://github.com/vaadin/web-components/issues/606
