### ISSUE TITLE
Support all click events

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2285]
See Studio issue: https://youtrack.jmix.io/issue/JST-4268/ClickEvent-for-button-are-duplicated.

**Description:**
We have 3 similar handlers from com.vaadin.flow.component.ClickNotifier:
- addClickListener
- addDoubleClickListener
- addSingleClickListener

**Possible solution:** 
Add parameter "method" (or "subject") in @Subsribe annotation to define handler method.

**Comment by KremnevDmitry** [comment]
The following logic for scanning for a method for subscription has been implemented:
1. When scanning methods, methods with the same signature are identified and written to the separate map
2. Now, when resolving the `@Subscribe` annotation, the presence of the `subject` attribute is taken into account

# E.g.
### Case 1:
No `subject`:
In this case, the method that is in the cache will be applied.
```java
    @Subscribe(value = "button")
    public void onButtonClick(final ClickEvent<JmixButton> event) {
        notifications.show("Clicked");
    }
```

### Case 2: 
A `subject` attribute for a method with an **clashing signature** has been specified.
```java
    @Subscribe(value = "button", subject = "doubleClickListener")
    public void onButtonDoubleClick(final ClickEvent<JmixButton> event) {
        notifications.show("Double clicked");
    }
```

### Case 3:
A `subject` attribute for a method with a **default signature** has been specified.
```java
    @Subscribe(value = "textArea", subject = "valueChangeListener")
    public void onTextAreaComponentValueChange(final AbstractField.ComponentValueChangeEvent<JmixTextArea, Object> event) {
        notifications.show("Text area value changed");
    }
```
