### ISSUE TITLE
Cannot clear filter fields in the "User tasks" screen.

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#2286]
Jmix version: 1.5.4.

It is impossible to clear filter fields "Assignee" and "Candidate user" in "User tasks" screen. These fields don't have clear actions and option lists don't contain empty values.

![image](https://github.com/jmix-framework/jmix/assets/11490702/6701f0bc-9c89-4dde-a6c3-c77bd632853d)

**Comment by gorbunkov** [comment]
I've created an issue for adding a clear action to the SuggestionField component: https://github.com/jmix-framework/jmix/issues/2309

**Comment by gorbunkov** [comment]
Clear buttons have been added to the suggestion fields. See https://github.com/jmix-framework/jmix-premium/pull/191#issuecomment-1745226236

**Comment by daring2** [comment]
@gorbunkov, after the PR is merged should I reassign related tasks (maybe to QA team)?

**Comment by gorbunkov** [comment]
> @gorbunkov, after the PR is merged should I reassign related tasks (maybe to QA team)?

@daring2 No, we'll handle it ourselves. Actually this issue is already marked for QA. You can find this by looking at its status on a Release 1.5 project board https://github.com/jmix-framework/jmix/projects/6#card-90740569

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.4
Jmix Studio plugin version: 2.1.1-233
IntelliJ version: IntelliJ IDEA 2023.3 RC (Ultimate Edition)
