### ISSUE TITLE
Ability to define theme names for layouts 

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2293]
It appears that hBox, vBox supports theme variants: `spacing-xs`, `spacing-s`, `spacing`, `spacing-l`, `spacing-xl`.

`layout.getThemeList().add("spacing-xs")`

**Comment by natfirst** [comment]
For QA: you can simply specify theme names in corresponding attribute
![image](https://github.com/jmix-framework/jmix/assets/17950251/7a89a23b-898c-4936-882b-d3960321440a)
