### ISSUE TITLE
Add alignSelf attribute to all components

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2294]
Similar to `colspan` attribute, add `alignSelf` attribute to all components and handle it by `FlexComponent` inheritors.

---

Studio issue: https://youtrack.jmix.io/issue/JST-4298/Support-alignSelf-attribute-for-FlexComponents

**Comment by KremnevDmitry** [comment]
- [ ] layout.xsd
- [ ] Loader
- [ ] Tests
- [ ] Studio annotations
