### ISSUE TITLE
Label for FileUploadField is not centered in FormLayout

### ISSUE THREAD

**Issue by yuriy-khrebtov** [jmix-framework/jmix#2299]
If we add FileUploadField in a form layout with label aside, the label will not be aligned in the center against of file upload component.
Looks like it's because of extra margin in file name component (button) of the upload field:

![image](https://github.com/jmix-framework/jmix/assets/142792860/bb82206c-6876-45a8-9b2a-374e70f8403f)

**Comment by glebfox** [comment]
<img width="1214" alt="Screenshot 2023-10-05 at 13 07 45" src="https://github.com/jmix-framework/jmix/assets/6077149/50bda73a-096c-4dd7-8c8e-4b452b913070">
<img width="931" alt="Screenshot 2023-10-05 at 13 07 58" src="https://github.com/jmix-framework/jmix/assets/6077149/f4907a47-2a86-4396-aae7-13d4c650b4bc">

**Comment by rusiaikinat** [comment]
Reopened

![image](https://github.com/jmix-framework/jmix/assets/114649487/bf03d7ad-c9dc-469e-89fa-729be99b12c1)

```
<layout>
        <formLayout labelsPosition="ASIDE">

<button icon="ADJUST" iconAfterText="true" text="msg://werty"/>
            <fileUploadField id="qwe" label="msg://qwe.label" clearButtonVisible="true" uploadIcon="ABACUS"
                             uploadDialogTitle="msg://qwe.uploadDialogTitle"
                             uploadDialogCancelText="msg://qwe.uploadDialogCancelText"
                             requiredMessage="msg://qwe.requiredMessage"
                             fileNotSelectedText="msg://qwe.fileNotSelectedText" fileNameVisible="true"
                             fileName="msg://qwe.fileName" uploadText="msg://qwe.uploadText"
                             connectingStatusText="msg://qwe.connectingStatusText"/>

        </formLayout>
    </layout>
```
