### ISSUE TITLE
BPM - UI/UX improvements

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#2306]
Jmix version: 1.5.4.

Discussion - https://forum.jmix.io/t/bpm-ui-ux/3716

Proposed changes:

1. Add screenSettings and presentations facets in browse screens (process-definition-browse.xml, process-instance-browse.xml, etc).
2. Add collapsed columns for avaiable entity properties in browse screens (process-definition-browse.xml - deploymentId, suspended; form-data-properties-fragment.xml - caption, editable, required; etc).
3. Add a notification about sucessfull process start.

**Comment by gorbunkov** [comment]
ScreenSettings faced has been added to the BPMN modeler screen. It is possible now to display the "Caption" column in the input dialog parameters table.
The height of the input dialog parameters table in the BPMN modeler has been increased (more parameters can be displayed at once).

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.1.2-233
IntelliJ version: IntelliJ IDEA 2023.3.2
