### ISSUE TITLE
Default enum value should use ComboBox in attribute detail view

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2312]
~~Also for better UI needs to backport feature visiblility component combo box + scan inside Visibility tab~~
UPD:  visiblility component combo box already implemented
### Feature:
Change text field to combo box ui element on "default value" property when dynamic attribute has type "Enumeration"

**Comment by rusiaikinat** [comment]
![image](https://github.com/jmix-framework/jmix/assets/114649487/23597fdf-8828-41d5-a078-4dc4baaca8c2)

**Comment by KartnDev** [comment]
> ![image](https://private-user-images.githubusercontent.com/114649487/303595955-23597fdf-8828-41d5-a078-4dc4baaca8c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODMwNzEsIm5iZiI6MTcwNzQ4Mjc3MSwicGF0aCI6Ii8xMTQ2NDk0ODcvMzAzNTk1OTU1LTIzNTk3ZmRmLTg4MjgtNDFkNS1hMDc4LTRkYzRiYWFjYThjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMjQ2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMTYyN2ExZTMwNWU1ZmEyYWYwNjU4NmIwYjMzZDgyOTNhNTFkYTdiOWY4NmYxZDUyOTM2NWYwNWViZWQ3Y2ZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zi1tdOh11GhiDUFTaazRDO6S_5ZGbBKZkM2Ay1UDYPE)
> 
> ![image](https://private-user-images.githubusercontent.com/114649487/303598520-5bb9b37d-a4fc-450c-ac89-78be442cf909.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0ODMwNzEsIm5iZiI6MTcwNzQ4Mjc3MSwicGF0aCI6Ii8xMTQ2NDk0ODcvMzAzNTk4NTIwLTViYjliMzdkLWE0ZmMtNDUwYy1hYzg5LTc4YmU0NDJjZjkwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOVQxMjQ2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNThhOTk3MWRkOWI1NWJhYjYxNGJiYzQ0NjIyNTlhZTFmN2MzNTJlMGJkMTA0NTFkZWFiOWI5OWMwMDM3NjNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wccsYL43EouA3V7xQzasgxUXJfOiBsEeaRzmriwzB8U)

Seems like some of flowui changes did this
