### ISSUE TITLE
 DataLoadCoordinator doesn't trigger reload if query contains a session attribute parameter (port to 1.6)

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2326]
See #1412

**Comment by natfirst** [comment]
*Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 3.0.SNAPSHOT5680-232
IntelliJ version: IntelliJ IDEA 2023.2.3 (Community Edition)*

1. Open sample project [session-param-data-loader.zip](https://github.com/jmix-framework/jmix/files/13225557/session-param-data-loader.zip)
2. Run it. Make sure that you have Customer with Doe last name
3. Open Customer browser
*A.R.* Nothing shown
*E.R.* All customers with Doe last name should be displayed

**Comment by knstvk** [comment]
Fixed in Classic UI.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.0-232
IntelliJ version: IntelliJ IDEA 2023.2.6 (Community Edition)

![image](https://github.com/jmix-framework/jmix/assets/158277660/550deae6-a611-4403-b708-072b7acde73b)

**Comment by SergeiAksenov2** [comment]
Added another customer using a script - Ok.
All customers with Doe last name are displayed.
