### ISSUE TITLE
Action providers are broken (create at least not working) 

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2328]
Right now Action install annotation (`@Install` and manual subscription) **not working** (no invocation)
Demo with `@install` proves [here](https://github.com/KartnDev/actionsinstaller)

**Comment by gorbunkov** [comment]
@KartnDev It seems that the problem is that you open views with the NAVIGATION open mode. 


Handlers that you mention only work with the DIALOG mode. Their documentation explains that:

![Image](https://github.com/jmix-framework/jmix/assets/7888486/ca2133b9-b2a2-4508-a4e5-3855ade4454a)
