### ISSUE TITLE
Ability to track progress of FileMultiUploadField upload

### ISSUE THREAD

**Issue by igor-korotkov** [jmix-framework/jmix#2342]
Currently there is no way of knowing the number of files to be uploaded before the upload happens. 
Consequently, there is no way of creating a progressbar for the whole upload process (each tick = uploaded file).

Usecase: uploading a large number of not-so-big files. In this case the user wants to track the progress of the whole operation instead of looking at a series of near instant progressbars.

**Comment by yuriy-khrebtov** [comment]
Added `totalProgressDisplayCaption` property to set custom total label text and `totalProgressDisplayEnabled` property to set whether to display total progress bar.
