### ISSUE TITLE
Support for dynamic attributes in genericFilter

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2343]

**Comment by rusiaikinat** [comment]
**Reopened**

Added attribute with ENUM
The attribute was created in the filter for the inherited entity
![image](https://github.com/jmix-framework/jmix/assets/114649487/b6bba0d3-9a0a-4d83-944d-a1016610ae48)


**ER**
![image](https://github.com/jmix-framework/jmix/assets/114649487/2e8434b7-456f-4be3-a6ac-06ef9afe560b)
