### ISSUE TITLE
Impossible to obtain autowired process variables and ProcessFormContext data in Jmix View process forms

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2365]
Jmix: 2.0.2

It seems that there is no way to obtain values of injected ProcessFormContext (e.g. the Task) or injected process variables when [Jmix View process form](https://docs.jmix.io/jmix/bpm/jmix-view.html) is being opened. Everything works fine when the process form is opened from the My Tasks screen and the form has a DIALOG open mode. But there are problems when the open mode for the form is NAVIGATION.

It's unclear in which view event handler (Init, BeforeShow, etc.) users should analyze process variables and ProcessFormContext.

See [forum topic](https://forum.jmix.io/t/jmix-2-0-2-processformcontext-gettask-null/3769).

### Solution
Rework JmixView process form injection logic

### Changes
From now all values will be injected between `InitEvent` and  `BeforeShowEvent` (before `BeforeEnterEvent` in case of navigation mode).

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5691-232
IntelliJ version: IntelliJ IDEA 2023.2.4 (Ultimate Edition)
