### ISSUE TITLE
Refactor autowiring of created objects

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#237]
io.jmix.ui.sys.ActionsImpl#autowireContext, io.jmix.ui.sys.UiComponentsImpl#autowireContext, etc.
Put the logic in a single place.

**Comment by knstvk** [comment]
See https://github.com/Haulmont/jmix-ui/tree/237-autowre-helper

**Comment by glebfox** [comment]
Jmix 2+ has `io.jmix.flowui.sys.BeanUtil`
