### ISSUE TITLE
[MainView] Change nav display style from block to flex

### ISSUE THREAD

**Issue by breakingfox** [jmix-framework/jmix#2382]
Make nav component in the `MainView` use `display: flex;` in `main-view.css` so underlying components could be styled easier.

### Solution

`jmix-main-view-navigation` css class that is set for MainView's `nav` element, defines:

```
display: flex;
flex-direction: column;
```

**Comment by konyashkina** [comment]
Tested on
 Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5691-232
IntelliJ version: IntelliJ IDEA 2023.2.2 (Ultimate Edition)
