### ISSUE TITLE
Support for Multitenancy in Email Templates and Dashboards add-ons

### ISSUE THREAD

**Issue by vfadeevGit** [jmix-framework/jmix#2386]
Multitenancy add-on doesn't support E-mail templates and Dashboards. Thus it's impossible to configure them for specific tenants. This is a serious limitation when adopting Mulitenancy in the Jmix project. Have concerns about others like Notifications, Quartz and etc. You can find more details following the [link](https://forum.jmix.io/t/compatibility-between-multitenancy-and-other-addons/3802)

**Comment by glebfox** [comment]
Same issue is needed for Jmix 2.x

**Comment by glebfox** [comment]
Related issue: https://github.com/jmix-framework/jmix/issues/2196
