### ISSUE TITLE
Support limiting the number of nested elements

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2388]
See Studio ticket: https://youtrack.jmix.io/issue/JST-4344/Support-limiting-the-number-of-nested-elements.
Need to provide ability to define possible nested elements in meta-annotations.

**Comment by KremnevDmitry** [comment]
Verifyed

Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT-232
IntelliJ version: IntelliJ IDEA 2023.2.2 (Community Edition)
