### ISSUE TITLE
newEntitySupplier not work in navigator way

### ISSUE THREAD

**Issue by BryanYin** [jmix-framework/jmix#2391]
Please see below code in `list_create` `CreateAction.java`, when opening the detail view in dialog mode, it considers the `newEntitySupplier` but when it opens the detail view in navigator, it skips the handler. 

![image](https://github.com/jmix-framework/jmix/assets/25950822/f525c10d-8cd9-4dc0-be5d-cf9ef3fc345c)

**Comment by glebfox** [comment]
Hi, this is not a bug. We have no access to the view while navigating to it, only after a view is fully shown on the screen, i.e. when it is too late to init an entity
