### ISSUE TITLE
Support WebDAVDocumentLink and WebDAVDocumentVersionLink in studio

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2397]
For now `WebDAVDocumentLink` and `WebDAVDocumentVersionLink` components can be used in xml but are not displayed in studio: 
<img width="496" alt="изображение" src="https://github.com/jmix-framework/jmix/assets/38808384/22a605f5-80e2-4b69-92f4-60293bd355c6">

See  `io.jmix.webdavflowui.meta.StudioWebdavComponents`

**Comment by syncro** [comment]
implemented as a part of #2418
