### ISSUE TITLE
Document links in WebDAV document browser don't work

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2402]
Jmix version: 2.1.0-RC1

Open the WebDAV documents view.
Click any document link:

<img width="1258" alt="Screenshot 2023-10-25 at 16 21 24" src="https://github.com/jmix-framework/jmix/assets/7888486/3394cb02-6715-4991-aeea-8ae8e66b3f84">

You'll get the following:

<img width="1262" alt="Screenshot 2023-10-25 at 16 21 57" src="https://github.com/jmix-framework/jmix/assets/7888486/1ced7957-ca56-4231-bb9d-9387f846ef33">

But after you refresh this page, the document will be opened.

The same happens if click the link in the "WebDAV document versions" screen:

<img width="1269" alt="Screenshot 2023-10-25 at 16 23 12" src="https://github.com/jmix-framework/jmix/assets/7888486/c3dcb951-3dbf-4db1-88f8-e408419f8513">

However, the document is opened successfully if you use the "Open" button in the "WebDAV document versions" view.

<img width="1028" alt="Screenshot 2023-10-25 at 16 25 18" src="https://github.com/jmix-framework/jmix/assets/7888486/5bc13a2e-9703-4718-8f8b-ec4499819143">

**Comment by Gavrilov-Ivan** [comment]
Links (internal 'Anchor' components) should have target '_blank'.
```
protected Anchor createDocumentLink() {
    Anchor anchor = uiComponents.create(Anchor.class);
    anchor.setTarget(AnchorTarget.BLANK);
    return anchor;
}
```

**Comment by rusiaikinat** [comment]
**Reopened**

If you do not save the authorization settings when opening the file for the first time, then you will not be able to reopen the file

_Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5686-232
IntelliJ version: IntelliJ IDEA 2023.2.4 (Ultimate Edition)_
