### ISSUE TITLE
Get rid of AcceptsTenant interface

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2404]
The `io.jmix.multitenancy.core.AcceptsTenant` is used only in `io.jmix.multitenancy.core.impl.TenantProviderImpl#getCurrentUserTenantId` for getting a current user tenant and checking that a user class supports tenant. It seems that we can analyze the presence of `@TenantId` annotation on any class field instead of checking this interface.  In this case [configuring a user entity](https://docs.jmix.io/jmix/multitenancy/index.html#configuring-users) will be simplified.

**Comment by KremnevDmitry** [comment]
# For QA

## Test case 1

1. Create a project with version 2.3
2. Set up multitenancy add-on according to [doc](https://docs.jmix.io/jmix/multitenancy/index.html#installation)
3. Check the functionality of the multitenancy add-on
4. Migrate the project version to 2.4
5. Check the functionality of the multitenancy add-on one more time

## Test case 2

1. Create a project with version 2.4
2. Set up multitenancy add-on in a new way (without using the `AcceptTenant` interface)
3. Check the functionality of the multitenancy add-on

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6866-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
