### ISSUE TITLE
ResetAction of the GenericFilter breaks the PropertyFilter

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2406]
Steps to reproduce:

1. Open `UserListView` XML descriptor
2. Add `<propertyFilter property="username" operation="CONTAINS" dataLoader="usersDl"/>`
3. Open the View
4. Set some value to the property filter component
5. Reset the generic filter
6. Try to use the proeprty filter

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5863-233
IntelliJ version: IntelliJ IDEA 2023.3 (Ultimate Edition)
