### ISSUE TITLE
Improve BPM process form templates

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#2410]
Need to update BPM process form templates and create scripts for injecting BPM process variables to views.
Studio [ticket](https://youtrack.jmix.io/issue/JST-3912/Improve-process-form-templates)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5691-232
IntelliJ version: IntelliJ IDEA 2023.2.4 (Ultimate Edition)

'Form for an entity object' option is not implemented yet, see Studio ticket JST-4349.
