### ISSUE TITLE
Remove version specification for hazelcast (Jmix 2.x)

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2412]
For now, Hazelcast 5.3.2 version used because of bug initially described in jmix-framework/jmix#2069. 
See also https://github.com/jmix-framework/jmix/issues/2071

#### Task
Remove version specification from `bom.gradle` when spring boot will provide hazelcast version without described bug (?5.2.5+?).

**Comment by gorbunkov** [comment]
Fixed in https://github.com/jmix-framework/jmix/issues/3196
