### ISSUE TITLE
WebDAV. Missing icons for elements 

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2418]
_Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5674-232
IntelliJ version: IntelliJ IDEA 2023.2.4 (Ultimate Edition)_

![image](https://github.com/jmix-framework/jmix/assets/114649487/499d91c3-0855-4e8f-8e84-4818c3621263)

**Comment by rusiaikinat** [comment]
Support WebDAVDocumentLink and WebDAVDocumentVersionLink in studio #2397

**Comment by Gavrilov-Ivan** [comment]
Need to introduce flowui-kit module and support all webdav ui components in studio.
