### ISSUE TITLE
Create translations for WebDAV addon

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#2421]
Add absent translation for WebDAV addon (EN and RU).

**Comment by MaxKatyshev** [comment]
_Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5750-232
IntelliJ version: IntelliJ IDEA 2023.2.5 (Ultimate Edition)_
verified
