### ISSUE TITLE
Implement global view events

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2428]
Implement follow events:

- ViewOpenedEvent - application event that is sent after the view is shown.
- ViewClosedEvent - application event that is sent after the view is closed.

Because these events are `applicationEvent`, so they must be listened to using spring event listeners.
How to work with spring events: https://www.baeldung.com/spring-events

Same as in the Classic UI: `io.jmix.ui.event.screen.ScreenOpenedEvent`

**Comment by natfirst** [comment]
Create Event Listener for working with event

```
@Component
public class OpenedEventListener implements ApplicationListener<ViewOpenedEvent> {

    private static final Logger log = org.slf4j.LoggerFactory.getLogger(OpenedEventListener.class);

    @Override
    public void onApplicationEvent(ViewOpenedEvent event) {
        log.debug(event.toString());
    }
}
```

Add application property `logging.level.com.company.sho.listener.OpenedEventListener = debug`

Start the app and open any screen.
Info in log appears `2024-02-06T18:11:10.543+04:00 DEBUG 10316 --- [nio-8080-exec-9] c.c.sho.listener.OpenedEventListener     : io.jmix.flowui.event.view.ViewOpenedEvent[source=io.jmix.securityflowui.view.resourcerole.ResourceRoleModelListView@6d4f4279]`
