### ISSUE TITLE
ExcelExportAction does not consider sort order while exporting all rows

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2441]
### Description
Affected versions: 1.5+, 2.x.

During the optimization of loading data, Loader resets its sorter by primary key property. See https://github.com/jmix-framework/jmix/issues/1211.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
