### ISSUE TITLE
Incorrect StudioUiKit meta annotation in WebDAV add-on

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2459]
See io.jmix.webdavflowui.meta.StudioWebdavComponents

AR: 
@StudioUiKit(studioClassloaderDependencies = "io.jmix.datatools:jmix-webdav-flowui")

ER:
@StudioUiKit(requiredDependencies = "io.jmix.datatools:jmix-webdav-flowui")

It breaks Studio view designer preview.

#### QA Notes:
create/use a project with webdav and open preview for view with [webdav document upload field](https://docs.jmix.io/jmix/webdav/ui-components.html#webdav-document-upload-field). 
**ER:** Preview runs without problems

**Comment by dtaimanov** [comment]
@Fedoseew , could you, please, check the issue?

**Comment by Fedoseew** [comment]
@dtaimanov, everything is fine.
