### ISSUE TITLE
Add the ability to set up show time for validation notifications for whole project

### ISSUE THREAD

**Issue by natfirst** [jmix-framework/jmix#246]
Forum issue: https://www.cuba-platform.ru/discuss/t/soobshheniya-validaczii/6062

1. Create a mandatory field in the entity, create standard screens
2. Run the app, create entity instance, do not fill the mandatory field
3. Try to save the entity

*A.R.* Validation notification will appear and disappears after a while automatically. It is not possible to set the time in the project after which the notification will disappear

*E.R.* It will be useful if we add the property, that sets up show time for validation notifications for whole project

**Comment by gorbunkov** [comment]
It is not relevant for FlowUI
