### ISSUE TITLE
Sorting user sessions does not work

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#2460]
Affect Jmix version: 1.5+

Note: If you create a custom list of entities, you must manually sort the list.

See forum: https://forum.jmix.ru/t/v-razdele-sessii-polzovatelej-ne-rabotaet-sortirovka-esli-sessij-bolshe-50ti-pri-sortirovke-po-lyuboj-kolonke/1444

**Comment by NikitaShchienko** [comment]
Not reproduce for Jmix 2.0+

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6349-241
IntelliJ version: IntelliJ IDEA 2024.1
