### ISSUE TITLE
UserIndicator doesn't reload user when refreshing

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2465]
If a currently logged in user has been changed, then invoking `UserIndicator#refreshUser` has no effect because `CurrentUserSubstitution#getAuthenticatedUser` returns old instance.

**Comment by gorbunkov** [comment]
Check in 2.x

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
