### ISSUE TITLE
Describe data grid inline edit in meta annotations

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2473]
1. See: https://demo.jmix.io/ui-samples/sample/data-grid-inline-editor
2. Try to copy-paste code and open Jmix UI tool window.
**AR:**
Following code isn't supported in hierarchy

> 
               <editorActionsColumn key="bufferedEditorColumn" visible="false">
                    <editButton text="Edit" icon="PENCIL"/>
                    <saveButton icon="CHECK" themeNames="success"/>
                    <cancelButton icon="CLOSE" themeNames="error"/>
                </editorActionsColumn>
                <editorActionsColumn key="nonBufferedEditorColumn" visible="true">
                    <editButton text="Edit" icon="PENCIL"/>
                    <closeButton text="Close" icon="CLOSE"/>
                </editorActionsColumn>

![image](https://github.com/jmix-framework/jmix/assets/17950251/88eb3309-18d7-4cfc-87c8-6fccd1e9c997)

**Comment by natfirst** [comment]
_Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5750-232
IntelliJ version: IntelliJ IDEA 2023.2.4 (Community Edition)_

Still reproduce

![изображение](https://github.com/jmix-framework/jmix/assets/17950251/813da4bd-a59e-43b6-a4d6-abd4e3614dee)

**Comment by Fedoseew** [comment]
I forgot to move the changes to the branch for release 2.1. 
Fixedю
