### ISSUE TITLE
No ability to resize columns in WebDAV documents list

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#2484]
1. Open WebDAV documents list view
2. Create new document
3. Lock document with "Lock" button
ER: Columns in table should be resizeable and the text in "Lock state" column should be visible.
AR: User can't resize columns and can't see whole text in "Lock state" column

![image](https://github.com/jmix-framework/jmix/assets/50058889/631521d8-7cec-4145-875c-52685077bea0)

**Comment by Gavrilov-Ivan** [comment]
No need to explicit testing - minimalistic changes
