### ISSUE TITLE
Explicitly add responsiveSteps in DetailView template

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2493]

**Comment by KremnevDmitry** [comment]
# For QA

Cases to check

1. Generating entity detail view (with and without `labelsPositionAside` property)
2. Generating DTO detail view (with and without `labelsPositionAside` property) 
3. Generating master-detail view (with and without `labelsPositionAside` property) 
4. Generating BPM process form descriptor

**Comment by SergeiAksenov2** [comment]
Incorrect labelsPosition position in Dto descriptor.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6859-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
