### ISSUE TITLE
Add more obvious hint for search strategy field in the Full text filter condition editor

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2495]
Jmix: 2.1.0

When you create a Full-text search condition in the generic filter component, it is not obvious how to the hint for the Search strategy field. You need to place the mouse pointer over the field caption. We don't do it this way anywhere in the framework.

<img width="643" alt="image" src="https://github.com/jmix-framework/jmix/assets/7888486/5a2bfe7f-ccdf-4f3d-9627-4bbd3cc9ba97">

The hint must be reworked in a different way.

How it was in Classic UI:

<img width="603" alt="image" src="https://github.com/jmix-framework/jmix/assets/7888486/be3b0cfa-1390-496a-86a8-5c1d82023e07">

**Comment by gorbunkov** [comment]
Also, generate parameter name automatically.

**Comment by rusiaikinat** [comment]
Tested on: Java, Kotlin
![image](https://github.com/jmix-framework/jmix/assets/114649487/9598f1ad-cf64-4998-b1df-ec5609510ade)
