### ISSUE TITLE
Not localized message in the dialog that displays background task exception

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2496]
Jmix: 1.5.4

The problem is in the `io.jmix.ui.executor.LocalizedTaskWrapper#showExecutionError`

<img width="644" alt="image" src="https://github.com/jmix-framework/jmix/assets/7888486/85d36ffa-b501-4320-b704-5229aa94a17a">

Sample project (open the **Test screen** and click the **Run task** button): 
[background-task-caption.zip](https://github.com/jmix-framework/jmix/files/13415024/background-task-caption.zip)

See [forum topic](https://forum.jmix.io/t/background-task-error-caption-change/3973).

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5856-233
IntelliJ version: IntelliJ IDEA 2023.3 (Ultimate Edition)

![backgr-task-except](https://github.com/jmix-framework/jmix/assets/85500330/390a356a-8daf-4d30-adbe-ed6bcd0d5b2d)
