### ISSUE TITLE
Implement Resource owner password credentials grant in Authorization server add-on

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2499]
Although [Resource owner password credentials grant](https://datatracker.ietf.org/doc/html/rfc6749#page-37) was deprecated in OAuth 2.1 and is not supported by the Spring Authorization Server library that we use, we may consider adding a support of this grant type to the add-on. 

Existing users who migrate from CUBA or Jmix 1.x may want to leave the authorization flow as it was before.

See [Spring documentation](https://docs.spring.io/spring-authorization-server/reference/guides/how-to-ext-grant-type.html) about implementing custom grant type.

See [forum topic](https://forum.jmix.io/t/how-to-authenticate-in-rest-with-jmix-user-credentials/3965).

**Comment by gorbunkov** [comment]
See description in jmix-docs PR: https://github.com/jmix-framework/jmix-docs/pull/678

**Comment by Gamer08YT** [comment]
Is a snapshot available? I think this function is very useful.

**Comment by gorbunkov** [comment]
> Is a snapshot available? I think this function is very useful.

When you create a new Jmix project choose the `nexus.jmix.io` repository and select the "Show unstable versions" checkbox. After that you'll be able to select the `2.3.999-SNAPSHOT` Jmix version.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6366-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6368-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

There is no exception. 
By command the access_token was generated - Ok.
Users were got from application with Bearer authorization with the access-token - Ok.
