### ISSUE TITLE
tenant is set to no_tenant after soft-deletion of entity 

### ISSUE THREAD

**Issue by klaus7** [jmix-framework/jmix#2500]
See title. I will try to implement a minimum test project.

It looks like this has to do with removing of an entity per id and only when authorized as a normal tenant user (not admin).

```java
datamanager.remove(Id.of(...));
```

**Comment by dtaimanov** [comment]
Hello @klaus7 
I've tried to reproduce the issue on [my simple project](https://github.com/jmix-framework/jmix/files/13953867/mtensftdel212.zip) and had no luck.
(Please see "Delete TestEntity by id" button on Test Entity list view. Id may be found in "test_entity" table using database viewer.)

It is the only way to reproduce it, that comes to mind: hard delete entity and reinsert it without authentification, which is, as expected, will create new entity with appropriate tenant_id. Maybe something similar happens?

I will close this issue for now. 
Please, reopen when reproducible example will be attached.
