### ISSUE TITLE
Upgrade to Spring Boot 3.2

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2503]
See [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2.0-Release-Notes)

**Comment by glebfox** [comment]
### Breaking changes

* `LiquibaseProperties` - the `getLabels()` has been removed, `getLabelFilter()` must be used instead.
* `org.eclipse.angus:jakarta.mail` (Angus Mail default provider) changed its root package from `com.sun.mail` to `org.eclipse.angus.mail`
* `AbstractPlatformTransactionManager.prepareSynchronization` is `private` now. Replaced with `TransactionExecutionListener`.
