### ISSUE TITLE
Chinese translation add-on: header is vertically oriented 

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#2505]
_Jmix version: 2.1.0 and 2.1.1
Jmix Studio plugin version: 2.1.0-232
IntelliJ version: IntelliJ IDEA 2023.2.5 (Ultimate Edition)
Tested with_ https://github.com/jmix-projects/jmix-flowui-smoke-test 

Simplified Chinese translation add-on.
Some headers are vertically oriented and do not fit in the space provided for it. (E.g. check Audit log or Roles)

![chinese-audit-log-header](https://github.com/jmix-framework/jmix/assets/85500330/ff8ddd50-63e3-4b62-82df-ae7fb6b43390)

![chinese-header](https://github.com/jmix-framework/jmix/assets/85500330/c0abdfc7-bdad-42ea-baa4-9070a276ec5d)

**Comment by glebfox** [comment]
I see that your main-view's `header` contains additional component located in the middle of it. Are you sure that your layout is correct? The default header without custom components displays everything correctly:

<img width="824" alt="Screenshot 2023-11-23 at 13 03 20" src="https://github.com/jmix-framework/jmix/assets/6077149/e633463b-3dff-4c3e-907f-aa17ef20f582">

Could you please attach either a main-view.xml code or a demo project?

**Comment by rusiaikinat** [comment]
TC
```
<mainView xmlns="http://jmix.io/schema/flowui/main-view"
          title="msg://MainView.title"
          xmlns:ntf="http://jmix.io/schema/notifications/ui"
          xmlns:search="http://jmix.io/schema/search/ui">

  <navigationBar>
            <header id="header" classNames="jmix-main-view-header">
                <drawerToggle id="drawerToggle"
                              classNames="jmix-main-view-drawer-toggle"
                              themeNames="contrast"
                              ariaLabel="msg://drawerToggle.ariaLabel"/>
                <h1 id="viewTitle" classNames="jmix-main-view-title"/>
                <vbox alignItems="CENTER">
                    <search:searchField id="idSearchField"/>
                </vbox>
                <vbox alignItems="END">
                    <hbox>
                        <button id="createNotificationBtn" action="createNotification"/>
                        <ntf:notificationsIndicator id="notificationsIndicator"/>
                    </hbox>
                </vbox>
            </header>
        </navigationBar>
```

**Comment by glebfox** [comment]
Bu default, `vbox` has `width=100%`, which within `flex` container behaves similar to class `extend` option. As a result, `h1` is narrowed down to the minimum possible `width`. It appears that in Chinese every hieroglyph can be wrapped, so you see them in a column. The same cab be achieved in every language if a view title contains space, e.g.:

<img width="811" alt="Screenshot 2023-11-27 at 11 48 12" src="https://github.com/jmix-framework/jmix/assets/6077149/851b010b-db3f-4426-97dc-37f80266bafe">

if the layout above is really needed, the following style fixes the problem:

```
.jmix-main-view-title {
    text-wrap: nowrap;
}
```
