### ISSUE TITLE
LoginForm missing XML attributes corresponding to HasStyle interface

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2506]
### Environment

Jmix version: 2.x

### Bug Description

`LoginForm` component implements `HasStyle` but missing corresponding attributes in XML.

**Comment by MaxKatyshev** [comment]
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5881-233
IntelliJ version: IntelliJ IDEA 2023.3 (Ultimate Edition)
_verified_
