### ISSUE TITLE
Add setViewConfigurer method to ViewOpeningAction interface

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2507]
### Feature Description

Since we have DIALOG related API in the `ViewOpeningAction` interface, e.g. `setAfterCloseHandler`, it would be convenient to have `setViewConfigurer` method similar to `setScreenConfigurer` from class UI, which accepts an opening view to invoke its API before it's opened.

**Comment by KremnevDmitry** [comment]
Studio support issue: https://youtrack.jmix.io/issue/JST-4534/viewConfigurer-install-point-generation-must-use-the-correct-parameter
