### ISSUE TITLE
DataGrid columns and TabSheet tabs are not injected into controller

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2508]
### Environment

Jmix version: 2.1.1

### Bug Description

Studio suggests injection of DataGrid columns and TabSheet tabs, but they remain `null` after view is opened. 

Injecting DataGrid columns can be discussed since we didn't have that option, but the tabs should be injectable.

### Steps To Reproduce

1. Open a controller of any view with DatGrid/TabSheet
2. Inject columns/tabs usingStudio
<img width="856" alt="Screenshot 2023-11-23 at 12 46 25" src="https://github.com/jmix-framework/jmix/assets/6077149/d3383d2e-3e7f-4132-ad3b-da1560bc1e15">
 
### Current Behavior

Injected fields are `null`

### Expected Behavior

Injected fields refers to the corresponding columns/tabs

**Comment by KremnevDmitry** [comment]
After discussions, it was decided not to implement DataGrid's columns in the view controller.

A corresponding task was assigned to the studio team: https://youtrack.haulmont.com/issue/JST-4529/Remove-DataGrid-columns-from-injection-suggestions

**Comment by MaxKatyshev** [comment]
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5887-232
IntelliJ version: IntelliJ IDEA 2023.2.5 (Ultimate Edition)
_verified_
