### ISSUE TITLE
Not all components suggest Renderer supplier

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2511]
### Environment

Jmix version: 2.1.1

### Bug Description

Currently, only VirtualList suggests Renderer supplier in Studio inject dialog.

### Current Behavior

`Renderer - Renderer` is suggested only for `VirtualList`, e.g.:

<img width="462" alt="Screenshot 2023-11-23 at 13 18 54" src="https://github.com/jmix-framework/jmix/assets/6077149/02b26bc8-1f9f-4845-8e9a-e0a05cd931a5">

### Expected Behavior

The following components also support Renderer supplier:

* Select
* ComboBox and inheritors
* RadioButtonGroup
* CheckboxGroup

---

**Solution:**

Add the following code to the components kit description:

```
supplyHandlers = {
                    @StudioSupplyHandler(
                            methodName = "setRenderer",
                            parameterType = "com.vaadin.flow.data.renderer.Renderer"
                    )
            }
```

**Comment by MaxKatyshev** [comment]
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5881-233
IntelliJ version: IntelliJ IDEA 2023.3 (Ultimate Edition)
_verified_
