### ISSUE TITLE
LockManager requests locks cache even for entities not configured for pessimistic locking

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2514]
### Environment

Jmix version: 2.1.1

### Bug Description

LockManager requests the locks cache even for entities not configured for pessimistic locking. In an environment with standalone Hazelcast it leads to long delays on opening each entity detail view.

### Expected Behavior

LockManager should first check if the entity is configured for pessimistic locking. If not, it should not access the cache at all. See `io.jmix.core.pessimisticlocking.impl.LockManagerImpl#lock(java.lang.String, java.lang.String)`

**Comment by gorbunkov** [comment]
Needs to be ported in 1.5
