### ISSUE TITLE
JpqlFilter generation strategy ignores the entity-field-type application property

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2516]
### Feature Description

See: https://forum.jmix.io/t/custom-filter-field/3884/11

It looks like there is no reason to hardcode the `entityPicker` creation here: `io.jmix.ui.component.factory.JpqlFilterComponentGenerationStrategy#createEntityField`.
 
Perhaps we should use:
```java
    protected Component createEntityField(ComponentGenerationContext context) {
        JpqlFilterComponentGenerationContext cfContext = (JpqlFilterComponentGenerationContext) context;
        MetaClass metaClass = metadata.getClass(cfContext.getParameterClass());
        return (EntityPicker<?>) entityFieldCreationSupport.createEntityField(metaClass, context.getOptions());
    }
```

Probably related to: https://github.com/jmix-framework/jmix/issues/746

**Comment by wwnjj13** [comment]
Using the above code in my own jmix fork worked without a hitch. Just wanted to share that.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6237-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Entity-field-type application property are available in the next condition creation steps

![image](https://github.com/jmix-framework/jmix/assets/158277660/1e6592e2-16cb-438a-9526-a47cfaeae473)
