### ISSUE TITLE
Components related to main view have no css attribute

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2517]
### Environment

Jmix version: 2.1x

### Bug Description

The following components have no `css` attribute:
* drawerLayout
* appLayout
* navigationBar

**Comment by MaxKatyshev** [comment]
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5881-233
IntelliJ version: IntelliJ IDEA 2023.3 (Ultimate Edition)
_verified_
