### ISSUE TITLE
Incorrect display of Tabs

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#2518]
### Environment

Jmix version: 2.1.1

### Bug Description

Incorrect display of Tabs when using the <tabs/> tag

### Steps To Reproduce

Create a screen with the following layout:
```xml
        <tabs id="tabs">
            <tab id="tab1" label="Tab 1">
                <span text="Tab 1"/>
            </tab>
            <tab id="tab2" label="Tab 2">
                <span text="Tab 2"/>
            </tab>
        </tabs>
```

### Current Behavior

Result:
![image](https://github.com/jmix-framework/jmix/assets/47520144/83964260-b8f1-475d-b135-b066fa2388cf)

### Expected Behavior

Result:
![image](https://github.com/jmix-framework/jmix/assets/47520144/5aabb6bc-140c-4ed1-9307-5ca3688443f9)

### Sample Project

Demo project: [jmix-tabs-demo.zip](https://github.com/jmix-framework/jmix/files/13456171/jmix-tabs-demo.zip)

**Comment by KremnevDmitry** [comment]
Seems like duplicate: https://github.com/jmix-framework/jmix/issues/2218

**Comment by glebfox** [comment]
Tabs component doesn't display content. Component nested in a tab is used as a `label` replacement.
