### ISSUE TITLE
Polish layout of security system views

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2519]
### Feature Description

Security system views have ugly layout, e.g. 

#### ResourceRoleModelDetailView and RowLevelRoleModelDetailView

Action buttons are go beyond view boundaries if not enough space
<img width="843" alt="Screenshot 2023-11-24 at 11 56 28" src="https://github.com/jmix-framework/jmix/assets/6077149/cd8b89bc-6b58-4c45-9854-ee092e38a739">

This can be fixed by making actions box fixed position, e.g.:

<img width="596" alt="Screenshot 2023-11-24 at 11 58 27" src="https://github.com/jmix-framework/jmix/assets/6077149/98109903-a3e1-4faa-b08e-a00126f693cb">

#### RoleAssignmentView

Tables don't occupy the full height

<img width="1331" alt="Screenshot 2024-01-22 at 00 35 29" src="https://github.com/jmix-framework/jmix/assets/6077149/9d7ceea4-4411-452b-bed1-63190fa718f1">

and can be collapsed for no reason

<img width="1446" alt="Screenshot 2024-01-22 at 00 34 23" src="https://github.com/jmix-framework/jmix/assets/6077149/99fe1451-53e0-4709-be9d-2031e53e04ea">

**Comment by glebfox** [comment]
Layouts of security system views have been changed, so may lead to problems if someone extended them.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3
