### ISSUE TITLE
Implement additional way of showing notification

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2526]
### Description
See support forum [topic](https://forum.jmix.io/t/notification-addon-cannot-open-on-iphone/4023/4)

Since Vaadin Grid has bug with double click in IOS Safari we should add additional way of showing notification:
- an icon in DataGrid
- a context action
- a button above DataGrid

**Comment by syncro** [comment]
merged in
https://github.com/jmix-framework/jmix-premium/commit/b6a905bc8932ed186e5b0afe3a695ff91148aa95

**Comment by SergeiAksenov2** [comment]
Tested on Mac OS:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6375-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)

There is button "Open" on the In-app notifications pop-up - Ok:

![image](https://github.com/jmix-framework/jmix/assets/158277660/b1201b4c-8c3e-4114-9588-072f4154b9d7)

Can open body text of a notification - Ok:

![image](https://github.com/jmix-framework/jmix/assets/158277660/61868cc5-2237-4920-8dc3-e07254164d1c)
