### ISSUE TITLE
Unwanted frame around the block

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2532]
Jmix version: 1.5.999-SNAPSHOT

TC
Create BPM process with Entity Data task

Look settings 

AR
![image](https://github.com/jmix-framework/jmix/assets/114649487/a7ec7e78-741c-4891-afb7-5186aa69f457)

**Comment by rusiaikinat** [comment]
Reopened
The changes have not been applied

_Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5851-233
IntelliJ version: IntelliJ IDEA 2023.3.1 (Ultimate Edition)_

**Comment by KartnDev** [comment]
Fixed also for  entity attributes box
![image](https://github.com/jmix-framework/jmix/assets/43281522/2e38e6fb-86a2-4e00-977d-5a5653d50918)

**Comment by KartnDev** [comment]
## 1. We will fix only boxes by following rules:
- Box contains datagrid and buttons
- Box looks wierd

### Other places:
1. Entity data task / modify entity task / create entity task
![image](https://github.com/jmix-framework/jmix/assets/43281522/013ec5e8-d720-4812-b508-63ca5f4567a5)
![image](https://github.com/jmix-framework/jmix/assets/43281522/d9c79873-bb9f-414d-aa7b-5f5fbe244f11)

2. Send email task/ attachments box
![image](https://github.com/jmix-framework/jmix/assets/43281522/60823dab-82fc-40f9-8f41-05bbc5d1cfc7)


We want fix methods list box
![image](https://github.com/jmix-framework/jmix/assets/43281522/e45ca44e-7a47-4378-af90-e85fff2be663)

**Comment by KartnDev** [comment]
# Fixed: SendEmailTask/Attachments
![image](https://github.com/jmix-framework/jmix/assets/43281522/08facf42-b9d7-4df3-820a-1dbbe595fd1f)
