### ISSUE TITLE
The component class io.jmix.flowui.component.loginform.JmixLoginForm includes  './src/login-form/jmix-login-form.js' but this file was not included when creating the production bundle

### ISSUE THREAD

**Issue by ig0rix** [jmix-framework/jmix#2537]
### Environment

Jmix version: <2.1.1>

### Bug Description

Error message in logs: 
ERROR 20516 --- [nio-8080-exec-9] c.v.flow.component.internal.UIInternals  : The component class io.jmix.flowui.component.loginform.JmixLoginForm includes
 './src/login-form/jmix-login-form.js' but this file was not included when creating the production bundle. The component will not work properly. Check that you have a reference to the 
component and that you are not using it only through reflection. If needed add a @Uses(JmixLoginForm.class) where it is used.

### Steps To Reproduce

1. Create new project from template Java Full Stack (version 2.1.1)
2. Build project ./gradlew -P"vaadin.productionMode=true" bootJar
3. Run project  java -jar <jar path>
4. Open login page

### Current Behavior

Application log contains message with ERROR level with text described above

### Expected Behavior

The application log does not contain errors

**Comment by glebfox** [comment]
Fixed by Vaadin in 24.1.16
