### ISSUE TITLE
Wrong behavior during locking WebDAV documents

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#2542]
### Environment

Jmix version: 2.1+, possible 1.5

### Bug Description

Wrong behavior during locking WebDAV documents

### Steps To Reproduce

Install WebDAV add-on.
Open WebDAV documents screen
Add some document
Lock this document
Wait more than 10 minutes
Unlock this document

### Current Behavior

Message "The document is not locked" is appeared

### Expected Behavior

document is unlocked

Possible right behavior is to display that document is not locked
"Unlock", "Show versions" and "Delete" button should work correctly
Cases with multiple selection and with multiple clicking lock and unlock buttons should work correctly.

Note. Discover using method that has incorrect implementation and its possible consequent problems. 

```
WebdavDocumentsManagementServiceImpl
public WebdavDocument retrieveDocumentByWebdavDocumentId(UUID documentId, String fetchPlanName) {
    return retrieveDocumentByWebdavDocumentId(documentId,
            fetchPlanRepository.getFetchPlan(WebdavDocument.class, FetchPlan.LOCAL));
}
```

**Comment by rusiaikinat** [comment]
**Reopened**
The REMOVE button is not working properly

**Bug Description**
now possible to delete an unblocked object

**Expected Behavior**
The object must be locked before being deleted

**Comment by rusiaikinat** [comment]
changing the visual version of an object via the object's context menu
![image](https://github.com/jmix-framework/jmix/assets/114649487/97ee33ec-d94d-422d-ab14-bbcea96a7139)

**Comment by Gavrilov-Ivan** [comment]
Previous behavior with explicit lock required before delete was based on issue in 'unlock' logic: 'unlock' operation failed if document is not locked or lock is expired. But the delete operation in fact doesn't check lock.
Now this behavior is changed - unlocking of unlocked document does nothing.
And it affects behavior of delete operation - there is no more failure if document is not explicitly locked.

So delete operation was modified - system itself locks unlocked document during delete operation.

Delete:

1. If document is not locked - system locks it and proceed
2. If document is locked by you - proceed
3. If document is locked by someone else - fail
