### ISSUE TITLE
Grouping buttons in WebDAV document list screen

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#2562]
Buttons in WebDAV document list screen should be grouped with drop-down lists.

Think about adding button for navigating to upper level of collections hierarchy.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6826-242
IntelliJ version: IntelliJ IDEA 2024.2.1
