### ISSUE TITLE
Add support "retry cycle" property on service task and other elements that supports retrying mecanism

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2563]
### Feature Description

For details check flowable documentation:
https://www.flowable.com/open-source/docs/bpmn/ch07b-BPMN-Constructs#fail-retry

**Comment by gorbunkov** [comment]
The issue must be ported to 1.6

**Comment by konyashkina** [comment]
After clearing the field, the tag remains
`<extensionElements/>`

Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6050-233

**Comment by KartnDev** [comment]
> After clearing the field, the tag remains `<extensionElements/>`
> 
> Tested on Jmix version: 2.2.999-SNAPSHOT Jmix Studio plugin version: 2.2.SNAPSHOT6050-233
## My thinks:
Seems like <extensionElements/> is part of internal "features" inside flowable that doesnt break process and its ok for BPMN 

## I did check:
1. create  schema and add service task with any of implementation (spring bean or expression, etc) => deployable
2. add retry cycle and then remove it
3. got the schema, where `<extensionElements/>` is present: 
```xml
<process id="process" name="Process" isExecutable="true">
    <startEvent id="startEvent1" />
    <serviceTask id="Activity_11htt4l">
      <extensionElements />
    </serviceTask>
  </process>
```
4. deploy it => still deployable
5. close modeler
6. open again and import  my new schema
7. deploy it => still deployable
8. conclusion that this `<extensionElements/>` is normal behavior for bpmn.io "remove" command inside modeler

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6060-233
IntelliJ version: IntelliJ IDEA 2023.3.4 RC

**Comment by knstvk** [comment]
Studio issue: https://youtrack.jmix.io/issue/JST-4663/Support-FailedJobRetryCycle-on-service-task-properties
