### ISSUE TITLE
IllegalArgumentException: MetaClass not found for null: Case with changing "Modify entity" type to "Create entity"

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2564]
### Environment
Jmix version: 1.5.999-SNAPSHOT

TC
https://github.com/jmix-framework/jmix/issues/2454#issuecomment-1831697255

**Comment by gorbunkov** [comment]
The issue should also be checked in Jmix 2 and fixed there if needed

**Comment by KartnDev** [comment]
> The issue should also be checked in Jmix 2 and fixed there if needed
Is not actual for Jmix 2.x

**Comment by KartnDev** [comment]
Also fixed for Jmix 1.6
