### ISSUE TITLE
Support search for users by different properties

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#257]
Currently UserRepository allows to get list of users by substring of username only (`UserRepository#getByUsernameLike`).
In most cases of substring-search users need to be found by human-readable properties (such as 'First name', 'Last name').

Suggested solution: introduce new method for substring-search accepted collection of properties to search within.

Additional: make configurable the way of wildcard placement. 'Starts with' is the most common way of such kind of search but currently it's always 'Contains'.

**Comment by gorbunkov** [comment]
We can override the `UserRepository#getByUsernameLike` at project level and implement any behavior there.
