### ISSUE TITLE
The name in the generated Code field does not start with a capital letter

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2570]
Jmix version: 2.1.999-SNAPSHOT

TC
add add-on Dynamic Attributes
Create attribute in Category
Look Code field 

![image](https://github.com/jmix-framework/jmix/assets/114649487/d4f9de7a-23b0-4af5-ad7d-21ec22994e60)

ER
CategoryAttributeName

**Comment by KartnDev** [comment]
first letter of code must be in lower case even if category name starts with capital

**Comment by rusiaikinat** [comment]
_1. The name of the category is missing_
**Category name** = categoryName; **Attribute name** = attribute / Attribute -> **Code** = attribute - FAIL
Category name = categoryName; Attribute name = attribute_one / attribute-one / attribute.one / "attribute one" -> **Code** = attributeOne - FAIL
 
===
_2. The formatting differs from the previous case. Code with a capital letter_
**Category name** = null; **Attribute name** = attribute / Attribute  -> **Code** = Attribute - FAIL 
Category name = null; Attribute name = attribute_one / attribute-one / attribute.one / "attribute one" -> AttributeOne - FAIL

===
_3. Repeats the behavior of the first case_
**Category name** = Some car-category 

ER
Take into account the name of the category where it is present
