### ISSUE TITLE
TypedDatePicker does not apply default date format

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2571]
### Environment

Jmix version: 2.1.0

### Bug Description

TypedDatePicker does not apply default date format and shows date as "MM/dd/yyyy".

### Steps To Reproduce

Add to XML:
```
<datePicker id="datePicker"/>
```
In the controller:
```
@ViewComponent
private TypedDatePicker<LocalDate> datePicker;

@Subscribe
public void onInit(final InitEvent event) {
    datePicker.setTypedValue(LocalDate.now());
}
```

### Current Behavior
Date is shown as: "MM/dd/yyyy"

### Expected Behavior
Should be "dd/MM/yyyy" as default date format is taken from `dateFormat`.

**Comment by inteacc** [comment]
Thanks for logging this issue. The default date format should be according to the Locale used by the user e.g. Canada dd/MM/yyyy, USA MM/dd/yyyy

**Comment by Flaurite** [comment]
@inteacc yes, the `dateFormat` is taken from messages_**.properties which is used by user's locale.

**Comment by KremnevDmitry** [comment]
## Duplicate

Issue: https://github.com/jmix-framework/jmix/issues/2444
Will be fixed with: https://github.com/jmix-framework/jmix/pull/2549

Closed.
