### ISSUE TITLE
After creating the category, the IS DEFAULT field is empty

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2578]
Jmix version: 2.1.999-SNAPSHOT

**TC** 
Dynamic attributes -> Create category  -> OK
![image](https://github.com/jmix-framework/jmix/assets/114649487/0dd1e91f-5f77-4912-b64d-f2b0585c3ba8)

Edit category -> is default = true -> OK
![image](https://github.com/jmix-framework/jmix/assets/114649487/a03f762b-673f-4c75-aaa1-6c98f2b9e9c1)

Edit category -> is default = false -> OK
![image](https://github.com/jmix-framework/jmix/assets/114649487/dc1ef0c8-ff57-4809-9588-bc29ec26f1cd)

**ER**
If the value is FALSE, the field must always be empty or always non - empty

**Comment by gorbunkov** [comment]
It seems that we may assign a default "false" value to the entity class field.
