### ISSUE TITLE
Wrong behavior on click "Pause" button in Quartz

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#2594]
### Environment

Jmix version: 2.1+

### Bug Description

1. Install Quartz add-on
2. Create project
3. Go to menu item Quartz->Quartz jobs
4. Select any job
5. Click "Pause" button

ER. Selected job should be still selected and actions buttons state should be changed(for example "Pause" button should be disabled, but "Remove" button should be enabled
AR: Selection is cleared(there are no selected lines) and buttons states are not modified

Note: strange line moving when button "Pause" is pressed. Possible some default sorting by "Job state" column is enabled.

**Comment by Gavrilov-Ivan** [comment]
About "moving line" - there is a forced sorting by 'Job state' (normal first) and 'Job name'.
And it ignores user sorting. We should keep it if exists - https://github.com/jmix-framework/jmix/issues/2755
