### ISSUE TITLE
Error running report via Rest API

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#2603]
### Environment

Jmix version: 2.1.1

### Bug Description

Add access to the `report_ReportExecution` entity for the `report-run-api` role.

Forum - https://forum.jmix.ru/t/accessdeniedexception-resource-report-reportexecution-type-entity-action-create/1486

### Steps To Reproduce

1 - Create a Jmix project with Reports add-on
2 - Create a simple report  
3 - Create an user with the `report-run-api` role
4 - Run a report

### Current Behavior

Exception: 
```java
io.jmix.core.security.AccessDeniedException: resource: report_ReportExecution, type: entity, action: create
```

### Expected Behavior

The report created successfully

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3
