### ISSUE TITLE
Add an understandable description of errors in the Rest API

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#2605]
### Environment

Jmix version: 2.1.1

### Bug Description

Make an understandable error message and correct the status

### Steps To Reproduce

1 - Create a Jmix project with a Reports add-on
2 - Create a report with required parameters
3 - Run the report by Rest API

### Current Behavior

Response: Status - 500
```
{
    "timestamp": "2023-12-12T16:03:08.369+00:00",
    "status": 500,
    "error": "Internal Server Error",
    "path": "/rest/reports/run/a2f873d6-45f0-1c09-73c1-0696c535cc63"
}
```

Exception:
```
Request processing failed: java.lang.IllegalArgumentException: Required report parameter "entity" not found
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1019) ~[spring-webmvc-6.0.12.jar:6.0.12]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.0.12.jar:6.0.12]
```

### Expected Behavior

Response: Status - 400
```
{
    "error": "Run report error",
    "details": "Required 'entity' param is missing"
}
```

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3
