### ISSUE TITLE
Root view element missing Studio metadata

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2608]
### Environment

Jmix version: 2.0+

### Bug Description

<img width="400" alt="Screenshot 2023-12-13 at 14 11 54" src="https://github.com/jmix-framework/jmix/assets/6077149/c7a53cc8-fd4c-4a76-bb76-5260352221de">

**Comment by KremnevDmitry** [comment]
Blocked by studio: https://youtrack.jmix.io/issue/JST-4535/Remove-hardcoded-view-and-mainView-support

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.SNAPSHOT5863-233
IntelliJ version: IntelliJ IDEA 2023.3 (Ultimate Edition)
