### ISSUE TITLE
[groupTable] The settings icon overlaps the sorting icon

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2633]
Jmix version: 1.5.999-SNAPSHOT (last version: 1.5.4)

**TC**
![image](https://github.com/jmix-framework/jmix/assets/114649487/cfaca596-830b-447e-849d-5f56eddfeb51)
move the cursor over the column

**AR**
the sort icon is hidden by another icon
![image](https://github.com/jmix-framework/jmix/assets/114649487/d9eab2bd-9ede-4125-a381-ceb40e3f2a96)

**Comment by glebfox** [comment]
Minor inconvenience. Icons overlapping doesn't prevent using both settings and sorting, because sorting works on whole header cell.
