### ISSUE TITLE
Synchronize the Vaadin's DataGrid selection model and visual representation of data

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2642]
See forum topic: https://forum.jmix.io/t/v2-1-datagrid-multiselect-issue/4144

Changing the visibility of table elements doesn't affect the selection model. This behaviour is misleading.

**Comment by yuriy-khrebtov** [comment]
Fixed in https://github.com/jmix-framework/jmix/issues/2221
