### ISSUE TITLE
Remove Label component from Studio Component Palette

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2655]
### Feature Description

`Label` is deprecated and marked for removal, so it's better to hide it from users. XSD support must be kept as is, until Vaadin removes component.

Check that NativeLabel component is present in Studio and XSD

**Comment by KremnevDmitry** [comment]
- the `label` has been removed from the Components palette
- made sure the `nativeLabel` component was present in Studio and XSD
