### ISSUE TITLE
Localization of dynamic attribute doesn't work for complex locales

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2659]
### Environment

Jmix version: 2.1.1

### Bug Description

Localized values of dynamic attribute category name and dynamic attribute category value doesn't work.

### Steps To Reproduce

1. Create Jmix project.
1. Add additional locale.
1. Create a dynamic attribute category.
1. Add dynamic attribute with enum type.
1. Provide localization for category name and for enum values.
1. Add dynamic attributes panel to the entity detail view.
1. Login to the application with additional language.

### Current Behavior

A list of categories on the dynamic attributes panel contains not localized value.
A list of enum values contains not localized captions.

### Expected Behavior

Localized captions should be displayed.

### Sample Project

See [forum topic](https://forum.cuba-platform.com/t/jmix-2-1-1-dynamic-attributes-issues/17195).

A sample project is attached there.

**Comment by KartnDev** [comment]
Jmix 3.0

![image](https://github.com/jmix-framework/jmix/assets/43281522/45eb394f-f46b-48a3-b53f-1e47ca014409)
![image](https://github.com/jmix-framework/jmix/assets/43281522/878102cb-e997-4e5f-89d2-1a6e47d47adc)
![image](https://github.com/jmix-framework/jmix/assets/43281522/43e7121e-c395-4b9e-9b93-6ffc83f51ce5)
![image](https://github.com/jmix-framework/jmix/assets/43281522/6e468899-f106-4c5f-8a4f-2e79e9b78c05)

**Comment by KartnDev** [comment]
UPD: 
If location contains complex tag like `da_DK`, `cz_CA`, `ru_RU` and etc, code will saved incorrectly:
like `da_DK` -> `da-DK`
And this reproduces key mismatching inside messages bundle
