### ISSUE TITLE
Improve ListMenu

### ISSUE THREAD

**Issue by yuriy-khrebtov** [jmix-framework/jmix#2667]
Improve ListMenu:
- move expand button to the end of menu item
- support badges (suffix components)
- support setting `Component` as icon for menu items

**Comment by glebfox** [comment]
> support setting Component as icon for menu items

Let's make it more generic, instead of setting icon, we will set prefix component. Same as in Vaadin SideNav

**Comment by MaxKatyshev** [comment]
_Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT5973-233
IntelliJ version: IntelliJ IDEA 2023.3.2 (Community Edition)_
verified
