### ISSUE TITLE
It is not obvious that keyword "join", "left join" or "," required in join clauses

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2674]
### Problem:
Despite it is mentioned in the documentation and in help, it is not obvious that "join" clause has to be started with keyword or "," because in "where" clause fields keyword `where` is not used.
Moreover join field value without starting keyword will be processed correctly in many cases, but sometimes such inaccurate usage leads to problems.

<img src=https://github.com/jmix-framework/jmix/assets/38808384/05476a66-ea59-4c42-86f4-e9e8c2ea4a42 width="75%">

### Proposed solutions:
This situation may be improved using different approaches:
**Option 1**. Use placeholder to give a hint. E.g. like that:

<img width="671" alt="изображение" src="https://github.com/jmix-framework/jmix/assets/38808384/8f2e893c-2b6d-4595-93b9-773f133b5819">

  - **[+]** Clearly
   - **[-]** Disappears when field value added
   - **[-]** May not be noticed

Or, maybe the best solution: https://github.com/jmix-framework/jmix/issues/2674#issuecomment-1867298197

**Option 2**. Add validation button or logic before view closing and show confirmation message if join clause lacks keyword or comma.
  - **[+]** Will be noticed
  - **[-]** Additional logic to maintain
  - **[-]** On closing check: May be annoying in case of bug or keyword skipped somehow intentionally
  
### Affected views:
- Dynattr: Category Attribute Details
- JPQL Filter Condition
- Report Parameter Detail
- Row-level policy

**Comment by gorbunkov** [comment]
Another solution for option 1 will be to use **helper text** for the field instead of input prompt
