### ISSUE TITLE
Unexpected order in locale selection on login screen

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2695]
### Environment

Jmix version: 2.1.999-SNAPSHOT (last version 2.1.1)
Kotlin
Note: can't reproduce in java

### Bug Description

After the Jmix studio update, sorting stopped working [JST-4432](https://youtrack.jmix.io/issue/JST-4432/Unnecessary-localeDisplayNameenEnglish-property-added-to-messageproperties-after-saving-Project-Properties-dialog)

![Сортировка языков](https://github.com/jmix-framework/jmix/assets/114649487/fa181d44-2194-44bd-a7a3-3a9f8a968170)

### Expected Behavior

#1656

**Comment by glebfox** [comment]
It's not a regression, I see no commit in Kotlin template in the linked issue.
