### ISSUE TITLE
Wrong context help in DMN Table Input definition dialog

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2698]
### Environment

Jmix version: 2.1.1

### Bug Description

Context help text for the **Process variable** text field of the **Input definition** dialog in the DMN modeler is wrong:

<img width="845" alt="image" src="https://github.com/jmix-framework/jmix/assets/7888486/36c693f3-6374-4157-bda0-07550d00ab34">

The current value is `Expression like ${EXPRESSION}`, but in ClassicUI (Jmix 1.5) it was 

```
Type process variable name, e.g. <b>clientStatus</b>. \
  If the variable is an entity, you may type its local field name: <b>order.amount</b>
```

The main problem that the value in this text field must not be wrapped in `${}` as the hint suggests - it leads to runtime errors.

**Comment by KartnDev** [comment]
Translations for this issue also added

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
