### ISSUE TITLE
DataGrid height should be corrected

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2699]
### Environment

Jmix version: 2.1.999-SNAPSHOT (last version 2.1.1)

### Bug Description

https://github.com/jmix-framework/jmix/issues/2396#issuecomment-1870307452

**Comment by Gavrilov-Ivan** [comment]
Moved to release Feb2024 due to rolling back of root cause (https://github.com/jmix-framework/jmix/issues/2396) from release 2.1
