### ISSUE TITLE
Add cause exception if screen controller cannot be created 

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2700]
### Feature Description

In the `io.jmix.ui.sys.ScreensImpl#createController` method if any problem occurs, an exception is thrown with a fixed message, making it difficult to identify the problem without debugging.

**Comment by SergeiAksenov2** [comment]
Tested, but 1.5.999 and 1.6.999 snapshots were not compiled.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
