### ISSUE TITLE
XML descriptor for composite component

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2707]
### Feature Description

Composite components are important building blocks in large applications. We should provide a way to describe their layout in XML descriptors similar to views.

As an additional benefit, a composite component with a XML descriptor will simplify creating internal layout of [virtualList](https://demo.jmix.io/ui-samples/sample/virtual-list-simple) component.

See also [forum discussion](https://forum.jmix.io/t/does-flow-ui-support-fragments/2607).

**Comment by glebfox** [comment]
Implemented in #841
