### ISSUE TITLE
Do not display byte array entity attributes in the entity inspector list view

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2712]
Jmix version: 2.1.1

Entity inspector displays byte[] attributes in the list view:

<img width="1448" alt="image" src="https://github.com/jmix-framework/jmix/assets/7888486/e9b3f0f4-188a-45de-a3f9-5d8757a5045f">

This doesn't make sense. byte[] attributes should not be displayed on the screen and should be excluded from a fetch plan.

See [forum topic](https://forum.jmix.io/t/customize-entity-inspector-table/4209).

**Comment by gorbunkov** [comment]
Maybe we should still display the column on the screen, but do not display its full value (just indicate that the value is set or limit displayed text length)

**Comment by glebfox** [comment]
Let's do same as FileUpload does, just display Attachment (XXX bytes)
