### ISSUE TITLE
Scrolling has appeared in the report creation window

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2717]
### Environment

Jmix version: 2.1.2
Kotlin project

### Bug Description

A description of what the bug is.

### Steps To Reproduce

Reports > Create > Using wizard
Entity: User
Report type: Report for list of entities, select by query
Next -> OK

### Current Behavior

![image](https://github.com/jmix-framework/jmix/assets/114649487/3a0c5fe9-47d7-4011-ac3f-0d6ef8072d60)
![image](https://github.com/jmix-framework/jmix/assets/114649487/77020892-a778-4351-a3dc-ac51c0a7d3df)

**Comment by NikitaShchienko** [comment]
The problem is reproduced when moving the dialog. To solve the problem, draggable mode was disabled in the wizard.
