### ISSUE TITLE
The saved report in xlsx does not have a header

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2718]
### Environment

Jmix version: 2.1.2
Kotlin project

### Bug Description

![image](https://github.com/jmix-framework/jmix/assets/114649487/2c994566-37dc-4887-a814-dd82f355ee8d)

### Steps To Reproduce

Create an entity with an association to the User entity
Reports > Create > Using wizard
_Entity: YourCreatedEntity
Template type: XLSX
Report type: Report for list entities_

Next
Region report : select attribute your entity and User entity
OK

### Current Behavior
The column names are at the bottom

**Comment by gorbunkov** [comment]
Duplicates https://github.com/jmix-framework/jmix/issues/1761
