### ISSUE TITLE
BPM process forms initialization using URL query parameters

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2721]
Jmix: 2.1.2

We may consider implementing BPM process form initialization (Jmix views) using the URL query parameter:

1. URL must have either the "taskId" or "processDefinitionId" query parameter
2. Each process form controller will have a code like this:

```java
@Subscribe
public void onQueryParametersChange(final QueryParametersChangeEvent event) {
	processFormViewInitializer.autowireTaskFormFields(event.getQueryParameters());
}
```

The purpose of the `ProcessFormViewInitializer` is to find the Task or ProcessDefinition using the corresponding URL parameters and autowire necessary controller class fields (`ProcessFormContext`, `@ProcessVaraibe`, `@ProcessFormParam`, etc.).

```java
public interface ProcessFormViewInitializer {
	//todo rename autowireTaskFormFields -> initTaskForm(...) ?
	public void autowireTaskFormFields(String taskId, View<?> view);
	public void autowireTaskFormFields(QueryParameters queryParameters, View<?> view);
	public void autowireStartFormFields(String processDefinitionId, View<?> view);
	public void autowireStartFormFields(QueryParameters queryParameters, View<?> view);

	public void autowireTaskFormFields(Task task, View<?> view);
}
```

This approach will allow us to get rid of storing process form context in a session and passing this temporary session identifies to process forms when they are opened using the navigation. 

See [forum topic](https://forum.cuba-platform.com/t/bpm-improvements/17246/3)

**Comment by gorbunkov** [comment]
See implementation details in the [PR](https://github.com/jmix-framework/jmix-premium/pull/255)

Now, Jmix View process forms are being opened with URL query parameters:
* `processDefinitionId` for start process forms
* `taskId` for task process forms

For QA: check that 
* start process forms and task process forms are opened with these parameters.
* process variables injection work fine
* the process form can be successfully refreshed or opened using this URL again

**Comment by SergeiAksenov2** [comment]
Tested on Java:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6389-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6385-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

There are ?taskId and ?processDefinitionId query parameters in URL - Ok.
