### ISSUE TITLE
DataGrid.SelectionEvent is published many times for single selection with multiple rows

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#2722]
### Environment

Jmix version: 1.4.1

### Bug Description

DataGrid.SelectionEvent is publised many times for single selection with multiple rows

### Steps To Reproduce

Create DataGrid with necessary data components.
Set DataGrid property "selectionMode" to "MULTI".
Add some data to grid.
Create listener for DataGrid.SelectionEvent and put breakpoint
Select one row, press "Shift" and select another row(in order to select for example 5 rows).

### Current Behavior

6 events are fired

### Expected Behavior

1 or 2 events (one "deselct" event) are fired

Also there is a problem with firing additional event with empty selection("deselect" before applying new selection).

**Comment by glebfox** [comment]
Not a bug. This is due to Vaadin API which assumes that we select rows one by one even for Multi mode.

As an option, you can reload entities by timeout since last selection event, e.g. by combining Timer facet and a flag.
