### ISSUE TITLE
Exception in Entity Inspector Selection because of DummyAppSettingsEntity

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2734]
### Environment

Jmix version: 2.1.2

### Bug Description
see [forum topic](https://forum.jmix.ru/t/hsqlexception-v-inspektore-sushhnostej/1553)

Entity Inspector throws an exception when `DummyAppSettingsEntity` selected

### Steps To Reproduce
1. Create a project with Application Settings and Data Tools addons.
2. Select `DummyAppSettingsEntity` in Entity inspector
**AR:** exception

### Proposed solution
1. Do not show `DummyAppSettingsEntity` in Entity inspector.
2. Look for another entities that require to be hidden from Entity inspector

**Comment by rusiaikinat** [comment]
Tested on:
Other available addons for 2.1
