### ISSUE TITLE
DataGrid column renderer is generated by Studio without generic type

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2739]
### Environment

Jmix version: 2.1.2

### Steps To Reproduce

Generate a DataGrid column renderer using Studio

### Current Behavior

No generic type for Renderer:

```java
@Supply(to = “salaryReviewsTable.promoteOpm”, subject = “renderer”)
private Renderer salaryReviewsTablePromoteOpmRenderer() {
   return null;
}
```

### Expected Behavior

There is a generic type for Renderer:

```java
@Supply(to = “salaryReviewsTable.promoteOpm”, subject = “renderer”)
private Renderer<SalaryReview> salaryReviewsTablePromoteOpmRenderer() {
   return null;
}
```

A description of what you expected to happen.

See [forum topic](https://forum.jmix.io/t/datagrid-column-renderer/4263)

**Comment by KremnevDmitry** [comment]
After investigation, it turned out that this is not a framework issue. 
Studio issue link: https://youtrack.jmix.io/issue/JST-4614/DataGrid-column-renderer-is-generated-without-generic-type
