### ISSUE TITLE
Unnecessary captions appear for buttons in BPMN modeler properties panel

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2740]
### Environment

Jmix version: 2.1.2

### Bug Description

Unnecessary captions appear for buttons in BPMN modeler properties panel.

### Steps To Reproduce

1. Open the BPMN modeler
2. Add the UserTask element
3. Select the InputDialog process form type - icons won't have captions

![a7d10d30d7befc04838f48923ba7f39f46b92e43](https://github.com/jmix-framework/jmix/assets/7888486/ea364e85-533d-472a-b4f7-5b15588f780f)

4. Switch to another element (e.g. Start Event)
5. Select the User Task again

### Current Behavior

Captions appear for buttons:

![57084fe457ce8df0e0242029bea8e6660e8cb9ab](https://github.com/jmix-framework/jmix/assets/7888486/ea95fba4-cc42-4c46-902c-d49112933be8)

### Expected Behavior

Buttons without captions should be displayed:

See [forum topic](https://forum.jmix.ru/t/podpisi-knopok-dejstvij-v-bpmmodeler/1561)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.1.999-SNAPSHOT
Jmix Studio plugin version: 2.1.3-233
IntelliJ version: IntelliJ IDEA 2023.3.3
