### ISSUE TITLE
"Could not resolve property path" for enum in DTO

### ISSUE THREAD

**Issue by artemy63** [jmix-framework/jmix#277]
Jmix 1.1.1
IntelliJ IDEA 2021.3 (Ultimate Edition)

TC.
1. Create new enumeration in the project via Jmix menu (Gender)
2. Create new DTO via Jmix menu and add enum property with using previously created enumeration (PersonDto)
3. Create new browse and edit screeen for this DTO via Jmix menu
4. Launch the project and try to open edit screen for creating new DTO

AR. IllegalStateException: Could not resolve property path 'gender' in 'PersonDto'

Simple test project attached
[problemWithEnum.zip](https://github.com/Haulmont/jmix-core/files/7745628/problemWithEnum.zip)

Maybe it is correlated with https://github.com/Haulmont/jmix-core/issues/150

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4305-213)
jmix versions (1.2.999-SNAPSHOT) (1.3.999-SNAPSHOT)
