### ISSUE TITLE
Incorrect assignment of action icon to JmixButton

### ISSUE THREAD

**Issue by yuriy-khrebtov** [jmix-framework/jmix#2779]
### Environment

Jmix version: 2.2

### Bug Description

When we assign an action to a button, button icon is updated by `JmixButtonActionSupport`:
```
    protected void updateIcon(boolean overrideComponentProperties) {
        if (button.getIcon() == null || overrideComponentProperties) {
            button.setIcon(action.getIcon());
        }
    }
```
Action icon is a component so it can be attached only to one parent component (button in that case). 
So if we have multiple buttons with same action assigned, the icon will be assigned to all of them but will actually be displayed for only one.
### Steps To Reproduce

1. Create multiple buttons for one action, for example in user-list-view.xml:
```
<hbox id="buttonsPanel" classNames="buttons-panel">
            <button id="createBtn" action="usersDataGrid.create"/>
            <button id="createBtn2" action="usersDataGrid.create"/>
            <button id="createBtn3" action="usersDataGrid.create"/>
...
</hbox>
```

### Current Behavior

Icon is displayed for last button only.

![image](https://github.com/jmix-framework/jmix/assets/142792860/b4f215c3-01d9-46b6-9a63-781719de551f)

### Expected Behavior

Icons are displayed for every button.

### Possible solution

Use `io.jmix.flowui.kit.component.ComponentUtils#copyIcon` to set icon copy instead of original icon.

**Comment by ilushaaa** [comment]
https://github.com/jmix-framework/jmix/commit/552ca5955499552d3c8b89722587cb5f1a9d5442

**Comment by KremnevDmitry** [comment]
`JmixButtonActionSupport` is not the only place where an icon instance copy can be used.
E.g.:`GridMenuItemActionSupport`

Suggested solution: provide a copy initially in the `io.jmix.flowui.kit.action.AbstractAction#getIcon` method.
