### ISSUE TITLE
Copy extended class instance to base class

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#278]
metadataTools.copy() checks if the field isn't exists in the target entity.
https://github.com/Haulmont/jmix-core/blob/d5f5b2d83613341eea68ddda88bc41884ed67b6b/core/src/main/java/io/jmix/core/MetadataTools.java#L975

metadataTools.deepCopy() doesn't

So it cannot copy extended class to base class instance.

**Comment by knstvk** [comment]
Decided to keep the method as is. You can easily replicate it with desired functionality in your project.
