### ISSUE TITLE
Development Bundle is running every startup

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2786]
### Environment

Jmix version: 2.1.2

### Bug Description

Because of Vaadin bug (see GitHub [issue 2](https://github.com/vaadin/flow/issues/17998)) which seems to affect only Windows machines.

It seems that bug has appeared between 24.1.10 and 24.1.16. We [updated](https://github.com/jmix-framework/jmix/issues/2601) Vaadin version to get fix for: https://github.com/jmix-framework/jmix/issues/2537

### Steps To Reproduce

Just restart app several times

### Current Behavior

Development Bundle is running every startup

### Expected Behavior

Development Bundle is created only for the first startup.

### Proposed solution

Roll back Vaadin version in platform.

**Comment by Flaurite** [comment]
Downgraded to Vaadin 24.1.12
