### ISSUE TITLE
Copy lazy fields

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#279]
metadataTools.copy() cannot copy lazy attributes
https://github.com/Haulmont/jmix-core/blob/d5f5b2d83613341eea68ddda88bc41884ed67b6b/core/src/main/java/io/jmix/core/MetadataTools.java#L975
persistentAttributesLoadChecker.isLoaded() returns false.

**Comment by knstvk** [comment]
Decided to keep the method as is. Improved Javadocs: https://github.com/jmix-framework/jmix/commit/06b89a6b9fdac1fb3a25c3f3c9aa04ca102c6ff2
