### ISSUE TITLE
Make editorActionsColumn automatically compatible with settings facet without explicit actions

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2793]
### The problem
If View contains DataGrid with `editColumnActions` and `settings` facet, we can face with a problem. If `editColumnActions` does not specify `key` attribute, the NPE will be thrown after reopening the View. See Russian support forum: [topic](https://forum.jmix.ru/t/nullpointerexception-v-settingsfacet/1587).

The reason is `settings` facet works only with columns that specify `key` attribute. Because it helps to save the right order of columns and its settings.

### Feature Description
There are some solutions we can implement:
1) Make `key` attribute required for `editColumnActions` element. However the migration will be need.
2) Generate `key` automatically like we do for the simple columns. However since `editColumnActions` can be defined more than one times, we need to generate stable id sequence in order to match with saved settings.
3) Add note to the documentation.

Also, add to the exception details.

**Comment by glebfox** [comment]
@ilushaaa seems like a duplicate

**Comment by ilushaaa** [comment]
Duplicate with https://github.com/jmix-framework/jmix/issues/3020
