### ISSUE TITLE
Dynamic attributes panel do not disallowing save entity with empty require attribute inside it

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2798]
### Environment

Jmix version: 2.1

### Bug Description
Dynamic attributes panel do not disallowing save entity with empty require attribute inside it
But message should notice that we cannot save enityt without required attribute

### Steps To Reproduce
1. Create dynamic attribute category
2. Create dynamic attribute inside category
3. Set type `"string"`
4. Add require option
5. Add visibility only for list view, or none views has visibility
6. Implement your entity **"Categorized"** interface
7. Add DynamicAttributePanel component onto you detail view
8. Go to the application
9. Choose current category inside `DynamicAttributePanel` 
10. Do not fill required attribute inside panel
11. Save

### Current Behavior

Save allowed if required attribute is only inside `dynAttr Panel`

### Expected Behavior

Save has to be banned. Also notificaton should notice that we cannot save entity without required attribute

**Comment by rusiaikinat** [comment]
Tested on:
Kotlin, Java
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6068-233
IntelliJ version: IntelliJ IDEA 2023.3.4 (Ultimate Edition)
