### ISSUE TITLE
Default Search jobs can't be disabled via app properties if they have been in use

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#2801]
### Environment

Jmix version: 2.1 (applies to any version)

### Bug Description

Application properties:
https://docs.jmix.io/jmix/search/search-properties.html#jmix.search.use-default-enqueueing-session-processing-quartz-configuration
https://docs.jmix.io/jmix/search/search-properties.html#jmix.search.use-default-indexing-queue-processing-quartz-configuration
can be used to disable default OOB configuration of jobs.

But if default configuration has been in use the further disable will just disable configuration itself but will not disable default job created via this configuration.
This job will have `User Defined` source instead of `Predefined` (because related JobDetails bean no longer exists), but it will keep working and will require manual disabling.

### Steps To Reproduce

- Add `Search` addon
- Run project with `true` value in properties mentioned above (they are `true` by default)
- Check there are active default jobs from Search addon: `IndexingQueueProcessing` and `EnqueueingSessionProcessing`
- Set `false` to properties mentioned above and restart project
- Check those jobs are still working

### Current Behavior

Properties disable prevent default jobs from the first creation, but not from execution if they already exist.

### Expected Behavior

There should be option to disable default jobs at any stage of the lifecycle.

**Comment by syncro** [comment]
1. There is theoretical possibility that user can create on job with the same tech name and group and then adds configuration property that disables system job and get his own job deleted 
2. Webdav job documentVersionsCleaning and documentVersionsCleaningCronTrigger clening was also implemented withing this  task

**Comment by SergeiAksenov2** [comment]
Tested on Java:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6350-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.2.1
Jmix Studio plugin version: 2.3.SNAPSHOT6351-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

There are no IndexingQueueProcessing and EnqueueingSessionProcessing jobs on Quartz job view.
