### ISSUE TITLE
The title for user task outcome column should be "Id" instead of "Business Id"

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2803]
### Environment

Jmix version: 2.1.2

### Bug Description

In a web modeler, the title for user task outcome column is "Business Id". In Jmix 1.5 it was just "Id". The same is relevant for user task outcome editor.

In Jmix 2:

<img width="338" alt="Screenshot 2024-01-30 at 13 16 05" src="https://github.com/jmix-framework/jmix/assets/7888486/80e373f9-cd70-41a8-a2c7-828d9069cb59">

Was in 1.5:

<img width="460" alt="Screenshot 2024-01-30 at 13 15 27" src="https://github.com/jmix-framework/jmix/assets/7888486/4b326c13-86e7-4de5-8b94-d74209c4b9a7">

**Comment by konyashkina** [comment]
Failed 

_Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6073-233
IntelliJ version: IntelliJ IDEA 2023.3.4 RC_

There is still the "Business Id" title. 

![2803-title](https://github.com/jmix-framework/jmix/assets/85500330/955915cf-9018-4383-a013-15286535d4c7)

**Comment by KartnDev** [comment]
Didnt catch "business id" for UserTask. Input dialog also available for `ProcessStart` element.
Also: added translations for branch `release_2_2`

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6073-233
IntelliJ version: IntelliJ IDEA 2023.3.4 RC
