### ISSUE TITLE
Fix localization of Service task type list in a BPMN modeler

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2804]
### Environment

Jmix version: 2.1.2

### Bug Description

In Jmix 1.5 the list was:

<img width="358" alt="Screenshot 2024-01-30 at 13 47 16" src="https://github.com/jmix-framework/jmix/assets/7888486/89947311-b622-4537-b77e-a29b6aba6645">

In 2.1 it is:

<img width="343" alt="Screenshot 2024-01-30 at 13 46 24" src="https://github.com/jmix-framework/jmix/assets/7888486/3044b3ad-536c-4e42-a5f0-9cd5e16b9779">

In some items all words start with a capital letter, in others they don't. In 1.5 there was **JavaDelegate class**, in 2.1 it became **Java Delegate Class**

The captions must be as they were in Jmix 1.5

**Comment by KartnDev** [comment]
![image](https://github.com/jmix-framework/jmix/assets/43281522/4ea63b8a-17c7-4c76-875b-063a7c849e1f)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6063-233
IntelliJ version: IntelliJ IDEA 2023.3.4 RC
