### ISSUE TITLE
For Service task element in the BPMN modeler select the "Spring bean" type by default

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2805]
Jmix: 2.1.2

When a new Service Task is added to the canvas, select the "Spring bean" type by default, because is seems to be the most used one.

<img width="524" alt="image" src="https://github.com/jmix-framework/jmix/assets/7888486/37247a01-eafd-404e-a504-3814498e8645">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6050-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
