### ISSUE TITLE
Support custom dependency injectors for Subscribe, Install and Supply annotations

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2812]
### Problem Description

Currently we can add custom dependency injector by implementing `ControllerDependencyInjector` interface. It works perfectly when it is need to support some complicated **field** injection. However, it cannot be used for custom Subscribe, Install, etc.

The mechanism of injection works in the following way:
1) At first, standard injection is used - `ViewControllerDependencyInjector`
2) Then all custom injectors

And the main problem is `ViewControllerDependencyInjector` throws an exception if it cannot perform `Subscribe`, `Install` or `Supply`.

### Feature Description
If `ViewControllerDependencyInjector` cannot perform `Subscribe`, `Install` or `Supply` it should call the chain of custom injectors. And if all injectors did not cope - throw an exception.

**Comment by KremnevDmitry** [comment]
## Internal API changes

* Removed classes
    - `io.jmix.flowui.sys.ControllerDependencyInjector`
    - `io.jmix.flowui.sys.ViewControllerDependencyInjector`
    - `io.jmix.flowui.sys.ViewControllerDependencyManager`
    - `io.jmix.flowui.sys.ViewControllerReflectionInspector`
    
* Changed constructor signature
   - `io.jmix.flowui.sys.ViewSupport`
   
## Public API changes

* Changed constructor signature
   - `io.jmix.flowui.facet.dataloadcoordinator.OnViewEventLoadTrigger`
   - `io.jmix.flowui.facet.impl.DataLoadCoordinatorImpl`
   - `io.jmix.flowui.facet.impl.SettingsFacetImpl`
   - `io.jmix.flowui.xml.facet.DataLoadCoordinatorFacetProvider`
   - `io.jmix.flowui.xml.facet.SettingsFacetProvider`

**Comment by KremnevDmitry** [comment]
@rusiaikinat,

It is necessary to test possible cases of injection into the view controller.

# Elements injection:
The following component must be available for injection in the view controller using `@ViewComponent` annotation:

E.g.:
```java
    @ViewComponent
    protected JmixButton someButton;
```

- Components defined using XML markup
- Instance/Collection/KeyValue containers
- Instance/Collection/KeyValue loaders
- DataContext
- Actions defined using xml markup (`actions` tag for the view)
- Facets
- MessageBundle, now available using `@ViewComponent` (see Studio issue: [JST-4969](https://youtrack.jmix.io/issue/JST-4969/Replace-injection-annotation-for-messageBundle))

# ClickListener injection

All click listeners must be available for subscribing.

See: [Vaadin ClickNotifier](https://github.com/vaadin/flow/blob/576b7b1e1d52cb817fb9ae40bbaf9d237b0019a6/flow-server/src/main/java/com/vaadin/flow/component/ClickNotifier.java)

E.g.:
```java
    @Subscribe(value = "button", subject = "clickListener")
    protected void onClick(ClickEvent<JmixButton> event) {
        // some code
    }
```

- clickListener (default without `subject`)
- clickListener (subject = `clickListener`)
- singleClickListener (subject = `singleClickListener`)
- doubleClickListener (subject = `doubleClickListener`)


# Subscription injection 
Subscriptions to **component**, **view**, **data elements** must be available:

E.g.:
```java
    @Subscribe
    protected void onInit(InitEvent event) {
        // some code
    }

    @Subscribe(target = Target.DATA_CONTEXT)
    protected void onDataContextPreSave(DataContext.PreSaveEvent event) {
        // some code
    }

    @Subscribe("textField")
    protected void onTextFieldTypedValueChangeEvent(TypedValueChangeEvent<TypedTextField<String>, String> event) {
        // some code
    }

   // etc.
```

- View events
- Data Elements events (dataContext, containers, loaders)
- Component events
- Facet events

# IntallPoints injection
InstallPoints must be accessible:

E.g.:
```java
    @Install(to = "comboBox", subject = "itemLabelGenerator")
    protected String comboBoxItemLabelGenerator(Customer customer) {
        return "";
    }

    @Install(to = "usersDataGrid", subject = "tooltipGenerator")
    protected String usersDataGridTooltipGenerator(final User user) {
        return "some tooltip";
    }

    // etc.
```

- Components
- DataElements (loader delegate, collection sorter)

# Renderer injection
Component renderers must be available for installation using the `@Supply` annotation:

E.g.:
```java
    @Supply(to = "usersDataGrid.username", subject = "renderer")
    protected Renderer<User> usersDataGridUsernameRenderer() {
        return new TextRenderer<>();
    }

    @Supply(to = "comboBox", subject = "renderer")
    protected Renderer<User> comboBoxRenderer() {
        return new ComponentRenderer<>(Span::new, (span, user) -> {
            span.setText(user.getUsername());
        });
    }
```

- DataGrid columns
- ComboBoxes
- ListBoxes
- VirtualList
- Other from [UI Samples](https://demo.jmix.io/ui-samples)

# Application events
Subscriptions to application events must be available in the controller

E.g.:
```java
    @EventListener
    public void eventListenerHandler(ViewOpenedEvent event) {
    // some code
    }
```

# P.S.
Smoke-testing on a large project (with all add-ons installed) can also be objective
