### ISSUE TITLE
The bpm-admin role doesn't grant access to DMN releated views

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2818]
### Environment

Jmix version: 2.1.2

### Bug Description

The **bpm-admin** role doesn't grant access to "Decision tables" and "Decision table modeler" views.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6073-233
IntelliJ version: IntelliJ IDEA 2023.3.4 RC
