### ISSUE TITLE
Change displayed "class" column header into "implementation" in BPMN Modeler for every execution listener table

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2827]
### Environment

Jmix 2.x

### Bug Description

For each "execution listener" tables we have **class** header that describes **ONLY** `class implementation` for listener.
**If listener has other implementation, like delegate, NOTHING would shown.** 

![image](https://github.com/jmix-framework/jmix/assets/43281522/be9b4545-1900-4520-bd71-535cdab6d52c)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6060-233
IntelliJ version: IntelliJ IDEA 2023.3.4 RC
