### ISSUE TITLE
The action="usersDataGrid.itemTracking" button has no 'title'

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2847]
### Environment

Jmix version: 2.2.999-SNAPSHOT

### Bug Description

![image](https://github.com/jmix-framework/jmix/assets/114649487/746dbed0-1f07-414b-ba71-26c22f1bfd49)

### Steps To Reproduce

Add action  `list_itemTracking` for datagrid
Add button 
`<button action="usersDataGrid.itemTracking"  id="itemTrackingBtn"/>`
Run project -> Open the view containing the created button

**Comment by glebfox** [comment]
Not a bug. `itemTracking` has no default text, icon and... action, it just assumes that action will update its enabled state according to the DataGrid selection.
