### ISSUE TITLE
Invalid handler is generated for propertyFilter inside genericFilter configuration

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#2850]
Need to remove `classFqn` property from meta description.
Nested `propertyFIlter` has no handlers and cannot be injected into view controller.
Studio issue: https://youtrack.jmix.io/issue/JST-4644/Invalid-handler-is-generated-for-propertyFilter-inside-genericFilter-configuration

**Comment by rusiaikinat** [comment]
Reopened
Kotlin project
`propertyFIlter` has handlers if you open it by clicking the button Generate Handler
![image](https://github.com/jmix-framework/jmix/assets/114649487/3d3f6f89-97a3-4834-ba3c-00548a4181a6)

**Comment by Fedoseew** [comment]
Will be fixed in Studio. See related Studio issue.
