### ISSUE TITLE
Add support "retry cycle" property on service task on classic ui (port from 2.x)

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2852]
### Feature Description

See: https://github.com/jmix-framework/jmix/issues/2563

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6212-233
IntelliJ version: IntelliJ IDEA 2023.3.6
