### ISSUE TITLE
AbstractValueComponentDelegate makes unchecked class cast to EntityValueSource

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2853]
### Environment
Jmix version: 2.1.0+

### Bug Description
See Russian support forum: [topic](https://forum.jmix.ru/t/classcastexception-pri-ispolzovanii-svoej-realizaczii-valuesource/1614).

Method `AbstractValueComponentDelegate#setValueSource()` takes `ValueSource` type parameter .
But then without checking type casts to `EntityValueSource` type:
```
setupProperties((EntityValueSource<?, T>) valueSource);
```

### Expected Behavior
I think we can change parameter type in `setupProperties()` to `ValueSource` and inheritors will check type itself.

**Comment by MaxKatyshev** [comment]
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6128-233
IntelliJ version: IntelliJ IDEA 2023.3.4 (Community Edition)
verified
