### ISSUE TITLE
MultiValuePicker does not update error state if the field is required

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2856]
### Environment

Jmix version: 2.1.x

### Bug Description
`MultiValuePicker` incorrectly handles the error state when `required` attribute is enabled. It starts to ignore validation if it is failed.

### Steps To Reproduce

1) Add `MultiValuePicker` to a detail view:
```
<multiValuePicker id="multiValuePicker"
                  label="MultiValuePicker"
                  required="true">
    <actions>
        <action id="entityLookup" type="multi_value_select">
            <properties>
                <property name="javaClass" value="java.lang.String"/>
            </properties>
        </action>
    </actions>
</multiValuePicker>
```
2) Add validator:
```
@Install(to = "multiValuePicker", subject = "validator")
private void multiValuePickerValidator(final List<OrderLine> value) {
    log.info("MultiValuePicker validated: {}", value.size());
    if (value.size() <= 1) {
        throw new ValidationException("Validation failed");
    }
}
```
3) Open a detail view. The field should be in error state (due to required=true)
4) Add new item to the field.

### Current Behavior
The validation fails, since we expect more than one item. However field **does not show the error state**.

### Expected Behavior
Since validation fails field **must show the error state**.

**Comment by MaxKatyshev** [comment]
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6086-233
IntelliJ version: IntelliJ IDEA 2023.3.4 (Ultimate Edition)
verified
