### ISSUE TITLE
Move SearchField to compatibility module

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#286]
### Description
As SearchField can work only wth datasource and doc says that it is duplicate functionality of SuggestionField [documentation](https://doc.cuba-platform.com/manual-7.2/gui_SearchPickerField.html) we need to move:
- SearchField
- SearchPickerFIeld

to the cuba module.
Also, do not forget to move xsd description.

**Comment by glebfox** [comment]
It will be introduced in #421.
