### ISSUE TITLE
Inline editor in DataGrid is not closed when DTO is used

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2861]
### Environment

Jmix version: 2.1.0+

### Bug Description
See Russian support forum: [topic](https://forum.jmix.ru/t/ne-zakryvaetsya-vnutristrochnyj-redaktor/1618)
Cannot close inline editor in DataGrid when DTO entity is edited.

### Steps To Reproduce
1) Download demo project: [jmix-test.zip](https://github.com/jmix-framework/jmix/files/14205124/jmix-test.zip)
2) Create test entity instance
3) Edit in DataGrid: enter some values
4) Close inline editor

### Current Behavior
Editor is not closed.

### Expected Behavior
Editor is closed and entity is updated.

Related issue: #2886

**Comment by gorbunkov** [comment]
Waits for https://github.com/jmix-framework/jmix/issues/2886

**Comment by dtaimanov** [comment]
Wrong equals and hashCode has been added by data class. See https://github.com/jmix-framework/jmix/issues/2886#issuecomment-2142886575
