### ISSUE TITLE
Multitenancy doesn't work with REST API and Authorization Server add-ons

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2862]
### Environment

Jmix version: 2.1.3

### Bug Description

Requests to Generic REST entities endpoints return all records ignoring the tenant of the user.

See [forum topic](https://forum.jmix.io/t/does-multitenancy-add-on-support-rest-api-addon/4261).

The current problem relates to https://github.com/jmix-framework/jmix/issues/2051. The `io.jmix.multitenancy.core.impl.TenantProviderImpl#getCurrentUserTenantId` cannot evaluate the tenant of the user because the current Authentication contains not the instance of User class, but a special `io.jmix.authserver.introspection.UserDetailsOAuth2AuthenticatedPrincipal` that doesn't store information about the tenant.

### Steps To Reproduce

1. Create application with REST API and Multitenancy add-ons.
1. Create users with different tenants.
1. Obtain a token using the [Authorization Code grant](https://docs.jmix.io/jmix/rest/access-control.html#authorization-code-grant) for a user with a tenant. Or better obtain the token using new Resource Owner Password Credentials grant.
1. Try to get a list of entities using the `/entities/**` endpoint with the token for that user.

### Current Behavior

Entity instances that belong to all tenants will be returned.

### Expected Behavior

Only entity instances that belong to the tenant of the user should be returned.

### Sample Project

[mt-rest.zip](https://github.com/jmix-framework/jmix/files/14207352/mt-rest.zip)

The `Company` entity is tenant-specific

Users: user1 (password: 1), user2 (password: 2)

Endpoint for reading a list of entities: `http://localhost:8080/rest/entities/Company`

**Comment by gorbunkov** [comment]
Fixed in #2051

**Comment by SergeiAksenov2** [comment]
Only entity instances that belong to the tenant of the user1 or iser2 were returned, depends on tokens of the users in Postman request - Ok.
