### ISSUE TITLE
Deprecate unused UiCrossFieldChecks annotation from flowui module

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2865]
### Feature Description

For now there are two `UiCrossFieldChecks`:
1) `io.jmix.flowui.component.validation.group.UiCrossFieldChecks` - in Flow UI module. Used in `StandardDetailView`.
2) `io.jmix.core.validation.group.UiCrossFieldChecks` - in Core module. Unused annotation.

It seems the `io.jmix.core.validation.group.UiCrossFieldChecks` stays since Jmix 1.x. But FlowUI has its own annotation for cross-field validation.

**Comment by gorbunkov** [comment]
We need to figure out which of annotations should be used and which one should be deprecated

**Comment by KremnevDmitry** [comment]
Now the annotation from the `core` module is the main one: `io.jmix.core.validation.group.UiCrossFieldChecks`

The `io.jmix.flowui.component.validation.group.UiCrossFieldChecks` annotation is deprecated.

An issue has been created for the Studio to replace it with the main annotation during migration: [JST-4982](https://youtrack.jmix.io/issue/JST-4982)

An issue has been created to remove unused annotation in future releases: #3300
