### ISSUE TITLE
Tab injection does not work when TabSheet is placed in component container

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2868]
### Environment
Jmix version: 2.1.3

### Bug Description
See Russian support forum: [topic](https://forum.jmix.ru/t/annotacziya-viewcomponent-s-parametrom-ne-rabotaet-dlya-tablicz-v-tabsheet/1594).

When TabSheet is placed in VerticalLayout/HorizontalLayout/FormLayout and probably other layouts, controller dependency injector cannot find Tab instance.

### Steps To Reproduce
1. Add to XML:
```
<layout>
    <vbox>
        <tabSheet id="tabSheet2"
                  width="100%">
            <tab id="tab3" label="tab3">
                <span text="content"/>
            </tab>
            <tab id="tab4"
                 label="tab4">
                <span text="content"/>
            </tab>
        </tabSheet>
        <hbox>
            <tabSheet id="tabSheet1"
                      width="100%">
                <tab id="tab1" label="tab1">
                    <span text="content"/>
                </tab>
                <tab id="tab2" label="tab2">
                    <span text="content"/>
                </tab>
            </tabSheet>
        </hbox>
    </vbox>
</layout>
```
2) Add to the controller:
```
@ViewComponent("tabSheet1.tab1")
private Tab tab1;
@ViewComponent("tabSheet2.tab3")
private Tab tab3;

@Subscribe
public void onBeforeShow(final BeforeShowEvent event) {
    Objects.requireNonNull(tab1);
    Objects.requireNonNull(tab3);
}
```
3) Set debug breakpoint to `onBeforeShow`

### Current Behavior
Both instances are null.

### Expected Behavior
Tabs are not null.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6256-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)
