### ISSUE TITLE
Optimize the width of the window to eliminate horizontal scrolling

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#2871]
### Environment

Jmix version: 2.2.999-SNAPSHOT

### Bug Description

![image](https://github.com/jmix-framework/jmix/assets/114649487/9daa7f2e-685c-45a9-a5cb-adccf9976ab9)

### Steps To Reproduce
Add several translation addons
Add dynamicAttribute addon
Create Category
Create this attribute 
Type -> Enumeration
Add Enumeration details
### Expected Behavior

Optimize the width of the window to eliminate horizontal scrolling

**Comment by rusiaikinat** [comment]
As part of this task, I ask you to look at this bug https://github.com/jmix-framework/jmix/issues/2312#issuecomment-1935525128

**Comment by gorbunkov** [comment]
Duplicates https://github.com/jmix-framework/jmix/issues/2660
