### ISSUE TITLE
Jmix Data Repositories in Views

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#2881]
In the continuation of jmix-framework/jmix#2490

#### Tasks:

- [x] Check corner cases of Jmix Data Repository usage in Views
- [x] Make templates for Views based on Jmix Data Repositories

#### Changes
Affected templates: "list", "detail", "list and detail", "master-detail" for java and kotlin projects
- "Use Data Repositories" checkbox has been added to "Advanced" section of templates
- "Data Repository" field allows to select Data Repository for specified entity. It visible and required when checkbox selected only
- Load, save and remove delegates with repository-based implementations will be generated If checkbox has been selected.

### QA Notes
It makes sense to check that templates generates correctly working views  for java and kotlin projects with and without repositories.

**Comment by rusiaikinat** [comment]
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6437-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Kotlin

Master-detail view
![image](https://github.com/jmix-framework/jmix/assets/114649487/989ac524-d0df-45af-9c8f-a3d78b779e34)

**Comment by dtaimanov** [comment]
> Jmix version: 2.3.999-SNAPSHOT Jmix Studio plugin version: 2.3.SNAPSHOT6437-233 IntelliJ version: IntelliJ IDEA 2023.3.6 (Ultimate Edition) Kotlin
> 
> Master-detail view ![image](https://private-user-images.githubusercontent.com/114649487/336010402-989ac524-d0df-45af-9c8f-a3d78b779e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDYyNDcsIm5iZiI6MTcxNzQwNTk0NywicGF0aCI6Ii8xMTQ2NDk0ODcvMzM2MDEwNDAyLTk4OWFjNTI0LWQwZGYtNDVhZi05YzhmLWEzZDc4Yjc3OWUzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwOTEyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2ZlYzE1ZDFhNTNhYWUyYjRlNDkwZDhhYzIxNzQ4YzEyOGI1MWNkNzk1ZDYwYTYxYzQ5ODBlZGI5ZjMwNjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9JvADq9bOq31IjHZlEYO7MIS6vYlV0prUouIM9-l0Mg)

Caused by https://github.com/jmix-framework/jmix/issues/2865
