### ISSUE TITLE
Add a feature toggle for enabling the notification about closing the browser tab

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2890]
There must be a feature toggle that enables the notification about closing browser tab. By default, this notifications should be disabled.

See https://github.com/jmix-framework/jmix/issues/1243

**Comment by ilushaaa** [comment]
https://youtrack.haulmont.com/issue/JST-4731/Migrate-preventBrowserTabClosing-when-migrating-to-22
