### ISSUE TITLE
AWS FileStorage improvements

### ISSUE THREAD

**Issue by dgodlevskiy** [jmix-framework/jmix#2893]
The following improvements will be helpful when working with non-amazon s3 storages. 

1. Make region property optional
2. Support path-style bucket access

**Comment by knstvk** [comment]
It would provide compatibility with https://ceph.io

**Comment by gorbunkov** [comment]
Regarding the "Support path-style bucket access": 
* Amazon is going to deprecate the path-style access (see [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html) and [here](https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/)). 
* It seems that ceph.io supports virtual-hosted-style requests (see [here](https://docs.ceph.com/en/quincy/radosgw/s3/commons/#bucket-and-host-name) and [here](https://github.com/rook/rook/issues/4780)).

Maybe we should not spend time on supporting the path-style access.

**Comment by dgodlevskiy** [comment]
@gorbunkov Regarding the "Support path-style bucket access":

It's easy to do and will be useful for intergrating with legacy systems that don't support virtual-hosted-style. It might be difficult or even not possible to change it on their side

**Comment by dgodlevskiy** [comment]
Done in fixes for other issues
