### ISSUE TITLE
bigDecimalField does not accept decimal separator characters in non-English locales

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#2904]
### Environment

Jmix version: 2.1.3

### Bug Description

The decimal separator for bigDecimalField cannot be anything other than a comma character, even if it is configured in the locale format properties or in the NumberFormat field annotation.

### Steps To Reproduce

1. Create a project with English and non-English locales (for example, Vietnamese or Russian).
2. Leave the default number separator formats:
```
numberDecimalSeparator=.
numberGroupingSeparator=,
```
4. Create an entity with an attribute of type BigDeciamal:
```
@NumberFormat(pattern = "#,##0.########", decimalSeparator = ".", groupingSeparator = ",")
@Column(name = "AMOUNT", precision = 20, scale = 8)
private BigDecimal amount;
```
5. Create lists and detail views, use the bigDecimal field for the amount attribute:
```
<bigDecimalField id="amountField" property="amount">
    <validators>
        <digits integer="20"
                     fraction="8"
                     message="Wrong format"/>
    </validators>
</bigDecimalField>
```
6. Run the project in a non-English locale, open the detail view, try entering 1,234.56789 in the amount field.

### Current Behavior

Can't enter a dot. But if you type 1234.56789, it will be saved and displayed in the list view as 1,234.56789.
If you enter 1,234,56789, it will be stored as a empty value.

### Expected Behavior

You can enter the entire number with group and decimal separators.

### Note: 

If you are logging in with an English locale, you can enter a dot in the field, but not a comma.

### Sample Project

[BigDecimalLocale.zip](https://github.com/jmix-framework/jmix/files/14319244/BigDecimalLocale.zip)

**Comment by glebfox** [comment]
Vaadin's `BigDecimalField`, `IntegerField` and other number fields have no `format` attribute. For example `BigDecimalField` is `<input type="text" inputmode="decimal">` and works according to [inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) attribute.

Use `<textField>` that support `datatype` instead.
