### ISSUE TITLE
UserIndicator doesn't reload user when refreshing v2.x

### ISSUE THREAD

**Issue by ilushaaa** [jmix-framework/jmix#2918]
### Environment

Jmix version: 2.x

### Bug Description

If a currently logged in user has been changed, then invoking `UserIndicator#refreshUser` has no effect because `CurrentUserSubstitution#getAuthenticatedUser` returns old instance.

### Steps To Reproduce

1. Create two users.
2. Set User1 as substitution for User2
3. Login as User1.
4. Change User1 first name.
5. Change user in the user indicator panel.

### Current Behavior

User doesn't change and shows old user first name.

### Expected Behavior

User indicator should show the actual user info.

Related to #2465

**Comment by ilushaaa** [comment]
The [PR](https://github.com/jmix-framework/jmix/pull/3098) should fix the problem.

**Comment by SergeiAksenov2** [comment]
Tested on Java and Kotlin on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6289-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6292-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)

Users' names are change - Ok.
