### ISSUE TITLE
EntityLogItem, LoggedAttribute, LoggedEntity do not have localized messages for attributes

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#2924]
### Environment

Jmix version: <2.1.3>

### Bug Description

A description of what the bug is.

### Steps To Reproduce

Create Jmix project and add the Audit add-on
Launch the application and open Entity Inspector

Find  `EntityLogItem`, `LoggedAttribute`,  `LoggedEntity` entities and see values in the table's header :

### Current Behavior

<img width="1535" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/5d842135-3677-463a-b911-dc86728a8f4f">
<img width="1535" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/6d032f4d-397a-42a5-9126-7e9794c05b39">
<img width="1535" alt="image" src="https://github.com/jmix-framework/jmix/assets/40686909/62b1928e-81e9-4c53-8998-437c7b8354ff">

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1
