### ISSUE TITLE
German date format for excel export incorrect

### ISSUE THREAD

**Issue by alferink** [jmix-framework/jmix#2925]
### Environment

Jmix version: 2.2.0-SNAPSHOT

### Bug Description

I have the an application with a german locale. I am exporting an entity with date attributes to excel. The export of LocalDate and LocalDateTime is incorrect. The translation uses Java Format which does not work here.

I have a sample project. Login with german locale and export the customer
[excel-exportdemo.zip](https://github.com/jmix-framework/jmix/files/14358086/excel-exportdemo.zip)

### Current Behavior

Exporting of LocalDate "21/02/2024" is shown in Excel as 45343.
Exporting of LocalDateTime "21/02/2024 01:00" is shown in Excel as 45343,04167.

### Expected Behavior

Exporting of LocalDate "21/02/2024" should be shown in Excel as 21.02.2024.
Exporting of LocalDateTime "21/02/2024 01:00" is shown in Excel as 21.02.2024 01:00.

Related to [#2826](https://github.com/jmix-framework/jmix/issues/2826)

**Comment by KremnevDmitry** [comment]
Port-issue for 1.x = #3150

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6306-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
2)  Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6305-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
