### ISSUE TITLE
CodeEditor component doesn't respond to programmatic focus setting

### ISSUE THREAD

**Issue by ilushaaa** [jmix-framework/jmix#2930]
### Environment

Jmix 2.x

### Steps To Reproduce

Call `CodeEditor#focus`

### Current Behavior

Component doesn't get focus

### Expected Behavior

Component is focused

**Comment by MaxKatyshev** [comment]
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6128-233
IntelliJ version: IntelliJ IDEA 2023.3.4 (Community Edition)
verified
