### ISSUE TITLE
Quartz Job displayed as Paused during execution

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#2951]
### Environment

Jmix version: 2.2

### Bug Description

Job state becomes Paused during its execution.
### Steps To Reproduce

1. Create Job class with long enough execution time (e.g. 30s)
2. Create Job via Quartz UI using this Job Class (with every-minute schedule)
3. Check Job states

### Current Behavior

Job states:
- `Normal` when Job is waiting for the next execution
- `Paused` when Job is being executed

Because it's `Paused` it's possible to start editing such Job.

### Expected Behavior

Job states:
- `Normal` when Job is waiting for the next execution
- `Running` (or similar) when Job is being executed

`Paused` state should be displayed for the actually paused jobs only.
Running job should be read only.

### Expected solution

1. Introduce new Job state for running Jobs.
2. Check if Job is actually running.
3. Use SchedulerListener to update state in runtime.
4. (Optional) Show UI notifications about started\finished Jobs while being on Jobs list view.

**Comment by Gavrilov-Ivan** [comment]
@syncro - merge fix to 2.2 (it's in master only for now). Don't test until it's done.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.1-241
IntelliJ version: IntelliJ IDEA 2024.1 RC (Community Edition)

The job changes its state: Running, Normal, Paused (in manual case) - Ok.
