### ISSUE TITLE
Keep Jobs filter & sorting between refreshes

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#2955]
Keep user filter and sorting via url query parameters \ user settings

**Comment by SergeiAksenov2** [comment]
Tested on:
1)  Java:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6351-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2)  Java:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6350-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
3) Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6350-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

All Filter options are in url - Ok.
