### ISSUE TITLE
Missing messages in Notification add-on RU translation

### ISSUE THREAD

**Issue by dubenko** [jmix-framework/jmix#2961]
### Environment

Jmix version: 2.2

### Bug Description

Wrong RU translation

**Comment by glebfox** [comment]
@dubenko please add a detailed description of the bug, e.g. what is considered as "wrong".

**Comment by syncro** [comment]
added translations for received notifications action buttons ("mark as read" etc.) and NEW status

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6246-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)

All messages on Notification UI are translated:

![image](https://github.com/jmix-framework/jmix/assets/158277660/fddb88ae-a01a-4002-826c-523f6989aa3b)
![image](https://github.com/jmix-framework/jmix/assets/158277660/edbe06c0-780a-45d8-9fc5-5f7176ae2838)
![image](https://github.com/jmix-framework/jmix/assets/158277660/5d4915b5-76d4-4bcf-a4a6-5db0b29b371b)
