### ISSUE TITLE
Restrict selection to only primary data source entities in the entity class dropdown when attribute type is 'entity'.

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#2963]
"Prevent selection of entity classes not from the primary data source in the entity class dropdown when the attribute type is 'entity'.

## Current Behavior:
Selecting 'secdb_Entity' for an entity attribute within 'Category' with any target entity (whether from the primary or secondary database) results in an exception.

## Expected:
It should be disallowed to choose an entity class located in the secondary database for a dynamic attribute with the 'entity' type."

**Comment by KartnDev** [comment]
#Behavior before fix

1. Entity link won't work(tyrowing exception) when "reference" refers to the entity which located in other datasource.
2. If "Dynamic attributed" entity located "not primary database" and it's attribute refers to the primary datasource entity - all fine and works.

## Proposal fix

1. Dynamic attributes still working with any of entity that located in any of datasource
2. If you want to refer the entity dynamically, you need to sure that `CategoryAttributeValue` entity located in same datasource neither do your target dynamic "Referred" entity.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6374-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6375-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

There are no entities from the secondary database for a dynamic attribute dropdown - Ok.
