### ISSUE TITLE
Initial Chart animation not working

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#2966]
### Environment

Jmix version: 2.2.0

### Bug Description

There is no chart initialization animation. You can compare with the ECharts examples: https://echarts.apache.org/examples/en/editor.html?c=gauge-stage

Most likely, the problem is a double call to the client-side Chart API during initialization. The first call is the passing of basic options. The second call is data passing. The first initialization must be performed with only one call to the client-size.

### Steps To Reproduce

1. Create any chart
2. Open view

### Current Behavior

https://github.com/jmix-framework/jmix/assets/75516667/7af027bf-0b92-4908-96c8-7076a13f57e2

### Expected Behavior

https://github.com/jmix-framework/jmix/assets/75516667/6bf123e3-be95-47c7-8dfa-2ebc4be65095

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6195-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)

Smooth drawing of the chart arrow at the beginning of movement - Ok.

![charts](https://github.com/jmix-framework/jmix/assets/158277660/50901a65-6ee7-4423-a3b1-8a5cb98e0c21)
