### ISSUE TITLE
Transfer YARG into the Reports add-on

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2968]
See #1407

**Comment by NikitaShchienko** [comment]
For QA:
Test all types of reports.

**Comment by SergeiAksenov2** [comment]
Error launching Excel report.
NPE appers after clicking 'Run' button.
Error logs:
[#2968 log1.txt](https://github.com/jmix-framework/jmix/files/15064885/2968.log1.txt)
[#2968 log2.txt](https://github.com/jmix-framework/jmix/files/15064888/2968.log2.txt)
Report screen:
![image](https://github.com/jmix-framework/jmix/assets/158277660/9356ac56-6f69-4f35-97dd-385b2e315a1b)
![image](https://github.com/jmix-framework/jmix/assets/158277660/807f967f-e39d-4229-9818-c25ee088e013)
Error screen:
![image](https://github.com/jmix-framework/jmix/assets/158277660/0b9b0960-16b0-4eae-a5a6-586cca458d82)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Kotlin
 Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2) Java
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6335-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)

Tested with wizard on Entities and Reports - Ok.
