### ISSUE TITLE
Entity of other non-jmix subproject was recognized as Jmix entity

### ISSUE THREAD

**Issue by codingxu97** [jmix-framework/jmix#297]
There was a root project called Project A, then I created project A-1 which was a ```Jmix``` project, also created a project B called A-2 which was a ```Vert.x``` project.

So, here was a simple structure.
> A (root)
>> A-1 (Jmix)
>> A-2 (Vert.x)

In ```Vert.x``` project, I used ```Hibernate Reactive```, so I defined some entity used standard ```JPA```. But Entity in my ```Vert.x``` project A-2 was recognized as ```Jmix``` Entity, it could be edited by Jmix Plugin, it seemd strange.

Maybe ```Jmix``` project couldn't be a subproject when another JPA subproject exists?

**Comment by Gasloff** [comment]
Fixed in [JST-3195](https://youtrack.cuba-platform.com/issue/JST-3195)
