### ISSUE TITLE
gridColumnVisibility menuItem text must be resource string

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2974]
### Environment

Jmix version: 2.2.0

### Bug Description

Currently it's just a text and if a message key is used it's displayed as is.

### Steps To Reproduce

Add the following to `user-list-view.xml`

```
<gridColumnVisibility dataGrid="usersDataGrid">
    <menuItem refColumn="firstName" text="msg://com.company.demo.entity/User.firstName"/>
</gridColumnVisibility>
```

### Current Behavior

<img width="433" alt="Screenshot 2024-03-07 at 11 47 24" src="https://github.com/jmix-framework/jmix/assets/6077149/3d432480-b5be-4f43-afe3-900f157f1798">

### Expected Behavior

`gridColumnVisibility` menuItem text is resource string

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6215-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)

![image](https://github.com/jmix-framework/jmix/assets/158277660/ca326ce3-8344-4dc3-9f71-9bc392021929)
