### ISSUE TITLE
UrlQueryParameters facet with `dataGridFilter` does not work together with Settings facet

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#2980]
### Environment

Jmix version: 2.2.0

### Bug Description

After adding Settings facet the data grid filter is not reflected in URL reliably.

### Steps To Reproduce

- Create new project
- Add to `user-list-view.xml`:
```
<facets>
    <urlQueryParameters>
        ...
        <dataGridFilter component="usersDataGrid"/>
    </urlQueryParameters>
</facets>

<dataGrid id="usersDataGrid" ...>
    <columns>
        <column property="username" filterable="true" autoWidth="true"/>
        <column property="firstName" autoWidth="true" filterable="true"/>
        <column property="lastName" autoWidth="true" filterable="true"/>
```
- Start the app and test the filter. At this moment the data grid filter is saved in URL properly.

- Add Settings facet:
```
<facets>
    <urlQueryParameters>
        ...
        <dataGridFilter component="usersDataGrid"/>
    </urlQueryParameters>
    <settings auto="true"/>
</facets>
```

- Restart the app. 
- Open Users list view, set the filter - it's in URL
- Refresh the page - the URL params are empty. After that, setting/clearing the filter doesn't affect the URL at all.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6700-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6702-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

UrlQueryParameters facet works correctly with Settings facet. Parameters in URL do not missing - Ok.
