### ISSUE TITLE
UiEventPublisher.publishEvent doesn't notify all UIs in the current session

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#2981]
### Environment

Jmix version: 2.2.0

### Bug Description

`io.jmix.flowui.UiEventPublisher#publishEvent` 

### Steps To Reproduce

**Case 1:**

1. Open several tabs in one browser
2. Send Application event using `io.jmix.flowui.UiEventPublisher#publishEvent` 

**Case 2:**

1. Open application in several browsers
2. Send Application event using `io.jmix.flowui.UiEventPublisher#publishEvent` 

### Current Behavior

`io.jmix.flowui.UiEventPublisher#publishEvent` notifies only the current UI and the number of events is equal to the number of opened browser tabs in the current browser (**Case 1**). If there are opened tabs in another browser, they are ignored (**Case 2**).

### Expected Behavior

`io.jmix.flowui.UiEventPublisher#publishEvent` notifies all UIs (aka browser tabs of all browsers)

### Sample Project

[UiEventPublisher-issue.zip](https://github.com/jmix-framework/jmix/files/14555730/UiEventPublisher-issue.zip)

**Comment by SergeiAksenov2** [comment]
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6254-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Ultimate Edition)
2)Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6256-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)

Button 'For Users' sends notifications to all opened user sessions in all browsers and all browser tabs,
and button 'All UIs' sends notifications to all opened sessions only one user - Ok.
