### ISSUE TITLE
Custom projection is not applied in Map component

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2984]
### Environment
Jmix version: 2.2.0

### Bug Description
See support forum: [topic](https://forum.jmix.io/t/maps-mapview-using-epsg-21781-instead-of-epsg-4326/4573).
When custom projection is registered and set in MapView the white screen is shown.

### Steps To Reproduce
1. Download sample project: [sample-2-2-0.zip](https://github.com/jmix-framework/jmix/files/14574648/sample-2-2-0.zip)

2. Open "Map sample view"

### Current Behavior
White view is displayed instead of tiled images.

### Expected Behavior
![image](https://github.com/jmix-framework/jmix/assets/22093943/d175d909-ae6a-44f7-9265-0b6a0e782018)

### Notes
Also, check the case from support forum topic.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6169-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)

Two maps opened correctly.
