### ISSUE TITLE
Implement view access using the Navigation Access Control from Vaadin

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#2990]
In Jmix 2.2.0 a regression appeared: https://github.com/jmix-framework/jmix/issues/2985.

Anonymous view access stopped working. The reason is that in Vaadin 24.3 a new Navigation Access Control mechanism was introduced. See [Vaadin documentation](https://vaadin.com/docs/latest/security/advanced-topics/navigation-access-control).

We should rework access to Jmix views using this mechanism. Workaround implemented in #2985 must be rolled back.

See also: https://github.com/jmix-framework/jmix/issues/2791

**Comment by glebfox** [comment]
Relates to https://github.com/jmix-framework/jmix/issues/2928

**Comment by gorbunkov** [comment]
Implemented in https://github.com/jmix-framework/jmix/issues/3226
