### ISSUE TITLE
View attributes are not removed while closing view in some cases

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2992]
### Environment
Jmix version: 2.2.0

### Bug Description
ViewAttributes is not removed while closing a view in some cases, and it leads to unexpected behavior.

### Steps To Reproduce
1. In `user-list-view.xml` add read action to DataGrid:
```
<action id="read" type="list_read"/>

<button id="readBtn" action="usersDataGrid.read"/>
```
2. In `user-detail-view.xml` add `enableEditing` action:
```
<action id="enableEditingAction" type="detail_enableEditing"/>

<button id="enableEditingBtn" action="enableEditingAction"/>
```
3. Try to "read" some user
4. In user detail enable editing and change some fields.
5. Open another view from menu.
6. The "Unsaved changes" dialog should be shown. Click on any action excluding "cancel".
7. Then try to create new user

### Current Behavior
The user detail view is opened in read only mode. We cannot edit fields.

### Expected Behavior
User detail view enables to edit fields.

**Comment by SergeiAksenov2** [comment]
Tested on
1) Java:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6335-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
2) Java:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
3) Kotlin
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6335-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)

All user fields are editable in detail mode while creating new user - Ok.
