### ISSUE TITLE
Read only field shows required state

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#2996]
### Environment
Jmix version: 2.2.0

### Bug Description
The required state is always shown even for read only fields.

### Steps To Reproduce
1. Add to some view:
```
<textField required="true" readOnly="true"/>
```
2. Launch the application

### Current Behavior
The field shows required state, but we cannot edit value since field is read only.
![image](https://github.com/jmix-framework/jmix/assets/22093943/5326dfad-82fd-4f79-9675-beb7d112670b)

### Expected Behavior
The error state should not be shown in read only mode

**Comment by SergeiAksenov2** [comment]
Tested on Java and Kotlin and on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6298-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6297-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)

There is no error state on the project flowUI.
