### ISSUE TITLE
Limit-offset pagination strategy for Excel export all action

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3001]
Currently, when all records are being exported using the excel export action, the exporting mechanism uses the "keyset" pagination strategy. The keyset pagination sorts all records by ID, remembers the last ID of the previous page and uses it in the WHERE ID > last_id condition for the next page.

The problem may appear for the Oracle database server (probably for some others as well). In Oracle, records may be sorted and compared using different mechanisms (`NLS_SORT` and `NLS_COMP` parameters). If these parameters have different values then it may break exporting all records to Excel file. See [forum topic](https://forum.cuba-platform.com/t/paging-error-while-export-data-to-excel-from-oracle-db-with-uuids/17295) for details.

The solution may be to implement the export that uses the "limit-offset" pagination.

1. By default, the existing "keyset" pagination strategy should be used.
2. A special application property that defines the strategy should be introduced (possible values: "keyset", "limit-offset")
3. The "keyset" exporting strategy should be implemented.

See [initial issue](https://github.com/jmix-framework/jmix/issues/1452).

**Comment by ilushaaa** [comment]
Do we need to create a separate issue for Jmix 1.6?

**Comment by gorbunkov** [comment]
> Do we need to create a separate issue for Jmix 1.6?

@ilushaaa Yes, we do

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6244-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)

With property 'limit-offset' - excel export Ok.
