### ISSUE TITLE
Duplicate key exception while importing entities with relation fields

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#301]
When imported entity has fields with relations oneToOne, oneToMany or manyToMany, and some values already exists at database exception thrown at https://github.com/Haulmont/jmix-core/blob/2edfd4bb9c09dc7e7afae6d1fd1acd8da7f0db1a/core/src/main/java/io/jmix/core/impl/importexport/EntityImportExportImpl.java#L277:
duplicate key violates unique constraint

I assume that must be option at import plan to merge, skip or throw exception when importing existing entities.

**Comment by gorbunkov** [comment]
@n-13 are you talking about importing from the Entity Inspector screen? If so then in this screen, it should only create referenced entities marked as "composition". The meaning of composition is that such entities cannot exist without main entity and it should not be possible that they exist when the main entity doesn't. 
Was it your case?
