### ISSUE TITLE
Zip task includes bundles folder

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3012]
### Environment
Jmix version: 2.2.x

### Bug Description
Vaadin changed dev-bundle folder name, and it's included to zip file again.

### Steps To Reproduce
1. Invoke zip task in any project that contains `bundles` folder.

### AR
Zip file contains `bundles` and its size is ~4.7MB

**Comment by gorbunkov** [comment]
For QA - check on snapshot version of Jmix Gradle plugin

**Comment by SergeiAksenov2** [comment]
Tested on:

Configuration -
```
plugins {
    id 'io.jmix' version '2.2.999-SNAPSHOT'
    id 'org.jetbrains.kotlin.jvm' version '1.9.22'
    id 'java'
}
```

settings.gradle -
```
pluginManagement {
    repositories {
        mavenLocal()
        maven {
            url 'https://nexus.jmix.io/repository/public'
        }
        gradlePluginPortal()
    }
}
rootProject.name = 'T3012-241-kotlin-22999'
```

Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Zip file size -
![image](https://github.com/jmix-framework/jmix/assets/158277660/bc05d7e4-4352-46d9-a572-e8574ce7e3c9)
