### ISSUE TITLE
DataManager Bugs

### ISSUE THREAD

**Issue by z3sb** [jmix-framework/jmix#3015]
# DataManager Bugs

I faced a lot of issues with the DataManager first when I was working with the keycloak and I had to access the users with an **ID** so it always returned a not found even when I saw that a user with that **ID** is existed in the user's table
```java
User user = manager
                    .load(event.getEntityId())
                    .optional()
                    .orElseThrow(
                            () -> new NotFoundException("User Not Found")
                    );
```

and the second issue I have is when I tried to get the soft deleted items in the assets table so I tried this : 

```java
List<Asset> assets = manager
                .load(Asset.class)
                .query("select a from Asset a where a.deletedDate is not null")
                .list();
```
and it always returns an empty array even when there is a deleted item and deletedDate is not null in the table

so tried another way using conditions like this: 
```java
List<Asset> assets =  manager
                .load(Asset.class).condition(
                LogicalCondition.and(
                        PropertyCondition.notEqual("deletedDate", null)
                );
```
and that is funny because I get the items that have deletedDate as null even when I use the equal as the same😂😂😂😂😂😂😂😂😂😂😂😂😂

so jmix team please do a good job

**Comment by knstvk** [comment]
> when I was working with the keycloak

Keep in mind that DataManager respects the security policies, see https://docs.jmix.io/jmix/security/authorization.html#data-access-checks
Use `UnconstrainedDataManager` instead if you want to bypass security in your business logic.

> when I tried to get the soft deleted items

You cannot access soft-deleted entities with your query. Use `hint(PersistenceHints.SOFT_DELETION, false)` as described in the docs: https://docs.jmix.io/jmix/data-model/soft-deletion.html#turn-soft-deletion-off

> tried another way using conditions

In Jmix prior to 2.2 the conditions with empty parameter values are skipped, see the IMPORTANT note here: https://docs.jmix.io/jmix/2.1/data-access/data-manager.html#load-by-conditions

In Jmix 2.2 the behavior has been changed, see https://docs.jmix.io/jmix/whats-new/index.html#handling-empty-conditions

**Comment by z3sb** [comment]
Hi, I have tried the UnconstrainedDataManager and it still has the same result. and for the soft deleted items hint(PersistenceHints.SOFT_DELETION, false) when I add it to my query still don't get the soft deleted items

**Comment by knstvk** [comment]
@z3sb - provide a reproducible test as requested when you create a bug report:

> ### Sample Project
> 
> Attach a zip-archive with a sample project or provide a link to a GitHub repository with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). 
> 
> Jmix Studio Toolbar provides an [action](https://docs.jmix.io/jmix/studio/tool-window.html#gradle) for creating a zip-archive from your project.
>
