### ISSUE TITLE
Unable to start project with `java-dynamic-sqs-listener-spring-starter`

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix#302]
**Environment:**
Jmix version: 1.2.1
Jmix Studio plugin version: 1.2.0-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)

**Preconditions:**
ask me for the credentials before reproducing

**TC:**
1. Open the [attached](https://github.com/Haulmont/jmix-core/files/8229639/jmix-sample-migrtion.zip) project
2. Open the MyMessageListener.java -> Set the queue URL to annotation
3. Start the app with passing variables:
```
  AWS_ACCESS_KEY_ID=$[aws_key_id} AWS_REGION=$[aws_region} AWS_SECRET_ACCESS_KEY=${aws_secret_key} SQS_QUEUE_URL=${aws_queue_url} ./gradlew bootRun
```

**AR:**
app starting error:
```
2022-03-11 10:17:00.569  INFO 143108 --- [           main] faultMessageListenerContainerCoordinator : Starting MessageListenerContainerCoordinator
2022-03-11 10:17:00.581  WARN 143108 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'messageListenerContainerCoordinator'; 
nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'core_Store' defined in URL [jar:file:/home/shatalova/.gradle/caches/modules-2/files-2.1/io.jmix.core/jmix-core/1.2.0/8dedaa6a6dd387ccdab24f978ca0a8ac5c7dd5f9/jmix-core-1.2.0.jar!/io/jmix/core/metamodel/model/impl/StoreImpl.class]: 
Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No qualifying bean of type 'java.lang.String' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
```

**Comment by Dylay** [comment]
> **Environment:** Jmix version: 1.2.1 Jmix Studio plugin version: 1.2.0-213 IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
> 
> **Preconditions:** ask me for the credentials before reproducing
> 
> **TC:**
> 
> 1. Open the [attached](https://github.com/Haulmont/jmix-core/files/8229639/jmix-sample-migrtion.zip) project
> 2. Open the MyMessageListener.java -> Set the queue URL to annotation
> 3. Start the app with passing variables:
> 
> ```
>   AWS_ACCESS_KEY_ID=$[aws_key_id} AWS_REGION=$[aws_region} AWS_SECRET_ACCESS_KEY=${aws_secret_key} SQS_QUEUE_URL=${aws_queue_url} ./gradlew bootRun
> ```
> 
> **AR:** app starting error:
> 
> ```
> 2022-03-11 10:17:00.569  INFO 143108 --- [           main] faultMessageListenerContainerCoordinator : Starting MessageListenerContainerCoordinator
> 2022-03-11 10:17:00.581  WARN 143108 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'messageListenerContainerCoordinator'; 
> nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'core_Store' defined in URL [jar:file:/home/shatalova/.gradle/caches/modules-2/files-2.1/io.jmix.core/jmix-core/1.2.0/8dedaa6a6dd387ccdab24f978ca0a8ac5c7dd5f9/jmix-core-1.2.0.jar!/io/jmix/core/metamodel/model/impl/StoreImpl.class]: 
> Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
> No qualifying bean of type 'java.lang.String' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}
> ```
