### ISSUE TITLE
Anonymous access to a view does not work if it's configured using resource role

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3022]
### Environment
Jmix version: 2.2.x

### Bug Description
There are two ways of enabling anonymous access to view:
- `@AnonymousAllowed` annotation
- Resource Role: view permission

Application redirects to `LoginView` if anonymous user has resource role and permission to a view.

### Steps To Reproduce
1. Download project: [anonymous-access.zip](https://github.com/jmix-framework/jmix/files/14650074/anonymous-access.zip)

2. Launch application
3. Try to go: "http://localhost:8080/public-view"

### Current Behavior
Application redirects to `LoginView`

### Expected Behavior
`PublicView` should be shown

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6335-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)

Jump to 'Public view' - Ok.
