### ISSUE TITLE
Monitoring loader in screens (port to 1.6)

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3023]
Backport dataloaders monitoring part from https://github.com/jmix-framework/jmix/issues/1704 to Jmix 1.6.

**Comment by rusiaikinat** [comment]
Jmix version: 1.6.999-SNAPSHOT
Kotlin, Java

application.properties
    management.endpoints.web.exposure.include=prometheus,health,info,metrics
    management.endpoint.health.show-details=always

build.gradle
    implementation 'io.micrometer:micrometer-registry-prometheus' 
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

[http://localhost:8080/actuator/prometheus](http://localhost:8080/actuator/prometheus)

![image](https://github.com/jmix-framework/jmix/assets/114649487/17ca7c06-3c10-42a1-b55d-89113b2c9996)

**Comment by linkinek** [comment]
In https://github.com/jmix-framework/jmix/issues/1704 I see dataLoader tag. Will they be here too?

**Comment by syncro** [comment]
> In #1704 I see dataLoader tag. Will they be here too?

They are, but in order to see them you must cause dataloader coee execution:

![image](https://github.com/jmix-framework/jmix/assets/195749/7fc7c437-bad2-4c4a-a36a-23c8df90c714)
