### ISSUE TITLE
Implement TabSheet lazy tabs

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3029]
Similar to Classic https://docs.jmix.io/1.x/jmix/1.5/ui/vcl/containers/tab-sheet.html#lazy-loading-tab-content

The TabSheet component switches tabs and each tab can have many components. To descrease loading time of a view we can set attribute `lazy=true` to some tabs. In that case the vew won't load components from lazy tabs. Those components will load automatically if user activates a tab.

Descriptor example:
```
<tabSheet id="tabSheet">
    <tab id="tab1" label="Tab1">
        <button id="tab1Button" text="Tab1 Button"/>
    </tab>
    <tab id="tab2" label="Tab2" lazy="true">
        <vbox>
            <button id="tab2Button" text="Tab2 Button"/>    
        </vbox>
    </tab>
</tabShee>
```

Controller example:
```
@ViewComponent(value="tabSheet.tab1")
private Tab tab1;

@ViewComponent(value="tabSheet.tab2")
private Tab tab2;

@ViewComponent
private JmixTabSheet tabSheet;

@Subscribe
public void onInit(final InitEvent event) {
    updateTabLabels();

    tabSheet.addSelectedChangeListener(new ComponentEventListener<JmixTabSheet.SelectedChangeEvent>() {
        @Override
        public void onComponentEvent(JmixTabSheet.SelectedChangeEvent event) {
            updateTabLabels();
        }
    });
}

private void updateTabLabels() {
    tab1.setLabel(String.format("Tab1 [component: %s]", getTabLabel("tab1Button")));
    tab2.setLabel(String.format("Tab2 [lazy] [component: %s]", getTabLabel("tab2Button")));
}

private String getTabLabel(String tabId) {
    return tabSheet.findComponent(tabId).isPresent()
            ? ((JmixButton) tabSheet.findComponent(tabId).get()).getText()
            : "Empty";
}
```

In this example we have two tabs: tab1 and tab2. Tab2 is marked as lazy. Thus when the view is opened only components from tab1 are loaded.

The view is opened: tab1Button is loaded and tab2Button is empty.
The tab2 is activated: tab1Button is loaded and tab2Button is loaded.

We should be carefull about injecting components from lazy tabs in a controller because they wouldn't be initialised.
```
@ViewComponent
private JmixButton tab1Button;

@ViewComponent
private JmixButton tab2Button;

```
In this example, tab1Button is initialised and tab2Button is equals null. Even after the lazy tab activation tab2Button won't be initialised. We should handle this case manually.

**Comment by SergeiAksenov2** [comment]
Tested on Java:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6350-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6351-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

The button 'tab2Button' always equals null - Ok
