### ISSUE TITLE
Support new attribute of MultiSelectComboBox in XML

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3033]
* Auto Expand - https://vaadin.com/docs/latest/components/multi-select-combo-box#auto-expand
* Selected Items on Top - https://vaadin.com/docs/latest/components/multi-select-combo-box#selected-items-on-top

**Comment by SergeiAksenov2** [comment]
Tested on:
1)Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6286-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2)
