### ISSUE TITLE
Use fetch callback to load users while searching in EntityLogView

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3034]
### Description
In `EntityLogView` users ComboBox **loads all users immediately** on init event:
```
@Subscribe
protected void onInit(View.InitEvent event) {
    // ...
    userField.setItems(userRepository.getByUsernameLike("")
            .stream()
            .map(UserDetails::getUsername)
            .collect(Collectors.toList()));
```
We can implement lazy loading using `setItemsFetchCallback()`.

**Comment by SergeiAksenov2** [comment]
Tested on Java:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6374-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

Tested on Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6375-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

Search users in Audit addons, type letters -> logs 'EntityLogView.userField Search' - Ok.
