### ISSUE TITLE
EntityLogView does not show users from LDAP in dropdown list

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3042]
### Environment
Jmix version: 2.0+

### Bug Description
The project is configured to logging in only by LDAP users. In `EntityLogView` when you try filter logs by user you see nothing. The problem occurs due to this code:
```
userField.setItems(userRepository.getByUsernameLike("")
// ...
```
LDAP does not load users by empty string.

**Possible solution** is to use fetch callback API as described here: https://github.com/jmix-framework/jmix/issues/3034

### Steps To Reproduce
1. Download project: [sample-sales.zip](https://github.com/jmix-framework/jmix/files/14754842/sample-sales.zip). It is configured to connect with LDAP.
2. Start your LDAP server and configure users
3. Launch the application
4. Go to `Audit` -> `Entity log`
5. Try to filter by user

### Current Behavior
Users from LDPA are not loaded

![audit](https://github.com/jmix-framework/jmix/assets/22093943/b5f6481e-00fd-4f6c-8f1e-4bc8133aaead)

### Expected Behavior
Users from LDAP should be loaded and shown in dropdown list.

**Comment by syncro** [comment]
using fetch callback as it done in issue https://github.com/jmix-framework/jmix/issues/3034 completely solves this problem. So we need just wait util it is released and check. 

![ldap_entity_user_lookup](https://github.com/jmix-framework/jmix/assets/195749/4a0cbfeb-dcae-4be8-87dd-77ab924b44ae)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6407-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6409-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

Users from LDAP are shown in dropdown list - Ok.
