### ISSUE TITLE
Improve russian translation of BPM add-on in Jmix 2.2

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#3050]
Jmix version: 2.2.1

The current translation contains some untranslated labels and typos, for example:

1. Decision table views.

![image](https://github.com/jmix-framework/jmix/assets/11490702/b0b0dd14-f411-4e0b-9d12-3c205480da09)

![image](https://github.com/jmix-framework/jmix/assets/11490702/03ee657b-8238-4c3c-926f-0b495cbc5aa0)

2. Entity and enum labels.

![image](https://github.com/jmix-framework/jmix/assets/11490702/d4f7b53f-d7cd-46f3-b409-3d62e98f2a4c)

![image](https://github.com/jmix-framework/jmix/assets/11490702/c65bd3c8-e76c-4cfe-b70a-a6a4a57d8cb1)

**Comment by konyashkina** [comment]
_Tested on 
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.3-241
IntelliJ version: IntelliJ IDEA 2024.1.1_  
1. 
![3050-rus-dmn-table](https://github.com/jmix-framework/jmix/assets/85500330/3b237046-4cbf-4a7d-82ad-e2ef0c8e0ca2)

2. 
![3050-rus-modeler-startEvent-viewId](https://github.com/jmix-framework/jmix/assets/85500330/d2bb8283-09c5-4b82-ada4-9364fd51499e)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6349-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

![image](https://github.com/jmix-framework/jmix/assets/158277660/dfcca04a-2b1a-476d-b63c-66cc0a6de874)

![image](https://github.com/jmix-framework/jmix/assets/158277660/d49e1ab1-ff02-4144-a764-6b1d469a5102)

Localisation 'Id экрана' on two views - Ok.
