### ISSUE TITLE
Port limit-offset pagination strategy for Excel export to 1.6

### ISSUE THREAD

**Issue by ilushaaa** [jmix-framework/jmix#3058]
Detailed description: https://github.com/jmix-framework/jmix/issues/3001

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6244-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)
