### ISSUE TITLE
JmixImage doesn't update its value if bound to CollectionContainer and item is changed

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3076]
### Environment

Jmix version: 2.2.1

### Bug Description

`JmixImage` is missing `InstanceChangeEvent` subscription as a result it doesn't update its value if bound to CollectionContainer and item is changed

### Steps To Reproduce

. Create an entity with `byte[]` attribute that represents an image
. Add `<image>` to the lists view that is bound to a collection container
. Select entities one by one

### Current Behavior

Image changes its value after first click

### Expected Behavior

Image changes its value after item is changed

**Comment by SergeiAksenov2** [comment]
Tested on:
Java
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6335-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

Kotlin

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Java
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6335-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

2) Java
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

3) Kotlin
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
