### ISSUE TITLE
Header filter in DataGrid doesn't work for nested association attribute

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3084]
### Environment

Jmix version: 2.2.1

### Bug Description

When the column in the DataGrid displays a nested property of the association , the header filter editor should display the editor of the nested property, not the association itself.

### Steps To Reproduce

We have the `Order` entity and the `customer` association in it.

In the grid we display the `customer.name` attribute

```xml
        <dataGrid id="ordersDataGrid">
            <columns resizable="true">
                <column property="number" filterable="true"/>
                <column property="customer.name" filterable="true"/>
            </columns>
        </dataGrid>
```

### Current Behavior

The header filter editor opens the dialog for selecting a "customer" reference.

<img width="617" alt="Screenshot 2024-04-03 at 09 46 06" src="https://github.com/jmix-framework/jmix/assets/7888486/453c4eb3-352e-4e57-8827-218ba4b518f4">

### Expected Behavior

When we click the filter for the customer.name column we expect to see the filter that will apply for the "name" string (as it works in Jmix 2.1.x)

<img width="624" alt="Screenshot 2024-04-03 at 09 45 26" src="https://github.com/jmix-framework/jmix/assets/7888486/83f41f0c-a274-4ba0-bbcb-bee66240c524">

### Sample Project

[headerfilter.zip](https://github.com/jmix-framework/jmix/files/14847306/headerfilter.zip)

See [forum topic](https://forum.cuba-platform.com/t/bug-in-filterable-column-headers/17359).

**Comment by KremnevDmitry** [comment]
Looks like a duplicate, needs to be verified: jmix-framework/jmix#2989
