### ISSUE TITLE
GridVisibility: Column names not displayed for filterable columns 

### ISSUE THREAD

**Issue by alferink** [jmix-framework/jmix#3087]
### Environment

Jmix version: 2.2.1

### Bug Description

I have list view with filterable columns. Then I have a GridVisibilityComponent for the grid. In the GridVisibilityComponent the column names are not displayed. If the column is not filterable then the names are displayed correctly.

![image](https://github.com/jmix-framework/jmix/assets/7936798/8d808d86-1474-4a68-bc76-f0959684dc5b)

### Steps To Reproduce

1. Login as admin
2. Open OrderListView
3. Open GridVisibilityComponent 

### Current Behavior

The menu of the GridVisibilityComponent does contain two entries for the two columns, but the names are empty.

### Expected Behavior

The names of the columns are correctly displayed.

### Sample Project

[grid-visibility-demo.zip](https://github.com/jmix-framework/jmix/files/14850489/grid-visibility-demo.zip)

**Comment by gorbunkov** [comment]
Duplicates https://github.com/jmix-framework/jmix/issues/2960
