### ISSUE TITLE
Reports not sortable by name

### ISSUE THREAD

**Issue by timlehmkuhl** [jmix-framework/jmix#3089]
### Environment

Jmix version: 2.2.1

### Bug Description

I open the reports list view. Then I sort the reports by name. Sorting is not applied, but I get the visual feedback that it has been applied.

### Steps To Reproduce

1. Login as admin
2. Open ReportListView
3. Sort column name

### Current Behavior

Nothings happens when sorting by report name.

It looks like that the problem is in ReportListView. initColumnDataGrid(). At this point column is added programmatically and sortable = true is set.

### Expected Behavior

Two possibilities:

- Sorting by report name is disabled.
- Sorting by report name is enabled and can be applied

### Sample Project

[reportsort.zip](https://github.com/jmix-framework/jmix/files/14851665/reportsort.zip)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6313-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6311-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)

Reports can be sorted by name - Ok.
