### ISSUE TITLE
Code completion for "property" attribute of dataVectorSource doesn't work

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3090]
See Studio issue and comments: https://youtrack.jmix.io/issue/JST-4818/Code-completion-for-property-attribute-of-dataVectorSource-doesnt-work

**Comment by rusiaikinat** [comment]
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6246-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)

Does not work

**Comment by Fedoseew** [comment]
Will be supported in Studio
