### ISSUE TITLE
Disable drop inside HTML components designed for text output

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3091]
See Studio issue: https://youtrack.jmix.io/issue/JST-4846/Disable-drop-inside-HTML-components-designed-for-text-output

**Comment by rusiaikinat** [comment]
Tested on
Kotlin
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6245-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

Java
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6246-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)
