### ISSUE TITLE
Support editing PK inside detail view

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#3095]
If you add `<textField id="idField" property="id"/>` inside any of detail view and try to edit PK of the selected entity, this would trigger. Jmix Data thinking that saving entity is new or stacked.
![image](https://github.com/jmix-framework/jmix/assets/43281522/31ce3743-7bd9-4511-b1df-7685a772b113)

Source: https://forum.jmix.io/t/bug-entity-with-pk-0-not-possible-to-edit/4667

Demo project - inside forum's topic

**Comment by gorbunkov** [comment]
It is not allowed to edit primary key
