### ISSUE TITLE
Job class is not displayed if it doesn't implement org.quartz.Job directly

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3109]
### Environment

Jmix version: 2.2.1

### Bug Description

Job classes that implement `org.quartz.Job` interface transitivelly via some intermediate abstract class or interface are not visible in Job creation UI.

Cause: class detection (`QuartzJobClassFinder`) based on `org.springframework.core.type.classreading.MetadataReader` can check only the first-level implementations.
Also it doesn't exclude interfaces and abstract classes from the final list.

### Steps To Reproduce

1. Create `interface ExtendedJob extends Job`
2. Create `class ExtendedJobImpl implements ExtendedJob`
3. Run project and go to Quartz Jobs UI
4. Start creating new Job
5. Check items in class combo box

### Current Behavior

Class combo box displays only classes\interfaces that implements `org.quartz.Job` directly

### Expected Behavior

Class combo box should display all classes that implements `org.quartz.Job` effectively via any hierarchy.
And it should not display interfaces or abstract classes - only concrete class.

**Comment by SergeiAksenov2** [comment]
1) Testrd on Java:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6321-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2) Tested on Kotlin:
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6320-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Ultimate Edition)

Class combo box displays all classes that implements or inherits org.quartz.Job

![image](https://github.com/jmix-framework/jmix/assets/158277660/f7ffe777-e46a-475d-97d1-b3cc145216dc)
