### ISSUE TITLE
Not localized values in the process event listener editor of the BPMN modeler

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3118]
### Environment

Jmix version: 2.2.1

### Bug Description

Not localized values in the process event listener editor of the BPMN modeler. See "Entity type" combo box:

<img width="837" alt="Screenshot 2024-04-09 at 15 57 29" src="https://github.com/jmix-framework/jmix/assets/7888486/326c60b2-f921-4f8e-8dbe-4da75754b7e7">

In Jmix 1.5 it was:

<img width="513" alt="Screenshot 2024-04-09 at 15 57 53" src="https://github.com/jmix-framework/jmix/assets/7888486/2b2ea464-5e3c-4b71-91df-28be0e20369e">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.2-241
IntelliJ version: IntelliJ IDEA 2024.1
