### ISSUE TITLE
NPE when generating a DOCX report with a formatter

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#3122]
### Environment

Jmix version: 2.2.1

### Bug Description

When generating a DOCX report with a formatter, NPE crashes.

Forum: https://forum.jmix.ru/t/oshibka-pri-formatirovanii-vyhodnogo-parametra-s-ispolzovaniem-groovy-skript/1718/7

### Steps To Reproduce

1 - Run the project
2 - Import a report
3 - Run the report

### Current Behavior

**Exception:**
```
NullPointerException: Cannot invoke "io.jmix.reports.libintegration.GroovyScriptParametersProvider.getParametersForFormatterParameters()" because "this.groovyScriptParametersProvider" is null
```

### Sample Project

Report: [User_report.zip](https://github.com/jmix-framework/jmix/files/14929912/User_report.zip)
Project: [demo_project.zip](https://github.com/jmix-framework/jmix/files/14930024/demo_project.zip)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6311-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6310-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Both reports are Ok.
