### ISSUE TITLE
Empty item caption in Grid Column Visibility component list

### ISSUE THREAD

**Issue by eartamonov** [jmix-framework/jmix#3125]
### Environment

Jmix version: 2.2.1

### Bug Description

Empty captions in the list of grid columns in gridColumnVisibility component (only if column mark as filterable="true")

If grid column is mark as filterable a DataGridHeaderFilter generated as Grid Header component.
Then method io.jmix.flowui.component.gridcolumnvisibility.JmixGridColumnVisibility#getColumnHeaderText is called (when menu items are generated)

### Steps To Reproduce

1. add gridColumnVisibility component for a dataGrid
2. mark column as filterable="true"
3. open screen with the grid and click on the settings button

### Current Behavior

drop-down list opens with empty item caption
![image](https://github.com/jmix-framework/jmix/assets/56630484/8bc1ec7e-2347-4bb7-9ee6-cde989c90bce)

### Expected Behavior

drop-down list opens with filled item caption (text from column header)

**Comment by gorbunkov** [comment]
Duplicates https://github.com/jmix-framework/jmix/issues/2960
