### ISSUE TITLE
Support Subscribe, Supply and Install annotations for nested elements in GeoMap

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3132]
### Description
Maps add-on has already have custom dependency injector: `GeoMapControllerDependencyInjector`. However Jmix does not support custom dependency injectors for Install, Subscribe and Supply.

Wait for: https://github.com/jmix-framework/jmix/issues/2812
Also see issue for temporary disabling Generate Handler: [JST-4885](https://youtrack.jmix.io/issue/JST-4885/Disable-Generate-Handler-dialog-for-nested-elements-in-GeoMap)

**Comment by KremnevDmitry** [comment]
An issue for support in the studio: [JST-4985](https://youtrack.haulmont.com/issue/JST-4985/Enable-generating-nested-elements-handler-in-GeoMap)
