### ISSUE TITLE
OptionDialogBuilder creates new buttons each time it is opened

### ISSUE THREAD

**Issue by ilushaaa** [jmix-framework/jmix#3134]
### Environment

Jmix version: 2.x

### Bug Description

The number of button increases each time a dialog is opened.

### Steps To Reproduce

Create instance of `OptionDialogBuilder` with action.
Call `open ` several times. 

### Current Behavior

When a dialog is opened new buttons are created but the old ones remain.

### Expected Behavior

The number of buttons remains the same regardless of the number of a dialog openings.

**Comment by Flaurite** [comment]
### QA
To reproduce the issue try the following code:
```
<button id="doBtn" text="Do btn"/>
```
```
Dialogs.OptionDialogBuilder builder;

@Subscribe(id = "doBtn", subject = "clickListener")
public void onDoBtnClick(final ClickEvent<JmixButton> event) {
    if (builder == null) {
        builder = dialogs.createOptionDialog()
                .withText("Option Dialog")
                .withActions(new BaseAction("act1"));
    }
    builder.open();
}
```
Steps to reproduce:
1. Add the code to a view
2. Open dialog and close
3. Open dialog.

Without fixes there will be two buttons.

4. Check the same steps with `InputDialog`.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6463-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6464-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

The Dialog window only one button each time it is opened - Ok.
