### ISSUE TITLE
Wrong handlers order for RichTextEditor

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#3135]
### Environment

Jmix version: <2.2>

### Bug Description

Wrong order of handlers

<img width="352" alt="Screenshot 2024-04-12 at 16 25 24" src="https://github.com/jmix-framework/jmix/assets/128021710/ab2e1edb-5c65-4d74-bae0-e2f785a112f0">

### Expected Behavior

Alphabetic order

**Comment by Fedoseew** [comment]
Will be fixed in Studio.
Studio issue: https://youtrack.jmix.io/issue/JST-4989/Wrong-handlers-order-for-RichTextEditor
