### ISSUE TITLE
Error importing a file from json

### ISSUE THREAD

**Issue by OlgaMoss** [jmix-framework/jmix#3136]
### Environment

Jmix version: <2.2.1.1>

### Bug Description

When importing an entity into json with a list of entities that has an attribute that is not included in the metadata, an error occurs from the entity inspector.
In addition, there is a spelling error in the Russian localization. See the screenshot.
![image](https://github.com/jmix-framework/jmix/assets/15741581/b5b07839-4424-42fd-a33f-ab73bf62a781)

The following was done on the project to solve this problem. io.jmix.core.impl.importexport.EntityImportExportImpl#importEntity has added a readonly check

if (metaProperty.isReadOnly()) {
continue;
}

### Steps To Reproduce

1. Create entity 1 with a method that is not an attribute of the entity, that is, not included in the metadata.. For example
@JmixProperty
@DependsOnProperties({"firstName", "lastName"})
public String getFullName() {…}

2. Create a second entity 2, which will contain a list of entities 1.
3. Create test data with a filled list of entities 1.
4. Go to the entity inspector.
5. Click on the Export -> Export to json button.
6. Click on the Import button. Select the generated file in step 5.

### Current Behavior

The error message "Import failed. Perhaps the file is 'User (4) (1).json' has incorrect content. Can't find setter for property 'fullName' at class com.eurochemgroup.crmec.entity.User»

### Expected Behavior

The file was exported successfully.

**Comment by Gavrilov-Ivan** [comment]
Unable to reproduce via original steps.
Simplified case - without extra top-level entity ("entity2"):

1. Create entity with read-only method-property depends on some persistent property.
2. Create entity instance and don't fill persistent property.
3. Export-import this instance
4. "Unfetched attribute" exception

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.2-242
IntelliJ version: IntelliJ IDEA 2024.2.0.2 (Community Edition)
Not reproduced. The file was exported successfully.
