### ISSUE TITLE
Different default value for alignItems property

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3142]
Change default value for `alignItems` property in meta annotations.
Now Studio set default value (STRETCH) if xml attribute `alignItems` is null or empty, but in runtime we do not set value if xml attribute is null or empty (or set null value) and component uses default value from client (START).

For QA: see cases in Studio issue.

See Studio issue: https://youtrack.jmix.io/issue/JST-4858/Difference-in-layout-between-preview-and-application
See Vaadin issue: https://github.com/vaadin/flow/issues/19160

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6306-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6305-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Checked hbox, vbox with property alignItems.
Cecked component entityPicker mentioned in JST-4858.
