### ISSUE TITLE
Date format for excel export incorrect

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3150]
### Environment

Jmix version: 1.6.999-SNAPSHOT

### Bug Description

See origin issue: #2925

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6306-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
2) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6310-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Date format in excel export as date - Ok
