### ISSUE TITLE
Backward navigation target is cleared after page refresh

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3155]
### Environment

Jmix version: 2.2.1

### Bug Description

Backward navigation target is cleared after page refresh.

### Steps To Reproduce

1. Open a detail view
2. Refresh the page
3. Close a detail view using ok/close button

### Current Behavior

User is navigated to the **main view**

### Expected Behavior

User is navigated to the **prev view**, e.g. list view

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6335-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Returns to list view - Ok.
