### ISSUE TITLE
withAfterNavigationHandler not called after save

### ISSUE THREAD

**Issue by alferink** [jmix-framework/jmix#3157]
### Environment

Jmix version: 2.2.1

### Bug Description

I open a new view from a details view and I have local changes in the view. When save the changes while navigating to the new view, the withAfterNavigationHandler is ignored. 

### Steps To Reproduce

1. Open Customers
2. Open 1 customer
3. Change customer name
4. Select one order and click edit
5. A dialog "You have unsaved changes" is displayed. Close it by clicking save.

### Current Behavior

The product view has been opened, but the notification is not shown. So "withAfterNavigationHandler" is not executed.

Additionally the back navigation does not work. When I close the product detail view, a blank view is shown.

### Expected Behavior

The product view has been opened, but and the notification is shown. The back navigation (on save/ cancel) works (navigate back to customer details view).

Actually this workflow results in the expected behaviour:
1. Open Customers
2. Open 1 customer (do not edit customer)
3. Select 1 order and edit

### Sample Project

[navigator-demo.zip](https://github.com/jmix-framework/jmix/files/14997637/navigator-demo.zip)

**Comment by glebfox** [comment]
`ViewNavigators` requires that _origin_ view is passed, same as for `DialogWindows`.

**Comment by alferink** [comment]
Does that mean you need to fix this in Jmix or do I have do set the origin view in the application code? I don't know how to do this.

**Comment by glebfox** [comment]
> Does that mean you need to fix this in Jmix or do I have do set the origin view in the application code? I don't know how to do this.

Sorry for inconvenience, it's just future fix hint for doc. The fix currently is on review, but due to API changes described above it will be in the next minor release (June 2024)

**Comment by glebfox** [comment]
**Breaking changes**

Since, it may be no origin view, e.g. if we open a root view or view is opened as root in tests, `UiComponentUtils#getCurrentView` used to find current view in case deprecated API is used, throws exception. 

Two solutions:

1. Use `io.jmix.flowui.view.navigation.ViewNavigationSupport#navigate` in case of root view, e.g.:

```
navigationSupport.navigate(ComponentRegistrationTestScreen.class)
```

2. For tests provide fake origin view if needed, e.g.:

```
def origin = navigateToView(BlankTestView)
viewNavigators.detailView(origin, Customer)
        .newEntity()
        .navigate()
```
