### ISSUE TITLE
Support for value formats in HTML-reports

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#3159]
Currently, value formats are not applied to reports with HTML-template.

Forum: https://forum.jmix.io/t/report-image-html/4750

**Comment by fractal3000** [comment]
Fixed in https://github.com/jmix-framework/jmix/pull/3584

**Comment by SergeiAksenov2** [comment]
Tested on Jmix version: 2.4.999-SNAPSHOT:
1) Jmix Studio plugin version: 2.3.SNAPSHOT6791-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix Studio plugin version: 2.3.SNAPSHOT6789-241
IntelliJ version: IntelliJ IDEA 2024.1.6 (Community Edition)
3) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6790-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)


Value format is supported in HTML-reports - Ok.

![image](https://github.com/user-attachments/assets/c9477591-e94a-45c7-9768-2737cafd04ab)
