### ISSUE TITLE
Filter components are not aligned when a label is split into two lines

### ISSUE THREAD

**Issue by ilushaaa** [jmix-framework/jmix#3164]
### Environment

Jmix: v2.2

### Bug Description

If the filter label is split into two lines, filters from one line will not be aligned.  

### Steps To Reproduce

Create a GenericFilter with two fields. Use a property with a long name to split the label into two lines.

### Current Behavior

![image](https://github.com/jmix-framework/jmix/assets/28649514/274403c9-c34d-4164-a1fa-0a078bc682d2)

### Expected Behavior

Filter components are aligned.

**Comment by KremnevDmitry** [comment]
Possibly a duplicate with https://github.com/jmix-framework/jmix/pull/3153. @ilushaaa, check required.

**Comment by gorbunkov** [comment]
Duplicates #2745
