### ISSUE TITLE
Redesign "Reset passwords" feature

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#3167]
1. Now the "Reset passwords" functionality is surprising. It's not clear what's going on when you click "Generate and save", and the upper message doesn't give enough information.

![screencast 2024-04-18 10-48-40](https://github.com/jmix-framework/jmix/assets/5513878/8b5e328d-7107-44a3-b104-9da9cdcbd657)

2. The Users data grid has no multi-selection by default, but the action is obviously designed for working with multiple rows.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6844-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
