### ISSUE TITLE
 Sort localized values in the process event listener editor of the BPMN modeler

### ISSUE THREAD

**Issue by konyashkina** [jmix-framework/jmix#3178]
Add an event listener to a BPMN process, open "Entity type" combo box 
(look at https://github.com/jmix-framework/jmix/issues/3118 ) 

ER: Values are in alphabet order.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6364-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6363-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

Entity type values are in alphabet order - Ok.
![image](https://github.com/jmix-framework/jmix/assets/158277660/65bcc916-a809-40cb-baa6-f6abce5f5884)
