### ISSUE TITLE
The fields of dynamic attributes are available for modification before the entity editing is started

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#3181]
### Environment

Jmix version: 2.2.999-SNAPSHOT (Last version 2.2.1)
Kotlin

### Steps To Reproduce

1. Create a project with dynamic attribute
2. Add the dynamic attribute to the User entity-detail-view
3. Add the master-detail-view to the User entity.
4. Run the project and open master-detail-view

### Current Behavior
Dynamic fields are not blocked
![image](https://github.com/jmix-framework/jmix/assets/114649487/ae74809e-d5bb-4212-8221-75f113622957)

### Expected Behavior

The fields must be locked before calling EDIT

#2874

**Comment by glebfox** [comment]
Check on 2.3+

**Comment by SergeiAksenov2** [comment]
Tested on Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

[TestProject.zip](https://github.com/user-attachments/files/16677120/T3181k.zip)
This situation is only reproduced after running the project, and before editing the User entity (even if the edit is cancelled by the Cancel button).

The Case is reproduced as follows:
1. Run project
2. Go to the "User M" view
3. Dynamic attributes fields attr1 and attr2 are editable.

![image](https://github.com/user-attachments/assets/da5e3ac8-4fc0-4f4e-a5cc-88acddcb0fdb)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6770-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

Still reproduced.

**Comment by SergeiAksenov2** [comment]
![image](https://github.com/user-attachments/assets/e28d1b61-f765-4515-9d6e-2cad98d8468f)

**Comment by ilushaaa** [comment]
The dynamic attributes panel had exactly the same behaviour. 
`<dynattr:dynamicAttributesPanel dataContainer="trackDc" categoryFieldVisible="true"/>`
So we need to test both cases.
