### ISSUE TITLE
Fix main view layout in preview

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3184]
See Studio issue: https://youtrack.jmix.io/issue/JST-4888/Fix-main-view-layout-in-preview

Note: need to fix meta annotations for MainView elements (NavigationBar, DrawerLayout, InitialLayout)

**Comment by SergeiAksenov2** [comment]
Tested in ticket JST-4888 on:
1) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6334-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6335-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)
