### ISSUE TITLE
Report Templates CodeEditor Fullscreen link should not be shown without editor

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix#3185]
### Environment

Jmix version: 2.3.999

### Bug Description

Fullscreen link for Report Templates Code Editor appears even when incompatible file type for template is selected

### Steps To Reproduce

1. Run project with development version deps
2. Goto to report templates
3. Upload any except html format e.g. docx
4. See "Fullscreen" link shown withoud the Code Editor

### Current Behavior

Fullscreen link is shown for any template file type

### Expected Behavior

Fullscreen link is shown only for supported template file types like .html

### Sample Project

[report-view-demo.zip](https://github.com/jmix-framework/jmix/files/15104940/report-view-demo.zip)

**Comment by rusiaikinat** [comment]
Fullscreen link is also displayed for  .csv
Tested on: 
Kotlin, java
Jmix version: 2.3.999-SNAPSHOT
