### ISSUE TITLE
MenuBarItem does not attach child item to a menu

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3194]
### Environment
Jmix version: 2.2.x

### Bug Description
`MenuBarItem#addChildItem()` method does not attach child item to menu. It adds item to a tree and even show it, however a subsequent child items of added item won't be shown.

### Steps To Reproduce
1. Add menu to the view:
```
<listMenu id="menu" loadMenuConfig="false"/>
```
2. Add the following code to controller:
```
@ViewComponent
private JmixListMenu menu;
@Subscribe
public void onInit(final InitEvent event) {
    ListMenu.MenuBarItem menuBarItem = new ListMenu.MenuBarItem("bar1")
            .withTitle("Bar 1");
    ListMenu.MenuItem menuItem = new ListMenu.MenuItem("item1")
            .withTitle("item1");
    menuBarItem.addChildItem(menuItem);
    menu.addMenuItem(menuBarItem);
    
    ListMenu.MenuBarItem menuBarItem1 = new ListMenu.MenuBarItem("bar2")
            .withTitle("Bar 2");
    menuBarItem.addChildItem(menuBarItem1);
    
    ListMenu.MenuItem menuItem1 = new ListMenu.MenuItem("item2")
            .withTitle("item2");
    menuBarItem1.addChildItem(menuItem1);
}
```

### Current Behavior
The last item `item2` is not shown

### Expected Behavior
All added items should be shown

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6468-233
IntelliJ version: IntelliJ IDEA 2024.1.1
