### ISSUE TITLE
URL is not updated when new entity is saved using DetailSaveAction action

### ISSUE THREAD

**Issue by PBeliaevHaulmont** [jmix-framework/jmix#3205]
### Environment

Jmix version: 2.2.1

### Bug Description

When creating a new entity, instead of actual ID, the `new` placeholder is used in URL, e.g.: `http://localhost:8080/users/new`

If we save an entity using `DetailSaveAction`, i.e. we stay in the detail view, then URL is not changed and in case we navigate somewhere else with `viewNavigators.withBackwardNavigation(true)` then new entity editor will be opened. Same happens if we refresh the page. 

### Steps To Reproduce

- open new entity editor screen
- fill required field and save changes via "save" action
- click on button, which has a handler with `viewNavigators.withBackwardNavigation(true)...`
    -  there should be a cancel button on the screen that opens.
- click on cancel button 

### Current Behavior

- new entity editor will be opened

### Expected Behavior

- saved entity editor screen will be opened

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6460-233
IntelliJ version: IntelliJ IDEA 2024.1.1
