### ISSUE TITLE
View action triggered by shortcut doesn't trigger any pending input value change events

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3213]
### Environment

Jmix version: 2.2.1

### Bug Description

If an action is triggered by a shortcut and the user has just entered a value into an input field but has not lost focus, i.e. the pending input value change event is not fired, then the entered value is ignored.

### Steps To Reproduce

1. Add view action with shortcut, e.g. <kbd>Enter</kbd>
2. Add a text field and a button associated with action
3. Add button click handler, that shows a notification with entered value
4. Type value into a text field and press <kbd>Enter</kbd>

### Current Behavior

Either null (empty) or previous value is shown

### Expected Behavior

Currently entered value is shown.

### Proposed solution

1. All actions should should set `ResetFocusOnActiveElement` to `true`, same as Detail actions do.

```
if (shortcutCombination != null) {
    shortcutCombination.setResetFocusOnActiveElement(true);
}
```

2. Add `resetFocusOnActiveElement` attribute, so user can setup it manually. Add nested `keyCombination` element.

**Comment by KremnevDmitry** [comment]
Added new nested component `shortcutCombination`.

E.g.:
```xml
    <actions>
        <action id="submitAction"
                text="msg://loginForm.submit"
                actionVariant="PRIMARY">
            <shortcutCombination keyCombination="ENTER" resetFocusOnActiveElement="true"/>
        </action>
    </actions>
```

Studio annotation is added, but it doesn't work:
![image](https://github.com/jmix-framework/jmix/assets/75516667/f189585c-c5d2-42ce-b310-5d041ee0c879)

@Fedoseew, please look
Probably Studio issue is required

**Comment by Fedoseew** [comment]
@KremnevDmitry, yes, now Studio doesn't support nested elements inside `action`. 
Studio issue: https://youtrack.jmix.io/issue/JST-4984/Support-nested-elements-inside-action-component
