### ISSUE TITLE
GenericFilterEditAction is not included to Studio meta

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3214]
### Environment
Jmix version: 2.2.1

### Bug Description
In component inspector it is not possible to add `GenericFilterEditAction` using "Add" - > "Actions" -> "Action".

### Solution
Add description of action to `StudioGenericFilterActions.java`

**Comment by gorbunkov** [comment]
@Flaurite Where should this action be added to?

**Comment by Flaurite** [comment]
@gorbunkov I've updated description
