### ISSUE TITLE
Upload fields are not generated for FileRef and byte array while creating Views for Entity

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3217]
See Studio issue: https://youtrack.jmix.io/issue/JST-4533/Upload-fields-are-not-generated-for-FileRef-and-byte-array-while-creating-Views-for-Entity

**Comment by gorbunkov** [comment]
In my opinion, generated fields must have the following attributes:
* clearButtonVisible="true"
* fileNameVisible="true"

For example:
```xml
    <fileUploadField dataContainer="userDc"
                     property="document"
                     clearButtonVisible="true"
                     fileNameVisible="true"/>
```

Without these attributes, if I open the details view I will only see the Upload button and won't see if the file was uploaded and will not be able to download it.

See [Jmix docs](https://docs.jmix.io/jmix/flow-ui/vc/components/fileUploadField.html#_basics) for the example.
