### ISSUE TITLE
Implement putMapping operation for incremental index mapping updates inside search add-on

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#3218]
Currently, we rely on drop-create/recreate operations for updating index mapping properties. This is disruptive, especially for adding properties without removals, leading to inefficiencies.

Implement the putMapping operation for incremental index mapping updates. This would streamline the process, especially for non-disruptive changes aimed at extending the mapping.

Test Cases.

The prerequesites: 
1. Install the Elastic Search server or Open Search server
2. Create a project and create the index in accordance to the documentation(links below)
https://docs.jmix.ru/jmix/2.1/search/index.html
https://docs.jmix.ru/jmix/2.1/search/getting-started.html

Create the two entities and and the index definition:

@JmixEntitySearchIndex(entity = Order.class)
public interface OrderIndexDefinition {

    @AutoMappedField(includeProperties =
            {"number", "product", "customer.status", "customer.lastName"})
    void orderMapping();
}

as it desribed in the article above.

3. Put the setting into the settinigs file:
jmix.search.index-schema-management-strategy = create-or-update

Index politic can be:
jmix.search.index-schema-management-strategy = create-or-recreate
jmix.search.index-schema-management-strategy = create-or-update
jmix.search.index-schema-management-strategy = create-only
jmix.search.index-schema-management-strategy = none
4. Create some instances of the created entites
5. Install JMX console

Test 1.
1. Run the application
2. Recreate the indexies for the entity in JMX console
![image](https://github.com/user-attachments/assets/fe01bc17-2fbf-48c2-907f-013fb734d476)
3. Rerun the application
5. Open the search screen.
6. Try to search something
ER. Search is working

Test 2.
1. Stop the application
2. Add some additional field to the index definition (Field A)
3. Run the application
4. Add the extra entities' instances (Field B)
5. Open the Search screen
7. Try to search the "old" entity's instances(the entities that were added before the index extending)
ER: The entites should be in the search results but without the "Field A"
8. Try to search the new created entity's instances
ER: The entites should be in the search results with the "Field A" and the "Field B"

Test 3.
1. Stop the application
2. Delete some field from the index configuration
3. Run the application
4. Validate Index in JMX console - it should be IRRELEVANT.
5. Try to search something
ER: The entites should be in the search results with "Field A" and not in result with "Field B"

**Comment by SergeiAksenov2** [comment]
Test project:
[T3659.zip](https://github.com/user-attachments/files/17377788/T3659.zip)
Test 2 is not passed.

**Comment by fractal3000** [comment]
The implemenation of this issue is correct. Problem will be fixed within the https://github.com/jmix-framework/jmix/issues/3776 issue.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.5.SNAPSHOT6893-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)

**Comment by fractal3000** [comment]
The additional non-breaking change was implemented. Added in this issue IndexManager.putMapping method was removed from the IndexManager interface.
