### ISSUE TITLE
Generate Liquibase Changelog and other liquibase options are not an option when application.yml contains ENV vars

### ISSUE THREAD

**Issue by jguthrie100** [jmix-framework/jmix#3220]
### Environment

Jmix version: 2.2.0

### Bug Description

In a normal application.yml file where all values are hardcoded, then right-clicking the Main datastore will display a list of liquibase actions that can be performed
![image](https://github.com/jmix-framework/jmix/assets/4670502/a3ac654f-ba73-4845-8575-c6d92510216f)

However, if there are ENV vars in application.yml, then those options all disappear
![image](https://github.com/jmix-framework/jmix/assets/4670502/d1bffc67-6630-4bed-8a9d-bd3d06b640ad)

### Steps To Reproduce

Edit application.yml to contain ENV vars
i.e. 
![image](https://github.com/jmix-framework/jmix/assets/4670502/cc9530b4-479b-433e-b133-dac1bd252fd2)

### Current Behavior

Liquibase options are not displayed

### Expected Behavior

Liquibase options are displayed, that operate on the default values

**Comment by knstvk** [comment]
Use separate variables for database host and database name, for example:
```
main.datasource.url = jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:demo}
main.datasource.username = ${DB_USER:root}
main.datasource.password = ${DB_PASSWORD:root}
```

Then Studio will recognize the URL properly. See also the example in the [docs](https://docs.jmix.io/jmix/studio/data-stores.html).
