### ISSUE TITLE
IllegalArgumentException when using DTO entity list view template without Remove action

### ISSUE THREAD

**Issue by iudaev** [jmix-framework/jmix#3223]
### Environment

Jmix version: <2.2.1>

### Bug Description

Using the **DTO entity list view** template, causes exception:

> IllegalArgumentException: DataGrid has no API to obtain component list

Apparently this is due to the delegate that gets created in the view controller:

```
    @Install(to = "projectStatsesDataGrid.remove", subject = "delegate")
    private void projectStatsesDataGridRemoveDelegate(final Collection<ProjectStats> collection) {
        for (ProjectStats entity : collection) {
            // Here you can remove entities from an external storage
        }
    }
```

### Steps To Reproduce

1. Create a view using the **DTO Entity list view** template
2. Run the app and navigate to this view

**Comment by knstvk** [comment]
Cannot reproduce neither on 2.2.1 nor on latest 2.2.3. Could you attach a test project?

**Comment by iudaev** [comment]
Sorry, I missed a step. To reproduce, disable "remove" table action when creating a view:

<img width="584" alt="image" src="https://github.com/jmix-framework/jmix/assets/128021710/40e7f926-8f55-40a1-8dae-59cfe58fd73f">

Here is a test project:
[TestDtoList.zip](https://github.com/jmix-framework/jmix/files/15237510/TestDtoList.zip)

**Comment by gorbunkov** [comment]
See also #3245

**Comment by rusiaikinat** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6713-242
IntelliJ version: IntelliJ IDEA 2024.2.0.1 (Ultimate Edition)
Kotlin, Java
Addon project
