### ISSUE TITLE
Generate Liquibase Changelog doesn't work when schema is specified in an entity

### ISSUE THREAD

**Issue by jguthrie100** [jmix-framework/jmix#3230]
### Environment

Jmix version: 2.2.0

### Bug Description

The "Generate Liquibase Changelog" operation doesn't generate a new changelog for any entities that have the schema argument set in the @Table annotation

### Steps To Reproduce

1. Create a new JPA Entity
2. In the @Table annotation, add `schema = "test_schema"`
3. Run Generate Liquibase Changelog

### Current Behavior

A message pops up saying that the changelogs/model are up to date with the database

### Expected Behavior

Generate a changelog with the schema specified

**Comment by gorbunkov** [comment]
Will be implemented in Jmix Studio. See [Studio Issue](https://youtrack.jmix.io/issue/JST-1101).
