### ISSUE TITLE
WebDAV document download NPE

### ISSUE THREAD

**Issue by SergeiAksenov2** [jmix-framework/jmix#3234]
### Environment

Jmix version: 2.2.3

### Bug Description

NPE when try to download WebDAV document.

### Steps To Reproduce

![image](https://github.com/jmix-framework/jmix/assets/158277660/9ec2e470-107b-499c-a469-aaa9d718a95b)

1. Add WebDAV addon
2. Open WebDAV > WebDAV documents
3. Upload a file
4. Click to file version sign (pop-up opened)
5. Click 'Download' and select 'Download'

### Current Behavior

NPE
[webdav download NPE logs.txt](https://github.com/jmix-framework/jmix/files/15245749/webdav.download.NPE.logs.txt)

![image](https://github.com/jmix-framework/jmix/assets/158277660/2c1603af-21fa-4f6b-b351-455464c14270)

### Expected Behavior

A document is downloaded and saved.

### Sample Project

[jmix-flowui-smoke-test-master.zip](https://github.com/jmix-projects/jmix-flowui-smoke-test)

**Comment by Gavrilov-Ivan** [comment]
Not a WebDAV issue - see https://github.com/jmix-framework/jmix/issues/3277

**Comment by Gavrilov-Ivan** [comment]
Please test again

**Comment by SergeiAksenov2** [comment]
Tested on Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6464-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

A file can be downloaded in both options as file and as archive - Ok.
