### ISSUE TITLE
Add fields with user session data to User Sessions screen

### ISSUE THREAD

**Issue by maistrenkoIulia** [jmix-framework/jmix#324]
In cuba platform there are :
-id, login, user name, address, client info, active since, last used on
![image](https://user-images.githubusercontent.com/66992566/109514108-1b485700-7abf-11eb-9b98-4c488267d8d9.png)

In JMIX:
-session id, user name, last required
![image](https://user-images.githubusercontent.com/66992566/109513958-0b307780-7abf-11eb-9b83-e05ffe7d65ad.png)

(missed: login, address, client info, active since)

**Comment by gorbunkov** [comment]
Duplicates #322
