### ISSUE TITLE
Action aware view generation

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3245]
### Environment

Jmix version: 2.2.999-SNAPSHOT

### Bug Description

In the wizard for creating the master-detail view, there is the ability to select actions for the `DataGrid`.
If you remove the `edit` and `create` actions, the generated view will not be able to open, because handlers for these actions will remain in the controller. 

Affected view templates:
* Master-detail
* DTO views

![image](https://github.com/jmix-framework/jmix/assets/75516667/de0e57e3-ab85-4915-87ff-b86e7f67cb12)
![image](https://github.com/jmix-framework/jmix/assets/75516667/7dafe735-858c-48e0-89a5-00f9ffe96ce1)

Still available:
![image](https://github.com/jmix-framework/jmix/assets/75516667/e1dcc2eb-492d-4e75-b1d6-605263b4778a)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6719-241
IntelliJ version: IntelliJ IDEA 2024.1.1
