### ISSUE TITLE
Full page refresh when opening a menu item from top menu

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#3258]
When using `MainViewTopMenu`, when clicking on a link, a white screen appears before the screen loads.

**menu.xml**
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<menu-config xmlns="http://jmix.io/schema/flowui/menu">

    <item view="User.list" title="msg://com.company.jmixtopmenu.view.user/UserListView.title"/>

</menu-config>
```

**Result:**
![May-17-2024 10-58-32](https://github.com/jmix-framework/jmix/assets/47520144/afd6f545-cbae-48df-8d11-76fd840fd350)

**Project** - [jmix-top-menu.zip](https://github.com/jmix-framework/jmix/files/15344881/jmix-top-menu.zip)

**Comment by KremnevDmitry** [comment]
The reason: https://github.com/vaadin/flow-components/issues/1440

Workaround will be applied.
