### ISSUE TITLE
 When forming a long row, the height of the cell is not recalculated (port to 1.6)

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#3266]
See #1269

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6407-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6409-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

Test excel reports on short cells and on more than 700 symbols cells. Cells' height were recalculated – Ok.

![image](https://github.com/jmix-framework/jmix/assets/158277660/600cbaf6-8d86-46d2-b4df-a2258e60dca6)
