### ISSUE TITLE
There is no message for an exception FutureOrPresent / PastOrPresent

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#3278]
### Environment

Jmix version: 2.3.999-SNAPSHOT (last version 2.2.3)
Kotlin

### Bug Description

![image](https://github.com/jmix-framework/jmix/assets/114649487/65a7df55-6126-4aff-a475-8b93e837438f)
`jakarta.validation.constraints.FutureOrPresent.message`
`jakarta.validation.constraints.PastOrPresent.message`
### Steps To Reproduce

Steps to reproduce the behavior.
Create attributes localdatetime and OffsetDateTime
Set validation FutureOrPresent /PastOrPresent
```
  @PastOrPresent
    @Column(name = "DATE_TIME_IN_PAST", nullable = false)
    @NotNull
    var dateTimeInPast: LocalDateTime? = null

    @FutureOrPresent
    @Column(name = "DATE_TIME_IN_FUTURE")
    var dateTimeInFuture: LocalDateTime? = null

    @PastOrPresent
    @Column(name = "OFF_DATATIME_PAST")
    var offDatatimePast: OffsetDateTime? = null

    @FutureOrPresent
    @Column(name = "OFF_DATATIME_FUTURE")
    var offDatatimeFuture: OffsetDateTime? = null
```
Create Master-detail-view
Run project
Add values to the created entity

**Note**:  at the first validation, the text is present
![image](https://github.com/jmix-framework/jmix/assets/114649487/961ef070-feeb-4616-8d6d-5c8cb6719636)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6700-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6702-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)


If the condition is not met, the message text is displayed, not the exception - Ok.
