### ISSUE TITLE
Unfetched attribute with ManyToOne relation & postgres

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#328]
Attributes that present in fetch plan not fetched.
Possibly cached instance with lesser fetch plan used.

[EntityAndTest.zip](https://github.com/Haulmont/jmix-data/files/7845364/EntityAndTest.zip)

jmix 1.1.2
Postgres from official docker image

**QA Notes:**
1. Create new Jmix project
2. Unpack and add entity and Test to project.
3. Fix packages and imports.
4. Run test
**ER:**
All tests passed

**Comment by kendovitskii** [comment]
verified on 
1.3.SNAPSHOT4133-213
