### ISSUE TITLE
Data binding for HTML components

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix#3288]
In some cases usage of flowui components can be not enough to fit developer's requirements and java-side data assignments   to achieve simple display purposes may feel too verbose. So there should be a way to easily render context data into custom ui layout, e.g. to show label with localized field title or span with database entity field value.

Possible solutions:

1. Add property attribute support for all or most-used and suitable html components, e.g. for container-like ones: span, div, label, headings, lists etc.

2. Implement new component for data binded output or add data-binding to html/div componets only

**Comment by glebfox** [comment]
Implement generic XML element aka wrapper for HTML components.

**Comment by knstvk** [comment]
Add Studio annotations for `dataContainer` and `property` attributes.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6896-242
IntelliJ version: IntelliJ IDEA 2024.2.3
