### ISSUE TITLE
[Kotlin] The DTO detail view controller is not being created correctly

### ISSUE THREAD

**Issue by Gasloff** [jmix-framework/jmix#3298]
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6409-241

Create add-on
Create DTO entity
Create view for DTO

![image](https://github.com/jmix-framework/jmix/assets/8830197/0b204a78-5027-425c-b1b4-83a21bb728c4)

https://youtrack.jmix.io/issue/JST-4981

**Comment by rusiaikinat** [comment]
Reopened

![image](https://github.com/jmix-framework/jmix/assets/114649487/0be8a626-2254-42f8-81bb-4571b4131595)

The bug remained on the list views

**Comment by gorbunkov** [comment]
@rusiaikinat Works for me. Could you please check again?
