### ISSUE TITLE
Strange behavior when mappedSuperClass has no successor in the same project

### ISSUE THREAD

**Issue by artemy63** [jmix-framework/jmix#330]
Hi, I've faced the next problem.
In my add-on, I have one class that I've marked as "@MappedSuperClass" and want to extend in another project so it has no successors in the add-on. But my tests in which I'm trying to extend that class for entities failed with the strange exception that ID is null
```Internal Exception: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint;```
 
I've attached a simple project in which it is possible to reproduce an exception - 
[mappedsuperclass-troubles.zip](https://github.com/Haulmont/jmix-data/files/7969000/mappedsuperclass-troubles.zip)

What I've noticed:
- if in the main project I have a mappedSuperClass and some successor of it in the main project it is possible to create and save entity of successor to DB in tests
- if in the main project I have a mappedSuperClass and some successor of it in the main project, I'm able to create another successor of it in tests and save it to DB in tests
- if in the main project I have a mappedSuperClass without any successors in the main project I'm able to create a successor in test BUT not able to save it to DB because the mentioned exception
```
Query: InsertObjectQuery(com.company.mappedsuperclasstroubles.entity.SuccessorMainAloneTestEntity-1 [new,managed])
javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.9.6-jmix): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: NOT NULL check constraint; SYS_CT_10269 table: SUCCESSOR_MAIN_ALONE_TEST_ENTITY column: ID
Error Code: -10
Call: INSERT INTO SUCCESSOR_MAIN_ALONE_TEST_ENTITY (ID, TEST_BOOLEAN_VAL, TEST_INTEGER_VAL, TEST_LONG_VAL, TEST_STRING_VAL, VERSION) VALUES (?, ?, ?, ?, ?, ?)
	bind => [null, true, 100500, 42, what the hell going on?, 1]
Query: InsertObjectQuery(com.company.mappedsuperclasstroubles.entity.SuccessorMainAloneTestEntity-1 [new,managed])
	at app//org.eclipse.persistence.internal.jpa.EntityManagerImpl.flush(EntityManagerImpl.java:984)
	at app//io.jmix.eclipselink.impl.JpaDataStore.beforeSaveTransactionCommit(JpaDataStore.java:356)
	at app//io.jmix.core.datastore.AbstractDataStore.save(AbstractDataStore.java:229)
	at app//io.jmix.core.impl.UnconstrainedDataManagerImpl.saveContextToStore(UnconstrainedDataManagerImpl.java:257)
	at app//io.jmix.core.impl.UnconstrainedDataManagerImpl.save(UnconstrainedDataManagerImpl.java:216)
	at app//io.jmix.core.impl.UnconstrainedDataManagerImpl.save(UnconstrainedDataManagerImpl.java:135)
	```

**Comment by dtaimanov** [comment]
duplicated by  #317
