### ISSUE TITLE
Sorting is ignored when exporting from a DataGrid

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3315]
### Environment

Jmix version: 2.3.999-SNAPSHOT

### Bug Description

If you enable sorting on a `DataGrid` and then export, the data will not be sorted.
See related: #3316

### Steps To Reproduce

1. Open an attached project
2. Open TestEntitiesListView
3. Sort by the `number` column
4. Export all rows

### Current Behavior

![image](https://github.com/jmix-framework/jmix/assets/75516667/8b8258c9-ab90-44b2-b8da-54a94f65a804)

### Expected Behavior

UI:
![image](https://github.com/jmix-framework/jmix/assets/75516667/1eb31dc4-7da0-4121-a634-dd504afdc966)

### Sample Project

[test.zip](https://github.com/jmix-framework/jmix/files/15497585/master.zip)

**Comment by gorbunkov** [comment]
Default all records exporting uses the "keyset" pagination strategy (records are always sorted by a primary key). So it ignores the sorting defined on the screen. 

However, in Jmix 2.3, an additional "limit-offset" exporting strategy has been introduced. See the issue #3001.

If you set this new strategy, then sorting will be kept in the resulting excel file:

```
jmix.gridexport.export-all-pagination-strategy = limit-offset
```
