### ISSUE TITLE
Excel exporter duplicates some rows when the total count of exported rows exceeds the batch size and sorting is applied

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3316]
### Environment

Jmix version: 1.6.999-SNAPSHOT
See related: #3315

### Bug Description

When sorting is used, export occurs incorrectly.

### Steps To Reproduce

1. Open attached project
2. Open Test data for exports screen
3. Sort by `number` column
4. Export all rows

### Current Behavior

Number of records in the database:
![image](https://github.com/user-attachments/assets/8585e284-2422-4fce-ab3b-97c8079986bd)

Data is exported **twice**, 1001 rows should be exported: 
![image](https://github.com/jmix-framework/jmix/assets/75516667/a39d9a68-b793-4886-9b2f-d1f11f231cb7)

### Sample Project
[TestExportExcel.zip](https://github.com/jmix-framework/jmix/files/15497663/TestExportExcel.zip)

**Comment by Flaurite** [comment]
Jmix 1.6 introduces an export pagination strategy that takes into account the order of the rows. See https://github.com/jmix-framework/jmix/issues/3058.

Use the following application property:
```
jmix.gridexport.export-all-pagination-strategy=limit-offset
```

Jmix 2.x has the same fix for the problem. See related issue in the description.

**Comment by Flaurite** [comment]
Fixed the duplication of exported rows. The problem occurs when sorting is applied and the total count of rows exceeds the export batch size. **After the fix, the exporter, by default, does not consider column sorting**. To make the exporter take sorting into account, use `jmix.gridexport.export-all-pagination-strategy=limit-offset`, as I described above.
