### ISSUE TITLE
Ugly error page when user is not permitted to open view

### ISSUE THREAD

**Issue by alferink** [jmix-framework/jmix#3319]
### Environment

Jmix version: 2.2.3

### Bug Description

If the user opens a view for which he has no permissions, an ugly error page it shown. It lacks the information what has happened and it looks like it does not belong to the application. I am not sure if the is a bug or a feature request.

### Steps To Reproduce

1. Login  as user/user
2. Open User List View
3. Edit 1 user

### Current Behavior

An error page is shown. In production it says:
"Could not navigate to 'users/d0910ca8-a04c-c045-e5ff-cb9747d61694''
The page looks like a tomcat error page.

There is no hint, what is the reason (Reason: Access denied is only shown dev mode)

This is the page in dev mode:
![image](https://github.com/jmix-framework/jmix/assets/7936798/181a8096-84a4-4b6e-a558-609102a02384)

### Expected Behavior

The application shows a regular Jmix-View (e.g. ListView or MainView) and there is a proper error message.
Something like the message, when the entity is not found would be fine:

![image](https://github.com/jmix-framework/jmix/assets/7936798/6592573e-3f36-48ca-82fb-1850e163c26c)

### Sample Project

[url-permission-demo.zip](https://github.com/jmix-framework/jmix/files/15501580/url-permission-demo.zip)

**Comment by glebfox** [comment]
Hello,

> it looks like it does not belong to the application

The above error page is belong to the application and provided by Vaadin. 

To replace the default error page, you can extend it. For example, `RouteNotFoundError` is shown for **403** and **404** errors. To replace it, the following code can be used:

```
@ParentLayout(MainView.class)
public class CustomRouteNotFoundError extends RouteNotFoundError {

    @Override
    public int setErrorParameter(BeforeEnterEvent event,
                                 ErrorParameter<NotFoundException> parameter) {
        getElement().setText("My custom not found class!");
        return HttpServletResponse.SC_NOT_FOUND;
    }
}
```

Since, Jmix 2.3 `AccessDeniedException` will be thrown for **403**, so a separate error page can be shown.

I've created a doc issue: https://github.com/jmix-framework/jmix-docs/issues/783
