### ISSUE TITLE
Reports not found in RunListEntityReportAction

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#3322]
### Environment

Jmix version: 2.2.1

### Bug Description

`RunListEntityReportAction` selects displays runs reports only that have a parameter with the entity type of this view.

### Steps To Reproduce

1. Open a project with a report add-in.
2. Add a report for a list of entities.
3. Add the `RunListEntityReportAction` action to the list view
4. Click on the button with the `RunListEntityReportAction` action.

### Current Behavior

Reports not found!

<img width="1840" alt="image" src="https://github.com/jmix-framework/jmix/assets/47520144/3877fdc0-762d-4659-b40c-2efe7b49a42a">

### Expected Behavior

The report must be found and executed.

### Example

[report-action-error.zip](https://github.com/user-attachments/files/15509420/report-action-error.zip)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

**Comment by NikitaShchienko** [comment]
The current implementation of actions is implemented with required parameters. It is necessary to rewrite the logic so that you can connect `RunListEntityReportAction` without parameters.

**Comment by NikitaShchienko** [comment]
This is the default behavior. 

_io.jmix.reportsflowui.action.RunListEntityReportAction - a [standard action](https://docs.jmix.io/jmix/flow-ui/actions/standard-actions.html) for printing reports for entity instances associated with a list component (DataGrid, TreeDataGrid)._

_The action only selects reports having an external parameter of the **Entity** or the **List of entities** type and where the parameter entity type matches the entity type displayed by the list component. If only one report is available as a result of selection, it is invoked immediately. If several reports are available, their list is offered to the user for selection._

Docs: https://docs.jmix.io/jmix/reports/run-report.html
