### ISSUE TITLE
 CSS and Vaadin Errors in '2.3.999-SNAPSHOT'

### ISSUE THREAD

**Issue by Gamer08YT** [jmix-framework/jmix#3324]
### Environment

Jmix version: '2.3.999-SNAPSHOT'

### Bug Description

ListViews with the ItemDoubleClick event on the datagrid can no longer be opened.

In addition, various CSS classes are no longer bundled/imported.

### Steps To Reproduce

Just install current '2.3.999-SNAPSHOT' Version and add custom css and a ItemDoubleClick Listener to a DataGrid.

### Current Behavior

![image](https://github.com/jmix-framework/jmix/assets/31771657/7e8f9bab-c4ea-42fe-93c8-70e13fd1eb1a)

![image](https://github.com/jmix-framework/jmix/assets/31771657/871406c0-96a8-4371-a937-9b7cfb484c72)

### Expected Behavior

![WhatsApp Bild 2024-05-18 um 17 55 58_fd01c753](https://github.com/jmix-framework/jmix/assets/31771657/9698891e-5b47-4349-bf2a-add80d2d31be)

**Comment by Gamer08YT** [comment]
A downgrade to older versions fixes the error, a new upgrade to ‘2.3.999-SNAPSHOT’ causes the error to reappear.

I have been using ‘2.3.999-SNAPSHOT’ for a long time without any problems, the problems only occurred a few days ago

**Comment by glebfox** [comment]
@Gamer08YT thank you for reporting the issues. 

* The first one is related to changes made to injection mechanisms of Jmix and will be fixed after https://github.com/jmix-framework/jmix/pull/3336 is merged
* For the second one, I've created a separate issue: https://github.com/jmix-framework/jmix/issues/3347

----

For QA: check and close the issue after the above is merged

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6464-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6463-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

Double click to user 'admin' on UI. No error. Listener message in project logs - Ok.
