### ISSUE TITLE
Fix BPM process form template for Kotlin

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#3326]
### Environment

Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6385-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

### Bug Description

See Studio [ticket](https://youtrack.jmix.io/issue/JST-4978)

**Comment by SergeiAksenov2** [comment]
Tested on kolin:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6443-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6442-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

BPM process form template for Kotlin is fixed, no errors in class - Ok.

![image](https://github.com/jmix-framework/jmix/assets/158277660/b89bfe60-b9d8-4fe0-8da9-3780ee61c59d)
