### ISSUE TITLE
DataGrid columns cannot be extended

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#3332]
### Environment

Jmix version: 2.2.3

### Bug Description

You cannot add new columns by extending the view and add them to dataGrid -> columns element.

### Steps To Reproduce

Base view:
```
<dataGrid id="departmentsDataGrid"
          width="100%"
          minHeight="20em"
          dataContainer="departmentsDc">
    <actions>
        <action id="create" type="list_create"/>
        <action id="edit" type="list_edit"/>
        <action id="remove" type="list_remove"/>
    </actions>
    <columns resizable="true">
        <column property="name"/>
    </columns>
</dataGrid>
```

Extended view:
```
<dataGrid id="departmentsDataGrid">
    <columns>
        <column property="description"/>
        <column property="manager"/>
    </columns>
</dataGrid>
```

### Current Behavior

The data grid will contain only the last extended column: `manager`

### Expected Behavior

There should be three columns in the resulting data grid.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6462-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

Create project, entities, extending entity, extend view. Attributes of both entities (parent and extended) are present on the extended view - Ok.
