### ISSUE TITLE
Months localization in business calendar is not supported

### ISSUE THREAD

**Issue by tychkov** [jmix-framework/jmix#3337]
### Environment

Jmix version: 1.5.4

### Bug Description

Don't support month's localization in business calendar when annual holiday creating

### Steps To Reproduce

Set Russian locale.
Go to Administrations -> Business calendars, edit calendar instance. Create new holiday. In Holiday editor choose Annual holiday, and click Month's dropdown.
(Администрирование - Бизнес календари - выбираем календарь, создаем новый выходной, в Редакторе выходного дня выбираем Тип входного как эжегодный выходной.)

### Current Behavior

Look month's naming as English
![image](https://github.com/jmix-framework/jmix/assets/1845401/18f2cf4b-dae5-41fb-b8eb-7baefd9d00d6)

### Expected Behavior

Look month's naming as current locale (ru)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6719-241
IntelliJ version: IntelliJ IDEA 2024.1.1 

Month's localization is fine in the drop-list: 
![russmonth01](https://github.com/user-attachments/assets/d560eb00-c44b-4940-b964-c6f156eed9a1)

But in the grid it's still not localized: 
![russmonth02](https://github.com/user-attachments/assets/0d118e64-2744-47a2-af2f-28cebaa8143f)

**Comment by NikitaShchienko** [comment]
Fixed a problem with localization in grid.

A new message format has also been added to display the date value:
```
io.jmix.businesscalendarflowui.view.calendar/monthFormat=%s, %s
```

**Comment by konyashkina** [comment]
Re-tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.2-242
IntelliJ version: IntelliJ IDEA 2024.2.0.2 (Community Edition)
Passed.
