### ISSUE TITLE
Lumo imports from parent theme is ignored

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3347]
### Environment

Jmix version: 2.3-SNAPSHOTS

### Bug Description

Caused by: #3311
Reason: Due to Vaadin Flow 24.3.11+ changes.

### Steps To Reproduce

1. Start the app
2. Login
3. Take a look at Side menu

### Current Behavior

CSS class names from Lumo Utility and Badges additional styles are not applied, e.g.: Side menu has `<li>` bullets

![image](https://github.com/jmix-framework/jmix/assets/6077149/3143a997-39f6-401a-804b-d29747a9b294)

### Expected Behavior

Lumo imports are applied

**Comment by glebfox** [comment]
### Solution

`lumoImports` must be present in the result application theme, e.g:

```
{
  "parent": "jmix-lumo",
  "lumoImports":["typography","color","spacing","badge","utility"]
}
```

**Comment by glebfox** [comment]
Studio migrator issue: https://youtrack.jmix.io/issue/JST-5008/Migrator-to-Jmix-23-should-add-lumo-imports-to-project-theme

**Comment by SergeiAksenov2** [comment]
Tested on:
1)Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6460-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6458-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

File paths:
frontend/generated/jar-resources/frontend/themes/jmix-lumo/theme.json
frontend/themes/T3347-236/theme.json

lumoImports presents in both files. lumo presents in page stylies.
Side menu has has not bullets.
