### ISSUE TITLE
routeParameters for the Horizontal menu component are not passed

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#3348]
### Environment

Jmix version: 2.2.3

### Steps To Reproduce

1) Create Jmix project
2) Add a new item to the menu:
```
<item view="User.detail" title="Admin User">
            <routeParameters>
                <parameter name="id" value="60885987-1b61-4247-94c7-dff348347f93"/>
            </routeParameters>
        </item>
```
3) Create a new view with **Main view with top menu** template. Use this view as default main view

4) Launch the application

### Current Behavior

```
Could not navigate to 'users'
Reason: Cannot set route for non registered class com.company.prjhmenu.view.user.UserDetailView
```

### Sample Project

[prjhmenu.zip](https://github.com/user-attachments/files/15586101/prjhmenu.zip)

**Comment by KremnevDmitry** [comment]
Should be fixed in: https://github.com/jmix-framework/jmix/issues/3258

**Comment by KremnevDmitry** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Community Edition)

Not reproduced
