### ISSUE TITLE
DataGrid is invisible when it is placed inside Hbox.

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix#3357]
### Environment

Jmix version: <2.2.3-241>

### Bug Description

Add a default value to minWidth or other parameter to make DataGrid visible when it is placed inside Hbox. Or add a wizard which will guide a user how to enter the required parameters. Otherwise Datagrid is compressed and is not visible.

### Steps To Reproduce

Add DataGrid to hbox with default settings

### Current Behavior

![image](https://github.com/jmix-framework/jmix/assets/30234682/9954d049-2291-4cf6-ac7f-c45759af8a4e)

### Expected Behavior

DataGrid is visible

**Comment by gorbunkov** [comment]
When a dataGrid is being added using the Add component action in Studio, then the min-width=100px property must be added to the dataGrid.
