### ISSUE TITLE
Add “id” attribute to @ViewController annotation

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix#3358]
The value of @ViewController annotation is referenced as viewId in documentation, but it is not quite clear that this viewId is the value inside the annotation @ViewController("st_Individual.detail"). 
It should look like @ViewController(id = "st_Individual.detail")

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6861-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
