### ISSUE TITLE
Show notification to add ui-minimal role after new User is created

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix#3359]
The new application project contains the ui-minimal role that gives permissions to log in to UI and to open the main view. It is required to assign this role to new users that will interact with the application through the UI, otherwise they won’t be able to log in.

**Comment by SergeiAksenov2** [comment]
Tested on Kotlin and Java:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6861-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
