### ISSUE TITLE
Report template. Changing Output type doesn’t change the file extension in Output name pattern field

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix#3361]
### Environment

Jmix version: <2.2.3-241>

### Bug Description

When Output type is changed to DOCX from PDF, file extension in Output name pattern field remains PDF.
![image](https://github.com/jmix-framework/jmix/assets/30234682/fcd4dca3-656b-46dc-aa81-5a28c71ad2b9)

### Steps To Reproduce

Change report output type to DOCX from PDF,

### Expected Behavior

When report output type changed to DOCX from PDF, the file extention shoul be change accordingly.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

The file extention changes accordingly - Ok.
