### ISSUE TITLE
Fragment creation templates

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3373]

**Comment by glebfox** [comment]
Blocked by: https://youtrack.jmix.io/issue/JST-5029/Studio-prevents-creating-views-from-template-if-they-dont-have-screenId

**Comment by Fedoseew** [comment]
@glebfox, Studio issue is fixed, you can check

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6470-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6471-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)

User detail view has Fragment view with address - Ok.
