### ISSUE TITLE
JPQL Filter with Boolean parameter cannot be reset

### ISSUE THREAD

**Issue by timlehmkuhl** [jmix-framework/jmix#3374]
### Environment

Jmix version: 2.2.3

### Bug Description

I have a list view. In this list view there is a generic filter configuration with jpql. The parameter class is Boolean. I now have yes/no as a selection option. So only values with yes or no are displayed. However, there is no option to reset the value. This means that all entries are never displayed again.

### Steps To Reproduce

1.	Download and start demo project
2.	Open customer list view
3.	Use the “VIP JPQL” filter and select yes or no

### Current Behavior

Only filtered entries are displayed and there is no way to see all entries again

### Expected Behavior

Only filtered entries are displayed. In addition to yes/no, there is an empty option to reset the filter.  All values are then displayed again

### Sample Project

[booleanfilterdemo.zip](https://github.com/user-attachments/files/15740573/booleanfilterdemo.zip)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1
