### ISSUE TITLE
Adding attributes to a report band is getting slower with data model complexity

### ISSUE THREAD

**Issue by breakingfox** [jmix-framework/jmix#3379]
### Environment

Jmix version: 2.2.3

### Bug Description
With a large datamodel adding entity attributes to a band gets too slow

### Steps To Reproduce

1. Create a project with multiple linked entities with deep nesting.
2. Create a new report for list of this entity
3. Select any attribute to include in the report
4. After the report is created open the ‘Select entity attributes’ dialog for the report band
5. Click on the OK button (it is not necessary to select any attribute)

### Current Behavior

Currently saving attribute chages takes a lot of time

### Expected Behavior

Saving attributes should be quicker

### Sample Project
[Forum description](https://forum.jmix.io/t/adding-attributes-to-a-report-band-is-getting-slower-with-data-model-complexity/4964)
[JmixReporting.zip](https://github.com/user-attachments/files/15757565/JmixReporting.zip)

**Comment by gorbunkov** [comment]
See #1588
