### ISSUE TITLE
PivotTable add-on

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3383]
Based on https://pivottable.js.org/examples/

----

- [x] Web-component
- [x] Server-side component
- [x] Data binding
- [x] Support all component properties
- [x] Styling
- [x] Update d3 library
- [x] Localization support
- [x] Settings facet
- [x] Excel export

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6885-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
