### ISSUE TITLE
The list of entities is not sorted when creating the report

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#3385]
### Environment

Jmix version: 2.3.0-RC1

### Bug Description

![image](https://github.com/jmix-framework/jmix/assets/114649487/a45b88ac-c157-4006-bcfe-1990008bb97a)

### Expected Behavior

**Possible behavior**: group by package and show project entities at the beginning

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

Only project entities and report entities are available (in alphabetical order).

![image](https://github.com/user-attachments/assets/e6c234c3-cedd-4162-b793-132ba0193869)
