### ISSUE TITLE
jpqlFilter not set as query parameter in url

### ISSUE THREAD

**Issue by alferink** [jmix-framework/jmix#3387]
### Environment

Jmix version: 2.2.3

### Bug Description

I have a genericFilter with a jpqlFilter. When I set the jpqlFilter the value is not added to the url as query parameter.
This is necessary for the navigation to work properly.

### Steps To Reproduce

Worflow
1. Open customers
2. Set filter "Has order" in generic filter
3. Edit 1 customer
4. Save customer

### Current Behavior

After save all customers are displayed. The previous condition is lost.

### Expected Behavior

After save only customers with orders should be displayed. The previous condition in the filter should be set.

### Sample Project

[filter-url-demo.zip](https://github.com/user-attachments/files/15789392/filter-url-demo.zip)

**Comment by KremnevDmitry** [comment]
Duplicate: https://github.com/jmix-framework/jmix/issues/1767
