### ISSUE TITLE
JRBandDataDataSource null pointer exceprtion

### ISSUE THREAD

**Issue by wirbi7** [jmix-framework/jmix#3393]
### Environment

Jmix version: 2.2.3

### Bug Description

Null pointer exception then running a jasper reports template with vertical print order.

### Steps To Reproduce

Create jasper reports template. Add a subreport in a short frame. Send the data which overflow the frame.

### Current Behavior

Null pointer exception in JRBandDataDataSource next method on currentBand.getChildrenList() line.

### Expected Behavior

Report works perfectly.

**Comment by gmmars** [comment]
Hi
Could you please attach the report template.

**Comment by wirbi7** [comment]
[PishPortfolioA4.zip](https://github.com/user-attachments/files/15914029/PishPortfolioA4.zip)

**Comment by gmmars** [comment]
Is it possible to add the sample project? And what subreport causes the error?
