### ISSUE TITLE
Upgrade to Vaadin 24.4

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3395]

**Comment by glebfox** [comment]
Updated to **Vaadin 24.4.4**

**Added**

* `overlayWidth` attribute to `ComboBox`, `EntityComboBox`, `MultiselectComboBox` and `MultiselectComboBoxPicker` components
* `helperText` attribute to `Checkbox` component
* `ariaLabel` and `ariaLabelledBy` attributes to `IFrame` and `Section` components
