### ISSUE TITLE
Exclude @SystemLevel and @Secret properties from wildcard coverage

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3402]
### Environment

Jmix version: 2.x

### Bug Description

`@SystemLevel` and `@Secret` properties are included into indexing schema via wildcard.

### Steps To Reproduce

1. Create entity with properties annotated with `SystemLevel` and `Secret` annotations.
2. Create index definition for created entity, include all properties by using wildcard "*".
3. Check indexed data.

### Current Behavior

Properties and their data are present in index.

### Expected Behavior

Such properties should not be evaluated via wildcard (but should be via direct declaration).

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6789-241
IntelliJ version: IntelliJ IDEA 2024.1.6 (Community Edition)
2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6786-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)

The @SystemLevel and @Secret entity properties not in index.
