### ISSUE TITLE
Invalid localeDisplayName message keys for several translation add-ons

### ISSUE THREAD

**Issue by Gasloff** [jmix-framework/jmix#3407]
### Environment

Jmix version: 2.3.0.RC1

### Bug Description

Italian, Arabic and Romanian translation add-ons have `localeDisplayName.en` message key with local language name defined in core/messages_xx.properties file, instead of `localeDisplayName.it`, `localeDisplayName.ar` and `localeDisplayName.ro`

So this languages have names in english in Jmix UI:
![Screenshot 2024-06-20 at 18 23 03](https://github.com/jmix-framework/jmix/assets/8830197/562ac931-a9ea-4652-bb81-91f35dec210e)

**Comment by gorbunkov** [comment]
For Arabic translation, there is no `messages_ar.properties` for the **core** module. So there is no `localeDisplayName` property that I can change.
