### ISSUE TITLE
Support for Accessing and Interacting with Option Dialogs for UI Testing

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#3408]
In UI tests, it is common to encounter situations where production code includes Confirmation Dialogs or Option Dialogs. Currently, interacting with these dialogs (e.g., pressing OK or Cancel) is not well supported, creating a significant limitation in testing these UI components effectively. This issue aims to address this gap by providing the necessary support to verify the presence of and interact with Option Dialogs during UI tests.

### Proposed Solution
Based on the discussion with the @Flaurite, the solution should involve:

1. Internal Events for Dialogs:
Implement internal events in flow UI that signal when an option/confirmation dialog is opened or closed.
Potentially use application properties to enable these events during testing by default.
2. Test Bean for Managing Dialogs:
Create a test-specific bean in the UI test assist module that listens to these internal events.
This bean will collect references to opened dialogs and provide methods to interact with them (similar to how it was done in https://github.com/jmix-framework/jmix/issues/2147). Ensure the bean clears all dialogs before each test to maintain a clean state.
3. Static Methods in UiTestUtils:
Provide convenient static methods in UiTestUtils to access the test bean and interact with the collected dialogs.

### Example Usage

In the jmix-windturbines example there is a different project-specific implementation where the usage can be seen: 
* https://github.com/jmix-framework/jmix-windturbines/blob/8e3e54495d6793f8bd073d39dffcfaba5fe9dd91/src/test/java/io/jmix/windturbines/test_support/jmix/TestDialogs.java
* https://github.com/jmix-framework/jmix-windturbines/blob/6a1f20bb1738ccd9fd755fb58f9cee39b0d641b2/src/test/java/io/jmix/windturbines/view/inspection/InspectionFindingCardTest.java

**Comment by KremnevDmitry** [comment]
# API description

Added new application events:
- `io.jmix.flowui.event.dialog.DialogOpenedEvent`
- `io.jmix.flowui.event.dialog.DialogClosedEvent`

These events are published at the moment of opening and closing of the dialog, respectively.
In the standard usage scenario, these events are **not published** when the project is launched at **runtime**, but are **published** when test environment is launched.

To control the publishing of events, an application property has been added:
```properties
jmix.ui.component.dialogs-opened-change-events-enabled
```

Added a singleton bean that listens to events and stores information about them:
io.jmix.flowui.testassist.dialog.OpenedDialogs`

Bean provides two methods:
- `getDialogs()` - returns immutable list of opened `DialogInfos`
- `getLastDialog()` - returns the most recent opened `DialogInfo` or `null` if no opened dialogs

> The same API is available in the `io.jmix.flowui.testassist.UiTestUtils` helper class using static methods

Bean contains opened Dialogs in order of opening.
Example of the storage order of dialogs:
- first opened dialog has index `0`
- seconds opened dialog has index `1`
- ...
- last opened dialog has index `openedDialogs.size() - 1`

All open dialogs are closed after each test
