### ISSUE TITLE
Support for Accessing and Verifying Notifications for UI Testing

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#3409]
In UI tests, it is common to encounter scenarios where production code displays notifications to the user. Currently, there is no straightforward way to programmatically access these notifications to verify their content, type (e.g., Error, Success), or presence. This issue aims to address this limitation by providing the necessary support to access and verify notifications during UI tests.

### Proposed Solution
Based on the discussion with @Flaurite, the solution should involve:

1. Internal Events for Notifications:
Implement internal events that signal when a notification is shown or hidden.
Use application properties to enable these events during testing by default.
2. Test Bean for Managing Notifications:
Create a test-specific bean in the UI test assist module that listens to these internal events.
This bean will collect references to shown notifications and provide methods to access their content and type.
Ensure the bean clears all notifications before each test to maintain a clean state.
3. Static Methods in UiTestUtils:
Provide convenient static methods in UiTestUtils to access the test bean and interact with the collected notifications.
4. Manual Cleanup Methods:
Provide methods for manually closing or clearing notifications, as they might remain open in a test environment without client-side interaction.

### Example Usage

I created an example from a forum request: https://forum.jmix.io/t/checking-notifications-in-ui-test/5034/2. The implementation is different compare to the proposed solution, but it gives a good understanding on how to potentially use it: https://github.com/mariodavid/jmix-example-test-notifications

**Comment by KremnevDmitry** [comment]
# API description

Added new application events:
- `io.jmix.flowui.event.notification.NotificationOpenedEvent`
- `io.jmix.flowui.event.notification.NotificationClosedEvent`

These events are published at the moment of opening and closing of the notification, respectively.
In the standard usage scenario, these events are **not published** when the project is launched at **runtime**, but are **published** when test environment is launched.

To control the publishing of events, an application property has been added:
```properties
jmix.ui.component.notifications-opened-change-events-enabled
```

Added a singleton bean that listens to events and stores information about them:
`io.jmix.flowui.testassist.notification.OpenedNotifications`

Bean provides two methods:
- `getNotifications()` - returns immutable list of opened `NotificationInfos`
- `getLastNotification()` - returns the most recent opened `NotificationInfos` or `null` if no opened notifications

> The same API is available in the `io.jmix.flowui.testassist.UiTestUtils` helper class using static methods

Bean contains opened Notifications in order of opening.
Example of the storage order of notifications:
- first opened notification has index `0`
- seconds opened notification has index `1`
- ...
- last opened notification has index `openedNotifications.size() - 1`


# API usage example:

Origin view controller code:
```java
@Route(value = "my-view", layout = MainView.class)
@ViewController(id = "MyView")
@ViewDescriptor(path = "my-view.xml")
public class MyView extends StandardView {

    @Autowired
    private Notifications notifications;

    @Subscribe
    public void onReady(final ReadyEvent event) {
        notifications.create("Hello from MyView")
                .withType(Notifications.Type.SUCCESS)
                .show();
    }
}
```

Test class code:
```java
@UiTest
@SpringBootTest(classes = {UntitledApplication.class, FlowuiTestAssistConfiguration.class})
public class NotificationUiTest {

    @Autowired
    ViewNavigators viewNavigators;

    @Test
    void when_viewIsReady_then_notificationIsDisplayed() {
        // when:
        viewNavigators.view(UiTestUtils.getCurrentView(), MyView.class).navigate();

        // then:
        // use getLastOpenedNotification() to access the notification
        // that were created in the production code
        NotificationInfo notification = UiTestUtils.getLastOpenedNotification();

        assertThat(notification)
                .matches(notificationInfo -> Notifications.Type.SUCCESS.equals(notificationInfo.getType()))
                .extracting(NotificationInfo::getText)
                .matches(message -> message.equals("Hello from MyView"));
    }
```
