### ISSUE TITLE
Error start event doesn't have error definition field

### ISSUE THREAD

**Issue by stasmakarov** [jmix-framework/jmix#3415]
### Environment

Jmix version: <2.2.3>

### Bug Description

When designing an event subprocess with Error start event, it's impossible to set error definition for this event.

### Steps To Reproduce

Open Modeler, create any process with event subprocess
Add Error start event
-- there is no property 'Error' with pull down list of error definitions

<img width="467" alt="image" src="https://github.com/jmix-framework/jmix/assets/161338989/a4c205be-0f8d-4b3d-aec7-67efaa80da5a">

### Expected Behavior

The system must allow to set error definition for the Error start event

<img width="316" alt="image" src="https://github.com/jmix-framework/jmix/assets/161338989/bf41f3d2-1b14-499d-a142-835fbb27ad5a">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1
