### ISSUE TITLE
Incorrect alignment in generated columns for TreeDataGrid when using HBoxLayout

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3416]
### Environment

Jmix version: 1.6.999-SNAPSHOT

### Bug Description

When displaying treeDataGrid in generated columns containing HBoxLayout, some elements are shifted to the side.

### Current Behavior

![image](https://github.com/jmix-framework/jmix/assets/75516667/e720318a-26ef-4f61-97ba-39b51736a571)

### Expected Behavior

![image](https://github.com/jmix-framework/jmix/assets/75516667/d15ef7cf-8463-47e1-bd1f-f4fd3fa53c48)

### Sample Project
[tdg_test.zip](https://github.com/user-attachments/files/15950279/tdg_test.zip)

**Comment by glebfox** [comment]
It appears to be a client side error related to issues to calculate correct padding and margin in case of expanding a component inside a layout. 

The correct layout look as follows:

<img width="1508" alt="Screenshot 2024-07-05 at 13 29 00" src="https://github.com/jmix-framework/jmix/assets/6077149/40df5041-b64d-4b26-b4f1-4f19878a9f82">

Padding 48px: 36px bot button and 12px for spacing

Incorrect layout:

<img width="1462" alt="Screenshot 2024-07-05 at 13 29 30" src="https://github.com/jmix-framework/jmix/assets/6077149/a6be4a85-2952-40eb-820d-5de098c2860e">

Padding 12px: only for spacing. For some reason a button isn't included into calculation. 

The problem can be avoided on project side, by implementing a different layout based on CSS Flex, so no calculating of padding and margin are needed to expand a components inside.

```
CssLayout layout = uiComponents.create(CssLayout.class);
layout.setWidthFull();
htmlAttributes.applyCss(layout, "display:flex; gap:12px");
```

To expand TextField inside Flex container, just set **width=100%** for it.
