### ISSUE TITLE
NPE when open a process in BPM modeler

### ISSUE THREAD

**Issue by SergeiAksenov2** [jmix-framework/jmix#3417]
### Environment

Jmix version: 2.3.0
Jmix Studio plugin version: 2.3.NIGHTLY1361-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

### Bug Description

Open a process in BPM madeler cause the exception

### Steps To Reproduce

1. Add BPM addon
2. Run project
3. Go to BPM Modeler
4. Create process
5. Deploy process
6. Go to "Process definitions", select the process
7. Click the button "Open in modeler"

### Current Behavior

There is a NPE: Cannot invoke 'io.jmix.bpmflowui.uicomponent.bpmnmodeler.BpmnModeler.setBpmnXml(String)' because 'this.bpmnModeler' is null
![image](https://github.com/jmix-framework/jmix/assets/158277660/9873e4e7-c289-47d8-9e09-05f3ca863122)

![image](https://github.com/jmix-framework/jmix/assets/158277660/7e1a550c-6a21-403e-bd85-17ef77880994)

### Expected Behavior

Modeler view is opend.

**Comment by gorbunkov** [comment]
Caused by #3419

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6519-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.NIGHTLY1361-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

A process can be opened in Modeler through 'Process definitions' menu 'Open in modeler' - Ok.
