### ISSUE TITLE
Bind button and grid action when lazy tab is opened

### ISSUE THREAD

**Issue by ilushaaa** [jmix-framework/jmix#3423]
When lazy tab loads its components, buttons aren't bound with grid actions.

![image (1)](https://github.com/jmix-framework/jmix/assets/28649514/c4b704b9-f579-4740-82af-5e4daec456bb)

Set the actions to the appropriate buttons when the lazy tab is activated.

**Comment by knstvk** [comment]
See also [forum topic](https://forum.jmix.io/t/table-buttons-in-lazy-loaded-tabs-losing-their-actions/5316).

**Comment by SergeiAksenov2** [comment]
Tested on Java:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

Tested on Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

The buttons on the lazy tab have titles and actions - Ok.
