### ISSUE TITLE
Kanban board add-on

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#3431]

**Comment by KremnevDmitry** [comment]
Related Jmix Studio issues: 
* [JST-5173](https://youtrack.jmix.io/issue/JST-5173/The-action-ID-cant-be-resolved-if-the-XML-component-is-defined-using-namespaces)
* [JST-5174](https://youtrack.jmix.io/issue/JST-5174/The-ID-attribute-is-defined-as-component-ID-in-the-component-hierarchy-even-if-it-has-an-other-type)
* [JST-5175](https://youtrack.jmix.io/issue/JST-5175/The-PROPERTYREF-attribute-type-has-no-hints-in-XML)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6786-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)
