### ISSUE TITLE
Logout button ignores the server.servlet.context-path property

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3435]
### Environment

Jmix version: 2.3.0

### Bug Description

If the `server.servlet.context-path` is set, then Logout button redirects to the root URL ("/").

See [forum](https://forum.jmix.io/t/logout-ignoring-server-servlet-context-path/5122).

### Steps To Reproduce

1. Create new project
2. Set the application property:
```
server.servlet.context-path=/demo
```
3. Login with admin at http://localhost:8080/demo
4. Click the "Logout" button

### Current Behavior

The application redirects to the http://localhost:8080 instead of http://localhost:8080/demo

<img width="867" alt="Screenshot 2024-07-01 at 13 45 04" src="https://github.com/jmix-framework/jmix/assets/7888486/5cb4be19-d7f8-473e-8ed8-244c04c31ab1">

### Expected Behavior

The login view is displayed.

### Workaround

The workaround is to define the extended Flowui security configuration in the project:

```java
import com.google.common.base.Strings;
import io.jmix.flowui.view.View;
import io.jmix.securityflowui.security.FlowuiVaadinWebSecurity;
import jakarta.servlet.ServletContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.stereotype.Component;

@Component
public class ExtFlowuiVaadinWebSecurity extends FlowuiVaadinWebSecurity {

    private static final Logger log = LoggerFactory.getLogger(ExtFlowuiVaadinWebSecurity.class);

    private ServletContext servletContext;

    @Autowired
    protected void setServletContext(ServletContext servletContext) {
        this.servletContext = servletContext;
    }

    @Override
    protected void initLoginView(HttpSecurity http) throws Exception {
        String loginViewId = uiProperties.getLoginViewId();
        if (Strings.isNullOrEmpty(loginViewId)) {
            log.debug("Login view Id is not defined");
            return;
        }
        Class<? extends View<?>> controllerClass =
                viewRegistry.getViewInfo(loginViewId).getControllerClass();
        String contextPath = servletContext.getContextPath();
        if (!contextPath.startsWith("/"))
            contextPath = "/" + contextPath;
        setLoginView(http, controllerClass, contextPath);
    }
}
```

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6530-241
IntelliJ version: IntelliJ IDEA 2024.1.1
