### ISSUE TITLE
Support trim attribute for TextField

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3437]
Source: [forum](https://forum.jmix.io/t/textfield-not-trimming-white-space-in-jmix-2/5132)
Similar to Classic UI - https://docs.jmix.io/1.x/jmix/1.5/ui/vcl/components/text-field.html#trim

**Comment by KremnevDmitry** [comment]
`TextArea` component is also supported

**Comment by glebfox** [comment]
@KremnevDmitry create doc issue

**Comment by KremnevDmitry** [comment]
Jmix Studio issues: 
* [JST-5277](https://youtrack.jmix.io/issue/JST-5277/Support-application-property-aware-meta-property-default-value)
* [JST-5278](https://youtrack.jmix.io/issue/JST-5278/Migrator-to-24-should-add-trim-enabled-application-property)

Doc issue: https://github.com/jmix-framework/jmix-docs/issues/861

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6816-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)
2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6809-241
IntelliJ version: IntelliJ IDEA 2024.1.6 (Community Edition)

Trim is supported - Ok.
