### ISSUE TITLE
RichTextEditor doesn't display button icons

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3443]
### Environment

Jmix version: 2.3.0

### Bug Description

Since Jmix 2.3.0 RichTextEditor doesn't display button icons. Presumably due to an update of the Vaadin version.

Reason: https://github.com/vaadin/flow/issues/19645

### Steps To Reproduce

Add RichTextEditor on a view

### Current Behavior

<img width="964" alt="Screenshot 2024-07-02 at 17 46 21" src="https://github.com/jmix-framework/jmix/assets/6077149/90a5f10f-dffd-466d-9f96-6f467796756b">

### Expected Behavior

<img width="981" alt="Screenshot 2024-07-02 at 17 40 20" src="https://github.com/jmix-framework/jmix/assets/6077149/a761f49e-4504-4e9c-86c5-c6de5c1d0b1d">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6567-241
IntelliJ version: IntelliJ IDEA 2024.1.1
