### ISSUE TITLE
Entity Inspector - Show mode field is too short

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix#3445]
### Environment

Jmix version: 2.3.0

### Bug Description

The "Show mode" field in Entity Inspector is too short, though there are lots of horizontal space.
It cannot contain english or russian caption.

### Steps To Reproduce

Create fresh project (data tools add-on will be included).
Start app.
Open Entity inspector page.
Pay attention to "Show mode" field.

![image](https://github.com/jmix-framework/jmix/assets/6158807/7b04845a-a089-4d6a-8ca4-a1064b791a59)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1
