### ISSUE TITLE
Authentication is not set in AuthenticationEventListener

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix#3447]
### Environment

Jmix version: <2.3.0>

### Bug Description
In standard User entity add new field
    @Transient
    private String language;

In AuthenticationEventListener
add the following lines of code
User user = (User) currentAuthentication.getUser();
user.setLanguage(currentAuthentication.getLocale().getLanguage().toLowerCase());
 
Run the project 
Error Authentication is not set. Use SystemAuthenticator in non-user requests like schedulers or asynchronous calls.

**Comment by gorbunkov** [comment]
We need to check this and either fix the problem or explain in the documentation.

**Comment by knstvk** [comment]
Using `CurrentAuthentication` in the `AuthenticationSuccessEvent` listener is impossible because this event is sent too early in the authentication process and the bean will throw an exception or return a previous authentication object.

Added a warning to the docs.
