### ISSUE TITLE
Support path-style bucket addressing in AWS file storage

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3448]
In Jmix 2.3 we increased AWS SDK version from 2.16.x to 2.25.x.

In 2.18.x AWS SDK started using virtual host-style addressing when including an endpoint override. See [AWS SDK documentation](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-s3.html).

This caused problems for some s3 compatible storages. For example, [minio](https://min.io/) stopped working with AWS Files Storage add-on after upgrading from Jmix 2.2 to 2.3 (see [forum](https://forum.jmix.io/t/aws-filestorage-nosuchbucketexception/5147)).

We also had requests to support path-style bucket access previously: #2893

It seems that we may introduce the application property that will enable the `.forcePathStyle(true)` for the S3 client of the AWS SDK.

**Comment by gorbunkov** [comment]
`jmix.awsfs.use-path-style-bucket-addressing=true` application property should be used to force the client to use the path-style bucket addressing.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT 
IntelliJ version: IntelliJ IDEA 2024.1.1
