### ISSUE TITLE
JMX Console view passes method argument values in random order

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3449]
### Environment

Jmix version: 2.3.0

### Bug Description

In JMX Console view provided by Jmix, method argument values are passed in random order.

### Steps To Reproduce

Create a simple management bean with a method that has several arguments:

```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jmx.export.annotation.ManagedOperation;
import org.springframework.jmx.export.annotation.ManagedOperationParameter;
import org.springframework.jmx.export.annotation.ManagedOperationParameters;
import org.springframework.jmx.export.annotation.ManagedResource;
import org.springframework.stereotype.Component;

@ManagedResource(description = "MySample MBean", objectName = "jmix.sample:type=MySample")
@Component("MySampleManagementFacade")
public class MySampleManagementFacade {

    public static final Logger log = LoggerFactory.getLogger(MySampleManagementFacade.class);

    @ManagedOperation(description = "Test method 1")
    @ManagedOperationParameters({
            @ManagedOperationParameter(name = "param1", description = "Param 1"),
            @ManagedOperationParameter(name = "param2", description = "Param 2"),
            @ManagedOperationParameter(name = "param3", description = "Param 3"),
            @ManagedOperationParameter(name = "param4", description = "Param 4")})
    public String method1(String param1,
                          String param2,
                          String param3,
                          String param4
                          ) {
        String result = "param1=" + param1 +
                " param2=" + param2 +
                " param3=" + param3 +
                " param4=" + param4;
        log.info("Result: {}", result);
        return result;
    }
}
```

Run the application and invoke this method using the JMX Console view.

### Current Behavior

Parameter values are passed in random order, e.g. value entered for `param4` is set to `param1`.

<img width="1365" alt="Screenshot 2024-07-04 at 13 06 26" src="https://github.com/jmix-framework/jmix/assets/7888486/7f59eccb-8aac-4b2b-892c-12051b64cea3">

### Sample Project

[jmix-random-order.zip](https://github.com/user-attachments/files/16096222/jmix-random-order.zip)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6563-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6571-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

Parameters and their values are passed in valid order - Ok.
