### ISSUE TITLE
Wrong storage of OffsetDateTime in HSQL

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#345]
#### Problem:
OffsetDateTime stored incorrectly in HSQL database: stored time is 4 hour ahead of real time (timezone is +4). At the same time there is no such problem for postgres. 

see [project](https://app.zenhub.com/files/285283915/f238b345-a28e-4814-831a-17a9f532b2d2/download)

#### Investigation:
Date stored in `TimestampData` seems to be correct: seconds in local time (GMT+4), zone is GMT+4 at `org.eclipse.persistence.internal.databaseaccess.DatabaseAccessor#executeDirectNoSelect:942`(2.7.9-4-jmix)
inside `statement.delegate.parameterValues`, but Insert statement generated incorrectly during `executeUpdate()` invocation (see second and third date): 
```
INSERT INTO JMOFDT_NEW_ENTITY VALUES('9069c59f-683b-9e72-8f6a-13aedb46fe5f',1,'admin','2021-10-12 19:40:22.764000',NULL,'2021-10-12 23:40:22.764000+4:00','2021-10-12 23:40:22.764000+4:00',NULL,NULL,NULL,NULL)
```
![изображение.png](https://images.zenhubusercontent.com/5ed6636766d0991824e90fb6/b70be2fa-ad9a-424e-9bfc-62d42b5b1be3)

**Comment by rusiaikinat** [comment]
Jmix version: 1.6.999-SNAPSHOT
![image](https://github.com/jmix-framework/jmix/assets/114649487/4cf69648-d447-4dc4-a655-cffd1b4928b5)

Jmix version: 2.3.999-SNAPSHOT
![image](https://github.com/jmix-framework/jmix/assets/114649487/89bab059-a577-45b7-aaca-fcbf3917993a)
