### ISSUE TITLE
Filter by DateTime property doesn't show time part of value

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#3452]
### Environment

Jmix version: 2.3.0

### Bug Description

Generic filter (and property filter) recognizes the DateTime attribute incorrectly - without time part:

<img width="731" alt="image" src="https://github.com/jmix-framework/jmix/assets/5513878/5f02c833-c86b-4287-8f50-b62782cdadfe">

### Steps To Reproduce

- Create an entity with DateTime attribute:
    ```
    @Column(name = "DATE_TIME_FIELD")
    @Temporal(TemporalType.TIMESTAMP)
    private Date dateTimeField;
    ```

- Create views and try to filter by this attribute.

### Current Behavior

The filter doesn't allow you to enter time for the property.

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1
