### ISSUE TITLE
BPM: Jmix form params equals NULL when the form is opened in Navigate mode 

### ISSUE THREAD

**Issue by stasmakarov** [jmix-framework/jmix#3453]
### Environment

Jmix version: 2.3.0

### Bug Description

When Jmix view process form has parameters, for example 
params = {
        @Param(name = "variableName"),
        @Param(name = "entityPickerCaption")
}

and a form is opened in 'Navigate' mode (This tab),
values of the parameters are equal NULL

### Steps To Reproduce

1. Create a process:
<img width="451" alt="image" src="https://github.com/jmix-framework/jmix/assets/161338989/993f97a3-cfd6-45ca-a660-f472067603f9">

2. Set Task 1 properties:
<img width="479" alt="image" src="https://github.com/jmix-framework/jmix/assets/161338989/5af09ee9-0a50-4bd8-8b4f-3cb2f9870d9b">

3. Create Jmix view form with parameters (see attached file)

4. Set Task 2 properties -- the same like Task 1, but Open mode = This tab:
<img width="482" alt="image" src="https://github.com/jmix-framework/jmix/assets/161338989/72f86e26-71dc-4ebc-8daf-4468c76302a8">

5. Deploy the process

### Current Behavior

1. Start the process
2. Open Task 1 -- params values are OK:
<img width="917" alt="image" src="https://github.com/jmix-framework/jmix/assets/161338989/dae77781-a4df-475e-a77a-69585a0c8c8b">

3. Open Task 2 params are nulls:
<img width="915" alt="image" src="https://github.com/jmix-framework/jmix/assets/161338989/324dc1c2-339b-428e-a37b-abe374aa5096">

When using params in code, it will cause NPE.

### Expected Behavior

Parameters are passed from the form properties, not nulls.

## QA notes
The problem also exists for the start form and a fix has been done for this case as well.

**Comment by mbucan** [comment]
Please check implementations of openStartProcessForm and openTaskProcessForm of the
io.jmix.bpmflowui.processform.ProcessFormViews interface, and their usage in StartProcessView and InputDialogTaskProcessForm. 

When I move from 2.2.3 to 2.3, I get problems with opening, probably due to the breaking changes "Navigation Requires Origin View" and "Navigation to BPM Process Forms"

Kind regards,
Mladen

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1
