### ISSUE TITLE
Quartz RunningJobCache works wrong in some cache implementation

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3454]
### Environment

Jmix version: 2.3

### Bug Description

https://forum.jmix.io/t/joblistener-quartz-jobexecutionlistener-threw-exception/5130

There are two issues in this `RunningJobsCache` that occur with some cache implementation like Hazelcast or Redis (but works with default one):

- `RunningTriggersWrapper `- cache value that is used for accumulation of currently running triggers - is not Serializable. That causes runtime issue.
- Updated `RunningTriggersWrapper` is not properly put back to the cache. Because of that job status doesn't change in UI.

Additional suggested changes:

- Evict entire wrapper from cache if there are not more triggers in it after invalidation
- Add invalidateAll method
- Add JMX facade for Quartz addon with cache management operations

### Steps To Reproduce

Steps to reproduce the behavior.

1. Enable Hazelcast as a cache provider
2. Create job with notable execution time.
3. Check job execution

### Current Behavior

Runtime exception with serialization issue.
UI not reflecting state changes (visible after fix of serialization issue)

### Expected Behavior

Cache should work properly with different cache implementations.

**Comment by Gavrilov-Ivan** [comment]
Changes:

- General fix of the cache
- Added additional invalidation methods to `RunningJobsCache`: 
   - `invalidate(JobKey)` - invalidate all running triggers for provided job key
   - `invalidateAll()` - invalidate entire cache
- Added JMX service with ability to manage `RunningJobCache` (`jmix.quartz:type=RunningJobsCache`)
- Added property to disable usage of `RunningJobsCache` - `jmix.quartz.running-jobs-cache-usage-enabled`. True by default.
- Added additional check if job is running via Scheduler. But it's not cluster aware.

For QA:

- Use Hazelcast as a cache provider (https://docs.jmix.io/jmix/deployment/k8s.html#hazelcast-configuration)
- Use job class with significant duration of execution (20-30sec)
- Use job class with and without `@DisallowConcurrentExecution` annotation
- Check single trigger case 
- Check multiple triggers case with overlapping execution time

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6580-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

Two class jobs, with the @DisallowConcurrentExecution annotation and without the one.
Two triggers for each jobs. Make crossing triggers. 
There is no Paused status in the automatic mode of jobs - Ok.
