### ISSUE TITLE
The report ignores fetchplan and selected entity attributes

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#3455]
### Environment

Jmix version: 1.6.0-RC1

### Steps To Reproduce 1
1. Create a user with all the attributes filled in

2. Create - Using wizard 
- User
- table
- report for list of entities

3. Select attributes...
- Username
- FirstName

4. Finish creating the report

Open templates -> select template
Add attribute `lastName`
![image](https://github.com/jmix-framework/jmix/assets/114649487/bd47a93b-55cb-483b-b1f9-92c506559732)

5. Run report
![image](https://github.com/jmix-framework/jmix/assets/114649487/7c905396-5659-46b1-b56d-0ea831946f2c)

### Current Behavior
The attribute `lastName` is filled in, although it was not selected in the attributes screen
![image](https://github.com/jmix-framework/jmix/assets/114649487/56185cf1-6b19-4b3b-a3a5-c3f39db3c0fc)

### Steps To Reproduce (continuation) 2
1.Create fetchPlan 
  ```  
<fetchPlan entity="User" name="user-fetch-plan">
        <property name="firstName"/>
        <property name="lastName"/>
    </fetchPlan>
```
2. Select display items from fetchPlan
![image](https://github.com/jmix-framework/jmix/assets/114649487/a8967d20-3f00-4e57-864d-55328dd8b88a)
3.Run report
![image](https://github.com/jmix-framework/jmix/assets/114649487/0edc729d-742a-47e8-a063-462653526e74)

### Current Behavior 2
UserName is missing in fetchPlan, but is present in the selection

**Comment by gorbunkov** [comment]
There is no harm in loading additional fields. We won't spend time on this issue.
