### ISSUE TITLE
Production build fails with new Vaadin version

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix#3456]
### Environment

Jmix version: 2.4.999

### Bug Description

Production build fails while development is fine

### Steps To Reproduce

1. Build jmix from master into local maven repo 
2. Create new project with 2.4.999 framework version selected
3. Run build or bootBuildImage with -Pvaadin.productionMode=true

`
./gradlew build -Pvaadin.productionMode=true
`

### Current Behavior

Fails with the following error:

`
> Task :vaadinBuildFrontend FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinBuildFrontend'.
> com.vaadin.flow.server.ExecutionFailedException: Failed to configure Hilla engine: no runner succeeded. Set log level to debug to see more details.

`

### Expected Behavior

Builds successful

**Comment by gorbunkov** [comment]
Will be fixed in #3459
