### ISSUE TITLE
Exclude Hilla dependencies in project template

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3459]
> The **Hilla framework** has been more closely integrated with the Vaadin platform. Vaadin BOM and Vaadin Spring Boot Starter now include the Hilla framework stating from version 24.4. This enables Vaadin users to choose between Flow and Hilla, or mix both frameworks when necessary.

Since we don't use Hilla views in Jmix apps, it's make sense to exclude Hilla dependencies in project template.

**Comment by glebfox** [comment]
`./gradlew -Pvaadin.productionMode=true bootJar` produces exception:

```
> Task :vaadinBuildFrontend FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':vaadinBuildFrontend'.
> com.vaadin.flow.server.ExecutionFailedException: Failed to configure Hilla engine: no runner succeeded. Set log level to debug to see more details.
```

**Comment by KremnevDmitry** [comment]
For QA:

Test the running of the project. Build and running jar: `./gradlew -Pvaadin.productionMode=true bootJar`

**Comment by KremnevDmitry** [comment]
Relates Jmix Studio issue: [JST-5268](https://youtrack.jmix.io/issue/JST-5268/Migration-to-24-should-update-the-buildgradle-file)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6810-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)
Ok.
