### ISSUE TITLE
User settings Facet throws exception when Logout is performed

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3460]
### Environment

Jmix version: 2.3.0

### Bug Description

Source: [forum](https://forum.jmix.io/t/v2-3-0-illegalstateexception-on-logout-w-save-settings-facet/5163)
Cause: https://github.com/jmix-framework/jmix/issues/3226

Due to changes in logout logic, User settings Facet throws exception when Logout is performed, because `authentication.getUser()` has no access to authentication object.

### Steps To Reproduce

1. Enable user settings facet on any view, e.g. user-list-view
2. Change any DataGrid settings, e.g. reorder columns, sort a column
3. Click Logout button

### Current Behavior

An exception is thrown

```
Caused by: java.lang.IllegalStateException: Authentication is not set. Use SystemAuthenticator in non-user requests like schedulers or asynchronous calls.
```

### Expected Behavior

No exception is thrown

----

**Note**: settings are not saved if a view is closed because Logout is performed. This is expected behavior and may be changed when https://github.com/jmix-framework/jmix/issues/2749 is implemented.

**Comment by SergeiAksenov2** [comment]
Tested on Java:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6563-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

Tested on Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6564-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)
