### ISSUE TITLE
Only Date input in Datetime field in filter

### ISSUE THREAD

**Issue by SergeiAksenov2** [jmix-framework/jmix#3461]
### Environment

Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6563-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

### Bug Description

Incorrect Date and Datetime formats in the Generic Filter on UI

### Steps To Reproduce

1. Create Jmix project.
2. Create an entity with Datetime attribute.
3. Run the project.
4. Open entity list view.
5. Add filter conditions for Datetime attribute - No time input.

### Current Behavior

The Datetime condition has only Date input and there is no Time input.

![image](https://github.com/jmix-framework/jmix/assets/158277660/1a62b5c4-4a2b-45c5-87ac-a8d0e46ca74e)

### Expected Behavior

The Datetime condition has two inputs.

**Comment by gorbunkov** [comment]
Duplicates #3452
