### ISSUE TITLE
Add more informative log for incorrect detail actions usage

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3464]
If add actions with "detail_" prefix in standard view or list view in runtime we will get `ClassCastException: "View cannot be cast to StandardDetailView"`. 

This is not an explicit exception and it is not clear why it occurred.

Also see Studio issue: https://youtrack.jmix.io/issue/JST-5128/Inspection-for-detail-view-actions

**Comment by gorbunkov** [comment]
It will be hard to implement
