### ISSUE TITLE
Add errorMessage attribute for twinColumn in meta annotations

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3465]
See Studio issue: https://youtrack.jmix.io/issue/JST-5099/Add-item-errorMessage-menu-for-twinColumn

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6567-241
IntelliJ version: IntelliJ IDEA 2024.1.1
