### ISSUE TITLE
Update page styles in index.html to avoid extra scroll problem on mobile devices

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3469]
Using VH length units leads to extra scroll on mobile device because the visible area changes dynamically as you scroll (known [issue](https://bugs.webkit.org/show_bug.cgi?id=141832)).

Problem can be solved by changing page styles in the `index.html` file:

Replace

```
<style>
  body, #outlet {
    height: 100vh;
    width: 100%;
    margin: 0;
  }
</style>
```

with

```
<style>
  html, body, #outlet {
    height: 100%;
    width: 100%;
    margin: 0;
  }
</style>
```

**Comment by glebfox** [comment]
For QA: check that newly created projects have adjusted styles in the `index.html` file

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6866-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
