### ISSUE TITLE
Incorrect value typing for MultiValueSelectAction

### ISSUE THREAD

**Issue by SergeiAksenov2** [jmix-framework/jmix#3470]
### Environment

Jmix version: 2.3.0

### Bug Description

Can not enter value more than 999 to Filter Number field

### Steps To Reproduce

1. Create a project
2. Run the project
3. Go to entity list view > Filter > Add search condition > Number (Integer) > "in" or "not in"
4. Try to fill this field values more than 999 (with comma in result)

![image](https://github.com/jmix-framework/jmix/assets/158277660/be79f0cb-eff7-4908-b753-6c303563fa74)

### Current Behavior

Unexpected error appears

![image](https://github.com/jmix-framework/jmix/assets/158277660/30e737d1-30e2-4f0e-bd80-f88221715511)

Logs:
[filter error logs.zip](https://github.com/user-attachments/files/16142148/filter.error.logs.zip)

### Expected Behavior

The Number field is filled.

### Sample Project

Any project

**Comment by glebfox** [comment]
Relates to: https://github.com/jmix-framework/jmix/issues/1442

**Comment by KremnevDmitry** [comment]
The reason is a typing error when adding values ​​to the collection on the MultiValueSelectDialog.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Java 
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6584-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Kolin
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6580-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)
