### ISSUE TITLE
Add pagination to entity inspector

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#3480]
The Entity Inspector component in Jmix currently loads all records from the database when an entity is selected. This behaviour can cause the Java application to collapse, leading to 100% CPU usage and making the server unresponsive when dealing with large databases or entities with many rows and columns. This was not an issue in Jmix 1 and the CUBA Platform, as both had pagination support in the Entity Inspector.

**Comment by KremnevDmitry** [comment]
Partly blocker by: #3490

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1
