### ISSUE TITLE
Namespace mapping problem in docx4j dependency

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#3483]
### Environment

Jmix version: 2.3.0
See: https://github.com/jmix-framework/jmix/issues/3482

### Bug Description

Latest version of MS word is adding the namespace - [http://schemas.microsoft.com/office/wor ... l/word16du](http://schemas.microsoft.com/office/word/2023/wordml/word16du) - and it is creating a problem when an edit happens to the file using docx4j. When using such files in YARG, the user receives the message - Word Found unreadable Content’

After migrating YARG to Jmix, you need to update the version in the Reports Add-on

Forum: https://forum.jmix.io/t/report-yarg-dependencies-breaking-docx-ouput-issue/5192
Issue: https://www.docx4java.org/forums/docx-java-f6/new-namespace-mapping-issue-t3112.html

See: https://github.com/cuba-platform/yarg/issues/183

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6866-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
