### ISSUE TITLE
FilterCondition operation not translated correctly 

### ISSUE THREAD

**Issue by timlehmkuhl** [jmix-framework/jmix#3485]
### Environment

Jmix version: 2.3.0

### Bug Description
In the group filter configuration, I can select the translated AND or OR operation  for the root group conditions. This selection is translated (e.g. German “UND”, “ODER”). The selected operation is then displayed under Conditions. It then says AND or OR instead the translated operations.

### Steps To Reproduce
1.	Open Demo Project
2.	Open Customers List
3.	Edit the Filter “Test Group Filter”

### Current Behavior
The root filter condition operation is named “AND” with German translation

![grafik](https://github.com/user-attachments/assets/940f2fc1-9c88-4949-977b-4cf917b4feb2)

It seems, that the attribute “localizedLabel” in entity “FilterCondition” is not set correctly.

### Expected Behavior
The filter condition operation is named “UND” with German translation.

### Sample Project

[filterdemo.zip](https://github.com/user-attachments/files/16235454/filterdemo.zip)

**Comment by glebfox** [comment]
For QA: check several translations

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1 
with  several jmix translation addons
