### ISSUE TITLE
Add Settings facet to Reports Run view

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#3487]
Originates from [forum topic](https://forum.jmix.io/t/order-reports-run/5203).

**Comment by gorbunkov** [comment]
Group may be empty. We can add the **settings** facet to the screen.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6700-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6702-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

Settings facet is working on the Reports Run view.
