### ISSUE TITLE
CodeEditor can't be enabled if it was disabled before

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3488]
### Source
Forum topic: [link](https://forum.jmix.io/t/code-editor-enable-disable-does-not-work/5221)

### Environment

Jmix version: 2.3.1

### Bug Description

If `CodeEditor` component has been disabled, then `codeEditor.setEnabled(true)` has no effect.

### Steps To Reproduce

1. Add `CodeEditor` component to any view
2. Set `enabled` property to `false`
3. Open the view
4. Switch`enabled` property to `true`
5. Try to type in the `codeEditor`

### Current Behavior

The text can't be typed.

### Expected Behavior

The component has enabled and it is possible to type text.

### Temporary workaround:

1. Use the `readOnly` property instead of `enabled`
2. After setting `enabled` to `true` call the following code
   ```java
   codeEditor.setEnabled(true);
   // text area activation
   codeEditor.getElement().executeJs(
       "$0._editor.textInput.getElement().removeAttribute('disabled');"
   );
   ```

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6634-241
IntelliJ version: IntelliJ IDEA 2024.1.1
