### ISSUE TITLE
Changelog Generation Error: User has no attribute applicable for table id column for new Kotlin project

### ISSUE THREAD

**Issue by valery-shinkevich** [jmix-framework/jmix#3489]
### Environment

Jmix version: 2.3.1

### Bug Description

liquibase.exception.CommandExecutionException: com.haulmont.jmixstudio.exceptions.SilentException: Entity ru.company.test_jmix_kotlin.entity.User has no attribute applicable for table id column

### Steps To Reproduce

Create new Full-Stack Application (Kotlin) Jmix project. Run Jmix Application, then press Execute and proceed to apply changelog. Got Changelog Generation Error.

### Expected Behavior

Application started without any exceptions.

### Sample Project

[test_jmix_kotlin.zip](https://github.com/user-attachments/files/16263250/test_jmix_kotlin.zip)

**Comment by valery-shinkevich** [comment]
Sorry, it is'nt reproduce on latest IDEA Community.
I've been using GIGA IDE for a while now.

It was reproduced on GIGA IDE 2024.1.1 (Community Edition)
Build #IC-241.15989.150, built on June 24, 2024
Runtime version: 17.0.10+1-b1207.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

io.jmix.studio (2.3.1-241)
com.haulmont.amplicode (2024.1.4-241-EAP)
Kotlin: 241.15989.150-IJ

**Comment by glebfox** [comment]
**For QA:** check case and create Studio issue.

**Comment by rusiaikinat** [comment]
Cant' reproduce:
Ubuntu22
attached project
Jmix version: 2.3.1
Jmix Studio plugin version: 2.3.3-241
IntelliJ version: GIGA IDE 2024.1.1 (Community Edition)

New project
Jmix version: 2.3.3
Jmix Studio plugin version: 2.3.3-241
IntelliJ version: GIGA IDE 2024.1.1 (Community Edition)
com.haulmont.amplicode (2024.2.1-241-EAP)

Win10
Jmix version: 2.3.1
Jmix Studio plugin version: 2.3.3-241
IntelliJ version: GIGA IDE 2024.1.1 (Community Edition)
GIGA IDE 2024.1.1 (Community Edition)
Build #IC-241.15989.150, built on June 24, 2024
com.haulmont.amplicode (2024.2.1-241-EAP)
Windows 10.0
