### ISSUE TITLE
GenericFilter condition with URL query parameters facet is added endlessly

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3490]
### Environment

Jmix version: 2.4.999-SNAPSHOT

### Bug Description

Probably after: #3419
Adding generic filter conditions loops.

### Steps To Reproduce

Steps to reproduce the behavior.

1. Create a snapshot project
2. Run the project
3. Open the `UserListView`
4. Add any condition

### Current Behavior

The condition is added endlessly.

### Expected Behavior

The condition is added only ones.

**Comment by glebfox** [comment]
See also Vaadin issue: https://github.com/vaadin/flow/issues/19580

**Comment by glebfox** [comment]
Fixed in: https://github.com/vaadin/flow/pull/19736 by providing a new API
Wait for: https://github.com/jmix-framework/jmix/issues/3704 and pass `false` to `com.vaadin.flow.component.page.History#replaceState(elemental.json.JsonValue, com.vaadin.flow.router.Location, boolean)`

**Comment by rusiaikinat** [comment]
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6826-242
IntelliJ version: IntelliJ IDEA 2024.2.2 (Ultimate Edition)
Kotlin, Java
