### ISSUE TITLE
Selected side menu item has no border radius

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3496]
### Environment

Jmix version: 2.3.0

### Bug Description

Selected side menu item has no border radius.

https://github.com/jmix-framework/jmix/blob/master/jmix-flowui/flowui-themes/src/main/resources/META-INF/resources/themes/jmix-lumo/component/jmix-list-menu.css#L97

`JmixListMenu` uses `--lumo-border-radius` which has been replaced by:

* `--lumo-border-radius-s` - Checkbox, badge, date-picker year indicator, etc.
* `--lumo-border-radius-m` - Button, text field, menu overlay, etc.
* `--lumo-border-radius-l` - Dialog, notification, etc.

### Steps To Reproduce

Click any side menu item.

### Current Behavior

No border radius

<img width="256" alt="Screenshot 2024-08-02 at 23 12 41" src="https://github.com/user-attachments/assets/518cdaad-0881-4935-82bd-2c85e9dfb779">

### Expected Behavior

Same border radius as for the other components. Use `--lumo-border-radius-m`

<img width="257" alt="Screenshot 2024-08-02 at 23 12 52" src="https://github.com/user-attachments/assets/317094be-b5ee-468b-a4f7-229902d08bae">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1
