### ISSUE TITLE
Configure export options for the Grid export action

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3497]
Jmix version: 2.3.1

When the user uses the excel export action, the dialog shows several buttons:

* All rows
* Current page
* Selected rows

In some cases, users don't need all these options. See [forum](https://forum.jmix.io/t/excel-export-action-disable-selected-rows-option/2534).

<img width="1236" alt="image" src="https://github.com/user-attachments/assets/9f373495-b520-416e-a74c-3fd06778bf60">

We may add a setting to the export action that will configure which buttons should be dispalayed in the dialog and probably the buttons order.

**Comment by gorbunkov** [comment]
See also https://github.com/jmix-framework/jmix/issues/3263

**Comment by KremnevDmitry** [comment]
For QA:

See PR comment: https://github.com/jmix-framework/jmix/pull/3665#issue-2497132966

**Comment by glebfox** [comment]
@KremnevDmitry doc issue

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6816-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)
2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6809-241
IntelliJ version: IntelliJ IDEA 2024.1.6 (Community Edition)

Export options are available.
