### ISSUE TITLE
Ability to add a single component inside PropertyFilter

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3501]
See Studio issue: https://youtrack.jmix.io/issue/JST-4876/Ability-to-add-a-single-component-inside-PropertyFilter

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6644-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6653-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)
