### ISSUE TITLE
Get rid of protected modifier in project template

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3505]
`LoginView` and `User` classes have `protected` modifier on some fields and methods. This makes no sense, since these classes are scaffolded and breaks uniformity, e.g. `id` and `version` attributes are `private`, while other attributes are `protected`.

**Comment by SergeiAksenov2** [comment]
Tested on Kotlin and Java
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6856-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
