### ISSUE TITLE
Adjust space and alignment between icon and text in DropdownButton and ComboButton components

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3508]
1. Adjust space between icon and text in `DropdownButton` and `ComboButton` components to match the same space in `Button`

<img width="714" alt="Screenshot 2024-07-23 at 10 54 24" src="https://github.com/user-attachments/assets/f64ce3e8-07c3-404f-8b7c-0bfa03938db0">
<img width="261" alt="Screenshot 2024-07-23 at 10 54 18" src="https://github.com/user-attachments/assets/45f5a115-16f7-496b-a3eb-642943eb0365">

2. Make `ActionItem` center its content

<img width="230" alt="Screenshot 2024-09-16 at 12 21 58" src="https://github.com/user-attachments/assets/db194b16-a20a-4114-9eed-819d50b2b754">

3. Make Vaadin icon button same size as Lumo

<img width="268" alt="Screenshot 2024-09-16 at 12 54 32" src="https://github.com/user-attachments/assets/6784fcb5-3760-40a6-bdf4-693e614ba517">

**Comment by glebfox** [comment]
Before:
<img width="232" alt="Screenshot 2024-09-16 at 13 19 49" src="https://github.com/user-attachments/assets/e58d962f-c5d9-4f12-a8bc-0e09b0b3f2fc">


After:
<img width="239" alt="Screenshot 2024-09-16 at 13 16 55" src="https://github.com/user-attachments/assets/e9305a69-19c3-4f6e-ac1c-7fb9850ffa72">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6892-242
IntelliJ version: IntelliJ IDEA 2024.2.3
