### ISSUE TITLE
Horizontal scrolling appeared in the "Report creation" window

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#3511]
### Environment

Jmix version: 2.3.1

### Bug Description

![image](https://github.com/user-attachments/assets/7b11544f-0b88-4c23-aab1-1af1bf4c80ce)

### Steps To Reproduce
Reports-> Create -> Using wizard

### Expected Behavior
There should not be any horizontal scrolling

**Comment by glebfox** [comment]
Use `align-items=STRECH`

**Comment by glebfox** [comment]
It looks like your project doesn't have `lumoImports` in the `theme.json` file. See https://github.com/jmix-framework/jmix/issues/3347.

Actual Wizards looks like below:

<img width="760" alt="Screenshot 2024-08-12 at 23 11 23" src="https://github.com/user-attachments/assets/be58e462-dceb-4acd-b2b3-3ac90cb215fe">

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6695-242
IntelliJ version: IntelliJ IDEA 2024.2 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6682-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
3) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6694-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

There is no any horizontal scrolling with page scale is from 25% to 500%.
