### ISSUE TITLE
Upgrade to Gradle 8.10.2

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3524]
See [release notes](https://docs.gradle.org/8.10/release-notes.html)

**Comment by glebfox** [comment]
Studio migration issue: https://youtrack.jmix.io/issue/JST-5053/Migrator-for-Jmix-24-should-upgrade-Gradle-wrapper-version-to-88

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6876-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)

**case 1: new project creation**
AR: Gradle 8.10

**case 2: migration**
AR: Gradle 8.10.2

**Comment by Gasloff** [comment]
Changed version in project templates to 8.10.2 (new project creation)

**Comment by konyashkina** [comment]
Re-tested on 
Jmix Studio plugin version: 2.4.SNAPSHOT6892-242

A new project created with gradle 8.10.2 version.
