### ISSUE TITLE
Incorrect number of records when using dataManager.getCount()

### ISSUE THREAD

**Issue by reloadall** [jmix-framework/jmix#3528]
### Environment

Jmix version: 1.5.5

### Bug Description

When using dataManager.getCount(LoadContext<?> context), if there are filtering conditions based on list attributes in the context, an incorrect JPQL is generated
`select distinct count(e) from Entity e join e.list ls where ls.a = :a`

### Possible Cause

The order of calling applyCount() and applyDistinct() in io.jmix.data.impl.JpqlQueryBuilder#buildResultQuery.

### Possible Solution

Swap the calls of applyCount() and applyDistinct() (call applyDistinct() first and then applyCount()). In this case, the JPQL becomes:
`select count(distinct e) from Entity e join e.list ls where ls.a = :a`
and returns the actual number of entities.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6682-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6697-242
IntelliJ version: IntelliJ IDEA 2024.2 (Community Edition)

With the condition "query.setDistinct(true);" the result of counting = 1. Ok.

[T3528-241j.zip](https://github.com/user-attachments/files/16624116/T3528-241j.zip)
