### ISSUE TITLE
OnDeleteInverse in composition applies despite missing Soft Deletion in both entities

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3536]
### Environment
Jmix version: 2.3.1

### Description
See RU forum topic: https://forum.jmix.ru/t/kaskadnoe-udalenie-pri-svyazi-odin-k-odnomu/1914

We have AEntity and BEntity with composition relation (one-to-many).
Both are hard entities (no soft deletion)
BEntity has `@OnDeleteInverse(DeletePolicy.CASCADE)`

When we delete AEntity, all related BEntity will be deleted too. Despite missing soft deletion.

It does not work if we will remove `OnDeleteInverse` and will add `OnDelete`. And it is correct behavior.

Studio issue for clarifying description of FK constraint action field: https://youtrack.jmix.io/issue/JST-5191/FK-constraint-action-field-in-entity-designer-should-clarify-that-it-applies-for-Soft-Deletion-entities

### Demo Project
Attached project: [release-demo-2-3-x.zip](https://github.com/user-attachments/files/16454037/release-demo-2-3-x.zip)

**Comment by knstvk** [comment]
Works as designed, now explained in the docs:

https://docs.jmix.io/jmix/data-model/entities.html#on-delete-inverse

> For regular hard-deleted entities, @OnDeleteInverse with CASCADE and UNLINK values is handled by Studio when generating Liquibase changelogs. It must be used only on the owning (the one with the @JoinColumn annotation) side of the relationship and leads to creating a foreign key constraint with the ON DELETE CASCADE or ON DELETE SET NUll parameters.
