### ISSUE TITLE
Missing action and buttons in composite screen

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#3537]
From Jmix Studio [ticket](https://youtrack.haulmont.com/issue/JST-5180/Missing-action-and-buttons-in-composite-screen)

### Environment

Jmix version: 2.3.1
Jmix Studio plugin version: 2.4.SNAPSHOT6630-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Ultimate Edition)

### Steps To Reproduce
Create 2 entities with a one-to-many composite connection
Create a view for entities
Open a view descriptor with a one-to-many connection

### Current Behavior

A dataGrid has been created for a related entity, but no actions have been created to work with it

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.1
Jmix Studio plugin version: 2.3.SNAPSHOT6668-241
IntelliJ version: IntelliJ IDEA 2024.1 (Ultimate Edition)
2) Jmix version: 2.3.1
Jmix Studio plugin version: 2.3.SNAPSHOT6674-242
IntelliJ version: IntelliJ IDEA 2024.2 (Ultimate Edition)

Action and buttons are present - Ok.

![image](https://github.com/user-attachments/assets/8f5ae2c2-4f01-4912-9620-d8adb04089e3)
