### ISSUE TITLE
Fragment doesn't initialize itself in lazy tabs

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3544]
### Environment

Jmix version: 2.3.0

Source: [forum](https://forum.jmix.io/t/fragments-inside-lazy-loaded-tabs/5308)

### Bug Description

If fragment placed inside a lazy tab, it doesn't send its own lifecycle events and doesn't autowire fields.

### Steps To Reproduce

1. Create a fragment and subscribe on its `ReadyEvent` (not the host one)
2. Place it inside lazy tab
3. Open view and switch to the lazy tab

### Current Behavior

Fragment doesn't send its own lifecycle events and doesn't autowire fields.

### Expected Behavior

Fragment send all its events and autowire fields.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6696-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6697-242
IntelliJ version: IntelliJ IDEA 2024.2 (Community Edition)

Injection in Fragments works correctly. Fragment handler ‘OnInit’ is executed when lazy tab is opened.
