### ISSUE TITLE
BPM Modeler: None Start Event: Business key property is visible only with forms

### ISSUE THREAD

**Issue by stasmakarov** [jmix-framework/jmix#3545]
### Environment

Jmix version: 2.3.1

### Bug Description

Business key field is available only when Input dialog form is selected and can be set only as process variable

### Steps To Reproduce

Open BPM Modeler
Select Start event
-- Initially the  'Business key' field is not visible.
Change Form property to Input dialog
-- 'Business key' field appeared

### Expected Behavior

1. Business key field is available for all types of start events (none, message, signal, timer)
2. The value of Business key can be set as following: direct value, process variable, expression

If the entity variable is set as business key, its instance name must be used.

**Comment by gorbunkov** [comment]
When we set business key for start events with forms we **have data** that may be used as s business key: we have field values.

In case of none, message, signal, timer there is no such data available. For example, when the process is started with timer start event, no fields or process variables exist in the process instance at that moment. Setting a "direct value" as a business key does not make sense to me in this case.
