### ISSUE TITLE
ExcelExporter rounds the fractional part of the number to four decimal places

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3548]
### Environment

Jmix version: 2.3.1

### Bug Description

ExcelExporter rounds the fractional part of the number to four decimal places.

See [forum topic](https://forum.jmix.io/t/download-excel-value-6-decimal-will-round-up-to-4-decimal/5332).

### Steps To Reproduce

* Create an entity with a BigDecimal attribute.
* Set scale to 6

```
@Column(name = "SOME_NUM", precision = 19, scale = 6)
private BigDecimal someNum;
```

* Add decimalFormat to messages_en.properties
```
decimalFormat = #,##0.######
```
* Generate view and add the Excel export action to the view.
* Create an order and enter the BigDecimal field with 6 digits in fractional part.
* Export data to excel

### Current Behavior

The value in excel is rounded to 4 digits after comma.

![image](https://github.com/user-attachments/assets/bcee95a4-c6c0-49d7-89ee-51d2689edede)

### Expected Behavior

The value should not be rounded

### Sample Project

[export-decimal.zip](https://github.com/user-attachments/files/16510473/export-decimal.zip)

**Comment by ilushaaa** [comment]
The decimal formatter defines how decimal values are displayed in UI components, such as Grid.
`
decimalFormat = #,##0.######
`

The Excel exporter has its own cell formatters.
`
excelExporter.decimalFormat=#,##0.###
`

Even if we set a custom Excel cell formatter, we can still see the original value.
![image](https://github.com/user-attachments/assets/098d7351-8e22-40aa-9b76-042589c803a0)

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

ExcelExporter rounds to six decimal places - Ok.
