### ISSUE TITLE
Support DataGrid SelectionEvent with Subscribe annotation

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3552]
Jmix version: 2.3.1

Currently, DataGrid selection listener can only be added this way:

```
    usersDataGrid.addSelectionListener(selectionEvent -> {
        Set<User> allSelectedItems = selectionEvent.getAllSelectedItems();
        log.info("Selected items: {}", allSelectedItems);
    });
```

We should support it using the `@Subscribe` annotation:

```java
@Subscribe("usersDataGrid")
public void onUsersDataGridSelected(final SelectionEvent<DataGrid<User>, User> event) {
    Set<User> allSelectedItems = event.getAllSelectedItems();
    log.info("Selected items2: {}", allSelectedItems);
}
```

See [forum](https://forum.jmix.ru/t/poluchat-selectionevent-dlya-datagrid-cherez-annotaczii/1922)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6861-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
