### ISSUE TITLE
Support extended out-of-the-box search functionality

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3553]
Restore functionality of CUBA FTS (eng\rus analysis, contains\starts with search based on input value syntax) as an OOB funcionality of Search addon.

# Expected updates
## Search strategies:

- _Starts With_ - search by prefix. Based on Edge NGram + regexp (in case of input text longer than max NGram length, can be disabled via settings)
- _Phrase_ - match all search terms in provided order.
- _Any term any field_ - match any of search terms independently.

## UI

- Support runtime Search Strategy selection within SearchField (context menu/settings popup). 
- Optional: Support runtime Search Entity selection.

## Configuration
This functionality should be able to be enabled per Index.
If enabled it generates special extended mappings so it prevents from using custom mapping.

**Comment by Gavrilov-Ivan** [comment]
## Changes
### `@ExtendedSearch` annotation
Optional annotation that can be applied on Index definition interface.
Provides functionality of `Starts with` search by creating additional "virtual" subfields (for each "real" field) to store prepared prefix terms. 
Also applies additional analysis (filter and analyzer) configuration to be used by those subfields.
This analyzer generates all prefixes from min to max length for every indexed word and store them in prefix subfields. The more difference between min and max - the more prefixes is generated for word (if it's long enough). Better search, but more index space consuming. 
Min and max value can be configured via app properties `jmix.search.minPrefixLength` / `jmix.search.maxPrefixLength`
These pre-indexed prefixes significantly increase performance of prefix search in comparison with wildcard/regex query.
#### Parameters

- `enabled`: allows to disable extended search functionality without removing the annotation. Default: **true**.
- `tokenizer`: defines tokenizer to be used in prefix analyzer. Default: **whitespace**.
- `additionalFilters`: defines additional analysis filters to be used in prefix analyzer besides 'lowercase' and 'edge N-gram' (this one generates prefix terms). Default: _none_

### Search strategies (breaking changes)
`allTermAnyField` and `allTermSingleField` have been removed due to little utility (can be reimplemented on project side if required).
`startsWith` has been added. It actually makes sense if `ExtendedSearch` is enabled for at least one index, so if it doesn't this strategy can be hidden by setting `jmix.search.unsupportedSearchStrategyVisible` to false.

#### Starts with
This strategy provide `starts with` search by using prefix subfields (generated by `ExtendedSearch` analyzer) as a target search fields.
Additionally it can use wildcard query if input search word is longer than max length of pre-indexed prefixes. This behavior can be configured by application property `jmix.search.wildcardPrefixQueryEnabled`.

### `SearchField` (UI)
SearchField UI component now has option to define size, entities to search and search strategy in runtime via additional settings button. Corresponding xml attributes are still available and defines initial values.
New attributes have been added:

- `settingsButtonVisible`: show/hide settings button. Default: **true**.
- `searchButtonVisible`: show/hide search button: Default: **true**.

### Index settings & Analysis configuration (breaking changes)
Index settings and analysis configuration are divided into separate builders (but still in the single configurer).

- For index settings (not for analysis) use `getCommonIndexSettingsBuilder` (applies to all indexes) or `getEntityIndexSettingsBuilder` (applied to some specific index).
- For analysis settings use `getCommonAnalysisBuilder` or `getEntityAnalysisBuilder`.

### Application properties

- `jmix.search.minPrefixLength` / `jmix.search.maxPrefixLength`: defines min-max length of generated prefix terms. If the length of the input search word is beyond these limits prefix search will not be able to find anything (unless `jmix.search.wildcardPrefixQueryEnabled` is set to true or it matches the exact word). Default: **min=3**, **max=8**.
- `jmix.search.wildcardPrefixQueryEnabled`: allows to perform wildcard query if search by prefix terms can't be performed due to the length of the input search word. Default: **true**.
- `jmix.search.unsupportedSearchStrategyVisible`: Show / hide additional search strategy provided by ExtendedSearch (Starts with) if there are no index definitions with enabled Extended search. Default: **false**.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6866-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)

**Comment by Gavrilov-Ivan** [comment]
New changes (original comment also has been updated):

- **Search strategies**: `allTermAnyField` and `allTermSingleField` strategies are not removed but deprecated and hidden in UI. No more breaking changes.
- **Index settings & Analysis configuration**: previous API is saved and deprecated. It works as before until new API is used (then ignored). No more breaking changes.
- **Application property** `jmix.search.unsupportedSearchStrategyVisible` is discarded.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.5.SNAPSHOT6908-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
