### ISSUE TITLE
User with limited permissions can choose all entities in Dynamic Atrributes config view without limitations

### ISSUE THREAD

**Issue by vfadeevGit** [jmix-framework/jmix#3555]
A user with limited permissions on the entities in the project can manipulate Dynamic Attributes without user permissions limitations. Supposed behavior - the list of entities should be limited to those the user can work within the assigned role. Now - the user can manipulate all entities without applying permission constraints. It seems not consistent because the Data Tools add-on, as a similar admin tool, applies current user role permissions when observing entity attributes of the project.

**Comment by gorbunkov** [comment]
Entity inspector is a generic screen for working with data, its not an admin tool. Dynamic attributes, audit and similar addons were made for admins. Permissions are give for entity operations (READ, CREATE, etc.). What permissions are expected to be taken into account in Dynamic attributes screen?
