### ISSUE TITLE
Required Combobox with value set still marked as invalid when added programmatically 

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3557]
### Environment

Jmix version: 2.3.1

### Bug Description

If a required combobox with a value set is added by button click handler then it is marked as invalid.

### Steps To Reproduce

Add Combobox programmatically when a button is clicked, e.g.:

```
@Autowired
private UiComponents uiComponents;

@Subscribe(id = "testBtn", subject = "clickListener")
public void onTestBtnClick(final ClickEvent<JmixButton> event) {
    JmixComboBox<String> comboBox = uiComponents.create(JmixComboBox.class);
    comboBox.setRequired(true);
    comboBox.setLabel("Test");
    comboBox.setItems("One", "Two", "Three");
    getContent().add(comboBox);
    comboBox.setValue("Two");
}
```

### Current Behavior

If a required combobox with a value set is added by button click handler then it is marked as invalid:

<img width="229" alt="Screenshot 2024-08-11 at 00 29 24" src="https://github.com/user-attachments/assets/bb6a5d57-03fe-4682-b748-8fca37d87918">

Same code executed in InitEvent listener works as expected.

### Expected Behavior

Combobox isn't marked as invalid since it has value set

**Comment by Flaurite** [comment]
Related Vaadin issue: https://github.com/jmix-framework/jmix/issues/3557

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2_ Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

The Required Combobox is not marked as invalid -  Ok.
