### ISSUE TITLE
Actions are not added for DataGrid component related to composite attribute for DetailView template

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3561]
### Environment

Jmix version: 2.3.1

### Bug Description

Actions are not added for DataGrid component related to composite attribute

### Steps To Reproduce

1. Create an entity with composite attribute one-to-mane
2. Create DetailView for this entity including composite attribute

### Current Behavior

Actions selected during creation process are **not** added to a view

### Expected Behavior

Actions selected during creation process are added to a view

**Comment by ilushaaa** [comment]
Duplicate with #3537
