### ISSUE TITLE
Dynamic Attribute of type Enumeration/Collection does not save value to the entity

### ISSUE THREAD

**Issue by pbaris** [jmix-framework/jmix#3569]
### Environment

Jmix version: 2.3.1

### Bug Description

Having a Dynamic Attribute of type Enumeration/Collection, the value is not saved in the entity

![image](https://github.com/user-attachments/assets/67048d76-9fee-45af-bdcb-fd249dbff23c)

### Steps To Reproduce

![jmix_dynatrr_collection](https://github.com/user-attachments/assets/a6bb34ce-787c-497c-ac94-11abf32514fe)

**Comment by pbaris** [comment]
Looking in the database i saw that values are stored, so i think the problem is not on save, but on loading the saved value in the field.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

Dynamic Attribute of type Enumeration/Collection can be saved to the entity - Ok.
