### ISSUE TITLE
Transformation code is not saved in the report

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#3577]
### Environment

Jmix version: 2.3.0

### Bug Description

A description of what the bug is.

### Steps To Reproduce

1. Create a new project with the Reports Add-on
2. Open a report
3. Add a parameter with the Transformation code
4. Add 'Transformation' groovy-script
![image](https://github.com/user-attachments/assets/cee58fbe-18aa-47b5-bf51-03e9ae4b05bc)
6. Save the parameter

### Current Behavior

The parameter doesn't display a groovy-script. 

### Expected Behavior

The Groovy-script was successfully saved

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

The Transformation text appears when reopen the Report parameter form - Ok..
