### ISSUE TITLE
Add application property to disable initial form validation

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3585]
Source: [forum](https://forum.jmix.io/t/how-to-disable-initial-form-validation/5352)

Currently, when a field is bound to an entity attribute and this attribute is mandatory, validation is triggered from `setRequiredIndicatorVisible`, e.g.:

```
@Override
public void setRequiredIndicatorVisible(boolean requiredIndicatorVisible) {
    super.setRequiredIndicatorVisible(requiredIndicatorVisible);

    fieldDelegate.updateInvalidState();
}
```

As a result a view is opened with error messages which may scare users :-)

Add application property to disable initial form validation, so even required validation is triggered by form submitting.

**Comment by rusiaikinat** [comment]
Kotlin, java
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6821-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Ultimate Edition)
