### ISSUE TITLE
Generic filter fails with dynamic attributes

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#3586]
### Environment

Jmix version: 2.3.1

### Bug Description

Generic filter fails with dynamic attributes

### Steps To Reproduce

1. Create any dynamic attribute
2. Add it to list view
3. Try to create filter condition of generic filter with this create dinamic attribute
4. Copy URL of the screen and open it in other browser tab

### Current Behavior

Runtime error with closing list view with filter.
### Expected Behavior

Filter works correctly.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.1
