### ISSUE TITLE
Fix ListMenu focus and icon styles

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3589]
### Environment
Jmix version: 2.3+

### Bug Description
1. Focus-ring for root menus is cut off on the right and has no padding on the left 

<img width="269" alt="Screenshot 2024-08-02 at 22 56 44" src="https://github.com/user-attachments/assets/15c2a9b5-c9dc-4af6-aa2b-e5f0e25a5ab6">

2. Vaadin icon size is bigger than font size. Compare for instance with button:

![image](https://github.com/user-attachments/assets/fbe62534-5f5f-4905-98ed-7d092d28f370)

### Steps To Reproduce
Use the Tab key to navigate through different menu items

### Breaking changes
- Changed margin and padding for `ListMenu` itself.
- Increased margin-inline-start for list of sub menu.
- Changed paddings for `MenuBarItem`.

Above styles can affect visual of representation of ListMenu if selectors were overridden in the project.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6810-242
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)
