### ISSUE TITLE
Add settings facet and resizable columns to all framework add-ons views

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#3602]
Possible issues:
* LoadDelegate may ignore sorting

**Comment by KremnevDmitry** [comment]
Progress:

- [ ] AppSettings
- [ ] Audit
- [ ] Datatools
- [ ] DynAttr
- [ ] Email
- [ ] FlowUI
- [ ] JmxConsole
- [ ] Multitenancy
- [ ] PessimisticLock
- [ ] PivotTable
- [ ] Quartz
- [ ] Reports
- [ ] Search
- [ ] Security
- [ ] BPM
- [ ] BusinessCalendar
- [ ] Notifications
- [ ] UiConstraints
- [ ] WebDav

**Comment by KremnevDmitry** [comment]
# For QA

All framework views that contain a `details` or `dataGrid` component should be checked to ensure that they retain state
There are cases where state persisting is intentionally ignored, please contact @KremnevDmitry for clarification

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.5.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7074-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
