### ISSUE TITLE
OpenSearch. Full-text Search Condition in GenericFilter Component does not work

### ISSUE THREAD

**Issue by kartushev** [jmix-framework/jmix#3605]
### Environment

Jmix version: 2.3.1
OpenSearch version: 2.13

### Bug Description
When trying to use the full-text search condition, an error occurs  
```
NoSuchBeanDefinitionException: No qualifying bean of type 
    'io.jmix.search.searching.SearchStrategyProvider<io.jmix.search.searching.SearchStrategy>' available: expected at 
    least 1 bean which qualifies as autowire candidate. Dependency annotations: 
    {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

### Steps To Reproduce

0. Add Search and Quartz add-ons; create index on User
1. Open User list view
2. Select "Create Full-text condition" in GenericFilter component

### Current Behavior

Unexpected error

### Sample Project
[opensearch-test.zip](https://github.com/user-attachments/files/16634822/opensearch-test.zip)

https://github.com/user-attachments/assets/5244b37e-31ba-41c5-a707-b4fb3e169027

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6711-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)
2) Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6714-241
IntelliJ version: IntelliJ IDEA 2024.1.4 (Community Edition)

Full-text Search Condition works correctly in GenericFilter Component.
![image](https://github.com/user-attachments/assets/27b774f8-ce3c-4298-b7fe-165ec0a37d7e)
