### ISSUE TITLE
Excelexport "All rows" does not take order into account

### ISSUE THREAD

**Issue by timlehmkuhl** [jmix-framework/jmix#3612]
### Environment

Jmix version: 2.3.1

### Bug Description

I have a datagrid with a string attribute. I sort the DataGrid by attribute. Now I export “All rows” to Excel. The order was not applied to Excel. With “Current page”, however, the order is applied. 

### Steps To Reproduce

1. open demo project
2. open “Orders” list
3. sort by “Order number
4. use Excel Export and export “All rows”
5. open Excel file

![image](https://github.com/user-attachments/assets/348816e0-f09f-4eab-a9de-b16afdacaa2b)
![image](https://github.com/user-attachments/assets/4c74b1eb-7107-4daa-955d-343c7b34c952)

### Current Behavior

The order was not applied to Excel.

### Expected Behavior

The order is applied to Excel.

### Sample Project

[excelorder.zip](https://github.com/user-attachments/files/16638354/excelorder.zip)

**Comment by KremnevDmitry** [comment]
This is not a bug, see duplicate issue comment: https://github.com/jmix-framework/jmix/issues/3315#issuecomment-2152619767
