### ISSUE TITLE
[Port to 1.6] Months localization in business calendar is not supported

### ISSUE THREAD

**Issue by NikitaShchienko** [jmix-framework/jmix#3614]
See origin issue: #3337

**Comment by NikitaShchienko** [comment]
For QA: Updated messages for business calendar source, need to check messages for all languages.

**Comment by konyashkina** [comment]
Tested on
_Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6840-242
IntelliJ version: IntelliJ IDEA 2024.2.3_
with jmix translation add-ons.
