### ISSUE TITLE
Shortcut for InputDialogAction does not work

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3617]
### Environment
Jmix version: 2.3.x

### Bug Description
Assigned shortcut for custom action in InputDialog is not triggered.

We can try to assign shortcut to button using limited scope like InoutDialog view or use global but carefully testing that it does not trigger other global shortcuts.

### Steps To Reproduce
1. Add the InputDialog:
```
dialogs.createInputDialog(this)
        .withParameter(InputParameter.stringParameter("name").withLabel("Name"))
        .withActions(
                new InputDialogAction("ok")
                        .withText("OK")
                        .withVariant(ActionVariant.PRIMARY)
                        .withShortcutCombination(KeyCombination.create("CONTROL-ENTER"))
                        .withHandler(actionPerformedEvent -> {
                            InputDialogAction dialogAction = (InputDialogAction) actionPerformedEvent.getSource();
                            InputDialog inputDialog = dialogAction.getInputDialog();
                            
                            inputDialog.close(InputDialog.INPUT_DIALOG_OK_ACTION);
                        }))
        .open();
```
2. Open the dialog and press CTRL + ENTER combination.

### Current Behavior
Nothing happens

### Expected Behavior
The dialog should be closed

**Comment by rusiaikinat** [comment]
Reopened
Shortcut does not work when the focus is not in the input field
