### ISSUE TITLE
Visual bug in CategoryListView

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3618]
### Environment

Jmix version: 2.3.999-SNAPSHOT

### 1. The category attributes `DataGrid`  extends beyond the view boundaries:
![image](https://github.com/user-attachments/assets/c610bf69-641c-4408-a832-dec8d0373200)

### 2. The category attributes `DataGrid` has two paddings on the right corner:
![image](https://github.com/user-attachments/assets/f8af0de1-785e-4374-a302-a9bdd8318aa4)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6826-242
IntelliJ version: IntelliJ IDEA 2024.2.1
