### ISSUE TITLE
Date datatype can't be formatted for Axes

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3620]
### Environment

Jmix version: 2.3.999-SNAPSHOT
Forum topic: [link](https://forum.jmix.io/t/how-to-format-date-in-dd-mm-yy-format-in-chart-axis/5370)

### Bug Description

An attribute of `java.util.Date` can't be formatted by the axis formatter

**Comment by ilushaaa** [comment]
Make sure that all Jmix data types related to date and time work after the changes.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6844-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
