### ISSUE TITLE
BpmAdminRole has no bpm_EntityDataTaskPropertiesFragment view permission

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix#3624]
### Environment

Jmix version: 2.3 and maybe previous

### Bug Description

The necessary "bpm_EntityDataTaskPropertiesFragment" view access permission is absent for BpmAdminRole

### Steps To Reproduce

1. Create new application project
2. Install BPM addon
3. Add user and assign BpmAdminRole and UIMinimal roles
4. Login as newly created user
5. Go to modeller section
6. Create Task from panel
7. Select "Change type" from task icons
8. Select "Entity Data Task"
9. Double-click on Task 
10. See "Access Denied" notification 

![image](https://github.com/user-attachments/assets/0a0cc8d4-23cd-46ef-92e9-b7bef37201b2)

### Current Behavior

"Access Denied" is displayed. User with role has no access to view that displays properties on right panel

### Expected Behavior

Properties for EntityDataTask are displayed in right panel w/p any warnings

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6840-242
IntelliJ version: IntelliJ IDEA 2024.2.3
