### ISSUE TITLE
Large-limit excel export action

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix#363]
e.g. topic https://www.cuba-platform.ru/discuss/t/vygruzka-v-excel/5546

Often users ask for an action like "excel", but which will export entities without standard 20 or 50 rows limit.

Requirements:
- export entities using data container's query and filter conditions from applied filter
- excel format
- columns = the same as in table
- generated columns - skip them, or maybe run install handlers to obtain data?..
- need some tunable hard limit to avoid out of memory, e.g. 100_000 rows

**Comment by gorbunkov** [comment]
Already implemented in #1211
