### ISSUE TITLE
Default value of dynamic attribute is cleared when detail view opens

### ISSUE THREAD

**Issue by fractal3000** [jmix-framework/jmix#3638]
### Environment

Jmix version: 2.3.2

### Bug Description

A description of what the bug is.

### Steps To Reproduce
Create dynamic attribute of String type
Set any default value for it
![image](https://github.com/user-attachments/assets/4794b9ab-d699-42b2-8f3b-8d18964e7223)
Save the attribute
![image](https://github.com/user-attachments/assets/0aa6ea4e-6ad5-4a03-9841-9de11962ac45)
Open editor screen of the attribute again

### Current Behavior

![image](https://github.com/user-attachments/assets/ed05b0be-6714-475b-bf99-89a83651d727)

### Expected Behavior

The being set up default value of the attribute have been saved.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6866-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
