### ISSUE TITLE
Add BulkEdit action to entity inspector browser

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix#365]
**Motivation**
Just today I was fixing email settings in some CUBA application.
After applying new SMTP settings, I came to Email History browser and saw that there are ~ 10 email in "Not Sent" status during the last days because of broken SMTP credentials.

I wanted to re-send them.
So I came to Entity Inspector, searched not sent emails and for every email I had to:
- open for Edit
- change Status and Attempts Made fields to put the message back to queue.
- Save the entity

And repeat the same for 10 entities in the table.

**Suggestion**
Add "Bulk Edit" action to the entity inspector browser to be able to quickly change some attributes of several entities at once.

**Changes:**
Standard "Bulk Edit" action has been added to the entity inspector browser. 
Either "Edit" action or "Bulk Edit" action will be active depending on how much records are selected.

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4337-213)
jmix version (1.3.999-SNAPSHOT)
