### ISSUE TITLE
Jar application not create database

### ISSUE THREAD

**Issue by florintanasa** [jmix-framework/jmix#3652]
### Environment

Jmix version: <2.3.2>

### Bug Description

When I start jar application this not create database. The database user in PostgreSQL have role to createdb.
Work only if I create the database manually by the user defined in application.properties.

### Steps To Reproduce

Steps to reproduce the behavior.

### Current Behavior

2024-08-28T09:10:37.024931+03:00 server genedatabank.sh[157307]: Caused by: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: FATAL: database "genedatabank" does not exist

### Expected Behavior

To create database when I start first time the application.

### Sample Project

https://github.com/florintanasa/genedatabank

**Comment by glebfox** [comment]
Not a bug. Jmix Applications never create databases, it's Studio job. Jmix Applications can only apply liquibase scripts, so you need to create database manually.

**Comment by florintanasa** [comment]
Ok,
I understood.
