### ISSUE TITLE
URL not updating after navigation

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3654]
### Environment

Jmix version: 2.3.999-SNAPSHOT
On version **2.4.999-SNAPSHOT** the error becomes **critical**, the view cannot be opened, because `History#replaceState` does navigation when using React Routing.

### Bug Description

In a special case (attached project) the URL route remains from the previous page.

### Steps To Reproduce

1. Run attached project
2. Open Test entities view
3. Open Users view

### Current Behavior

URL: `http://localhost:8080/testEntities?genericFilterCondition=property%3Aparent_in-list_&genericFilterConfiguration=defaultConfiguration`

### Expected Behavior

URL: `http://localhost:8080/users?genericFilterCondition=property%3Aparent_in-list_&genericFilterConfiguration=defaultConfiguration`

### Sample Project
[jmixtest.zip](https://github.com/user-attachments/files/16783414/jmixtest.zip)

### Temporary workaround:

Extend `io.jmix.flowui.view.navigation.RouteSupport`, override `io.jmix.flowui.view.navigation.RouteSupport#setQueryParameters` method:

```java
    @Override
    public void setQueryParameters(UI ui, QueryParameters queryParameters) {
        Page page = ui.getPage();

        String locationString = ui.getActiveViewLocation().getPath();
        Location newLocation = new Location(locationString, queryParameters);

        log.debug("Replace URL state with new location: {}", newLocation.getPathWithQueryParameters());
        page.getHistory().replaceState(null, newLocation);
    }
```

P.S.
It is not yet entirely clear whether it is safe to use `location` from a servlet.
See the 6cf26f5d commit.

**Comment by MeyersJeff** [comment]
This problem was also reported in this [forum post](https://forum.jmix.io/t/routing-problems-maybe-with-default-generic-filters/5471/6?u=chicojeff). The primary symptom we see is when the user opens a detail view, then returns to the list view, the wrong view is displayed.
