### ISSUE TITLE
User without permission to modify global filter configuration still can update it

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3655]
### Environment

Jmix version: 2.3

### Bug Description

Source: [forum](https://forum.jmix.io/t/genericfilter/5435/5)

User without permission to modify global filter configuration still can update it

### Steps To Reproduce

1. Create a role that gives full access to the filter except `ui.genericfilter.modifyGlobalConfiguration`

```
@ResourceRole(name = "FlowUIEditAccessRole", code = FlowUIEditAccessRole.CODE)
public interface FlowUIEditAccessRole {

    String CODE = "magnetlibrary-security-flow-u-i-editaccess";

    @EntityAttributePolicy(entityClass = GroupFilterCondition.class, attributes = "*", action = EntityAttributePolicyAction.MODIFY)
    @EntityPolicy(entityClass = GroupFilterCondition.class, actions = EntityPolicyAction.ALL)
    void groupFilterCondition();

    @EntityAttributePolicy(entityClass = FilterCondition.class, attributes = "*", action = EntityAttributePolicyAction.MODIFY)
    @EntityPolicy(entityClass = FilterCondition.class, actions = EntityPolicyAction.ALL)
    void filterCondition();

    @EntityAttributePolicy(entityClass = FilterConfiguration.class, attributes = "*", action = EntityAttributePolicyAction.MODIFY)
    @EntityPolicy(entityClass = FilterConfiguration.class, actions = EntityPolicyAction.ALL)
    void filterConfiguration();

    @EntityAttributePolicy(entityClass = JpqlFilterCondition.class, attributes = "*", action = EntityAttributePolicyAction.MODIFY)
    @EntityPolicy(entityClass = JpqlFilterCondition.class, actions = EntityPolicyAction.ALL)
    void jpqlFilterCondition();

    @EntityAttributePolicy(entityClass = PropertyFilterCondition.class, attributes = "*", action = EntityAttributePolicyAction.MODIFY)
    @EntityPolicy(entityClass = PropertyFilterCondition.class, actions = EntityPolicyAction.ALL)
    void propertyFilterCondition();

    @SpecificPolicy(resources = {"ui.genericfilter.modifyJpqlCondition", "ui.genericfilter.modifyConfiguration"})
    void specific();

    @ViewPolicy(viewIds = {"flowui_AddConditionView", "flowui_GroupFilterCondition.detail", "flowui_JpqlFilterCondition.detail", "flowui_PropertyFilterCondition.detail", "flowui_DateIntervalDialog"})
    void screens();
}
```

2. Create a global filter configurations (aka **available for all users**), e.g. by `admin` user
3. Create a new user and assign `UiMinimalRole`, `FlowUIEditAccessRole` (created by you) and role that gives access to a view with genericFilter that contains global configuration
4. Select **global configuration** from available configurations

Case 1:

6. Add a new conditions using **Add search condition** button
7. Edit configuration
8. Click **OK** to save

Case 2:

6. Enter a value to a filter
7. Invoke **Save with Values** action

### Current Behavior

Global configuration is updated.

### Expected Behavior

User is not allowed to modify global configurations

**Comment by rusiaikinat** [comment]
Test on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6830-242
IntelliJ version: IntelliJ IDEA 2024.2.2 (Ultimate Edition)
Java, Kotlin

![image](https://github.com/user-attachments/assets/e7f16e02-81e6-4f69-9e11-6b87b9ca003c)
