### ISSUE TITLE
RuntimeException when creating entity with a generated attribute in entity inspector

### ISSUE THREAD

**Issue by reloadall** [jmix-framework/jmix#366]
If we try to create an entity with a generated attribute in the entity inspector, for example:
`@JmixProperty
@DependsOnProperties({"name", "code"})
public String getFullName() {
        return String.format("%s (%s)", name, code);
}`

We get an error:
`java.lang.RuntimeException: Property not found: fullName
    at io.jmix.core.MetadataTools.isAnnotationPresent(MetadataTools.java:494)
    at io.jmix.core.MetadataTools.isAnnotationPresent(MetadataTools.java:468)`
    
Tested on new JMIX 1.3 and 1.4 project with Datatools addon

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4303-213)
jmix version (1.3.999-SNAPSHOT)
