### ISSUE TITLE
Unexpected behavior of the view with different URL query parameters

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3661]
### Environment

Jmix version: 2.3.999-SNAPSHOT
See related issue: #3345

### Bug Description

Let's imagine that we have two views in the `menu` that differ only in their query parameters. These query parameters are applied to the `dataLoader`, so the `dataGrid` on the two views has a different set of data.

### Steps To Reproduce

1. Open view_1 and go to the second page using pagination
2. Open view_2 different set of data is loaded
3. Pagination component persists pagination from previous page (no data on this page)

See the video:

https://github.com/user-attachments/assets/441bc3d7-8c1c-45ac-98f5-058e98be4810

### Current Behavior

Pagination configuration are saved.

### Expected Behavior

Pagination configuration should be reset to default.

### Sample Project
[paginationTest.zip](https://github.com/user-attachments/files/16812410/paginationTest.zip)

### The reason
The same as in #3345
When switching to the same view, which differs only in the query parameters, the view instance is not recreated. Thus, the pagination settings remain from the previous view.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.5.SNAPSHOT6966-243
IntelliJ version: IntelliJ IDEA 2024.3 (Community Edition)
