### ISSUE TITLE
Remove the metaClass attribute from the listMenu component

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#3675]
### Environment

Jmix version: 2.3.3
Jmix Studio plugin version: 2.4.SNAPSHOT6763-241
IntelliJ version: IntelliJ IDEA 2024.2.1 (Community Edition)

### Bug Description

The `metaClass` attribute is in the JMIX Studio, but not in the xsd schema

<img width="827" alt="image" src="https://github.com/user-attachments/assets/4d11fe10-c6ee-41d9-ad2b-00f632838e43">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6840-242
IntelliJ version: IntelliJ IDEA 2024.2.3
