### ISSUE TITLE
Search displays some meta information of indexed xlsx file

### ISSUE THREAD

**Issue by SergeiAksenov2** [jmix-framework/jmix#3678]
See ticket [File parsing in search add-on doesn't work](https://github.com/jmix-framework/jmix/issues/3659)

### Environment

Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6778-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

### Bug Description

OpenSearch shows unnecessary information for xlsx files in FilesRef attribute.

### Steps To Reproduce

1. Create an project with Search and Quartz addons,
2. Create blank-view with Search,
3. Create an Entity with FileRef attribute,
4. Configure OpenSearch in application.properties,
5. Run the project
6. Add entities with simple xlsx file in FileRef attribute, for example, contains cells with word "moment",
7. Try to search by file content (by word "moment").

![image](https://github.com/user-attachments/assets/18b0b819-7deb-4f31-a6e7-f94d6d5a3536)

### Current Behavior

Unnecessary information is displayedsary (in "Car - excel" entity):

![image](https://github.com/user-attachments/assets/430066c7-3ab8-4bb2-a173-fa8d0aeda712)

### Expected Behavior

Showed only content: "moment, moment1"

**Comment by glebfox** [comment]
Requires research if it possible to ignore meta information like formatting while indexing.

**Comment by Gavrilov-Ivan** [comment]
Reproduced on xlsx file created in LibreOffice (MS Office is ok).
Internal stucture for the same-content documents is different - additional meta information is included as header-footer.
Header-footer processing is disabled.
