### ISSUE TITLE
BpmSendNotificationUserTaskListener can't be selected in the modeller

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#3679]
### Environment

Jmix version: 1.6.999-SNAPSHOT

### Bug Description

If the Notification addon is installed, you cannot select a method

### Steps To Reproduce

1. Add Notification addon
2. Create task listener in UserTask
![image](https://github.com/user-attachments/assets/2f9cee38-4ebe-4e26-b991-05f9fb6c8dd9)

### Current Behavior
class list is empty

### Expected Behavior

![image](https://github.com/user-attachments/assets/6afb0065-98b2-4f62-b7e2-5c037fa08ada)

**Comment by konyashkina** [comment]
Tested with property
`jmix.bpm.notification-sending-enabled `
**Case 1**
Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6840-242
IntelliJ version: IntelliJ IDEA 2024.2.3
**Passed.** 

**Case 2**
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6840-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
**Failed:** there is no 'Send notification' section for User task or Service task.

**Comment by NikitaShchienko** [comment]
Integration has been removed in Jmix 2.0, integration needs to be returned: https://github.com/jmix-framework/jmix/issues/3749
