### ISSUE TITLE
Error restoring Resource role and a Row-level role after a soft delete

### ISSUE THREAD

**Issue by isunagatov** [jmix-framework/jmix#368]
jmix 1.1.4
Case:
1. Create Resource role and Row-level role;
2. Remove them;
3. Open the Entity inspector, select the display of deleted ones, click [Restore].

AR: JPQLException:
Exception Description: Problem compiling [select e from sec_RowLevelPolicyEntity e where e.role.id = :id and e.deletedDate >= :start and e.deletedDate <= :end].
[67, 80] The state field path 'e.deletedDate' cannot be resolved to a valid type.
[95, 108] The state field path 'e.deletedDate' cannot be resolved to a valid type.

#### QA Notes:
Please, check also restoration of entities with `@OnDelete(DeletePolicy.CASCADE)`-relation to other entities that have standard ("deletedDate") and non-standard (e.g. "momentOfDeletion") name of property with `@DeletedDate` annotation.

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4305-213)
jmix version (1.3.999-SNAPSHOT)
