### ISSUE TITLE
Getting focus on the first input element in dialogs

### ISSUE THREAD

**Issue by trx0eth7** [jmix-framework/jmix#3682]
### Environment

Jmix version: 2.2.2

### Bug Description
no focus set on the first input element in input dialog
![image](https://github.com/user-attachments/assets/0e9c3d0c-cb23-4905-8a26-5350958e0206)

### Steps To Reproduce
``` java
dialogs.createInputDialog(this)
                    .withHeader("Редактирование комментария")
                    .withParameter(
                            parameter("message")
                                    .withField(() -> {
                                        JmixTextArea messageField = uiComponents.create(JmixTextArea.class);
                                        messageField.setWidthFull();
                                        messageField.setValue(message);
                                        return messageField;
                                    })
                    )
                    .withActions(DialogActions.OK_CANCEL)
                    .open();
```

### Workaround
before returning parameter component, call focus method
``` java
// looks bizarre, but works
 messageField.focus();
 return messageField;
```

**Comment by rusiaikinat** [comment]
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6830-242
IntelliJ version: IntelliJ IDEA 2024.2.2 (Ultimate Edition)
Kotlin, Java

![image](https://github.com/user-attachments/assets/5577eec4-454a-4388-ab6c-7ede155d03d8)
