### ISSUE TITLE
 Adding HeaderRow to DataGrid removes header columns from Excel Export

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3706]
### Environment

Jmix version: 2.3.999-SNAPSHOT

### Bug Description

If HeaderRow is added to DataGrid, column headers are missing after export to Excel

![image](https://github.com/user-attachments/assets/2996f18c-e181-4e5e-89a7-1f19c202d809)
![image](https://github.com/user-attachments/assets/ffa6e366-bfb2-4d23-9cef-5141b7874cfa)

**Comment by rusiaikinat** [comment]
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6830-242
IntelliJ version: IntelliJ IDEA 2024.2.2 (Community Edition)
Java, kotlin

![image](https://github.com/user-attachments/assets/a2ebe8da-87b7-491b-90f3-4748e7201d55)


![image](https://github.com/user-attachments/assets/2bce7436-23a6-4ed5-914e-7ad02d304022)
