### ISSUE TITLE
Unhandled exception after opening screen with dynamicAttributesPanel  

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix#371]
**Enviroment:**
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2706-202
IntelliJ version: IntelliJ IDEA 2020.3.1 (Community Edition)

**TC:**

1. Run [attached](https://github.com/Haulmont/jmix-dynattr/files/6264636/dynamic.zip) project
2. Open New entities brower -> Create

**AR:**
unhandled exception:
![image](https://user-images.githubusercontent.com/45730069/113710950-688a9a80-96f5-11eb-974c-972b673208c3.png)

Exception is expected because entity NewEntity doesn't implement interface Categorized

**ER:**
more user-friendly error

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4313-213)
jmxi version (1.3.999-SNAPSHOT)
