### ISSUE TITLE
Composite project template for monorepo

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#3713]
Create a second composite project template suitable for storing subprojects in a monorepo. It should contain composite build scripts in the root. For example:

```
composite-project/
    subproject1/
        src/
        build.gradle
        settings.gradle
    subproject2/
        src/
        build.gradle
        settings.gradle
    build.gradle
    settings.gradle
    README.md
```

Change the name and description of the current template to something like "Composite Project for Multiple Repositories".

**Comment by knstvk** [comment]
Studio issue: https://youtrack.haulmont.com/issue/JST-5342/Support-for-composite-project-in-monorepo

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6867-241
IntelliJ version: IntelliJ IDEA 2024.1.6 (Community Edition)
