### ISSUE TITLE
Worng place of suffix and prefix component on an IntegerField

### ISSUE THREAD

**Issue by pbaris** [jmix-framework/jmix#3726]
### Environment

Jmix version: 2.3.3

### Bug Description

Wrong place of suffix and prefix component on an IntegerField when stepButtonsVisible is set to true

### Steps To Reproduce

Add a suffix or prefix component on an IntegerField and set stepButtonsVisible="true"
```
<integerField id="doorsField" property="doors" stepButtonsVisible="true">
    <suffix>
        <image resource="icons/vehicle-doors.svg" width="17px" height="17px"/>
    </suffix>
</integerField>
```

### Current Behavior

The suffix/prefix component is inside the +/- buttons

![image](https://github.com/user-attachments/assets/4ca0e23f-ca06-4846-94cf-c4013fbc97cf)

### Expected Behavior

The suffix/prefix component to be outside the +/- buttons

**Comment by glebfox** [comment]
Hi,

This is not our design. `IntegerField` comes from **Vaadin**. If you consider this behavior to be a bug, please create an issue on the Vaadin repository: https://github.com/vaadin/flow-components
