### ISSUE TITLE
Update bpm_container script

### ISSUE THREAD

**Issue by tmusin** [jmix-framework/jmix#3731]
Update file bpm_container.xml for studio [ticket](https://youtrack.jmix.io/issue/JST-5338)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6840-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
