### ISSUE TITLE
FullCalendar icons are missing

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3733]
See Studio issue: https://youtrack.jmix.io/issue/JST-5334/fullCalendar-icons-are-missing

**Comment by rusiaikinat** [comment]
Reopened

_Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6866-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Ultimate Edition)_

```
<calendar:calendar>
 <calendar:businessHours>
                <calendar:entry>
                    <calendar:day name=""/>
                </calendar:entry>
            </calendar:businessHours>
</calendar:calendar>
```

![Image](https://github.com/user-attachments/assets/bd945472-69f6-4298-b3df-ba6e48baadef)

**Comment by Flaurite** [comment]
Fixed in the commit: https://github.com/jmix-framework/jmix/commit/8da112adf99d59f28d0156a2071253a5935a9fa4
