### ISSUE TITLE
Incorrect redirect to non view URLs after login

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3756]
### Environment

Jmix version: 2.3.3
Source: [forum](https://forum.jmix.ru/t/dobavlenie-sobstvennyh-ikonok-v-addon/1998)

### Bug Description

To decide which initial view should be shown, `LoginViewSupport` also checks `VaadinDefaultRequestCache` which can contain non view URLs, e.g. to resources like icons. As a result, we will see 404 error

### Steps To Reproduce

1. Start the project
2. Open test view (see icon)
3. Log out and log in again

### Current Behavior

<img width="565" alt="Screenshot 2024-10-04 at 13 59 21" src="https://github.com/user-attachments/assets/c08100c1-858b-42ee-a9c5-947161f7a8e5">

### Expected Behavior

Main view is shown

### Sample Project

[jmix-test-com.zip](https://github.com/user-attachments/files/17256503/jmix-test-com.zip)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.2-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
