### ISSUE TITLE
String typed default value is not loaded to Dynamic Attribute edit form

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix#3769]
### Environment

Jmix version: 2.3

### Bug Description

From testing by forum issue: [https://forum.jmix.ru/t/dinamicheskie-atributy-nevozmozhno-udalit-znachenie-po-umolchaniyu/2007](https://forum.jmix.ru/t/dinamicheskie-atributy-nevozmozhno-udalit-znachenie-po-umolchaniyu/2007)

When dynamic attribute is created with string type it's default value saved but not displayed in edit form, other types has no such problems

![image](https://github.com/user-attachments/assets/776b992e-be82-49b9-8b2a-98af5461e44f)

### Steps To Reproduce

1. Create project with dynamic attribues addon installed
2. Create entity with views
3. Create and save category and add attribute with String type, set default value to it
4. Open newly created category for edit

### Current Behavior

default value is not displayed 

### Expected Behavior

default value is displayed in field

**Comment by Gavrilov-Ivan** [comment]
Fixed in https://github.com/jmix-framework/jmix/issues/3638
