### ISSUE TITLE
NotSerializableException: io.jmix.dynattr.impl.DynAttrMetaProperty

### ISSUE THREAD

**Issue by dstrmv** [jmix-framework/jmix#377]
After adding a dependency to an application that runs in kubernetes with hazelcast according to the documentation (https://docs.jmix.io/jmix/deployment/k8s.html), an exception is thrown

#### Steps to reproduce:
- Create new Jmix project
- Follow the instruction for deploy in k8s 
-  Do not forget to setup database correctly in app.properties(or studio):
    ```properties
        main.datasource.url = jdbc:postgresql://sample-db-service/sample
        main.datasource.username = root
        main.datasource.password =root
   ```
- Add this dependency
- Create any entity or use "User" entity
- Add new Category and Category attribute for this entity, save to DB
- Try to open browse screen, if there is no exception, try to open filter
**ER:** no exceptions, entity loaded, dynamic attribute shown and work

**Comment by dtaimanov** [comment]
Not serializableExceprion is fixed, one more problem moved to #734
