### ISSUE TITLE
Index settings are not generated properly

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3776]
### Environment

Jmix version: 2.4.0-RC1

### Bug Description

1. Index settings (not analysis) for all indexes and for specific indexes are not merged properly - common settings are suppressed.
2. Structure of index settings stored in memory is different from acquired from OpenSearch. It's valid in terms of search server comparison is failed -> index is recreated. Due to builder structure.

### Steps To Reproduce

Configure common and index specific settings on project side

### Current Behavior

1. Index specific settings suppress all common settings.
2. Index is considered as changed even if there are no actual changes.

### Expected Behavior

1. Settings should be merged properly.
2. Index should be considered as 'Actual'.

### Sample Project

Attach a zip-archive with a sample project or provide a link to a GitHub repository with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). 

Jmix Studio Toolbar provides an [action](https://docs.jmix.io/jmix/studio/tool-window.html#gradle) for creating a zip-archive from your project.

Reports that include a sample will take priority over reports that do not.

**Comment by Gavrilov-Ivan** [comment]
Related to https://github.com/jmix-framework/jmix/issues/3553

**Comment by fractal3000** [comment]
Search doesn't work with all the strategies exept the "create-or-recreate" strategy.

**Comment by fractal3000** [comment]
Base test cases with all index management strategies should be checked.
