### ISSUE TITLE
Avoid overlapping text and graphics

### ISSUE THREAD

**Issue by SergeiAksenov2** [jmix-framework/jmix#3782]
### Environment

Jmix version: 2.4.999-SNAPSHOT

### Bug Description

A barchart is overlaid on the text in the Pivot Table (Total 77.00 on the screen)

### Steps To Reproduce

Create a Table barchart Pivot table

### Current Behavior

![image](https://github.com/user-attachments/assets/4e1ceb55-d179-44d9-930b-4d57b8bf0155)

![image](https://github.com/user-attachments/assets/b0539ebe-ae0b-49ff-bf24-f6d1a1c57dad)

### Expected Behavior

A barchart is not overlaid on the text.

**Comment by glebfox** [comment]
It's problem of PivotTable.JS itself. We have mo power there.
