### ISSUE TITLE
Repeated search within search result dialog window opens new dialog window as a result

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3783]
### Environment

Jmix version: 2.4.0-RC1

### Bug Description

Repeated search within search result dialog window opens new dialog window as a result.

### Steps To Reproduce

1. Add searchField, openMode=dialog
2. Perform some search
3. Perform search again within opened dialog

### Current Behavior

New dialog window with results is created over existing one

### Expected Behavior

Results should be updated within current dialog

**Comment by SergeiAksenov2** [comment]
Tested on Jmix version: 2.4.999-SNAPSHOT:
1) Jmix Studio plugin version: 2.4.SNAPSHOT7043-242
IntelliJ version: IntelliJ IDEA 2024.2.5 (Community Edition)
2) Jmix Studio plugin version: 2.4.SNAPSHOT7042-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
