### ISSUE TITLE
PivotTable `columns` and `rows` has wrong attribute `name` in Component Inspector

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3785]
See Studio issue: https://youtrack.jmix.io/issue/JST-5386

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.5.SNAPSHOT6895-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.5.SNAPSHOT6895-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
