### ISSUE TITLE
Empty options for dynamic attribute lookup in filter

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#379]
Filter component shows empty option list for lookup entity dynamic attribute.

The problem can be reproduced in [jmix-petclinic](https://github.com/daring2/jmix-petclinic) project:
1. Add lookup entity dynamic attribute petType2 for Pet entity.
2. Open pet browse screen
3. Add petType2 property in table filter.

Result: petType2 component shows empty option list

Screenshots:
1. Add petType2 attribute:

![image](https://user-images.githubusercontent.com/11490702/158567700-5ea5c7a9-b991-43a1-8a5a-39b3746fe97e.png)

2. petType2 filter component with empty options:

![image](https://user-images.githubusercontent.com/11490702/158567870-ea1be3ae-3ca9-4800-9424-5c1f71423786.png)

#### QA Notes:
Check also:
* Case for not entity but datatype attribute (e.g. Integer).
* Case when `entity` variable used in options loader script: filter must not be broken if this attribute selected in search condition: just empty options and maybe exception in log.

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
