### ISSUE TITLE
Grid looks strange without security Policy for the corresponding class

### ISSUE THREAD

**Issue by gmmars** [jmix-framework/jmix#3790]
When there is no security policy a grid will shrink to a single column empty table corrupting the view design. Maybe it will be better to show an empty table.

**Comment by glebfox** [comment]
<img width="600" alt="Screenshot 2024-10-25 at 10 47 12" src="https://github.com/user-attachments/assets/4e863f66-72a3-4fa3-8968-e51a4a13f20b">

By default, if we have no attribute permissions DataGrid is shown as a border. We cannot display empty columns or something. Please check of you have `width` defined. As an option define `min-width`.
