### ISSUE TITLE
Opening item on master-details view via double-click keeps 'Edit' and 'Remove' buttons enabled

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3791]
### Environment

Jmix version: 2.3.4

### Bug Description

If item editing starts via double-click 'Edit' and 'Remove' buttons remain enabled.
See https://forum.jmix.ru/t/datagrid-v-shablonnom-ekrane-master-detail-ne-dizejblit-knopki-dejstvij-pri-dablklike/2017

### Steps To Reproduce

1. Create master-details view for some entity.
2. Create item.
3. Double-click on created item - start editing.

### Current Behavior

'Edit' and 'Remove' buttons remain enabled.

### Expected Behavior

Buttons should be disabled during editing

**Comment by Lood** [comment]
Perhaps the problem is related to #3835

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.2-243
IntelliJ version: IntelliJ IDEA 2024.3 (Community Edition)
