### ISSUE TITLE
BPM: incorrect work if process name is null

### ISSUE THREAD

**Issue by stasmakarov** [jmix-framework/jmix#3792]
### Environment

Jmix version: <2.3.4>

Process name is not mandatory, so it can be empty. 
But the system must work correctly in this case.

1. Notification when process starts:
![image](https://github.com/user-attachments/assets/8799782d-f07b-472e-a36e-f21b99b07a9b)

2. If the process name is empty (null), it causes NPE when user opens the task.
![image](https://github.com/user-attachments/assets/a85cea5a-dd76-4980-a079-4a04597b52c6)

### Steps To Reproduce

Create process without name, only id:
![image](https://github.com/user-attachments/assets/92f58104-f0c1-441a-b5a0-15b2d20f98c9)

Deploy and start it.

### Expected Behavior

1. In notification use process id if name is null
2. In My Tasks: in the tree element use process id if name is null
3. Allow to open and complete the user task  

### Sample Project

Attach a zip-archive with a sample project or provide a link to a GitHub repository with a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). 

Jmix Studio Toolbar provides an [action](https://docs.jmix.io/jmix/studio/tool-window.html#gradle) for creating a zip-archive from your project.

Reports that include a sample will take priority over reports that do not.

**Comment by NikitaShchienko** [comment]
**Results**:
1. In notification use process id if name is null - ✅ Done!
2. In My Tasks: in the tree element use process id if name is null - ✅ Done! 
3. Allow to open and complete the user task - 🚫 Not reproduced
