### ISSUE TITLE
Enum values displayed without localization in entity editor

### ISSUE THREAD

**Issue by natfirst** [jmix-framework/jmix#380]
Forum issue https://forum.jmix.ru/t/dinamicheskie-atributy/345
Platfrom version 1.2.1

1. Create entity
2. Add enum dynamic attribute
3. Add some values, add localization 
![image](https://user-images.githubusercontent.com/17950251/158761810-d0b2e143-9e2d-4b74-b861-2efed0c1ab0f.png)
4. Add attribute to browser and editor screens
5. Create entity item, select dynamic attribute value
*A.R.* Value in editor shows without localization
![image](https://user-images.githubusercontent.com/17950251/158761907-0e9a3eb5-94d0-4e81-a8a3-e5103b6f7e2b.png)
*E.R.* Value in editor should be shown with localization like in browser
![image](https://user-images.githubusercontent.com/17950251/158761955-3a14ef8d-3000-4583-8437-22cfb182a966.png)

## QA Notes
Please, check with CUBA addon too

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
