### ISSUE TITLE
Only last change to UrlQueryParametersFacet is applied

### ISSUE THREAD

**Issue by alexpopovlist** [jmix-framework/jmix#3802]
### Environment

Jmix version: <2.3.3>

### Bug Description

In urlQueryParameters contains union of genericFilter & dataGridFilter. When user change generic filter or filters in dataGridFilter (in columns) URL change and contains parameters only for one enum of filterParameters (genericFilter or dataGridFilter). 

When user change genericFilter and dataGridFilter url (not union of filters): 
http://localhost:8080/opportunities?genericFilterConfiguration=subordinateConfiguration OR
http://localhost:8080/opportunities?opportunitiesDataGridFilter=name_name_contains_123

![image](https://github.com/user-attachments/assets/0a520661-3cc6-4aa0-9d45-d0beeecce2ec)

### Steps To Reproduce

Example: 
User navigate to screen http://localhost:8080/opportunities
User change genericFilter and dataGridFilter

First **case** when user start works from:
- http://localhost:8080/opportunities

Second **case** when user start works from (navigate to URL and refresh browser):
- http://localhost:8080/opportunities?genericFilterConfiguration=myOrSubordinateConfiguration
User create dataGridFilter (input filter value in dataGrid)
Url contains union of filters: http://localhost:8080/opportunities?genericFilterConfiguration=myOrSubordinateConfiguration&opportunitiesDataGridFilter=name_name_contains_name1

In first case: class io.jmix.flowui.facet.impl.UrlQueryParametersFacetImpl
method: protected void onComponentQueryParametersChanged(UrlQueryParametersChangeEvent event) {
string: 79

![image](https://github.com/user-attachments/assets/3760f52b-7177-49e6-a77d-35b5aaf31656)

In second case (Navigate to http://localhost:8080/opportunities?genericFilterConfiguration=myOrSubordinateConfiguration and refresh browser): 

![image](https://github.com/user-attachments/assets/1706367c-7708-4247-b04d-4ab15a2ae909)

### Current Behavior

When user change genericFilter and dataGridFilter  URL contains parameters only for genericFilter and dataGridFilter : 

http://localhost:8080/opportunities?genericFilterConfiguration=subordinateConfiguration OR
http://localhost:8080/opportunities?opportunitiesDataGridFilter=name_name_contains_123

### Expected Behavior
Url contains union of parameters of genericFilter and dataGridFilter 

http://localhost:8080/opportunities?genericFilterConfiguration=myOrSubordinateConfiguration&opportunitiesDataGridFilter=name_name_contains_name1

Best Regards,
Alex.

**Comment by glebfox** [comment]
Caused by: https://github.com/jmix-framework/jmix/issues/3420

**Comment by glebfox** [comment]
**For QA:**

In addition check previous cases:
* https://github.com/jmix-framework/jmix/issues/3420
* https://github.com/jmix-framework/jmix/issues/3345
* https://github.com/jmix-framework/jmix/issues/3654

Also check:
* **Settings** facet enabled
* Different **Context Path**
* Setup `dataLoadCoordinator` so that data is loaded in the `ReadyEvent`.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.2-243
IntelliJ version: IntelliJ IDEA 2024.3
