### ISSUE TITLE
`Byte[]` and `URI` attributes are not included in list view (browser screen)

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3814]
See Studio issue: https://youtrack.jmix.io/issue/JST-3279/Byte-and-URI-attributes-are-not-included-in-browser-screens

We have a conditions that excludes `URI` and `byte[]` entity attributes from generated columns (`see jmix-templates/content/snippet/flowui/table.xml`, method `allowPutToDataAware()` without boolean argument filter out `byte[]` attribute on **line 9** and on **line 15** we filter out `URL` attribute).

Method `allowPutToDataAware()` from Studio:
![image](https://github.com/user-attachments/assets/e475cb43-0b56-4f1f-a65a-d85da69efd9b)

To discuss: should we allow this attributes in columns?

**Comment by glebfox** [comment]
Make no sense adding columns for `Byte[]` and `URI` without renderer. We can't add default rended because we don't know actual content, e.g. image etc.
