### ISSUE TITLE
Reports 2.x add-on script fullscreen-editor always on Groovy mode

### ISSUE THREAD

**Issue by KartnDev** [jmix-framework/jmix#3815]
### Environment

Jmix version: 2.x

### Bug Description

Whenever you want to create a report, after attempting to edit script opens **fullscript** editor - doesn't matter which type of script selected: groovy, jpql or sql - always only groovy opens

### Steps To Reproduce

1. Go to Reports menu
2. Click reports menu item
3. create new report (casually, not by wizard)
4. Go to the Bands tab
5. Select any type neither Groovy
6. Click "Full screen"
7. Dialog appears
8. No JPQL/SQL language highlight, but even you try type Groovy type words - it would be highlighted as keywords of dialect of JPQL/SQL
9. Click question mark - tip context would be about Groovy, not sql or jpql

### Current Behavior

Full screen editor always sets type of context as Groovy

![Screenshot 2024-10-25 at 16 13 04](https://github.com/user-attachments/assets/7a569edf-19d4-48f2-90e2-7c1c1302d2a6)
<img width="783" alt="Screenshot 2024-10-25 at 16 17 53" src="https://github.com/user-attachments/assets/7e168f9b-725b-41eb-af6a-fb9da0b05e13">

### Expected Behavior

For each type of script - full screen editor also should change type for target script

**Comment by rusiaikinat** [comment]
Current behaviour:
Dataset type: 
SQL - Full screen (Y), Helper (N)
JPQL - Full screen (Y), Helper (N)
Groovy - Full screen (Y), Helper (Y)
Entity - Full screen (N), Helper (N)
List Entity - Full screen (N), Helper (N)
JSON  - Full screen (N), Helper (Y)
