### ISSUE TITLE
`Charts` and `CodeEditor` doesn't apply `light` theme

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3819]
### Environment

Jmix version: 2.4.0

### Bug Description

`Charts` and `CodeEditor` doesn't apply `light` theme.

### Steps To Reproduce

1. Add theme switcher component from doc: https://docs.jmix.io/jmix/2.4/flow-ui/themes/themes.html#changing-theme-variants-at-runtime
2. Create blank view
3. Add `Charts` or `CodeEditor` component
4. Switch theme to `dark` and switch back to `light'

### Current Behavior
`Charts` and `CodeEditor` doesn't apply `light` theme.

### Expected Behavior
`Charts` and `CodeEditor` apply `light` theme.

**Comment by Fedoseew** [comment]
Note: `charts` and `codeEditor` components correct applies `light` theme if `theme` attribute in `html` equals an empty string (not "light").

**Comment by KremnevDmitry** [comment]
Also, in some cases, the exception appears in the console log
![image](https://github.com/user-attachments/assets/2b6a3d5b-ae7e-4fe0-8f63-c883a9bc59e5)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.2-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
