### ISSUE TITLE
FullCalendar does not work under non-secure HTTP

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3830]
### Environment
Jmix version: 2.4.0

### Bug Description
FullCalendar uses `window.crypto` that works only under HTTPS. Consider to replace it by a library or something else.

### Current Behavior
```
window.crypto.randomUUID is not a function
```

**Comment by Flaurite** [comment]
### For QA
To reproduce the issue use your local IP instead of "localhost" in the browser's address bar.

**Comment by maxcomgr** [comment]
Nope, it has not been fixed.
