### ISSUE TITLE
The error message on entity inspector view does not fit on the screen

### ISSUE THREAD

**Issue by OctagonDeluge** [jmix-framework/jmix#3834]
### Environment

Jmix version: 2.3.4

### Bug Description

When trying to import an entity via a json file, an error message appears and the message does not fit on the screen.

### Preconditions
Resolution: 1920 x 1080
Browser scaling: 100%

### Steps To Reproduce

- Launch provided project sample
- Navigate to Entity inspector
- Set Entity type to Department
- Click Import
- Import next JSON :
        [
          {
            "_entityName": "Department",
            "id": "0d7804e8-e219-0930-c727-62b2519a6596",
            "version": 1
          }
        ]

### Current Behavior

An error message appears that does not fit on the screen.
![image](https://github.com/user-attachments/assets/efcf9a6d-fd9c-4b19-a655-b69b71e84e11)

### Expected Behavior

An error message appears that fits on the screen.

### Sample Project

[jmix-onboarding-2-main.zip](https://github.com/user-attachments/files/17598600/jmix-onboarding-2-main.zip)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.5.999-SNAPSHOT
Jmix Studio plugin version: 2.5.SNAPSHOT6964-242
IntelliJ version: IntelliJ IDEA 2024.2.4 (Community Edition)
