### ISSUE TITLE
Migrate to 2.4.0 breaks reports

### ISSUE THREAD

**Issue by pbaris** [jmix-framework/jmix#3841]
### Environment

Jmix version: 2.4.0
Addon: Reports

### Bug Description

When migrating from version 2.3.4 to 2.4.0, the previously working reports breaks

Version 2.3.4
![image](https://github.com/user-attachments/assets/dbd02d75-072b-4743-9d23-c28225d64cb4)

After migrate to 2.4.0 the same report
![image](https://github.com/user-attachments/assets/ed548811-231c-49f3-87f4-a1f21644e38f)

### Steps To Reproduce

Run the report in version 2.3.4 of the attached project.
Migrate attached project to 2.4.0 version and run the report again.

### Current Behavior
I use a freemarker template in my report. It has problem with the nested objects. Now they are all Strings.

The same happens if i use groovy template engine for my report template. 

### Expected Behavior

Work as in version 2.3.4

### Sample Project
[test_reports.zip](https://github.com/user-attachments/files/17633164/test_reports.zip)

**Comment by Gavrilov-Ivan** [comment]
Regression due to https://github.com/jmix-framework/jmix/issues/3159.

As a hot fix those changes can be reverted on project side:

1. Override bean `io.jmix.reports.libintegration.JmixHtmlFormatter` (https://docs.jmix.io/jmix/modularity/extension.html#beans)
2. Override method `getBandModel`
    ```
    @Override
    protected Map getBandModel(BandData band) {
        Map<String, Object> model = new HashMap<>();
    
        Map<String, Object> bands = new HashMap<>();
        for (String bandName : band.getChildrenBands().keySet()) {
            List<BandData> subBands = band.getChildrenBands().get(bandName);
            List<Map> bandModels = new ArrayList<>();
            for (BandData child : subBands)
                bandModels.add(getBandModel(child));
    
            bands.put(bandName, bandModels);
        }
        model.put("bands", bands);
        Map<String, Object> data = new HashMap<>();
        for (String key : band.getData().keySet()) {
            if (band.getData().get(key) instanceof Enum) {
                data.put(key, defaultFormat(band.getData().get(key)));
            } else {
                data.put(key, band.getData().get(key));
            }
        }
        model.put("fields", data);
    
        return model;
    }
    ```

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6955-242
IntelliJ version: IntelliJ IDEA 2024.2.3 (Community Edition)
