### ISSUE TITLE
Increase liquibase version to provide compatibility with MySQL 8.4+ 

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix#3844]
As from reported on forum: [https://forum.jmix.io/t/audit-addon-not-supported-on-mysql-8-4/5758](https://forum.jmix.io/t/audit-addon-not-supported-on-mysql-8-4/5758)

new version of MySQL added word "Manual" to reserved keywords list [https://github.com/liquibase/liquibase/pull/6128](https://github.com/liquibase/liquibase/pull/6128)

This breaks compatibility with this and newer versions at least in Audit addon. 

Fixing changes for liquibase are added in version v4.30.0 that is not available in mvn repos yet. Current platform version is 4.27. A version update is proposed when packages will became available.

**Comment by syncro** [comment]
eclipselink/jpa/jdbc compatibility also may need to be checked

**Comment by knstvk** [comment]
We get Liquibase version from Spring Boot BOM.
Currently for SB 3.3.5 it's 4.27.0
