### ISSUE TITLE
Default value field of enumeration dynamic attribute

### ISSUE THREAD

**Issue by SergeiAksenov2** [jmix-framework/jmix#3857]
### Environment

Jmix version: 2.4.0

### Bug Description

Default value field is not available while creating enum dynamic attribute.
But this field is available when attribute is editing.

### Steps To Reproduce

Start to create enumeration dynamic attribute with default value.

### Current Behavior

Default value field is not available.

![image](https://github.com/user-attachments/assets/17f716f4-92b9-425d-bcc3-50a1c147953e)

### Expected Behavior

Default value field is available to clicking and contains the enam values.

**Comment by knstvk** [comment]
@SergeiAksenov2 - How does it work in 2.3?

**Comment by SergeiAksenov2** [comment]
@knstvk 
In 2.3 it works correctly.

**Comment by SergeiAksenov2** [comment]
Tested on Jmix version: 2.4.999-SNAPSHOT:
1) Jmix Studio plugin version: 2.5.SNAPSHOT6964-242
IntelliJ version: IntelliJ IDEA 2024.2.4 (Community Edition)
2) Jmix Studio plugin version: 2.5.SNAPSHOT6966-243
IntelliJ version: IntelliJ IDEA 2024.3 (Community Edition)
