### ISSUE TITLE
The action buttons for GridExport are incorrectly displayed

### ISSUE THREAD

**Issue by rusiaikinat** [jmix-framework/jmix#3867]
### Environment

Jmix version: 2.4.0

### Steps To Reproduce

Add an EXCEL button to the user-list view

### Current Behavior

![image](https://github.com/user-attachments/assets/13d3011b-1af6-4af6-9ec0-d5f1614758a6)

### Expected Behavior

![image](https://github.com/user-attachments/assets/b4b8ee59-01a2-457c-bc12-243b01543821)

**Comment by knstvk** [comment]
What is wrong? New row of buttons when the button text is long?

**Comment by glebfox** [comment]
**Solution:** changed fixed `width: 32em` to `min-width: 32em` `max-width: 50em`.
