### ISSUE TITLE
Unable to edit full-text condition in filter

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#3869]
### Environment

Jmix version: 2.4.0

### Bug Description

Editing of full-text condition within filter causes exception - unable to set value of comboBox.

### Steps To Reproduce

1. Create full-text filter condition on some browser view
2. Edit created filter configuration
3. Select and edit created full-text condition

### Current Behavior

Exception occurred.

### Expected Behavior

Editor of full-text condition should be opened.

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.5.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6961-243
IntelliJ version: IntelliJ IDEA 2024.3 (Community Edition)
2) Jmix version: 2.5.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6960-242
IntelliJ version: IntelliJ IDEA 2024.2.4 (Community Edition)
