### ISSUE TITLE
Non-editable DateField does not hide asterisk

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#387]
### Description
See Russian forum: [topic](https://forum.jmix.ru/t/na-datefield-otobrazhaetsya-otmetka-obyazatelnosti-zapolneniya-dazhe-esli-ekran-v-rezhime-readonly/248). **The same problem with TimeField.**

#### Steps to reproduce
1. Download attached project: [demo.zip](https://github.com/Haulmont/jmix-ui/files/7719682/demo.zip)

2. Open: _Application -> First store entities -> Order_
3. Try to "view" some record.

**ER**
Fields should be non-editable and without asterisk

**AR**
Only DateField has an asterisk

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
