### ISSUE TITLE
Unable to run with EnableJmixDataRepositories

### ISSUE THREAD

**Issue by Gamer08YT** [jmix-framework/jmix#3880]
### Environment:
- Jmix version 2.4.0.

### Bug Description: 
- Application does not run or build for production.

###  To reproduce the issue: 
- Add @EnableJmixDataRepositories in the Main Class or Configuration.

### Possible related issue: 
- https://github.com/vaadin/flow/issues/19616.

**Comment by knstvk** [comment]
Duplicates #3772
