### ISSUE TITLE
Focus ring is cut off for HorizontalMenu component

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3893]
### Environment

Jmix version: 2.4

### Bug Description

Focus ring is cut off for HorizontalMenu component

### Steps To Reproduce

1. Create **MainView with TopMenu**
2. Try to navigate to main menu by Tab key

### Current Behavior

Focus ring is cut off

<img width="497" alt="Screenshot 2024-11-19 at 16 30 50" src="https://github.com/user-attachments/assets/0904df39-0b49-4732-9b80-722d8e714ecc">

### Expected Behavior

Focus ring is clearly visible

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7033-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
