### ISSUE TITLE
default filter breaks url

### ISSUE THREAD

**Issue by pavkh** [jmix-framework/jmix#3906]
### Environment

Jmix version: 2.3.4

### Bug Description

Having default filter in view "breaks" url of screen with filter.

### Steps To Reproduce

1. Define filter in view via interface, save it and make default
![image](https://github.com/user-attachments/assets/c968d777-7fac-4a05-9844-8e41bcddc9e1)
2. Switch to other view
![image](https://github.com/user-attachments/assets/feabb912-8814-4ee1-92e7-588961ee4d24)
3.  Go back to view with default filter
![image](https://github.com/user-attachments/assets/1d932c7a-1e01-447e-911c-e379980cf014)

### Current Behavior
Url in browser at step 3 contains view route from step 2 and filter part from step 1

### Expected Behavior

Url in browser in step 3 same as step 1

### Sample Project

[https://github.com/pavkh/sample-jmix-project](https://github.com/pavkh/sample-jmix-project)

**Comment by KremnevDmitry** [comment]
Duplicate: https://github.com/jmix-framework/jmix/issues/3654
