### ISSUE TITLE
Fix report_showExecutionReportHistory action

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#3912]
### Environment

Jmix version: 2.4.999-SNAPSHOT

#### Point 1

The action should open the `ReportExecutionDialog` to select reports for which to display execution history.
But the `loadDelegate` is never loaded.
![image](https://github.com/user-attachments/assets/ece3a2f6-53a5-4a9b-861a-694cc459c88c)

#### Point 2

The table is not editable:
![image](https://github.com/user-attachments/assets/017755fd-4677-402e-a096-3bb3e2b71b41)

**Comment by gmmars** [comment]
It is not a bug.
To enable Execution history functionality it is required to add  jmix.reports.historyRecordingEnabled = true to application.properties

**Comment by KremnevDmitry** [comment]
> It is not a bug. To enable Execution history functionality it is required to add jmix.reports.historyRecordingEnabled = true to application.properties

@gmmars 
This is a bug.

In this example, the `jmix.reports.historyRecordingEnabled` application property has been set.
The `loadDelegate` is still never loaded.

Btw, the `enable` property for the button does not depend on the value of the application property.

**Comment by gmmars** [comment]
In this case i can not reproduce the issue. Without this property enabled the execution history really doesn't work. But when enabled, it works like a charm.

**Comment by KremnevDmitry** [comment]
> In this case i can not reproduce the issue. Without this property enabled the execution history really doesn't work. But when enabled, it works like a charm.

Double check if you are really using the `report_showExecutionReportHistory` action, which is set as an action for custom `DataGrid`? This `DataGrid` should display some entity related to the report.

How do you open the `ReportExecutionDialog` view?

**Comment by Flaurite** [comment]
### For QA
1. Add to the project: `jmix.reports.historyRecordingEnabled=true`
2. Create JPA entity and views
3. In Entity list view add:
   - to dataGrid: `<action id="reportHistory" type="report_showExecutionReportHistory"/>`.
   - and button with the given action
4. Create any report for the entity with "Report for list of entity" or "Report for single entity".
5. In report details, in "Roles and views" tab assign entity list view.
6. Create entity instance, and run report.
7. In entity list view open reports history dialog.

The report should be shown and can be selected.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7059-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
