### ISSUE TITLE
Exclude Vaadin Copilot dependency

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#3916]
Add the following to `build.gradle`:
```
configurations.implementation {
    exclude group: 'com.vaadin', module: 'copilot'
}
```

 to get rid of 

![Image](https://github.com/user-attachments/assets/e39b38cb-c426-4741-9f44-c22273a1aaa2)

**Comment by rusiaikinat** [comment]
`exclude group` successfully added in new (2.4.2) project. Adding is not performed during migration - this is normal
