### ISSUE TITLE
TenantProvider does not support substituted users

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#3947]
### Environment

Jmix version: 2.4.1

### Bug Description

The `TenantProvider#getCurrentUserTenantId()` returns tenant for current authenticated user, not for substituted. There is a case:
 - User: admin (no-tenant)
 - User: userA (a-tenant)
 
 When admin logs in as userA, the `TenantProvider#getCurrentUserTenantId()` returns `no-tenant` instead of `a-tenant`.

### Steps To Reproduce

1. Download demo project: [tenant-demo.zip](https://github.com/user-attachments/files/17947621/tenant-demo.zip)

2. Log in as admin
3. Change user to `userA`
4. Open `Application -> Demo view`

### Current Behavior
The view shows `Your tenant is no_tenant`

### Expected Behavior
The view should show `Your tenant is a-tenant`

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7042-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
