### ISSUE TITLE
Current locale query parameter

### ISSUE THREAD

**Issue by dgodlevskiy** [jmix-framework/jmix#3958]
Sometimes it's required to get the current session's locale in jpql query to get some records based on the locale. So it would be useful if the platform provides the current locale the same way as the :current_user or :current_session parameters.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.5.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7059-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
