### ISSUE TITLE
FileRef field contents support for default search strategies

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix#3968]
Currently when you add FileRef type to indexing and use * or just a field name in Indexing configuration search will not look into FileRef field's filename and contents.

This goes so besides indexing will add this info into the index data. 

This happens because search strategies add field names directly to query field list.

To make searching by file contents functional "out-of-box" SearchStrategy must include "${fieldname}.*" (or specify fileRef subfields _file_name and _content explicitly) when FileRef type is met.

![image](https://github.com/user-attachments/assets/ace5b920-e48d-4ca9-9a08-4b133cdd5d88)
[testjmixsearch241.zip](https://github.com/user-attachments/files/18004542/testjmixsearch241.zip)

**Comment by Gavrilov-Ivan** [comment]
Changes:

- Support search within FileRef field
- Two deprecated search strategy now also have explicitly specified set of search fields (to not search prefixes if enabled). And use escaped search text.

For QA: Besides FileRef search, check if all search strategies works as intended with and without enabled Advanced search.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7033-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
