### ISSUE TITLE
@TenantId from base class is ignored

### ISSUE THREAD

**Issue by syncro** [jmix-framework/jmix#3969]
Currently https://github.com/jmix-framework/jmix/blob/47d34fb97d63e6e4bda8b1c4db2b797ea17460c5/jmix-multitenancy/multitenancy/src/main/java/io/jmix/multitenancy/core/impl/TenantProviderImpl.java uses getDeclaredFields method to lookup tenantId field, but this method does not support class inherited fields. This makes developers unable to use tenant fields in parrent Entity classes (some of them used it in previous version) and can be easily improved.

**Comment by Flaurite** [comment]
###For QA
1. Download demo project: [tenant-demo.zip](https://github.com/user-attachments/files/18126733/tenant-demo.zip)
2. Log in as "userA" - "1"
3. Go to "Demo view"
4. It should show the "a-tenant"

Case 2:
1. Login as admin
2. Select substituted user - "userA"
3. Go to "Demo view"
4. It should show the "a-tenant"
