### ISSUE TITLE
Excel Export: OffsetDateTime Attributes Not Properly Formatted

### ISSUE THREAD

**Issue by timlehmkuhl** [jmix-framework/jmix#3973]
### Environment

Jmix version: 2.4.1

### Bug Description

When exporting a table to Excel that contains attributes of type OffsetDateTime (e.g., createdDate), the format of the date is not preserved. Instead of being formatted as shown in the list view (e.g., 27.11.2024 13:06), the exported value appears in its raw ISO 8601 format (e.g., 2024-11-18T14:11:37.292+01:00).

### Steps To Reproduce

1. Open the "Orders" list view.
2. Observe the createdDate column in the list, correctly formatted.
3. Export the list to Excel using the export functionality.
4. Open the exported Excel file and check the createdDate column.

### Current Behavior

The createdDate column in the exported Excel file displays values in ISO 8601 format (e.g., 2024-11-18T14:11:37.292+01:00).

### Expected Behavior

The createdDate column in the exported Excel file should display values formatted as they are in the list view, e.g., 27.11.2024 13:06.

### Sample Project
[offsetdatetimeexcel.zip](https://github.com/user-attachments/files/18023295/offsetdatetimeexcel.zip)

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7059-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
