### ISSUE TITLE
`grdexp_excelExport` and `grdexp_jsonExport` actions do not have an default icon and text

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3978]
See Studio issue: https://youtrack.jmix.io/issue/JST-5489/Excel-and-Json-buttons-do-not-have-an-icon-and-name

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7027-243
IntelliJ version: IntelliJ IDEA 2024.3 (Community Edition)
2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7028-242
IntelliJ version: IntelliJ IDEA 2024.2.4 (Community Edition)
