### ISSUE TITLE
Autocomplete for properties in PivotTable

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#3997]
See Studio issue: https://youtrack.jmix.io/issue/JST-5438

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.5.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7083-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
