### ISSUE TITLE
ContextHelpText attribute does not work for CheckBox component

### ISSUE THREAD

**Issue by GlebDurygin** [jmix-framework/jmix#402]
ContextHelpText attribute does not work for CheckBox component

- Minimal reproducible example

```
<checkBox caption="Custom Checkbox" contextHelpText="CONTEXT"/>
```

- Expected behaviour
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/4c4e8eea-69ab-46d2-9dae-73b433c99a26)

- Actual behaviour
![image.png](https://images.zenhubusercontent.com/5ca1d2f80ed044440d208a92/634f6ad0-22a2-4098-a628-b0970c384625)

**Comment by Flaurite** [comment]
Fixed in: [jmix-framework/jmix#400](https://github.com/jmix-framework/jmix/issues/400)
