### ISSUE TITLE
Improve error message on attempt to execute query for scalar values

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#4020]
The current error message reads "DataManager cannot execute query for single attributes".
Actually `DataManager` can execute such queries, just through different methods: `loadValues()` and `loadValue()`.

**Comment by knstvk** [comment]
Now the message is "Cannot execute query for scalar values in a method that loads entities. Use loadValues() and loadValue() methods instead."

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.5.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7083-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
