### ISSUE TITLE
Ability to pass parameters from menu item XML to bean and runnable class methods

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#414]
As it was in CUBA.
Now `io.jmix.ui.menu.MenuItemCommands#loadParams` always returns an empty collections.

**Comment by knstvk** [comment]
See also #300

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4337-213)
jmix version (1.3.999-SNAPSHOT)
CUBA (15.9-213)
