### ISSUE TITLE
Action overriding should be possible in addons

### ISSUE THREAD

**Issue by karstarr** [jmix-framework/jmix#420]
**Description**
Actual overridden action should be taken from the lowest module in the hierarchy.

**Reproducing steps**
1. Create addon;
2. Install addon Grid Export Actions;
3. Override the `io.jmix.uiexport.action.ExcelExportAction` according to the [documentation](https://docs.jmix.io/jmix/backoffice-ui/actions/custom-action-type.html);
4. Publish addon to the local maven repository;
5. Create a new Jmix project and install published addon in there;
6. Add to the User browser button to export data to Excel, and the corresponding action with `type="excelExport"`;
7. Start created project and try to export users to the excel file.

**ER**
The Grid Export Actions addon's action is called.

**AR**
The action from the third step is called.

**Comment by SergeiAksenov2** [comment]
Tested on:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6407-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

Addon: 
[T420-addon.zip](https://github.com/jmix-framework/jmix/files/15484699/T420-addon.zip)
Project:
[T420-project.zip](https://github.com/jmix-framework/jmix/files/15484710/T420-project.zip)

Steps tp reproduce:
1. Command to compile addon: ./gradlew publishToMavenLocal.
2. Add the addon to the project in Gradle.
3. Run the project.
4. Add breakpoint to the addon's actionPerform() method in AddonExcelExportAction class in the project.
5. Try to export users by 'Excel' button on Users list view.

Current behaviour:
The breakpoint will not be reached.
