### ISSUE TITLE
Strange filter field width behaviour

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#421]
While browser page width is growing, field width changes its width in random order.

![image](https://user-images.githubusercontent.com/13851473/146927696-96aa135e-c3e2-47e5-be91-74a352ac059e.png)

![image](https://user-images.githubusercontent.com/13851473/146927746-e90d3708-569e-47f7-a3bd-71e5d89ca9a9.png)

**Comment by gorbunkov** [comment]
Probably relates to #436
