### ISSUE TITLE
Support input prompt in ValuePicker

### ISSUE THREAD

**Issue by Gavrilov-Ivan** [jmix-framework/jmix#427]
ValuePicker component supports manual input (via fieldEditable attribute) so it will be useful to have input prompt on it.

## Solution

The following components now support `inputPrompt`:

* valuePicker
* valuesPicker
* entityPicker

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4306-213)
