### ISSUE TITLE
ExcelExportAction uses only the XLSX format

### ISSUE THREAD

**Issue by sukhova** [jmix-framework/jmix#429]
The `ExcelExportAction.java` mentions the phrase:

> Action for export table content in XLSX or XLS formats

But we can see:

`protected ExportFormat exportFormat = ExportFormat.XLSX;`

The logic of the `ExcelExportAction` class includes the work of XLS and XLSX, but there is no method to set the desired format.

**Comment by gorbunkov** [comment]
We decided not to support XLS format
