### ISSUE TITLE
Support 'year' options in date interval conditions

### ISSUE THREAD

**Issue by glaschenko** [jmix-framework/jmix#435]
I.e here:

![image](https://user-images.githubusercontent.com/17944806/130790191-6dcf32cf-aa78-43fb-ae0f-b14ab8ed26df.png)
![image](https://user-images.githubusercontent.com/17944806/130790256-b1f12443-338b-454b-ab0e-18ae5757c938.png)

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
