### ISSUE TITLE
Provide a single configuration for username claim name for OIDC and JWT resource access

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#441]
Currently OIDC login to web application and authentication using JWT bearer token use different mechanisms for creating the `OidcUser` object instance. The main problem is that they may use different claims for username.

For example, for web login we may define the following application property:

```
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
```

This means that Id Token claim with the "preffered_username" name will be used as Jmix user username.

However when accessing API using JWT token, the `JmixJwtAuthenticationConverter` uses the "sub" claim as a username by default.

We should consider using a single application property for both mechanisms or at least mention it in the documentation (maybe do not use the preferred_username by default).

Forum topic: https://forum.jmix.io/t/jmix-1-2-jmix-oidc-using-rest-api-has-some-issues/1215

**Comment by gorbunkov** [comment]
Additional application property has been added. This property is used to configure which JWT token claim should be used as a username.

```
jmix.oidc.jwt-authentication-converter.username-claim=preferred_username
```

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4305-213)
jmix version (1.3.999-SNAPSHOT)
