### ISSUE TITLE
CORS allowed origins setting should be applied to REST autorized urls

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#442]
There is the `jmix.rest.authenticated-url-patterns` application property that allows to protect custom Spring MVC controllers with Bearer token.

There is another property [jmix.rest.allowed-origins](https://docs.jmix.io/jmix/rest/app-properties.html#jmix.rest.allowed-origins) that specifies a list of origins that can access REST API. Currently, this property only affects requests to `/rest/**` and `/oauth/**` patterns. 

Probably, the patterns defined by the `jmix.rest.authenticated-url-patterns` should also be affected by the allowed origins setting.

Another thing is that maybe the CORS settings should be pulled to a higher level than the REST add-on, because users may have MVC controllers without including REST API (just jmix-security-oauth or authenticating using keycloak).

Forum: https://forum.jmix.io/t/cors-problem-with-authenticatedurlpatterns/1172

**Comment by Afanasevaa36** [comment]
1.3.999 - SNAPSHOT: Verified
