### ISSUE TITLE
DELETE operations should send a 204 (No Content) status code

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#446]
The [HTTP 1.1 specification](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.5
) says:

>    If a DELETE method is successfully applied, the origin server SHOULD
   send a 202 (Accepted) status code if the action will likely succeed
   but has not yet been enacted, a 204 (No Content) status code if the
   action has been enacted and no further information is to be supplied,
   or a 200 (OK) status code if the action has been enacted and the
   response message includes a representation describing the status.

We don't return any content in  response so the response code should probably be 204 instead of 200 (as we return now).
**QA Notes:**
Delete some entity through restApi and check that returned code is 204

**Comment by Afanasevaa36** [comment]
Jmix version: 1.4.999-SNAPSHOT
Verified
![Снимок экрана от 2022-07-27 13-48-10](https://user-images.githubusercontent.com/95623805/181229412-5e8a4d44-47d2-4177-9b7a-b4a80ba27087.png)
