### ISSUE TITLE
Circular reference error when adding the springdoc-openapi-ui dependency

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#458]
Create new project (Jmix 1.1.2)
Add REST API add-on
Add `implementation 'org.springdoc:springdoc-openapi-ui:1.6.4'` dependency
Start the application

AR:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  io.jmix.security.SecurityConfiguration (field private org.springframework.security.core.session.SessionRegistry io.jmix.security.SecurityConfiguration.sessionRegistry)
└──<-──┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.
```

See [forum topic](https://forum.jmix.io/t/openapi-failure/961)

**Comment by gorbunkov** [comment]
Relates to #287

**Comment by gorbunkov** [comment]
Check on FlowUI

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 2.0.0
2) Jmix version: 2.3.999-SNAPSHOT
3) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6604-233
IntelliJ version: IntelliJ IDEA 2023.3.7 (Community Edition)

Using dependencies
implementation 'org.springdoc:springdoc-openapi-ui:1.6.4'
implementation 'org.springdoc:springdoc-openapi-ui:1.8.0'

No Circular reference error - Ok.
