### ISSUE TITLE
Provide the ability to assign a role to multiple users

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#462]
Currently, the UI only allows to assign a role to a single user. However, it's a common case when some must be assigned to many users or even to all users of the application.

**Comment by KremnevDmitry** [comment]
For QA:
Multiple user selection will be added in a future (by other Issue)

**Comment by rusiaikinat** [comment]
**TC**
For `Resource roles` and `Row-level` roles screens
Click on the `Assign to users` button (the list contains users without this role)
Select users

Open Users screen 
Select a user with assigned roles 
Click the `Edit` button
**ER**
The user contains the added roles (Resource roles and Row-level roles)
