### ISSUE TITLE
Add the ability to allow access to a bean menu item for a role

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix#466]
based on forum's [question](https://forum.cuba-platform.com/t/menu-authorization/15591/3)

**Environment:**
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.0.2-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Community Edition)

**TC 1**
1. Create new Spring bean e.g. NewBean and add a method e.g. `sayHello`
2. Create new menu item with this bean method
3. Create new role -> Switch to Backoffice UI tab 

**TC 2**
1. Run app -> Open Resource roles browser -> Create new
2. Invoke Create -> Screen policy

**AR**:
it's impossible to allow access to a bean menu item for a role because it's not displayed on any of tabs in Studio / in any of lists in runtime

**Comment by SergeiAksenov2** [comment]
Tested on:
1)
2) Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6365-241
IntelliJ version: IntelliJ IDEA 2024.1.1 (Community Edition)
