### ISSUE TITLE
Set X-Frame-Options to SAMEORIGIN by default

### ISSUE THREAD

**Issue by glebshalyganov** [jmix-framework/jmix#475]
By default `X-Frame-Options` is set to `DENY` in spring security. But we need it to be set to `SAMEORIGIN` for the file downloading support.
As for now this setting is hardcoded in `JmixCoreSecurityConfiguration` and `StandardSecurityConfiguration`. But if clients want to provide their own security configuration, they should add this setting as well.
So it would be better to think about more generic approach.

**Comment by gorbunkov** [comment]
Duplicates #3493
