### ISSUE TITLE
Table header is broken if columns don't fit the table width

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#492]
- Start the attached project
[tickman.zip](https://github.com/jmix-framework/jmix/files/4740037/tickman.zip)

- The table header looks like this:
![image](https://user-images.githubusercontent.com/5513878/83944491-f0252580-a814-11ea-8340-212fdc0a52ec.png)
![image](https://user-images.githubusercontent.com/5513878/83944528-1b0f7980-a815-11ea-8af9-c0dc310efd46.png)
- It turns to normal if you move the last column to the left or decrease the columns width to fit the whole available width.

**Comment by Flaurite** [comment]
Migrate fix from: [cuba-platform/cuba#2925](https://github.com/cuba-platform/cuba/issues/2925)
