### ISSUE TITLE
Throw GuiDevelopmentException when using incorrect container type

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#514]
See https://github.com/cuba-platform/cuba/issues/3173 as an example

**Comment by KremnevDmitry** [comment]
Could you provide more information about the issue? Which container type is not considered correct?

**Comment by glebfox** [comment]
> Could you provide more information about the issue? Which container type is not considered correct?

Instance container cannot be used as `dataContainer` for DataGrid or `itemsContainer` for ComboBox like components

**Comment by KremnevDmitry** [comment]
Using `CollectionPropertyContainer` to display a selection list is valid for Jmix Framework.

```xml
    <data>
        <instance id="orderDc"
                  class="com.company.master.entity.Order">
            <fetchPlan extends="_base">
                <property name="customer" fetchPlan="_instance_name"/>
                <property name="orderItems" fetchPlan="_base"/>
            </fetchPlan>
            <collection id="orderItemsDc" property="orderItems"/>
            <loader id="orderDl"/>
        </instance>
    </data>
    <layout>
    <!-- some code -->
       <textField label="Favorite" dataContainer="orderItemsDc" property="name" readOnly="true"/>
   </layout>
```
Result: 
![image](https://github.com/jmix-framework/jmix/assets/75516667/815af5db-73ae-4edc-b798-a203b54107df)
