### ISSUE TITLE
Declarative actions for entity editor

### ISSUE THREAD

**Issue by alexbudarov** [jmix-framework/jmix#519]
Create mechanism of declarative actions for entity editor.
Those can be applied to:
- entity editor screen
- entity combined screen
- ... or any screen with instance container ?? Need to think.

Such actions have access to the edited entity, and are integrated with screen lifecycle (update state after edited entity changed or after commit etc.)

Actions should be annotated for later integration into Studio UI.

Examples / ideas of such actions:
- already existing editor actions, e.g. commit
- rollback changes (reload edited item)
- "Save and new" - jmix-framework/jmix#523
- run report(s) for edited entity
- send by email / sms / slack ...
- copy permanent link to edited entity
- start associated business process...

**Comment by gorbunkov** [comment]
Implemented in FlowUI for existing actions
