### ISSUE TITLE
Provide an ability to define custom DataGrid.Renderer for the column declaratively

### ISSUE THREAD

**Issue by GlebDurygin** [jmix-framework/jmix#525]
### Description of the bug or enhancement
In Jmix project the DataGrid.Rendereres have become prototype beans (#509). But user cannot define custom DataGrid.Renderer for the column declaratively. 
Maybe we can add `<custom bean="bean_name" />` element to `<renderers/>` to allow the user to define a custom DataGrid.Renderer for the column declaratively.

See [Vaadin documentation](https://vaadin.com/docs/v8/framework/clientsidewidgets/clientsidewidgets-grid.html#clientsidewidgets.grid.renderers) for information on implementing custom renderers.

**Comment by glebfox** [comment]
For flow UI there is a separate issue: https://github.com/jmix-framework/jmix/issues/3101
