### ISSUE TITLE
Provide an ability to define custom field Validator declaratively

### ISSUE THREAD

**Issue by GlebDurygin** [jmix-framework/jmix#534]
### Description of the bug or enhancement
In Jmix project the Validators have become prototype beans (#510). But user cannot define custom Validator for the field declaratively, because legacy `<validator/>` element has been moved to compatibility module. 
Maybe we can add `<custom bean="bean_name" />` element to `<validators/>` to allow the user to define a custom Validator declaratively.

**Comment by glebfox** [comment]
@GlebDurygin add samples
