### ISSUE TITLE
UI is not good with horizontal scroll

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#539]
See https://github.com/Haulmont/jmix-appsettings/issues/3

Jmix version: 1.2.999-SNAPSHOT

1. Run project [addonsIn120.zip](https://github.com/Haulmont/jmix-appsettings/files/8187142/addonsIn120.zip)
2. Open Administration > Application settings
3. Select "Custom settings"
4. Make window size smaller to see both scrolls
5. Scroll all the way to the right, look at the fields
6. Select "Sorted settings"
7. Make window size higher to see only horizontal scroll
8. Scroll all the way to the right, look at the fields

Actual: the right border of fields are not visible
<img src="https://user-images.githubusercontent.com/73226373/156798678-2226bb69-632c-4b2f-bcaf-852d3046c5a6.png" height="250"/> <img src="https://user-images.githubusercontent.com/73226373/156798870-ea7d88b3-7a71-47e0-9071-f3595f3efb10.png" height="350"/>

Expected: goog UI of field
<img src="https://user-images.githubusercontent.com/73226373/156799173-3da9868b-2a30-4c56-96b7-6ae1cec7dfed.png" height="40"/>

**Comment by reznikova21** [comment]
1.2.999-SNAPSHOT - verified
