### ISSUE TITLE
Total band is printed in a wrong position in case of vertical bands

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#553]
Report template type: XLSX
Bands orientation: Vertical

When you add a band with total values after the main band (on the right side) then in the generated report the total band should be printed after all data bands.

The template:
<img width="1021" alt="Screenshot 2021-10-13 at 15 47 03" src="https://user-images.githubusercontent.com/7888486/137138785-ac8940e1-fa38-4d9e-b1b4-8f1213cd6c33.png">

The report result:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/7888486/137138977-f6754b91-60ed-4bfb-9e8c-eb88eda4a8b5.png">

In case of horizontal band orientation the total band is printed on the very bottom, after all data band elements.

The same thing is relevant for crosstab reports.

The sample project: [jmix-horizontal-reports.zip](https://github.com/Haulmont/jmix-reports/files/7338349/jmix-horizontal-reports.zip)

The report: [Report for entity _Order_ (1).zip](https://github.com/Haulmont/jmix-reports/files/7338354/Report.for.entity._Order_.1.zip)

CUBA Platform forum topic: https://www.cuba-platform.ru/discuss/t/perekryostnaya-polosa-zapolnyaet-polosu-s-itogami-sprava-exel-generacziya-otchyotov/6067

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4333-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
