### ISSUE TITLE
Impossible to set the body encoding type

### ISSUE THREAD

**Issue by awillaum** [jmix-framework/jmix#556]
Hi,

I don't find how to change encoding type of the body so when I send an email in french I receive an email with bad character 

`Bonjour lara croft [lara@croft.com], 

Han Solo [han.solo@alliancerebel.com] vient de vous inscrire � l'�v�nement Crunch Time 2022.
Voici les informations pour vous connecter :

nom d'utilisateur : lara@croft.com
mot de passe : 

Nous allons prochainement activer votre compte.

Cordialement

l'�quipe du Crunch Time`

**Comment by gorbunkov** [comment]
The issue is probably related to https://github.com/jmix-framework/jmix/issues/651 and should be fixed in 1.2.2
