### ISSUE TITLE
Resent important message is not marked as important

### ISSUE THREAD

**Issue by m-orlova** [jmix-framework/jmix#559]
Jmix version: 1.1.0
Project: [emailsending.zip](https://github.com/Haulmont/jmix-email/files/7625722/emailsending.zip)
 
**Steps to reproduce:**
1. Configure email properties in `application.properties` such as SMTP host, port, username, and password.
2. Open menu: Application -> Email sending screen.
3. Click on  the "Send Important Email" button
4. Open menu: Administration -> Email history
    AR=ER: Message is created and the "Important" flag is set as true.
6. Select this message and click the "Resend email" button.
7. Input details to resend an email and click the Resend button.
8. Click on the "Refresh" button.
9. Select resent message and check a value of the "Important" flag.
AR: Resent message is not marked as important
ER: Resent message is marked as important

**Comment by Dylay** [comment]
> Jmix version: 1.1.0 Project: [emailsending.zip](https://github.com/Haulmont/jmix-email/files/7625722/emailsending.zip)
> 
> **Steps to reproduce:**
> 
> 1. Configure email properties in `application.properties` such as SMTP host, port, username, and password.
> 2. Open menu: Application -> Email sending screen.
> 3. Click on  the "Send Important Email" button
> 4. Open menu: Administration -> Email history
>    AR=ER: Message is created and the "Important" flag is set as true.
> 5. Select this message and click the "Resend email" button.
> 6. Input details to resend an email and click the Resend button.
> 7. Click on the "Refresh" button.
> 8. Select resent message and check a value of the "Important" flag.
>    AR: Resent message is not marked as important
>    ER: Resent message is marked as important
