### ISSUE TITLE
Unhandled exception if document with the same name is uploaded and `jmix.webdav.auto-generate-unique-resource-uri` property is disabled

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix#565]
**Environment:**
Jmix version: 1.2.0-RC1
Jmix Studio plugin version: 1.1.SNAPSHOT3577-212
IntelliJ version: IntelliJ IDEA 2021.3.1 (Community Edition)

**TC:**
1. Open the attached project -> Run the app
2. Open the New entities browser
3. Create two instances -> upload the same document 

**AR:**
unhandled exception is displayed:
![image](https://user-images.githubusercontent.com/45730069/155990579-1987645a-a2de-42ad-beeb-2d01c520721e.png)

**ER:**
the error notification is displayed as follows:
![image](https://user-images.githubusercontent.com/45730069/155990697-16c27c9c-8f64-4d1c-84bb-ff79c5016b75.png)
[webd.zip](https://github.com/Haulmont/jmix-webdav-public/files/8153621/webd.zip)

**Comment by syncro** [comment]
For the moment this error is actually not reproducable neither for v.2 nor for 1.6:
1. When database is set as PostgreSQL as on screenshot provided application shows "handled" error messages as there is a database constraint
2. When database is HSQL or MySQL or any other webdav addon allows to create items with the same names as no constraints for field fullPath are defined in database migration scripts
