### ISSUE TITLE
Webdav credentials are not set when creating new user

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#566]
When `jmix.webdav.authenticationMethod = digest`, user passwords must be hashed and stored in `webdav_credentials` table.
Now it is done only when you change a user password. So if you create a new user, the server won't be able to authenticate webdav requests for this user with digest auth.

**Comment by gorbunkov** [comment]
UserEdit templates have been changed for Java and Kotlin, so we need to test this issue on both languages. The fix will only work for new projects. Existing projects will still have this problem.

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
