### ISSUE TITLE
User is able to edit current document's versions

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix#569]
**Environment:**
Jmix version: 1.0.1
Jmix Studio plugin version: 1.1.SNAPSHOT3517-212
IntelliJ version: IntelliJ IDEA 2021.2 (Ultimate Edition)
OS: Windows 10
desktop app: MS Office 16
add-on version: 1.1.0-SNAPSHOT

**TC:**
1. Create new project -> add add-on
2. Run the app
3. Open browser -> Open document browser
4. Upload any files
5. Select any file and click Manage versions OR click v2 near filename
6. Select any file and click Copy to head OR upload new file -> Save
7.  Select any file and click Manage versions OR click v2 near filename
8. Click a link of any document version
9. Authorize in desktop app
10. Click button for enabling editing

**AR:**
User is able to edit this file, there is no access error

**ER:**
user should not be able to edit file opened via link in the version's manager

**Comment by SergeiAksenov2** [comment]
Tested on:
1) Jmix version: 1.6.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7059-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)
2) Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT7059-243
IntelliJ version: IntelliJ IDEA 2024.3.1 (Community Edition)

To save a document in WebDAW, you must open the document itself in the WebDAV table, but not the versioned document on the versioning form.
