### ISSUE TITLE
Caption of createButton has no localized resource in ntf_InAppNotification.browse

### ISSUE THREAD

**Issue by artemy63** [jmix-framework/jmix#571]
see forum topic https://forum.jmix.ru/t/knopka-create-new-notification-v-ntf-inappnotification-browse-ne-imeet-lokalizaczionnogo-resursa/375

![image](https://user-images.githubusercontent.com/26215116/158976516-af8ce174-f0ce-4a99-b5ac-5afdb56ab1d4.png)

**Comment by reznikova21** [comment]
1.2.999-SNAPSHOT - Verified
