### ISSUE TITLE
A dialog does not appear before closing the editor with unsaved data

### ISSUE THREAD

**Issue by zhenyazb** [jmix-framework/jmix#572]
A dialog does not appear before closing the editor with unsaved data in the following cases:

One
1. Go *Administration -> Notifications* 
2. Click the *Create* button and fill in some fields.
3. Click the cross button of the editor.

Two
1. Go *Administration -> Notifications* 
2. Click the *Create* button and fill in some fields.
3. Click the *Cancel* button in the editor.

Three
1. Go *Administration -> Notifications* and create a new notification.
2. Open the created notification for editing.
3. Make changes in some fields.
4. Click the *Close* button in the editor.

Four
1. Go *Administration -> Notifications* and create a new notification.
2. Open the created notification for editing.
3. Make changes in some fields.
4. Click the cross button of the editor.

ER: The gialog will appear
![image](https://user-images.githubusercontent.com/45868670/154244964-7e1dcc9e-9652-4019-812b-e44aab4013e0.png)
AR: The editor is closed.

**Comment by Gavrilov-Ivan** [comment]
Check if it's relevant for 2.2 and 1.6
