### ISSUE TITLE
Wrong icon in process instance diagram for emailSendingTask and entityDataTask

### ISSUE THREAD

**Issue by artemy63** [jmix-framework/jmix#584]
See forum topic https://forum.jmix.ru/t/pri-prosmotre-diagrammy-vypolnyaemogo-proczessa-dlya-send-email-task-ispolzuetsya-nekorrektnaya-ikonka/367

The problem is actual for EmailSendingTask and EntityDataTask

**Comment by artemy63** [comment]
Notes for QA:
In case of using any of entityDataTask or emailSendTask icons for these tasks should look identically in BPMN modeler and diagram viewer for process instance

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4231-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
