### ISSUE TITLE
Possible improvement of User task caption 

### ISSUE THREAD

**Issue by artemy63** [jmix-framework/jmix#585]
See forum topic https://forum.jmix.ru/t/usertask-i-eyo-zagolovok/372

Maybe it makes sence not to add "Complete ${taskName}  task" for each user task, cause if user task has a name it already contains statement of work

**Comment by artemy63** [comment]
For QA:
  Caption for all user task forms should not have any "Claim % task" or "Complete %task" captions. If a user task has a name, it should be used as user task form caption, if there are no name for given user task it identifier should be used

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4308-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
