### ISSUE TITLE
Support dynamic attributes in EntityDataTask

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#589]
If the *Dynamic Attributes* add-on is included to the project, we may allow setting and updating of dynamic attribute values in the EntityData task (with *create entity* and *modify entity* types).

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4209-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
