### ISSUE TITLE
Support JPQL query parameters for EntityDataTask

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#591]
Currently, EntityDataTask that loads entities with JPQL queries doesn't support external query parameters. It will be useful to be able to use process variable values as query params.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.2.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4163-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
