### ISSUE TITLE
Add validation for fill mandatory attrs via Create Entity Data Task

### ISSUE THREAD

**Issue by maistrenkoIulia** [jmix-framework/jmix#602]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3579-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)

There isn't validation now, so it's possible to create new entity via  Create Entity Data Task without filling all mandatory (containing @NotNull) attr

relates to https://github.com/Haulmont/jmix-bpm-public/issues/27

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4209-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
