### ISSUE TITLE
Required to update xsd schema to support EntityDataTask, EmailTask and class attribute for flowable:eventListener

### ISSUE THREAD

**Issue by maistrenkoIulia** [jmix-framework/jmix#607]
Required to update xsd schema to support EntityDataTask, EmailTask and class attribute for flowable:eventListener
also for signal -> flowable:scope="global" 
![image](https://user-images.githubusercontent.com/66992566/137113863-783031eb-0921-4db0-9d29-87e13efff728.png)

**Comment by gorbunkov** [comment]
Must have been fixed in https://youtrack.jmix.io/issue/JST-2401
