### ISSUE TITLE
'Class', 'Entity type' fieds in Event listener editor should be mandatory/'Events' should contain at least one value

### ISSUE THREAD

**Issue by maistrenkoIulia** [jmix-framework/jmix#608]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3541-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)

TC: run app>modeler>create new process
for the process>event listener>create
ER:It's possible to create event listener with empty fields
AR:'Class', 'Entity type' fieds in Event listener editor should be mandatory/'Events' should contain at least one value

open Class dropdown
ER: values should be sorted by name
AR:
![image](https://user-images.githubusercontent.com/66992566/134498988-ed94eb0b-2e71-4b09-aab0-e02a260c1b5d.png)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4169-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)

Case 1 - **Passed**
Class fied is mandatory. Events and EntityType are optional.

Case 2 - **Failed** 
Values in Class dropdown aren't sorted by name.
![event_listeners_sorting-by-name_failed608](https://user-images.githubusercontent.com/85500330/161525792-938efca9-505c-43e2-a84b-067b17a5167d.png)

**Comment by artemy63** [comment]
Applied default sorting for all event listener names in editor

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4178-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
