### ISSUE TITLE
It shouldn't be possible to create a new form param via ui

### ISSUE THREAD

**Issue by maistrenkoIulia** [jmix-framework/jmix#617]
Jmix version: 1.0.0-SNAPSHOT
Jmix Studio plugin version: 1.0.SNAPSHOT2958-211
IntelliJ version: IntelliJ IDEA 2021.1.1 (Community Edition)

TC: 
create screen in idea> for controller add annotation
``` @ProcessForm(
        params = {
                @Param(name = "variableName"),
                @Param(name = "lookupCaption")
        }
```
run the app with bpm
BPM>Modeler>start task
form type = jmix screen, select screen id from dropdown list
1. form params table>context menu>create
ER: It shouldn't be possible to create a new form param
AR: It's possible to create new form param
2. select a form param
3. ER: edit button should be present
4. AR: it's possible to edit param only by double click

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4138-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
