### ISSUE TITLE
ProcessInstanceData should contain information about user who starts this process

### ISSUE THREAD

**Issue by artemy63** [jmix-framework/jmix#618]
It is necessary to fill `ProcessInstance#startUserId` with current authenticated user when actually start a new process in the same manner as we have in Bproc.

**Comment by artemy63** [comment]
Also Flowable table `act_hi_procinst` in column `start_user_id_` should contain username of the user who started process

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4209-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
