### ISSUE TITLE
Messages are not added to main messages.properties if other locale is defined in add-on project

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#623]
Environment:

Jmix version: 1.2.0

Jmix Studio plugin version: 1.2.0-213

IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)

TC:
1. Create single module addon project

2. Add new locale to addon

3. Create a new JPA entity and add any attributes

4. Open the messages.properties

AR:

messages are added to messages_xx.properties only:
![image](https://user-images.githubusercontent.com/61343016/159237128-4612bab2-0bc7-4a10-b885-63b77b0b2c90.png)

**Comment by Afanasevaa36** [comment]
1.3.999-SNAPSHOT
1.2.0-SNAPSHOT
Verified
