### ISSUE TITLE
Getter mismatch causing NPE during entity loading

### ISSUE THREAD

**Issue by owlet1997** [jmix-framework/jmix#626]
see [the issue](https://github.com/cuba-platform/cuba/issues/3264)

**Environment:**
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4110-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)

Test project for Jmix is attached, TC is the same
[frmjmx.zip](https://github.com/jmix-framework/jmix/files/8321673/frmjmx.zip)

**Comment by konyashkina** [comment]
Teted on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4335-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
