### ISSUE TITLE
Multiple outcome buttons are not displayed correctly in the Input Dialog process form

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#628]
Jmix version: 1.3.999-SNAPSHOT

Define an input dialog process form the User Task.
Add multiple outcomes with long captions. Start the process and open the form for the user task.

AR: the ford outcome button is not displayed, the button for the second outcome is cut.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/7888486/159457231-2ab53394-fbcd-4616-826b-0e9eb52eb647.png">

We have following solutions:

* increase the default input dialog form width
* allow user to set the form width in the modeler
* change the buttons panel layout to layout that support line wrapping, e.g. buttons that doesn't fit to the current row will be put to the next row (seems the best option for me)
* put buttons panel into a scrollbox

**Comment by artemy63** [comment]
For QA:
It is necessary to model a simple process, startEvent -> userTask -> endEvent.
For userTask choose "Input dialog" as "form" and specify multiple outcomes with diffeent captions.
Start the process and ensure that input dialog with any number of outcomes looks good (there is no any hidden outcomes or any overlapping between them)
