### ISSUE TITLE
Unnecessary text field is displayed in a report template editor

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#629]
Jmix: 1.2.1

Create a report with XLSX template
Open the report in the editor
Switch to Templates tab and edit the template
Change Output type from XLSX to PDF

AR:
Some weird text area appears

![Screenshot 2022-03-22 at 20 17 52](https://user-images.githubusercontent.com/7888486/159526289-a5a1f492-d1a2-478e-8c47-22ab061baa15.png)

![Screenshot 2022-03-22 at 20 18 04](https://user-images.githubusercontent.com/7888486/159526318-0d76b6fe-3aaa-4efd-a70b-72b3265e1b4e.png)

The similar behavior is in CUBA reporting as well. So we must first try to figure out is this a bug or this text area is required for something.

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
