### ISSUE TITLE
@DependsOnProperties caused exception

### ISSUE THREAD

**Issue by codingxu97** [jmix-framework/jmix#632]
I had two Entity which called A and B, and A was a property in B. there was only one property in A called `name`.

I hope to get `name` using Entity B directly, bypass Entity A, in order to make something easier, so I used @DependsOnProperties.

Here was the code in Entity B:
```
@DependsOnProperties("a")
@JmixProperty
fun getName(): String? = a?.name
```

So, two entity was built like this:
A
-- name

B
-- A
-- name (related to A)

Then I created a editor called BEdit which didn't use property `name` related Entity A, only contained one field A, like this:
![B Ediotor](https://user-images.githubusercontent.com/35094351/159866350-6f60a36a-97b2-42f8-b2f8-e7d2ad813eb0.png)

But, exception occurred when I picked the entity A, like this:
![Pick](https://user-images.githubusercontent.com/35094351/159866911-caafa2e5-3810-4a6c-925f-bf4735e9fa2c.png)

Here was exception: 
```
IllegalStateException: Cannot get unfetched attribute [name] from detached object com.codingxu97.demojmix.entity.A-924a43e2-a060-3346-ba1e-213195ae65cf [detached].
```

It could works only by adding property `name` to A's Fetch Plan, like this:
```
<collection id="aDc" class="com.codingxu97.demojmix.entity.A">
    <fetchPlan extends="_instance_name">
        <!--  add following code   -->
        <property name="name"/>
    </fetchPlan>
    <loader>
        <query>select e from A e</query>
    </loader>
</collection>
```

It looks strangy, I didn't use property `name` in B, but property `name` led to the exception.

Here was the [Demo Project](https://github.com/codingxu97/demo-jmix).

**Comment by codingxu97** [comment]
Hi, I thought that it could be manifested as following rules:
1. if entity `B` used `@DependsOnProperties("a")`, but not used property `name` in Edit or Browse, the query didn't need to load property `name`.
2. if `BEdit` used property `name`, the query could load property `name` automatically, and no longer need to add `name` to fetch plan.

These were some of my humble opinion. Might I know your opinion about the issue? @dtaimanov 

Thanks! :)

**Comment by dtaimanov** [comment]
Hello,
It is normal behaviour. Setting value to property leads to invocation of property change listeners for dependent properties as well as for current one. Because in fact dependent properties have been updated too by this operation and related listeners must be notified to process this changes.

In order to notify listeners new value has to be calculated, so all properties that required to calcule value of dependent property has to be loaded too.

**Comment by codingxu97** [comment]
> 1. if entity `B` used `@DependsOnProperties("a")`, but not used property `name` in Edit or Browse, the query didn't need to load property `name`.
> 2. if `BEdit` used property `name`, the query could load property `name` automatically, and no longer need to add `name` to fetch plan.

Yeah, I knew how it works roughly. but, was there any way to meet my demand? Thanks ! @dtaimanov .

**Comment by dtaimanov** [comment]
Hello, @codingxu97! 
Sorry for the late reply.
>was there any way to meet my demand?

Unfortunately it is no way. If such thing could be possible, fetch plans would not be needed at all on edit/browse screens and all properties would be loaded according to screen usage, but screens is highly customisable and there is no guarantee that developer did not added field, screen fragment or even method in controller that relies on particular property. 
So all properties in fetch plans should be listed manually.
