### ISSUE TITLE
Upgrade to Flowable 6.7.2 release

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#633]
https://github.com/flowable/flowable-engine/releases/tag/flowable-6.7.2

**Comment by artemy63** [comment]
For QA
It's necessary to perform smoke test 
- model a process and deploy it
- check process definition editor screen
- start process functionality
- check process instance editor for active and completed process

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4222-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
