### ISSUE TITLE
InAppNotificationChannel should save notification in separate transaction

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#636]
Now InAppNotificationChannel joins an existing transaction. It causes the following problems:
- If the transaction is rolled back, the notification is shown in UI but not saved
- If you send a notification in an after-commit entity listener (annotated with `@TransactionalEventListener`), the current transaction still exists but in the post-commit phase. It means that DataManager doesn't start a new one automatically and fails when saving the notification.

**Comment by reznikova21** [comment]
1.2.999-SNAPSHOT - verified
