### ISSUE TITLE
Pagination becomes disabled when the last item on the last page is removed

### ISSUE THREAD

**Issue by Flamesson** [jmix-framework/jmix#644]
**Preconditions:**
- A pagination with 10 items per page exists.
- 21 entity is visible in a browse screen.

![Screenshot 2022-03-30 at 10-04-46 Jmix Pagination Problem application](https://user-images.githubusercontent.com/51899225/160764912-6a65bdb9-87f5-4b87-9f22-074244ef2bf8.png)

**Steps:**
- Remove 21-th entity (on third page of the paginaton)

**What expected:**
- First and second pages are available to click and open and current page - is empty. Or previous page is opened.

**What got:**
- Not available to open previous pages (they are not visible).

![Screenshot 2022-03-30 at 10-04-54 Jmix Pagination Problem application](https://user-images.githubusercontent.com/51899225/160765289-cd8b0692-59ab-4437-80b0-1ee641ac699d.png)

**Sample project:**
https://github.com/izumi-jmix/jmix-pagination-problem

**Comment by kendovitskii** [comment]
Verified on
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4170-213)
jmix version (1.3.999-snapshot)
