### ISSUE TITLE
Tenant is not saved

### ISSUE THREAD

**Issue by klaus7** [jmix-framework/jmix#647]
Reproduce:
- change an entity with a tenant user
- `EntityLogItem` tenant column `SYS_TENANT_ID` is still set to null - look in database directly

Minimum test project included:

credentials: user: t1, password: t1

[auditnotenant.zip](https://github.com/jmix-framework/jmix/files/8390119/auditnotenant.zip)

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
