### ISSUE TITLE
Email templates addon does not work properly with cyrillic

### ISSUE THREAD

**Issue by Afanasevaa36** [jmix-framework/jmix#651]
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT4166-213
IntelliJ version: IntelliJ IDEA 2021.3.3 (Ultimate Edition)
See forum [topic](https://forum.jmix.io/t/email-templates-addon-does-not-work-properly-with-cyrillic/1289)
**Steps**:

1. Create new project.
2. Install Email templates addon.
3.  Run project
4. Log in
5. Administration>Email templates
6. Create from designer
7. In the field "Name" and "Code" enter "Test"
8. Click button "HTML code"
9. Insert a code snippet: [Code.txt](https://github.com/jmix-framework/jmix/files/8396238/Code.txt)
10. In the field "To" enter Email adress
11. Click OK
12. Select the created template and click button Send.
13. Click button Preview.

**ER**:
A ready-made version of the template will be displayed
![Screenshot_1](https://user-images.githubusercontent.com/95623805/161231537-6fea0be3-2b87-45bc-828a-3ba90cabea9a.png)

**AR**:
![Screenshot_2](https://user-images.githubusercontent.com/95623805/161231663-84bfce04-12f1-412d-88b9-7efb4b4e120d.png)

**Comment by artemy63** [comment]
For QA:
1. It is assumed that changes should be done into YARG library, commit with fix already there - https://github.com/cuba-platform/yarg/commit/d9dd7a1f41ee77f7abee53c0588373f618b09e42
2. It is necessary to build and install YARG locally as described in trevis.yaml:
```
cd core
/gradlew --no-daemon assemble install
```
3. After YARG installed locally it is necessary to rebuild `jmix-reports` with that YARG version, it is necessary to change version in `bom.gradle` - https://github.com/jmix-framework/jmix/blob/master/jmix-bom/bom.gradle#L340 and build and install reports locally
