### ISSUE TITLE
DataLoader was loaded in strange sequence

### ISSUE THREAD

**Issue by codingxu97** [jmix-framework/jmix#655]
There was a strange behavior in `DataLoader` when I used `InstanceContainer` and `CollectionLoader`.

First, we put aside specific scenarios, let's debug the code.

Interface `ScreenData`  was designed to save Screen's data, e.g. data context, all data loaders.

```
protected DataContext dataContext;

protected Map<String, InstanceContainer> containers = new HashMap<>();

protected Map<String, DataLoader> loaders = new HashMap<>();
```

Each loader were registered in `loaders` when new screen was loaded:
```
@Override
public void registerLoader(String id, DataLoader loader) {
    loaders.put(id, loader);
}
```

Then, each loader was going to load as its defination, ```ScreenData``` got each id as a collection in loads:
```
public Set<String> getLoaderIds() {
    return loaders.keySet();
}
```

Each load was going to execute in sequence of collection, but a potential exception occurred.

**The `loaders` was a map used `HashMap`. Each loader was registered in `loaders` in sequece, but they didn't order in sequece, their execution order just depended on their hashcode of id**, so it was uncontrollable and even random behavior.

Finally, let's analyze the specific scenarios I had met.

I had some entities, they formed as following structure:
AEntity
--- blist (BEntity)

BEntity
--- c (CEntity)

So, I was supposed to use collection of `c` related the property `blist` as `cField`'s list of options.

Here was XML and Kotlin code:
```
<instance id="aDc" class="com.codingxu97.demojmix.AEntity">
    <fetchPlan extends="_base">
        <property name="bList" fetchPlan="_instance_name">
            <property name="c" fetchPlan="_instance_name"/>
        </property>
        <property name="c" fetchPlan="_instance_name"/>
    </fetchPlan>
    <loader/>
</instance>

<collection id="cDc" class="com.codingxu97.demojmix.CEntity">
    <fetchPlan extends="_instance_name"/>
    <loader id="cLoader"/>
</collection>

...

<entityComboBox id="cField" property="c" optionsContainer="cDc"/>

```

```
@Install(to = "cLoader", target = Target.DATA_LOADER)
private fun cLoaderLoadDelegate(loadContext: LoadContext<CEntity>): List<CEntity> {
    val bList = editedEntity.bList ?: return emptyList()
    return bList.mapNotNull { it.c }
}
```

Strange thing happend. When I clicked edit button which was belong to `AEdit`, unfecthed exception occurred occasionally, puzzled me a lot. it didn't occurred certainly, so I started to debug until I saw the above and following source code in class `ScreenDataXmlLoader`:
```
    protected void loadInstanceContainer(ScreenData screenData, Element element, @Nullable ScreenData hostScreenData) {
        ...

        Element loaderEl = element.element("loader");
        if (loaderEl != null) {
            loadInstanceLoader(screenData, loaderEl, container, hostScreenData);
        }

        ...
    }

    protected void loadInstanceLoader(ScreenData screenData, Element element, InstanceContainer<Object> container,
                                      @Nullable ScreenData hostScreenData) {
        ...

        String loaderId = element.attributeValue("id");
        if (loaderId == null) {
            loaderId = generateId();
        }

        ...
    }

    protected String generateId() {
        return RandomStringUtils.randomAlphanumeric(8);
    }
```
`LoaderId` was determined by its element id, but it would be genrated as a random string when element id was null.
It seemd that the element id of `InstanceContainer` was null, so it would be generated as long as screen loaded. Then would exception occurred when `loaderId` of `InstanceContainer` was not first one in collection of `loaderId`.

Therefore, execution of `InstanceContainer` loader was random which caused the exception.

**Comment by codingxu97** [comment]
Use `LinkedHashMap` instead of `HashMap` might be one of approach to avoiding the exception. It seemd that LinkedHashMap wouldn't affect much performance in this case.

**Comment by knstvk** [comment]
Thank you for the detailed description of the problem. 
You are right, `LinkedHashMap` should help in case of loaders with delegates that depend on data of other loaders above in the XML.
