### ISSUE TITLE
Strange behaviour in Create Jmix Screen window for Entity Fragment template

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#662]
See: https://youtrack.jmix.io/issue/JST-2741
**Precondition:**
- Create a project
- Create a JPA entity

**Steps to reproduce:**
- Click create -> screen
- Select **Entity fragment**
- Click Next
- Entity view field -> click Create fetch plan…

**AR:**
"Create fetch plan..." isn't selected and you can't do it (previous item selected). This problem disappears when you create fetch plan config file ("+" (or "New") -> advanced -> fetch plan configuration)

**ER:**
Behaviour like in "Browse screen" or "Editor screen" template

**P.S.** "Entity view" is also incorrect name for field

**Comment by lovtsovaik** [comment]
verified on 1.2.2 jmix version
