### ISSUE TITLE
Additional password validation

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#664]
### Description
See forum [discussion](https://forum.jmix.io/t/nosuchmethodexception-problems-using-a-regexpvalidator-in-an-extended-password-dialog/1306).

There two points where the user password should be validated:
- ChangePasswordDialog
- UserEdit screen.

The main idea is to do not extend ChangePasswordDialog if password requires additional validation. It can be implemented by Spring bean and injected to ChangePasswordDialog and UserEdit as list of corresponding bean type.

**Comment by knstvk** [comment]
Added `PasswordValidator` interface and `PasswordValidation` bean.
To implement a custom password validation in the application, create a bean implementing `PasswordValidator` interface:

```
@Component
public class MyPasswordValidator implements PasswordValidator<User> {

    @Override
    public void validate(User user, String password) throws PasswordValidationException {
         if (password.length() < 3)
            throw new PasswordValidationException("Password is too short, must be >= 3 characters");
    }
}
```
You can create multiple beans of this type.

All password validators will be automatically used in the ChangePassword action dialog.
To add the validation to the User edit screen or detail view, use `PasswordValidation`:

```
  @Autowired
  private PasswordValidation passwordValidation;

  @Subscribe
  protected void onBeforeCommit(BeforeCommitChangesEvent event) {
      if (entityStates.isNew(getEditedEntity())) {
          // ...
          List<String> validationErrors = passwordValidation.validate(getEditedEntity(), passwordField.getValue());
          if (!validationErrors.isEmpty()) {
              notifications.create(Notifications.NotificationType.WARNING)
                      .withCaption(String.join("\n", validationErrors))
                      .show();
              event.preventCommit();
          }
          getEditedEntity().setPassword(passwordEncoder.encode(passwordField.getValue()));
      }
  }
```
