### ISSUE TITLE
Defining date formatter for a column associated with LocalDate field leads to ClassCastException

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#677]
Case:
1. Create an entity with LocalDate field
2. In the browser screen descriptor add a formatter for a corresponding column
```
<column id="fooLocalDate">
    <formatter>
        <date format="yyyy-MM-dd"/>
    </formatter>
</column>
```

AR:
ClassCastException: class java.time.LocalDate cannot be cast to class java.util.Date (java.time.LocalDate and java.util.Date are in module java.base of loader 'bootstrap')

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4306-213)
jmix version (1.3.999-SNAPSHOT)
