### ISSUE TITLE
XLSX formula value is not calulated when the report file is opened in LibreOffice

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#679]
Add a formula that sums column values.

![Screenshot 2022-04-14 at 10 41 10](https://user-images.githubusercontent.com/7888486/163328754-3db77f86-f068-4059-903e-1d162bd0392a.png)

Run the report. 

If you open the report using MS Office, the formula is evaluated correctly.

If you open the report using LibreOffice, there will be a correct formula in the cell, but the value is not calculated. 

![Screenshot 2022-04-14 at 10 34 32](https://user-images.githubusercontent.com/7888486/163328795-bb6171cd-4efc-4e95-97da-f16af79c77c6.png)

If you invoke *Data - Calculate - Recalculate (F9)* command in LibreOffice, the formula value will be refreshed.

See [CUBA forum topic](https://forum.cuba-platform.com/t/xlsx-report-formulas-are-not-evaluated/16079)
See [CUBA issue](https://github.com/cuba-platform/reports/issues/199)

**Comment by gorbunkov** [comment]
The workaround is to post-process the report using Apache POI that can [evaluate formulas](https://poi.apache.org/components/spreadsheet/eval.html):

```java
        ReportOutputDocument document = reportRunner.byReportCode("contracts-report")
                .run();
        ByteArrayInputStream bis = new ByteArrayInputStream(document.getContent());
        Workbook wb = new XSSFWorkbook(bis);
        FormulaEvaluator evaluator = wb.getCreationHelper().createFormulaEvaluator();
        for (Sheet sheet : wb) {
            for (Row r : sheet) {
                for (Cell c : r) {
                    if (c.getCellType() == CellType.FORMULA) {
                        evaluator.evaluateFormulaCell(c);
                    }
                }
            }
        }
        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        wb.write(bos);
        byte[] modifiedFileBytes = bos.toByteArray();
```

**Comment by Gavrilov-Ivan** [comment]
Added new property to force formulas evaluation - `jmix.reports.formulas-post-processing-evaluation-enabled`.
True by default.

**Comment by rusiaikinat** [comment]
Checklist
A template xlsx containing the formula has been created
Open the generated report using LibreOffice 7.4

**Comment by Gavrilov-Ivan** [comment]
Updated: default value is 'false'.

**Comment by Gavrilov-Ivan** [comment]
In most cases is will be enough to set LibreOffice property **Tools - Options - LibreOffice Calc - Formula - Recalculation on FIle Load** to 'Always recalculate'
