### ISSUE TITLE
Export/import of resource and row-level roles

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#688]
See also #378

**Comment by lovtsovaik** [comment]
@artemy63 please add qa notes

**Comment by artemy63** [comment]
For QA
In browser screens for resource and row-level roles an user now has a possibility to export and import roles in different formats.  
Export can be performed in JSON and ZIP format.
If an user does not select any role all available roles will be exported.
Only roles with source == "Database" can be exported, roles with source "Annotated class" will be ignored from export prospective.

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4337-213)
jmix version (1.3.999-SNAPSHOT)
