### ISSUE TITLE
Access to menu folders is not granted for anonymous role

### ISSUE THREAD

**Issue by oshiryaeva** [jmix-framework/jmix#690]
Jmix version: 1.2.2

Here are the steps to grant access to a screen for an anonymous role:
https://forum.jmix.io/t/how-can-i-verify-and-use-the-anonymous-user-functionality/938/3
The screen is available without login, but the menu is not available despite the explicit permission:

```
    @ScreenPolicy(screenIds = {"MyAnonymousScreen"})
    @MenuPolicy(menuIds = {"MyAnonymousScreen"})
    void screens();
```

Demo project: [jmix-anonymous-screen-sample.zip](https://github.com/jmix-framework/jmix/files/8561275/jmix-anonymous-screen-sample.zip)

See also: https://github.com/jmix-projects/jmix-security/issues/52

**Comment by oshiryaeva** [comment]
Exactly. Is there a way to make multiple screens available anonymously
(and, consequently, display a menu for them)?

P.S. Smells like a feature request: anonymous access with menu and Login
button.

A quarta, 11/05/2022, 18:51, Maxim Gorbunkov ***@***.***>
escreveu:

**Comment by gorbunkov** [comment]
In this case your anonymous screen must be created using the "Main screen with side menu" template. 
Such template contains menu, working area, etc.
Keep in mind that you'll have two main screens in your app. The default one will be used for authenticated users and the anonymous one for anonymous:

```
jmix.ui.main-screen-id = MainScreen
jmix.ui.initial-screen-id=AnonymousMainScreen
```

**Comment by oshiryaeva** [comment]
Thank you for comprehensive explanation. Not a bug, so.
