### ISSUE TITLE
Entity Inspector does not allow to specify "rows per page" in pagination

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#691]
Currently, the Entity inspector renders a Table with a SimplePagination component. The configuration of the component does not activate "rows per page" settings. 

This is in particular useful for this screen, as it is an administration screen, and exporting is very inconvenient when one can only export 50 items per page and has to deal with tens/hundreds of files to re-import.

It would be good if for the entity inspector the "rows per page" attributes are properly set. As this screen is only used by administrators/developers, it would even be good to activate the unlimited option.

As a workaround, it is possible to override this behavior with the following class definition:

```
public class PaginationInspectorTableBuilder extends InspectorTableBuilder {

    public PaginationInspectorTableBuilder(CollectionContainer collectionContainer) {
        super(collectionContainer);
    }

    public Table build() {
        Table table = super.build();
        table.getPagination().setItemsPerPageVisible(true);
        table.getPagination().setItemsPerPageUnlimitedOptionVisible(true);
        return table;
    }
}
```

and overriding the bean accordingly:
```
    @Bean("datatl_EntityInspectorTableBuilder")
    @Primary
    @Scope(BeanDefinition.SCOPE_PROTOTYPE)
    InspectorTableBuilder inspectorTableBuilder(CollectionContainer collectionContainer) {
        return new PaginationInspectorTableBuilder(collectionContainer);
    }
```

But this should be either activated by default or alternatively be activatable via a setting in the `application.properties`.

----
### Changes
Now **Items per page** ComboBox can be configured by application properties:
- **jmix.datatools.entity-inspector-browse.items-per-page-options** - comma separated values that will be available as options in the dropdown list.
- **jmix.datatools.entity-inspector-browse.items-per-page-unlimited-option-visible** - visibility of unlimited option in the dropdown list.
- **jmix.datatools.entity-inspector-browse.items-per-page-visible** - visibility of ComboBox.

`InspectorTableBuilder` class now has `withSimplePagination()` method. It provides the ability to configure simple pagination component from Java code.

Note, `InspectorTableBuilder#withSimplePagination()` overrides application properties.

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.2.SNAPSHOT4249-213)
jmix version (1.2.999-SNAPSHOT)
