### ISSUE TITLE
Fix "Upload/Download from file storage" code snippets

### ISSUE THREAD

**Issue by Rumata42** [jmix-framework/jmix#692]
In the code snippet "Download from file storage" in a template for kotlin replace a line `val fileStorage = fileStorageLocator.getDefault()` with `val fileStorage = fileStorageLocator.getDefault<io.jmix.core.FileStorage>()`.
Current text causes an error https://youtrack.haulmont.com/issue/JST-2667 TC1

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
org.jetbrains.kotlin (213-1.6.10-release-923-IJ5744.223)
io.jmix.studio (1.2.SNAPSHOT4239-213)
jmix version (1.2.999-SNAPSHOT)
Kotlin: 213-1.6.10-release-923-IJ5744.223
