### ISSUE TITLE
Introduce an API for getting currently opened dialog and their type

### ISSUE THREAD

**Issue by mariodavid** [jmix-framework/jmix#693]
In Jmix 1.2 it is currently not possible to programmatically get references to all open dialogs like Message Dialogs or Option Dialogs.

The closest match (API wise) is the `OpenedScreens::getDialogScreens`, but it does only return the Input Dialog instances.

The Use-case for getting references for the dialog boxes is UI web integration tests.

When an application currently uses these types of dialogs in the UI, it is not possible to write an integration test for it that interacts with these screens.

The only solution to currently handle this situation is to not use option dialogs and instead create dedicated screens that represent this dialog. Then it is possible once again to interact with those screens in a web integration test.

The corresponding CUBA issue: https://github.com/cuba-platform/cuba/issues/3039

**Comment by ina-schaal** [comment]
Is there an update on this issue? The behaviour is quite inconsistent at the moment, as _getDialogScreens()_ only returns one type of dialogue. If we could get all dialogue types, this would really help us with our testing setup.

**Comment by gorbunkov** [comment]
Will be implemented for FlowUI in #3371
