### ISSUE TITLE
Default filter is not applied after screen opening

### ISSUE THREAD

**Issue by daring2** [jmix-framework/jmix#694]
After screen opening the default filter is loaded but not applied to the table.

The problem can be reproduced in [jmix-petclinic](https://github.com/daring2/jmix-petclinic) project:
1. Open Owners screen.
2. Add a filter condition for "First name" property with some value (for example, "Ash")
3. Set "Default for me" flag and save the filter with values.
4. Reopen the screen.

Result:
The default filter is loaded but not applied, the table shows all rows.

![image](https://user-images.githubusercontent.com/11490702/165776262-618a0030-9ffe-44f8-a951-1ad5163c93b2.png)

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.2.SNAPSHOT4239-213)
jmix version (1.2.999-SNAPSHOT)
