### ISSUE TITLE
Creating resource roles with a menu policy at runtime is not available

### ISSUE THREAD

**Issue by reznikova21** [jmix-framework/jmix#697]
see [forum](https://forum.jmix.io/t/unexpected-error-when-menu-includes-a-separator-and-menu-policy-is-being-created-at-runtime/1374)

**Environment**:

Jmix version: 1.2.999-SNAPSHOT

Jmix Studio plugin version: 1.2.SNAPSHOT4217-213

IntelliJ version: IntelliJ IDEA 2022.1 (Ultimate Edition)

**STEPS**:

1. Create a new jmix project
2. Open Main Menu > Add Separator in Application and Administration
<img width="392" alt="image1" src="https://user-images.githubusercontent.com/87806606/165922403-af4bc3c9-f9b6-4b7a-8ac3-02b04a2d4bcf.png">

3. Launch the App
4. Administration > Resource roles > Create > Create Menu policy

**AR**: Can't create menu policy
![image2](https://user-images.githubusercontent.com/87806606/165922504-a6eb6d7c-e6f4-4d5a-adfe-b4094b1ccf1c.png)

**ER**:
![image3](https://user-images.githubusercontent.com/87806606/165922488-5e50810e-45d4-4c2f-9e7c-033f9330fe76.png)

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.2.SNAPSHOT4249-213)
jmix version (1.2.999-SNAPSHOT)
