### ISSUE TITLE
DataManager query to allow programmatic pessimistic lock

### ISSUE THREAD

**Issue by yos1p** [jmix-framework/jmix#698]
Just like EntityManager can do pessimistic lock programmatically to ensure no changes from other thread, it would be great if this is also implemented in jmix DataManager.

**Comment by knstvk** [comment]
Usage example:
```
dataManager.load(Customer)
                .id(customerId)
                .lockMode(LockModeType.PESSIMISTIC_WRITE)
                .one()
```
