### ISSUE TITLE
Links are not saved in email templates

### ISSUE THREAD

**Issue by Afanasevaa36** [jmix-framework/jmix#705]
Jmix version: 1.3.999-SNAPSHOT

Jmix Studio plugin version: 1.3.SNAPSHOT4234-213

IntelliJ version: IntelliJ IDEA 2022.1 (Ultimate Edition)

**Steps**:

1. Create new project
2. Add addon Email template
3. Run project
4. Submit>Administration>Email templates
5. Create >From designer
6. Add Link in Body
7. Click twice on the link
8. Add link "jmix.io" in field>OK
9. Open Link

**ER**: A window opens with the added link.

**AR**:
The link is not added
![Screenshot_10](https://user-images.githubusercontent.com/95623805/167123816-6e2e86ee-5716-48d3-9bcd-1156f9b07e70.png)

**Comment by artemy63** [comment]
Current status of investigation - the problem related to `ckeditor` plugin - https://github.com/jmix-framework/jmix/blob/master/jmix-emailtemplates/emailtemplates-ui/src/main/resources/io/jmix/emailtemplatesui/screen/emailtemplate/json/json-email-template-edit.xml#L158
Maybe it is necesary to provide extra configuration for `grapesjs-plugin-ckeditor` that is used in grapesjs add-on.

There is a WA for creating and editing links - just place text somewhere in the editor, select or print desire text and click on the `Link` button
![image](https://user-images.githubusercontent.com/26215116/173045665-6482aba1-10f2-4fe5-993e-f66c0803994c.png)
