### ISSUE TITLE
Icon in PropertyFilter component is missed

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#707]
### Environment
*Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4234-213
IntelliJ version: IntelliJ IDEA 2022.1 (Community Edition)*

### Steps
* Open any project
* Open a screen descriptor with studio subscription
* Open Component Palette
* Find PropertyFilter component

AR: icon is missed
![image](https://user-images.githubusercontent.com/73226373/167140520-f974d5a4-35cb-49df-8ff8-12e304da483e.png)

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.2.SNAPSHOT4249-213)
jmix version (1.2.999-SNAPSHOT)
