### ISSUE TITLE
Filter component should work with DTO entities and non-JPA attributes

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#709]
Now it completely ignores non-JPA attributes. However, it could generate query conditions that could be used in custom services.

See https://forum.cuba-platform.com/t/filter-non-peristent-entities

**Comment by mbucan** [comment]
https://forum.cuba-platform.com/t/filter-non-peristent-entities/16264/3?u=mbucan

**Comment by Dzhuliyan-Ovcharov** [comment]
@knstvk any update on how we can use the filter with DTO ?

**Comment by knstvk** [comment]
@Dzhuliyan-Ovcharov could you describe your motivation on the forum in the topic mentioned above?
Just to keep all discussion in one place.
