### ISSUE TITLE
Only a single session or user attribute parameter can be used in query

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#710]
If you use more than one `:current_user_` or `:session_` parameters in a query, it will throw an exception on execution.
See also https://forum.jmix.io/t/old-session-atributes-in-jmix/1382/8

Relates to https://github.com/jmix-projects/jmix-data/issues/120

**Comment by kendovitskii** [comment]
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.2.SNAPSHOT4253-213)
jmix version (1.2.999-SNAPSHOT)
