### ISSUE TITLE
Remove triggers from User table after migration to Jmix with MySQL

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#720]
### Steps to reproduce
1. Create CUBA project with MySQL
2. Migrate project to the Jmix
3. Launch luquibase scripts or run the application using Jmix configuration.

Case 1.
```
Cannot drop column 'GROUP_ID': needed in a foreign key constraint 'SEC_USER_GROUP'
```
**Solution**:
```
<changeSet id="some_id" author="cubasample">
    <dropForeignKeyConstraint baseTableName="sec_user" constraintName="SEC_USER_GROUP"/>
</changeSet>
```
Create DB from CUBA project and migrate it again.

Case 2.
1. Open User screen
2. Create user instance
3. Try to edit and save it.

**AR**
```
SQLSyntaxErrorException: Unknown column 'DELETE_TS' in 'NEW'
```
**Solution**:
Add liquibase script for deleting triggers:
```
SEC_USER_SYS_TENANT_ID_NN_AND_DELETE_TS_NN_UPDATE_TRIGGER
SEC_USER_SYS_TENANT_ID_NN_INSERT_TRIGGER
```

**Comment by knstvk** [comment]
According to the [migration instructions](https://docs.jmix.io/jmix/cuba/index.html#main-migration) item 12, you should remove and ignore all dangerous changesets (in red) from the generated changelog. In this case, the described problem doesn't appear.
