### ISSUE TITLE
Nested property collection container of second level duplicates created items

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#722]
- Run attached project: [demo.zip](https://github.com/jmix-framework/jmix/files/8705873/demo.zip)
- Create Customer
- In Customer edit screen add Order and OrderPosition for it
- Add second Order and OrderPosition for it
- You will see both OrderPositions for the second Order: the one for first Order and the one for second Order

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Community Edition)
io.jmix.studio (1.3.SNAPSHOT4269-213)
jmix version (1.2.999- SNAPSHOT)
