### ISSUE TITLE
Update org.springframework.security.oauth:spring-security-oauth2 

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#730]
Use the latest `org.springframework.security.oauth:spring-security-oauth2:2.5.2.RELEASE`.
See https://mvnrepository.com/artifact/org.springframework.security.oauth/spring-security-oauth2/2.5.1.RELEASE

**Comment by gorbunkov** [comment]
For QA: briefly test that REST add-on works properly

**Comment by Afanasevaa36** [comment]
Tested on
Jmix version: 1.2.999-SNAPSHOT
