### ISSUE TITLE
SideMenu loses item selection on the client-side after page refresh

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#742]
### Description
See forum [discussion](https://forum.jmix.io/t/side-menu-item-selected-state-is-lost-on-page-reload/1502)

### Steps to reproduce

1. set to SideMenu:
```
<sideMenu id="sideMenu"
          selectOnClick="true"
          ...
```
2. Open screen from SideMenu. Item should be highlighted.
3. Refresh the page.

**AR**
Item is not selected.

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4305-213)
jmix version (1.2.999-SNAPSHOT)
