### ISSUE TITLE
`jmix.ui.component.entity-field-type` property doesn't affect components used in Filter conditions

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#746]
See [forum topic](https://forum.jmix.io/t/jmix-ui-component-entity-field-type-no-effect-on-filter/1510) and [docs](https://docs.jmix.io/jmix/ui/app-properties.html#jmix.ui.component.entity-field-type).

Caused by https://github.com/jmix-projects/jmix-ui/issues/171

**Comment by reznikova21** [comment]
1.2.999-SNAPSHOT - verified
