### ISSUE TITLE
Code completion in filter JPQL condition should support user attributes

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#751]
See https://docs.jmix.io/jmix/data-access/jpql-extensions.html#session-and-user-attributes

- Refactor to use `io.jmix.ui.component.autocomplete.JpqlUiSuggestionProvider#getSuggestions(io.jmix.ui.component.autocomplete.AutoCompleteSupport, java.lang.String, java.lang.String, java.lang.String, boolean)` (see changes of #467)
- Add hint about these attributes and code completion in general to context help of the fields

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2021.3 (Ultimate Edition)
io.jmix.studio (1.3.SNAPSHOT4305-213)
jmix version (1.3.999-SNAPSHOT)
