### ISSUE TITLE
jmix-search-aws-starter not compatible with aws es 7.10

### ISSUE THREAD

**Issue by Vi3arD** [jmix-framework/jmix#755]
jmix-search uses depedency org.elasticsearch.client:elasticsearch-rest-high-level-client:7.17.3 that not compatible with aws es 7.10. 
During starting jmix application occurs the error Invalid or missing build flavor [oss]
Based on this error aws es uses we can make conclusion that they use elasticsearch-oss (image docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0) license.
In local test based on elasticsearch:7.10.0 the error was't reproduced. 
Now aws support ES 7.10 and below and OpenSearch

**Comment by gorbunkov** [comment]
See also https://github.com/jmix-framework/jmix/issues/3367
