### ISSUE TITLE
GroupBox.outerMargin attribute works incorrectly in Helium theme

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#771]
Try this:
```
<groupBox id="groupBox1" caption="GroupBox1" width="100%" height="100%" outerMargin="true">
    <textArea height="100%" width="100%"/>
</groupBox>
```
The margin is added inside the group box border rather than outside, at least in Helium theme:
![image](https://user-images.githubusercontent.com/5513878/173403294-47f76168-54a0-4d93-be44-4902bd1a0760.png)

**Comment by glebfox** [comment]
In order to fix this issue for Helium it's required wrapping GroupBox with one more `div` which may lead to performance issues.
