### ISSUE TITLE
GroupBox predefined styles don't work in Helium theme

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#772]
At least `borderless` should work.

Now the styles defined in XSD do the following:

`borderless`:
![image](https://user-images.githubusercontent.com/5513878/173404619-b653412c-e411-45c1-9fb6-5366ba96133f.png)

`light`, `well` (no changes):
![image](https://user-images.githubusercontent.com/5513878/173404839-eddb7326-71f6-4385-90f4-09f893a441c0.png)

## Solution

Added `light` implementation
![Screenshot 2022-07-07 at 15 06 25](https://user-images.githubusercontent.com/6077149/177759517-debec36e-467e-4bf3-9084-99c1bc893748.png)
![Screenshot 2022-07-07 at 15 06 33](https://user-images.githubusercontent.com/6077149/177759521-b159f502-5a5a-4ab6-9d12-9f840c5c75c7.png)

**Comment by lovtsovaik** [comment]
For QA: define this style in `stylename` attribute for `groupBox` component

Tested on Jmix version: 1.3.999-SNAPSHOT

- borderless (only with showAsPanel)
- well (only with showAsPanel)
- light (only without showAsPanel)

light - need to align the margins
![image](https://user-images.githubusercontent.com/73226373/178429109-03b32dea-620a-4093-a238-468d52f32295.png)

without styles:
![image](https://user-images.githubusercontent.com/73226373/178429251-ada98b7a-dcce-4cd4-9481-d6e235ac5b8a.png)

Also, sometimes a line has a serif
![image](https://user-images.githubusercontent.com/73226373/178429492-bdcabe07-a0b3-48cf-9e97-c828cef1d070.png)

**Comment by lovtsovaik** [comment]
Jmix version: 1.3.999-SNAPSHOT

Fixed
![image](https://user-images.githubusercontent.com/73226373/178654632-ec69ca81-c35c-4b40-9434-28cd619776f1.png)
