### ISSUE TITLE
LogoutButton ignores unsaved changes in screens

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#777]
See [forum](https://forum.jmix.io/t/logout-button-action-ignores-unsaved-changes/1561)

Case:

1. Open any entity on edit
2. Change some values
3. Click `LogoutButton`

AR:

User logged out without a prompt

ER:

Unsaved changes dialog appears

**Comment by MaxKatyshev** [comment]
1.3.999-SNAPSHOT - verified
