### ISSUE TITLE
Entity inspector hangs on large datasets

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#781]
Problem in early container loading. 
Data loaded before pagination parameters set.

https://github.com/jmix-framework/jmix/blob/5c29fd9ed05bf4b345c5fdecb84f1bc65d801f6e/jmix-datatools/datatools-ui/src/main/java/io/jmix/datatoolsui/screen/entityinspector/EntityInspectorBrowser.java#L300

**Comment by GurSergey** [comment]
QA notes: To test, you need to have a large number of entities, say 100000, and that the page opens as quickly as, when there are only 50 entities

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2022.1.3 (Community Edition)
io.jmix.studio (1.3.SNAPSHOT4410-213)
jmix versions (1.3.0)
