### ISSUE TITLE
Ability to use jmix-oidc add-on in migrated application

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#783]
Now `java.lang.RuntimeException: Authentication type is not supported` is thrown in `UserSessionSourceImpl.updateUserSessionFromAuthentication()` method.

See [forum](https://forum.jmix.io/t/cuba-jmix-migration-scheduled-task-application-properties-screen-error/1575).

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2022.1.3 (Community Edition)
io.jmix.studio (1.3.SNAPSHOT4410-213)
jmix versions (1.3.0, 1.3.0-RC1)
