### ISSUE TITLE
Screens that are overridden in the add-ons are ignored

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#785]
[Forum](https://forum.jmix.io/t/screen-cannot-be-overrided/1546)

[archive 2.zip](https://github.com/jmix-framework/jmix/files/8957112/archive.2.zip)

In the project above, `UserInAppNotificationBrowseScreenExt` from the **xyzui** add-on extends `UserInAppNotificationBrowseScreen` from the **Notifications** add-on and used in the result **app**.

ER:

`UserInAppNotificationBrowseScreenExt` is opened instead of its parent

AR: 

`UserInAppNotificationBrowseScreenExt` is ignored

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
