### ISSUE TITLE
UserTask due date is incorrectly calculated when duration is defined in business days using calendar

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#790]
Jmix version: 1.2.3

When user task duration is defined in days, e.g. **P1D** and business calendar is selected for date evaluation then the due date is actually calculated not by adding one business day to the current time, but by adding 24 **business** hours to the current time (it's about 3 business days depending on the schedule)

![image](https://user-images.githubusercontent.com/7888486/175291134-16ccc60a-0739-45ce-b598-d85fa1c4cad0.png)

**Comment by gorbunkov** [comment]
When business calendar is selected for the UserTask and due date interval is defined in days (e.g. `P2D`), then such process should not be deployed.

**Comment by konyashkina** [comment]
Tested on Jmix version: 1.3.999-SNAPSHOT
