### ISSUE TITLE
Disabling automatic generation of unique names of WebDAV documents does not work

### ISSUE THREAD

**Issue by Afanasevaa36** [jmix-framework/jmix#793]
Jmix version: 1.3.0-RC1
Jmix Studio plugin version: 1.3.SNAPSHOT4339-213
IntelliJ version: IntelliJ IDEA 2022.1 (Ultimate Edition)

**Steps**:

1. Create new project.
2. Add add-ons WebDAV.
3.  In application. properties add:
```
jmix.webdav.auto-generate-unique-resource-uri=false
```
5. Run project.
6. LogIn admin/admin.
7. Click Administration>WebDAV documents.
8. Click the "Upload" button> Upload a document less than 20 MB in size.
9. Click the "Upload" button> Upload a document of less than 20 MB with the same name.

**ER**:
Error notification is displayed.
**AR**:
Files added successfully.
![Screenshot_5](https://user-images.githubusercontent.com/95623805/175313960-ba647d27-2489-4510-ac00-5ed6d5075e47.png)

**Comment by gorbunkov** [comment]
Jmix 1.3.0

Can't reproduce. The error is displayed:

![image](https://user-images.githubusercontent.com/7888486/177485907-06698f44-3a0e-486f-acbf-83f145cbd7bf.png)

**Comment by Afanasevaa36** [comment]
This function only works with the postgresql database
The unique index in the database is made only for postgresql

**Comment by gorbunkov** [comment]
The feature was intentionally implemented for PostgreSQL only. There are no plans to implement it for other databases.
