### ISSUE TITLE
EntityInfoWindow throws AbstractMethodError for UISetting

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#798]
#### Steps:
1. Use project with datatools addon (e.g. petclinic sample)
2. Create `UISetting` (e.g. by moving/resizing columns on some browser screen)
3. Open Entity Inspector and select UI_Setting entity
4. Try to open "Entity information" from context menu for some record
**ER:** EntityInfoWindow opened with correct information
**AR:**
![MicrosoftTeams-image](https://user-images.githubusercontent.com/38808384/176155994-76824434-4674-46bc-964d-6862e399bf67.png)

**Cause:** Entity with `@Created-` fields but without `@LastModified-` fields still counts as auditable.

**Comment by kendovitskii** [comment]
Verified on:
IntelliJ IDEA 2022.1.3 (Community Edition)
io.jmix.studio (1.4.SNAPSHOT4449-213)
jmix version (1.4.999-SNAPSHOT)
