### ISSUE TITLE
Create Single Module Add-On (Kotlin) project template for Studio

### ISSUE THREAD

**Issue by Gasloff** [jmix-framework/jmix#799]
We have Single Module Add-On template for Java, need  Kotlin version

**Comment by tmusin** [comment]
Ticket in [youtrack](https://youtrack.haulmont.com/issue/JST-2973)

**Comment by lovtsovaik** [comment]
Need to edit description for Java addon template (add Java language note), as it done for single module

**Comment by lovtsovaik** [comment]
Tested on Jmix Studio plugin version: 1.3.SNAPSHOT4410-213

see also a bug https://youtrack.jmix.io/issue/JST-3033
