### ISSUE TITLE
Pagination does not show result in some cases when Filter autoApply is false

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#802]
### Steps to reproduce
1. Download the demo project: [demo.zip](https://github.com/jmix-framework/jmix/files/9010941/demo.zip)

2. Open _Sandbox -> Entities -> Order entity -> Order - GroupTable_
3. Select last page in the pagination.
4. Add condition to filter, e.g. "Order.number contains 6"
5. Try to filter

**AR**
Pagination does not show the pages and table is empty.

**Comment by gorbunkov** [comment]
Probably duplicates #788

**Comment by MaxKatyshev** [comment]
1.4.SNAPSHOT4416-213 - verified
