### ISSUE TITLE
Add confirmation when user group type is changed

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#807]
In the user group editor, when group type is changed from User or Roles to something else and some roles or users have been already added, the confirmation saying that current users or roles will be cleared must be displayed. If no users or roles are selected then no confirmation should de displayed.

Forum: https://forum.cuba-platform.com/t/bproc-user-groups-management-screen-bug-and-behavior/16371

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4632-222
IntelliJ version: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
