### ISSUE TITLE
WINDOW_CLOSE action has wrong localised message key and icon

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#808]
Jmix version: 1.3.0

[forum](https://forum.cuba-platform.com/t/eidtor-window-close-action-default-caption-is-not-adequate/16384)

**To do**
See `StandardEditor` in `io.jmix.ui.screen`
Need to change message and icon for WINDOW_CLOSE action from "actions.Cancel" to "actions.Close"

```
protected Action addDefaultCloseAction(Messages messages, Icons icons) {
    Action action = new BaseAction(WINDOW_CLOSE)
            .withCaption(messages.getMessage("actions.Cancel"))
            .withIcon(icons.get(JmixIcon.EDITOR_CANCEL));
```

**Steps to reproduce**
Open user-edit.xml
Delete "windowClose" action
```
<action id="windowClose"
    caption="msg:///actions.Close"
    icon="EDITOR_CANCEL"/>
```
Run the app
Start creating a new user

AR: Cancel button
![image](https://user-images.githubusercontent.com/73226373/177152157-16e85b3c-8288-40ee-b7b1-52b74b0d3d55.png)

ER: Close button
![image](https://user-images.githubusercontent.com/73226373/177152303-063458b9-ed64-4f7a-ae86-1a3bb2d06273.png)
(the screenshot contains "cancel" icon from the template. But it seems we should replace in to some "close" button)

**Comment by glebfox** [comment]
The `addDefaultCloseAction` method exists for CUBA compatibility. Changing its implementation will affect all projects that uses this code. In case a different localization is needed, this method can be easily overridden.
