### ISSUE TITLE
Add StudioElement and StudioElementsGroup annotations to flowui-kit module

### ISSUE THREAD

**Issue by GlebDurygin** [jmix-framework/jmix#810]
Describe `formatters` elements group and `number`, `collection`, `custom`, `date` elements for `ValuePicker`, `ValuesPicker`, `EntityPicker`.
Describe `description` and `term` elements for `descriptionList` component.

Studio issues - https://youtrack.jmix.io/issue/JST-2948, https://youtrack.jmix.io/issue/JST-2949

**Comment by konyashkina** [comment]
Tested on Jmix version: 1.3.999-SNAPSHOT
