### ISSUE TITLE
[ScreenSettingsFacet] ability to disable settings for certain components

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#812]
Currently, in order to prevent some component from saving its settings, you need to remove `auto="true"` and define all other components explicitly.

It would be more convenient to have a way to disable settings for certain components rather than enable it for the others explicitly.

### Changes
Now `ScreenSettingsFacet` provides the ability to exclude component from settings mechanism, i.e. excluded component won't apply/save its settings.

#### Declarative example:
```XML
 <facets>
     <screenSettings id="facet" auto="true">
         <components>
             <component id="groupBox" enabled="false"/>
         </components>
     </screenSettings>
 </facets>
```
The "facet" will scan all component that should apply/save settings due to `auto="true"` attribute. But component with "groupBox" id will be excluded due to `enabled="false"` attribute.

#### Java API
`ScreenSettingsFacet` interface has new methods:
- `excludeComponentIds()` - adds component ids that should be excluded from settings mechanism.
- `getExcludedComponentIds()` - returns excluded component ids.

**Comment by MaxKatyshev** [comment]
Jmix version: 1.4.999-SNAPSHOT - verified
