### ISSUE TITLE
[FlowUI Template] Users editor screen is generated without project id prefix

### ISSUE THREAD

**Issue by pbaris** [jmix-framework/jmix#819]
Using the "Full-Stack Application with Experimental FlowUI" template, the generated editor screen for Users, does not have the project id prefix, As a result cannot open the editor from the browser screen. If i add the prefix it works just fine.

![image](https://user-images.githubusercontent.com/242612/177612566-c8b79d3d-d08a-4e76-97d4-479a16069129.png)

**Comment by glebfox** [comment]
fixed: b9e23d68990cf03fd171acd20daf2b7bbc684cd2
