### ISSUE TITLE
Add localization for ResourcePolicyEntity and RowLevelPolicyEntity

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#820]
Provide localization for entity names and their attributes

See [forum](https://forum.jmix.ru/t/net-lokalizaczii-dlya-sushhnostej-securitydata/456)

**Comment by konyashkina** [comment]
ResourceRoleEntity attributes are not localized. 

Tested on Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4517-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
![820ResourceRoleEntityAttributes](https://user-images.githubusercontent.com/85500330/183413854-55f16d3f-fbbb-47c3-8820-891565901d50.png)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4519-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
