### ISSUE TITLE
NullPointerException if /search request finds nothing

### ISSUE THREAD

**Issue by dtaimanov** [jmix-framework/jmix#824]
Port changes from 
https://github.com/cuba-platform/restapi/issues/144

### QA Notes
Send similar search request with empty conditions and make sure that no exception occurs and empty list returned.

**Comment by Afanasevaa36** [comment]
Jmix version: 1.4.999-SNAPSHOT
verified
![Снимок экрана от 2022-07-27 12-29-58](https://user-images.githubusercontent.com/95623805/181214306-bd59ae2d-164c-4e9e-b75b-f42e6488df0c.png)
