### ISSUE TITLE
[Flow UI] Support facets in studio for flow ui module

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#825]
Add meta annotations for support facets in studio for flow ui module
Also see studio ticket: https://youtrack.haulmont.com/issue/JST-3010

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4473-213
IntelliJ version: IntelliJ IDEA 2022.1.4 Preview (Ultimate Edition)
