### ISSUE TITLE
jmix.core.pessimistic-lock.use-default-quartz-configuration property doesn't work

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#827]
Currently, auto configuration expects the `jmix.pessimistic-lock.use-default-quartz-configuration` property, not the `jmix.core.pessimistic-lock.use-default-quartz-configuration`.

See [forum](https://forum.jmix.io/t/jmix-1-3-released/1643/8)

**Comment by lovtsovaik** [comment]
verified on Jmix version: 1.3.999-SNAPSHOT
