### ISSUE TITLE
When downloading a file using the download URL the spaces in the filename are not preserved

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#828]
Jmix: 1.3.0

If we've uploaded a file called `My file.docx` then when we download it using [REST API](https://docs.jmix.io/jmix/rest/files-api.html#downloading-files) the name of downloaded file contains + instead of space: `My+file.docx`.

See [forum topic](https://forum.jmix.io/t/file-downloading-via-rest-with-space-in-filename-wont-work/1655/8?)

Probably, we should encode the filename header using RFC5987

**Comment by MaxKatyshev** [comment]
Jmix version: 1.4.999-SNAPSHOT - verified
