### ISSUE TITLE
working with JPA entity in other appliation than Jmix

### ISSUE THREAD

**Issue by anasoid** [jmix-framework/jmix#830]
Hello,
I try to use multi project in jmix and use datamodel in a simple spring boot pplication but i found many problem (like i have to use eclipelink and the jmix version .. ) related to this because class are compiled with jmix.
There is any way to use entity source code in another module without jmix ??

**Comment by gorbunkov** [comment]
Hi,

As you said, Jmix entities require a couple of Jmix-specific annotations and also classes are enhanced by Jmix and Eclipselink while being compiled. So I'm not sure that you can share entity classes with other applications. If you need other "pure" Spring Boot applications work with the same data model, then I think the best option will be to duplicate JPA entities in that project and connect them with database table.

We have a separate tool called [JPA Buddy](https://www.jpa-buddy.com/) for managing any JPA entity not linked with Jmix. You may find it useful for your other projects.

BTW, we have community forum: https://forum.jmix.io/. It's a better place to ask questions than GitHub issues. Will be glad to see you there:)

**Comment by anasoid** [comment]
Many thanks @gorbunkov for your help
