### ISSUE TITLE
Outcome list is empty in sequence flow if UserTask has Custom form type

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#832]
Jmix: 1.3.1

1. Create User task with a form type "Custom"
1. Add outcomes to the form
1. For any sequence flow try to select condition based on the task outcome

AR: for tasks with form type custom outcomes list will be empty

See [forum](https://forum.jmix.ru/t/rabota-redaktora-s-outcome/482)

The issue must also be fixed in Studio BPMN designer

**Comment by gorbunkov** [comment]
Studio issue: https://youtrack.jmix.io/issue/JST-3083

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4494-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
