### ISSUE TITLE
EntitySnapshot entity does not have localized messages for attributes

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#833]
### Steps to reproduce
1. Add Audit add-on using Studio marketplace.
2. Go to the "Entity Inspector" screen
3. Find EntitySnapshot entity.

**AR**
![image](https://user-images.githubusercontent.com/22093943/179360991-f67a1b6f-b692-4bfd-b1de-6835b68e5fdf.png)

**Comment by konyashkina** [comment]
Some fields are localized, but others aren't. Please take a look at screenshots below.
![EntitySnapshotTest001](https://user-images.githubusercontent.com/85500330/183451094-ef8b1bf0-507d-4b39-9fb7-cb51ca8f2d08.png)

![EntitySnapshotTest002](https://user-images.githubusercontent.com/85500330/183451121-18b9cef5-b6fd-4b21-815f-1b8bfe6ad311.png)

**Comment by dtaimanov** [comment]
Commit: https://github.com/jmix-framework/jmix/commit/f9dbb39c3f8a2d9456bc6e407b2df55685c684b5
EntitySnapshot.id - localized
ReferenceToEntity - localized
Fetch plan XML - is the same as for cuba translation:
<img width="1502" alt="Снимок экрана 2022-08-09 в 01 25 13" src="https://user-images.githubusercontent.com/38808384/183520362-5ede8888-e1fc-4afa-b953-738980738dd5.png">

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4519-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
