### ISSUE TITLE
TabSheet component

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#834]
Wait for: https://github.com/orgs/vaadin/discussions/3175

**Comment by rusiaikinat** [comment]
**Check list:**
- Created empty TabSheet with tabs
- Created TabSheet with dataGrid (...-list-view.xtml)
- Checked [Lazy Loading Tab Content](https://docs.jmix.io/jmix/ui/vcl/containers/tab-sheet.html#lazy-loading-tab-content)
- Checked vaadin [vaadin style](https://vaadin.com/docs/latest/components/tabs#tab-sheet). To check themeNames="icon-on-top", the component `Tab` was generated in the controller
