### ISSUE TITLE
Reports add-on with Flow UI

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#839]
## General
- [x] - Reports
   - [x] - Report Browser
   - [x] - Report editor
      - General tab
         - [x] - Template editor
         - [x] - Creating/editing bands
         - Band details (@Flaurite)
            - Data set types
               - [x] - SQL, JPQL, Groovy
               - [x] - Entity
               - [x] - List of entities
               - [x] - JSON
      - [x] - Locales tab -  @breakingfox 
      - [x] - Parameters and formats tab + Parameters Editor - @breakingfox 
      - [x] - Security tab - @breakingfox 
   - [x] - Report wizard - @breakingfox 
      - [x] Region editor
- [x] - Execution history  - @NikitaShchienko
- [x] - Report groups - @NikitaShchienko 
- [x] - Run reports - @NikitaShchienko
   - [x] - Views
   - [x] - Runner
   - [x] - Action
- [x] - Report Import - @NikitaShchienko 
- [x] - Show tables  - @NikitaShchienko
- [x] - Add report roles - - @NikitaShchienko
- [x] - #1407 - @NikitaShchienko
- [x] - #1625 - @NikitaShchienko

## Refactoring
- [x] - Redesign - @NikitaShchienko 
- [x] - Controllers and Views - @NikitaShchienko 
- [ ] - #1912 - @NikitaShchienko 

Cannot be implemented
- Show charts
- Show pivot tables

**Comment by m-shambarova** [comment]
[NullPointerException when clearing the value "Template type" in the Report wizard #561](https://github.com/jmix-framework/jmix-docs/issues/561)

**Comment by m-shambarova** [comment]
https://github.com/jmix-framework/jmix/issues/1878#issue-1765474089

**Comment by m-shambarova** [comment]
No notification about the mandatory filling of the "Report name" field #1882

**Comment by m-shambarova** [comment]
NullPointerException when clearing the value "Entity" in the Report wizard #1883

**Comment by m-shambarova** [comment]
NullPointerException when clearing the value "Report output type" in the Report wizard #1895

**Comment by m-shambarova** [comment]
General remarks in Wizard #1898

**Comment by m-shambarova** [comment]
- [ ] Report import does not work on the "Report details" tab #1915

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5281-231
IntelliJ version: IntelliJ IDEA 2023.1 (Community Edition)
