### ISSUE TITLE
Menu improvements

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#844]
* Separators
* Key combinations?
* Different menu item types: bean, runnable, etc.
* Query and Route params

**Comment by KremnevDmitry** [comment]
### Code samples:

### Separators:
```
        <item view="User.list" title="msg://com.company.untitled.view.user/UserListView.title"/>
        <separator/>
        <item view="User.list" title="msg://com.company.untitled.view.user/UserListView.title"/>
```
![image](https://user-images.githubusercontent.com/75516667/209295284-bc786b1f-ac79-4299-84a2-2a1cec8e6d6d.png)


### KeyCombinations:

```
        <item view="User.list" title="msg://com.company.untitled.view.user/UserListView.title"
              shortcutCombination="Alt-J"/>
```

### Menu types [only bean]:

```
        <item bean="untitled_MenuBean" beanMethod="showNotification" title="Bean item">
            <properties>
                <property name="notificationParam" value="testValue"/>
            </properties>
        </item>
```

![image](https://user-images.githubusercontent.com/75516667/209296502-4344250d-90c5-4bed-9973-cea741899673.png)


### Query parameters:

```
        <item view="User.list" title="msg://com.company.untitled.view.user/UserListView.title">
            <queryParameters>
                <parameter name="queryParam" value="testParam"/>
            </queryParameters>
        </item>
```

![image](https://user-images.githubusercontent.com/75516667/209297001-82c65110-661f-47c2-8ac5-baf0d989bada.png)

### Route parameters:

```
        <item view="User.detail" title="Admin detail">
            <routeParameters>
                <parameter name="id" value="60885987-1b61-4247-94c7-dff348347f93"/>
            </routeParameters>
        </item>
```

![image](https://user-images.githubusercontent.com/75516667/209297258-f171e9dc-7cfd-4734-8081-ed9becc390b8.png)
