### ISSUE TITLE
Re-work Grid context menu

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#851]
See `GridActionsSupport`

* Support icons (aka prefix component)
* Support shortcuts (aka suffix component, consider using [`<kbd>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd). Worth adding app property whether to show actions' shortcut)
* Support RLT (should work by default)

* Separators - declarative way of defining context menu
* Hierarchy - declarative way of defining context menu

* Public API, ability to add custom items w/o Actions (Alternatively,  this can be achieved by giving direct access to the ContextMenu instance)
* Support context menu open listener, so that user can display items depending on item/column clicked (Alternatively,  this can be achieved by giving direct access to the ContextMenu instance)

**Comment by yuriy-khrebtov** [comment]
Improvements:
1. Action icons and shortcuts can be displayed in grid context menu items. It can be enabled in application.properties:
```
jmix.ui.component.grid-context-menu-show-action-icons=true
jmix.ui.component.grid-context-menu-show-action-shortcuts=true
```
2. New option `showInContextMenuEnabled` was introduced to switch on/off automatic addition grid actions to context menu:
```
<dataGrid id="studentsDataGrid"
                  dataContainer="studentsDc">
            <actions showInContextMenuEnabled="true">
                <action id="create"
                        type="list_create"
                        shortcutCombination="CONTROL-E"/>
                <action id="edit"
                        type="list_edit"/>
                <action id="remove"
                        type="list_remove"/>
            </actions>
...
</dataGrid>
```
3. It is possible to define custom grid context menu using xml:
```
<contextMenu id="cm1">
                <item id="menu1"
                      text="Menu one">
                    <item id="item1"
                          icon="vaadin:abacus"
                          text="Item one"/>
                    <item icon="vaadin:academy-cap"
                          text="Item two"
                          css="color:red"
                          action="studentsDataGrid.edit"/>
                    <separator/>
                    <item icon="vaadin:alarm"
                          text="Item three"
                          classNames="className3"
                          action="studentsDataGrid.edit"/>
                </item>
                <separator/>
                <item text="Item four"
                      icon="vaadin:anchor"/>
</contextMenu>
```
4. New method `studentsDataGrid.getContextMenu()` was added to get context menu instance of a grid to perform some customization.
5. Context menu and menu items are now available for injection in a view:
```
    @ViewComponent
    private GridContextMenu<Student> cm1;
    @ViewComponent
    private GridMenuItem<Student> item1;

    @Subscribe("item1")
    public void onItem1GridContextMenuItemClick(final GridContextMenu.GridContextMenuItemClickEvent<?> event) {
        notifications.show("clicked on item1 with id: " + item1.getId().get());
    }

    @Install(to = "cm1", subject = "dynamicContentHandler")
    private boolean cm1DynamicContentHandler(final Student student) {
        if (student != null) {
            cm1.addItem("Student " + student.getName());
        }
        return true;
    }
```

**Comment by rusiaikinat** [comment]
Tested on:
Kotlin
Jmix version: 2.2.999-SNAPSHOT
Jmix Studio plugin version: 2.2.SNAPSHOT6038-233
IntelliJ version: IntelliJ IDEA 2023.3.3 (Ultimate Edition)
