### ISSUE TITLE
Provide margin attribute for DynamicAttributesPanel and disable it by default

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#861]
### Description

By default `DynamicAttributesPanel` has inside margin=true. It add spaces around the component and result layout looks unaligned.

![image](https://user-images.githubusercontent.com/22093943/179750963-c8776bbd-739e-4fb8-8ca1-03a1ff014c8f.png)

### Solution

Add margin attribute to the XML and Java API to configure it. Default margin value should be "false".

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4517-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
