### ISSUE TITLE
Localization problems when extending jmix-reports screens

### ISSUE THREAD

**Issue by n-13** [jmix-framework/jmix#863]
Screens uses getClass() at getMessage() call.
For extended screens it must be changed to getClass().getSuperclass() in order to see proper text.
So, every method with messages at screen must be overrided in order to see proper text.

https://github.com/jmix-framework/jmix/blob/0b84b355e90676dc2113119a0f694eacda52d7d9/jmix-reports/reports-ui/src/main/java/io/jmix/reportsui/screen/report/edit/ReportEditor.java#L188

**Comment by gorbunkov** [comment]
`MessageBundle` is used in framework screen controllers instead of `messages.getMessage(getClass(), "...)`.

In the extended screen you may specify the `messageGroup` of the parent screen. This should avoid localization problems.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<window xmlns="http://jmix.io/schema/ui/window"
        caption="msg://io.jmix.reportsui.screen.report.edit/reportEditor"
        messagesGroup="io.jmix.reportsui.screen.report.edit"
        extends="io/jmix/reportsui/screen/report/edit/report-edit.xml">
    <layout/>
</window>
```

**Comment by Afanasevaa36** [comment]
Jmix version: 1.4.999-SNAPSHOT - Verified
