### ISSUE TITLE
Support main view and login view in Studio

### ISSUE THREAD

**Issue by GlebDurygin** [jmix-framework/jmix#864]
Studio issue: [JST-3009](https://youtrack.jmix.io/issue/JST-3009) Support main and login views in flowui module

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4473-213
IntelliJ version: IntelliJ IDEA 2022.1.4 Preview (Ultimate Edition)
