### ISSUE TITLE
[FlowUI] 'Entity list view' template isn't working in Screen wizard

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#865]
Also see: https://youtrack.haulmont.com/issue/JST-3038

Steps to reproduce:

Create an Entity in project with FlowUI.
Click Screens on the top menu and select +Create screen ('Create Jmix Screen wizard appears).
In the Screen wizard select 'Entity list view' template and click Next button.
ER: Next step with some options for a new screen.

AR: Nothing happens.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4473-213
IntelliJ version: IntelliJ IDEA 2022.1.4 Preview (Ultimate Edition)
