### ISSUE TITLE
Typo in Recalculation script of Dynamic attributes

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#866]
### Description

> if(EntityValue.getValue(entity,"+PassengerNumberofseats") > 9) return 'Bus' else return 'Passenger'

but should be

`if (EntityValues.getValue`

**Also fix in all translations**.

![image](https://user-images.githubusercontent.com/22093943/179971646-6c77f087-b3b1-4c05-8d90-65be2faa8785.png)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4517-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
