### ISSUE TITLE
[Flow UI] Add the ability to determine the place where the user can insert a component when adding from Component Hierarchy

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#867]
Use regular expression to validate component path in XML when adding component

For QA:
1. Try to add dataLoadCoordinator (facet component) in any places (right place for this component is "Facets" node)
2. Try to add any components in hierarchy in any view descriptor
3. Try to add any components in main view descriptor

Also see Studio ticket here: https://youtrack.haulmont.com/issue/JST-3015

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4481-213
IntelliJ version: IntelliJ IDEA 2021.3 (Community Edition)
