### ISSUE TITLE
Add validation to Create Entity Data Task when @Size, @NotBlank or @Email annotation exists in entity's attributes.

### ISSUE THREAD

**Issue by johnis89** [jmix-framework/jmix#870]
When `@Size`, `@NotBlank` or `@Email` annotation exists in entity's attributes, the Create Entity Data Task will create the entity instance but with invalid data. Other validation annotations like `@NotNull` or `@Column(length=value)` throws "SQLIntegrityConstraintViolationException". It would be better if `@Size`, `@NotBlank` and `@Email` constraint Violations worked the same way, or even better if all of them could throw their specified message.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4702-222
IntelliJ version: IntelliJ IDEA 2022.2.3
