### ISSUE TITLE
RadioButtonGroup bound to entity's attribute with Entity type doesn't display its value on initial editor screen opening

### ISSUE THREAD

**Issue by Afanasevaa36** [jmix-framework/jmix#881]
See [topic](https://forum.jmix.ru/t/radiobuttongroup-ne-otobrazhaetsya-znachenie-v-dialoge-redaktirovaniya-sushhnosti/493).

[radiobutton.zip](https://github.com/jmix-framework/jmix/files/9267031/radiobutton.zip)

**Comment by glebfox** [comment]
Can't reproduce. According to the description `optionsEnum` is added explicitly, but it isn't required in case `RadioButtonGroup` is bound to data, hence I presume that `RadioButtonGroup` has no data binding. 

@Afanasevaa36 could you please attach xml descriptor code?

**Comment by Afanasevaa36** [comment]
@glebfox in the attachment is the project on which I reproduced the problem.
[ForumRadioButton.zip](https://github.com/jmix-framework/jmix/files/9248188/ForumRadioButton.zip)

**Comment by glebfox** [comment]
Your project proves my theory. `radioButtonGroup` has no data binding

```
<radioButtonGroup caption="Vertical"
                  optionsEnum="com.company.forumradiobutton.entity.NewEnum"/>
```

**Comment by small75** [comment]
This is my case:
Screen
![image](https://user-images.githubusercontent.com/37901315/183033851-96f97cdd-36b0-4fb9-867a-335fc9d50a61.png)

On editing entity
![image](https://user-images.githubusercontent.com/37901315/183033943-b259da75-1b73-4741-bd9e-86c511b1ab58.png)

**Comment by glebfox** [comment]
@small75 could you please attach a small demo project that reproduces the problem? In my case, everything works as expected.

**Comment by small75** [comment]
[radiobutton.zip](https://github.com/jmix-framework/jmix/files/9267031/radiobutton.zip)
![image](https://user-images.githubusercontent.com/37901315/183040034-50925824-97b8-4270-a264-438c08356019.png)

**Comment by glebfox** [comment]
@small75 thank you for the demo project. It helped to correct steps to reproduce the problem.

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT
Verified
