### ISSUE TITLE
Set custom searchFilter for ActiveDirectoryLdapAuthenticationProvider

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#885]
When the `ActiveDirectoryLdapAuthenticationProvider` instance is built in the `LdapActiveDirectorySecurityConfiguration` we should also configure the `searchFilter`. The search filter value may be taken from `LdapProperties`.

See [forum](https://forum.jmix.io/t/ad-ldap-login-not-working-without-extending-ldapsecurityconfiguration/1051/9)

**Comment by gorbunkov** [comment]
Since now, users may define user search filters when AD is used.

Examples

Users should enter their username and domain on login form: `username@domain`:

```properties
jmix.ldap.use-active-directory-configuration = true
jmix.ldap.user-search-filter = (&(objectClass=user)(userPrincipalName={0}))
```

Users should enter just username on login form, the domain will be taken from corresponding application property:
```properties
jmix.ldap.use-active-directory-configuration = true
jmix.ldap.user-search-filter = (&(objectClass=user)(sAMAccountName={1}))
jmix.ldap.active-directory-domain=mydomain.com
```

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT
Verified
