### ISSUE TITLE
REST API and OpenID Connect plugins conflict 

### ISSUE THREAD

**Issue by alexzelenuyk** [jmix-framework/jmix#887]
Hello everyone,
we are getting an exception when starting a jmix project with `REST API` and `OpenID Connect` plugins installed:

```
Caused by: java.lang.IllegalStateException: @Order on WebSecurityConfigurers must be unique. Order of 200 was already used on io.jmix.autoconfigure.oidc.OidcAutoConfiguration$OAuth2LoginSecurityConfiguration$$EnhancerBySpringCGLIB$$c6383a3d@2e8edc36, so it cannot be used on io.jmix.autoconfigure.securityoauth2.SecurityOAuth2AutoConfiguration$Oauth2AuthorizationServerConfiguration@255c2e7e too.
```

jmix verions: `1.3.1`

Could you, please, take a look? Thank you in advance!

**Comment by gorbunkov** [comment]
Hi,

you probably forgot to remove the `jmix-security-oauth2-starter dependency` from the build.gradle:

```
implementation("io.jmix.security:jmix-security-oauth2-starter")
```

See https://github.com/jmix-framework/jmix/tree/master/jmix-oidc#protecting-api

**Comment by alexzelenuyk** [comment]
You're right, that's the case. 
When installing both plugins from Marketpalce those dependencies would be installed. Thank you for the help!

**Comment by alexzelenuyk** [comment]
With that done, I have a problem, that CORS is not enabled. When switching to jmix `1.2.3` CORS works fine again.

**Comment by gorbunkov** [comment]
> With that done, I have a problem, that CORS is not enabled. When switching to jmix 1.2.3 CORS works fine again.

We have a forum for answering questions and discussing problems: https://forum.jmix.io. Could you please describe your case there? I think it will be a better place than the current github issue:)

**Comment by gorbunkov** [comment]
The order of OAuth2LoginSecurityConfiguration has been changed. At least there will be no error on application start.

**Comment by alexzelenuyk** [comment]
Thank you very much for taking a look!

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT
Verified
