### ISSUE TITLE
[Flow UI] Disable Edit button in multi select Grid?

### ISSUE THREAD

**Issue by pbaris** [jmix-framework/jmix#889]
Having a Grid with selection mode MULTI, when i select more than one rows and click Edit button, editor opens with the first selected row's entity.

I think it would be better if Edit button was disabled when multiple rows selected.

![jmix_flowui_multi_edit](https://user-images.githubusercontent.com/242612/181098207-c61bc17a-43c5-45df-9e6a-f796a32f52c3.gif)

**Comment by SergeiAksenov2** [comment]
Tested on Java:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6351-241
IntelliJ version: IntelliJ IDEA 2024.1 (Community Edition)

Tested on Kotlin:
Jmix version: 2.3.999-SNAPSHOT
Jmix Studio plugin version: 2.3.SNAPSHOT6350-233
IntelliJ version: IntelliJ IDEA 2023.3.6 (Community Edition)

The 'Edit' button only is avaliable in a Grid table when one entity is selected.
