### ISSUE TITLE
Rename shortcut attribute to shortcutCombination

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#895]
* Several components have the `shortcut` attribute in XML. It's worth renaming it to `shortcutCombination`, same as Vaadin class name
* Add `HasShortcutCombination` to `Action`

**Comment by KremnevDmitry** [comment]
Related to Studio Issue: https://youtrack.haulmont.com/issue/JST-3189

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4631-213
IntelliJ version: IntelliJ IDEA 2021.3.3 (Community Edition)
