### ISSUE TITLE
Migrate to Vaadin 8.14.3

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#900]
It seems that one of our minor issues has been fixed there: https://github.com/jmix-framework/jmix/issues/396

### How to test
1. Especially check `Table` component and its styles. 
2. Especially check `DataGrid` component.
3. Check case from issue above.

**Comment by knstvk** [comment]
See also https://github.com/jmix-framework/jmix-dependencies/security/dependabot/106

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
