### ISSUE TITLE
Describe actions using Studio meta annotations

### ISSUE THREAD

**Issue by GlebDurygin** [jmix-framework/jmix#904]
Studio issue - https://youtrack.jmix.io/issue/JST-3060

Describe actions using Studio meta annotations:

**MainView actions:**
1) logout

**View actions:**
1) view_close
2) lookup_select
3) lookup_discard
4) detail_close
5) detail_commit
6) detail_commitClose
7) detail_discard
8) detail_enableEditing

**ValuePicker actions:**
1) value_clear

**EntityPicker actions:**
1) value_clear
2) entity_clear
3) entity_lookup
4) entity_open
5) entity_openComposition

**ListDataComponent actions:**
1) create
2) edit
3) itemTracking
4) remove

**Comment by MaxKatyshev** [comment]
1.3.999-SNAPSHOT - verified
