### ISSUE TITLE
Export/import of report does not preserve default template link

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#905]
- Create any report with the wizard
- Export the report
- Import the report
- Edit the report

AR: "Default template" field is empty

**Comment by gorbunkov** [comment]
The issue doesn't happen if importing reports manually. It only appears when importing reports programmatically using the `ReportImportExport` service.

An example of this is in the following project: [demo.zip](https://github.com/jmix-framework/jmix/files/9242894/demo.zip)

The projects imports the report on the first application start. See `DbInitializer` bean for details.

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
