### ISSUE TITLE
Describe formLayout using Studio meta annotations

### ISSUE THREAD

**Issue by KremnevDmitry** [jmix-framework/jmix#907]

**Comment by KremnevDmitry** [comment]
Related to Studio issue: https://youtrack.haulmont.com/issue/JST-3005

**Comment by KremnevDmitry** [comment]
- add formLayout to designer
- add formLayout's child (ResponsiveStep) to designer
- remove formLayout and ResponsiveStep

**Comment by MaxKatyshev** [comment]
1.3.999-SNAPSHOT - verified
