### ISSUE TITLE
Changing editable to true makes DateField required

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#910]
Caused by: https://github.com/jmix-framework/jmix/issues/387

Case 1:

1. Create a screen with _non-required_ `DateField`.
2. Open a screen - `DateField` has **no** required indicator - OK
3. Make `DateField` read-only - `DateField` has **no** required indicator - OK
4. Make `DateField` _editable_ again

ER:
`DateField` has **no** required indicator

AR:
`DateField` has required indicator

Case 2 for QA:

Check that required DateField works as expected

**Comment by reznikova21** [comment]
1.3.999-SNAPSHOT - verified
