### ISSUE TITLE
[DeviceInfoProvider] isTouchDevice() returns false for every touch device 

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#917]
Case:

1. Inject `DeviceInfoProvider` to any screen
2. Obtain `DeviceInfo` object
3. Call `deviceInfo.isTouchDevice()`

Test code:
```
@Autowired
private DeviceInfoProvider deviceInfoProvider;
...
DeviceInfo deviceInfo = deviceInfoProvider.getDeviceInfo();
deviceInfo.isTouchDevice();
```

ER:

`deviceInfo.isTouchDevice()` must return `true` for Touch Devices like iPhone, iPad, Android

AR:

`deviceInfo.isTouchDevice()` returns `false`

**Comment by MaxKatyshev** [comment]
1.3.999-SNAPSHOT - verified
