### ISSUE TITLE
[Flow UI] Describe DataGrid and TreeDataGrid using Studio meta annotations

### ISSUE THREAD

**Issue by GlebDurygin** [jmix-framework/jmix#919]
Studio issue: https://youtrack.jmix.io/issue/JST-3004

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4519-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
