### ISSUE TITLE
[Flow UI] Support "itemsEnum" and "metaClass" attributes

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#920]
See studio ticket here: https://youtrack.haulmont.com/issue/JST-2987

Add suggestion for `itemsEnum` (similar to `optionsEnum` from Jmix)

https://github.com/jmix-framework/jmix/commit/7eaf724026f2edd90e83dbca36ec266aa36879a2

Support property types:
1) ENUM_CLASS
2) ENTITY_NAME
3) ENTITY_NAMES

**Comment by MaxKatyshev** [comment]
1.3.999-SNAPSHOT - verified
