### ISSUE TITLE
Add vertical lines between columns in Table header

### ISSUE THREAD

**Issue by knstvk** [jmix-framework/jmix#921]
Now newcomers don't understand that columns width can be easily changed.

### Solution

By default a table has vertical line in the header in the **Helium** theme
<img width="1533" alt="Screenshot 2022-10-14 at 11 37 02" src="https://user-images.githubusercontent.com/6077149/195789768-3736048c-7ef2-487b-8f4d-84f3a58ec99c.png">

In order to remove them, the predefined style can be used: `stylename="no-vertical-lines"`

**Comment by lovtsovaik** [comment]
For QA: check also stylename working
