### ISSUE TITLE
DateField. Full month name is not displayed

### ISSUE THREAD

**Issue by Flamesson** [jmix-framework/jmix#924]
I wanted to display localized month name in date field (for local-date) in my screen. But it is not shown for some reason.

Sample projeft: https://github.com/izumi-jmix/date-field-format-problem
How to reproduce: 
- Start the application
- Open SampleScreen (will be opened by default)

You will get the expected result in terminal and actual on the screen. 

### Example:

**_Terminal_**
`
2022-08-08 20:54:19.903  WARN 1848 --- [nio-8080-exec-8] o.i.j.dffp.screen.sample.SampleScreen    : August 22
2022-08-08 20:54:19.907  WARN 1848 --- [nio-8080-exec-8] o.i.j.dffp.screen.sample.SampleScreen    : 08 August 22
2022-08-08 20:54:19.908  WARN 1848 --- [nio-8080-exec-8] o.i.j.dffp.screen.sample.SampleScreen    : 08 22
2022-08-08 20:54:19.909  WARN 1848 --- [nio-8080-exec-8] o.i.j.dffp.screen.sample.SampleScreen    : August
`

and corresponding **_state of the screen_**

![Screenshot 2022-08-08 at 20-55-22 Date Field Format Problem application](https://user-images.githubusercontent.com/51899225/183473562-5e8d4387-ce2a-419b-a0b7-362e26379fd4.png)

**Comment by Flamesson** [comment]
Note: in _io.jmix.ui.component.Calendar_ component mentionted pattern displayed correctly

![image](https://user-images.githubusercontent.com/51899225/187061661-9085477e-a618-405e-9b4d-d0a77402ea3b.png)

**Comment by gorbunkov** [comment]
As [documentation](https://docs.jmix.io/jmix/ui/vcl/components/date-field.html#date-format) states:

> DateField is primarily intended for quick input by filling placeholders from a keyboard. Therefore, the component supports only formats with digits and separators. Complex formats with the textual representation of weekdays or months will not work.
