### ISSUE TITLE
[Flow UI]: Attribute cacheable is not used for Loader

### ISSUE THREAD

**Issue by Fedoseew** [jmix-framework/jmix#926]
See original issue here: https://youtrack.haulmont.com/issue/JST-3091

Steps:
1. Open descriptor and select instance loader
2. Open Component Inspector
3.  Cacheable -> true

AR: Attribute cacheable is not allowed here

**Comment by MaxKatyshev** [comment]
1.3.999-SNAPSHOT - verified
