### ISSUE TITLE
Embedded image in excel template is not printed on each band row

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#928]
1. Create Excel report using Wizard (e.g. for User entity)
2. In the excel template add an image. The image must be inside the named region
<img width="502" alt="image" src="https://user-images.githubusercontent.com/7888486/183825844-e478097f-846f-4697-8dc8-815af08a1839.png">
3. Run the report

ER: the image is displayed in each row
AR: the image is displayed only in the cell where it is defined in the template (e.g. C3)

<img width="500" alt="image" src="https://user-images.githubusercontent.com/7888486/183826060-fe158e61-13dd-4eb7-b11f-9fc32ce9dde3.png">

See [forum](https://forum.cuba-platform.com/t/embedding-image-in-excel-template-bands-for-reporting/16457)

**Comment by gorbunkov** [comment]
We also need to fix this in YARG

**Comment by konyashkina** [comment]
Tested on
Jmix version: 2.4.999-SNAPSHOT
Jmix Studio plugin version: 2.4.SNAPSHOT6826-242
IntelliJ version: IntelliJ IDEA 2024.2.1
