### ISSUE TITLE
Cannot use two or more JPQL conditions with join in filter

### ISSUE THREAD

**Issue by tychkov** [jmix-framework/jmix#930]
Hi, guys! I tried to creat two JPQL conditions with joins in filter. But in result query I see only one join (first).
```sql
select   e
from
  TestEntity e
  join e.ref1 br
where
  and (
      lower (br.name) like: StringpNhZyxGH
      or lower (sup.name) like: StringbDBtINcP
  )
order by
  e.id asc
```
As WA, we can collect and put joins into one JPQL condition (ex: join User umod on umod.username = e.lastModifiedBy join User ucrt on ucrt.username = e.createdBy). In this case - that's working, but it's necessary to be careful. :)

found in  **JMIX v.1.2.4**

**Comment by dtaimanov** [comment]
Hello @tychkov !
I've tested this case on JMIX v.1.2.4, 1.5.4 and 2.1: the only way to reproduce it that I've found is to remove `join` or `left join` keyword from join clause, which contradicts with field help and [documentation](https://docs.jmix.io/jmix/flow-ui/vc/components/genericFilter.html#jpql-conditions):

>Join — specifies an optional join clause to be included to the from clause of the data loader. This can be used to create a conditions based on an attribute of a related collection.
>
>When writing this clause:
>
>   * Start with join or left join keywords.

If this issue occurs during another circumstances, please provide minimal, reproducible example.
