### ISSUE TITLE
Decide what java type to use for audit fields

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#935]
Currently audit fields added by Studio (lastModifiedDate and createdDate) have `java.util.Date` type. 

Two concerns about that:

1. The `java.util.Date` is a legacy datatype and it's not a good that we force users to use it.
2. We should decide do we need to store the timezone value for audit fields. From one point of view we should because in this case we can always get the exact point in time when the instance was created or modified. From another point of view we may consider these fields as service dates that are always stored in server timezone. In any case we should mention it somewhere in the documentation, because developer may use these fields not properly.

**Comment by Gavrilov-Ivan** [comment]
For now the most appropriate type for date-audit fields supported by EclipseLink is OffsetDateTime.

**Comment by Gavrilov-Ivan** [comment]
https://youtrack.haulmont.com/issue/JST-3828/Change-default-datatype-for-audit-fields
