### ISSUE TITLE
Day of week name cannot be localized in business calendar editor

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#936]
Jmix version: 1.3.1

Create new project with business calendars add-on
Add any translation
Open the business calendar editor

AR: day of week names are not translated.

![Screenshot 2022-08-12 at 14 45 00](https://user-images.githubusercontent.com/7888486/184339262-620229df-b450-4950-b278-fb820789e318.png)

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4604-222
IntelliJ version: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
