### ISSUE TITLE
Duplicates mails after synchronization from mail.yandex

### ISSUE THREAD

**Issue by MaxKatyshev** [jmix-framework/jmix#939]
_Jmix version: 1.3.2
Jmix Studio plugin version: 1.4.SNAPSHOT4513-213
IntelliJ version: IntelliJ IDEA 2022.2 (Community Edition)
IMAP v 1.5.2_

**Steps:**

   1. Create project and add IMAP-addon
   2. Add IMAP configuration with map.yandex.ru host
   3. Check emails in IMAP message browser

**AR:**
<img width="1171" alt="Снимок экрана 2022-08-14 в 18 13 48" src="https://user-images.githubusercontent.com/11402689/184590540-4c5f7ad4-faeb-4cf5-88b1-c56b65f6c944.png">

**Comment by GurSergey** [comment]
This problem is also reproduced with outlook mail

**Comment by GurSergey** [comment]
the problem occurs with any imap server with a large number of emails that need to be synchronized. This is probably due to multiple threads being started at some point. Need to do a deeper analysis of the problem
