### ISSUE TITLE
Upload component

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#945]
https://vaadin.com/docs/latest/components/upload

### Changes
Added two new components:
- `FileStorageUploadField`
- `FileUploadField`

----
### FileStorageUploadField

FileStorageUploadField - is a field for working with `FileRef` datatype and placing files to `FileStorage`.

#### Simple example
```
<fileStorageUploadField id="fileStorageUploadField"
                        dataContainer="fileEntityDc"
                        property="fileRef"/>
```
By default it looks like a button:
![image](https://user-images.githubusercontent.com/22093943/213411179-a7a569ba-9de7-414d-ab38-9a3cdb9e68da.png)

#### XML

1) Common attributes:
- `uploadText` - Sets text to upload button.
![image](https://user-images.githubusercontent.com/22093943/213412090-10410e3e-8e5e-4f76-b336-759a68b4ed04.png)

- `uploadIcon` - icon in the upload button
![image](https://user-images.githubusercontent.com/22093943/213416986-2f76ac14-4e91-48c3-9f10-a18fbe36e4d8.png)

- `fileNameVisible` - whether file name should displayed after the upload button.

  Without uploaded file:
  ![image](https://user-images.githubusercontent.com/22093943/213413137-4f886e04-083f-427e-9fc4-560b79ad05ba.png)
  With uploaded file
  ![image](https://user-images.githubusercontent.com/22093943/213413543-038cc2a8-2881-4b4a-bac6-ff2ef04160d4.png)

- `fileNotSelectedText` - Text that is shown when `fileNameVisible="true"` and file is not uploaded.

  Example for `fileNotSelectedText="No file uploaded"`
  ![image](https://user-images.githubusercontent.com/22093943/213414481-63184b91-6b4a-4627-ac41-45214a2b6029.png)

- `maxFileSize` - sets the maximum file size in bytes. It is a client-side constraint which will be checked before sending the request. Note (from JavaDocs), if `MultipartProperties` is available, the default value will be set from `MultipartProperties#getMaxFileSize()` that is equal to 1Mb. To increase maximum file size for all fields in the application use `MultipartProperties#getMaxFileSize()` property.

- `fileTooBigText` - Text of exception when file size exceeds value in `maxFileSize` attribute.
![image](https://user-images.githubusercontent.com/22093943/213416693-6abb11b8-cdb9-42f2-a1b8-d3c808ce6fab.png)

- `acceptedFileTypes` - sets accepted file in the system choose file dialog. For instance: `acceptedFileTypes=".png, .jpg, .jpeg"`
- `incorrectFileTypeText` - sets the text if file extension is not included to `acceptedFileTypes` attribute.

- `dropAllowed` - enable/disable drag and drop file to upload button. The default value is `true`.
![image](https://user-images.githubusercontent.com/22093943/213419756-395e8d98-7a30-4b6d-af71-a8eb0dfdcc4a.png)

- `uploadDialogTitle` - the title of upload dialog that is shown while uploading file.
- `uploadDialogCancelText` - text of cancel button in the upload dialog.

   ![image](https://user-images.githubusercontent.com/22093943/213420790-fed725eb-d0e6-462f-ae44-9ae6908476a3.png)

- `processingStatusText` - text of status in the upload dialog when file is uploaded and is processed. 
- `connectingStatusText` - text of status in the upload dialog when connection is set. 
- `remainingTimeText` - text in the upload dialog when it shows remaining time.
- `remainingTimeUnknownText` - text in the upload dialog when it cannot calculate remaining time.
- `clearButtonAriaLabel` - aria-label for clear button.
- `clearButtonVisible` - whether clear button should be shown after the file name. Works only if `fileNameVisible="true"`.
![image](https://user-images.githubusercontent.com/22093943/213422708-ac0694f5-252d-4c5b-b89e-63499eb1bb14.png)

2. Specific for `FileStorageUploadField`
- `fileStorageName` - sets file storage name where to place uploaded files.
- `fileStoragePutMode` - put mode: `MANUAL`, `IMMEDIATE`.

#### Common field events
- `addFileUploadStartedListener`
- `addFileUploadFinishedListener`
- `addFileUploadSucceededListener`
- `addFileUploadProgressListener`
- `addFileUploadFileRejectedListener`
- `addValueChangeListener`

#### Java examples

1. Upload file in MANUAL mode.
```
@ViewComponent
private FileStorageUploadField manuallyFileStorageUploadField;
@Autowired
private TemporaryStorage temporaryStorage;

manuallyControlledField.addFileUploadSucceededListener(event -> {
           FileTemporaryStorageBuffer receiver = succeededEvent.getReceiver();
           File file = receiver.getFileData().getFileInfo().getFile();
           if (file != null) {
               notifications.create("File is uploaded to temporary storage at " + file.getAbsolutePath())
                       .show();
           }
 
           FileRef fileRef = temporaryStorage.putFileIntoStorage(receiver.getFileData().getFileInfo().getId(), event.getFileName());

           // set value to field as it won't be updated
           manuallyControlledField.setValue(fileRef);
 
           notifications.create("Uploaded file: " + event.getFileName())
                   .show();
       });
```
2. Override showing notification for `maxFileSize` and `acceptedFileTypes`. To override default behavior just add listener for `FileUploadFileRejectedEvent`.

```
@ViewComponent
private FileStorageUploadField maxFileSizeFileStorageUploadField;

maxFileSizeFileStorageUploadField.addFileUploadFileRejectedListener(event -> {
    notifications.show("Custom File rejected: " + event.getErrorMessage());
});
```

### FileUploadField

FileUploadField- is a field for working with `byte[]` datatype to store files in memory.

#### Simple example
```
<fileUploadField id="uploadField"
                 dataContainer="fileEntityDc"
                 property="fileByte"/>
```
Looks the same as `FileStorageUploadField`.

#### XML
1. Common attributes see above in `FileStorageUploadField -> XML -> Common attributes`.
2. Specific for `FileUploadField`:
- `fileName` - the text that should be shown if value is set from data container. When user uploads file, the field shows the file name. However when value is saved to the database field loose information about the file name. The `fileName` attribute allows us to set custom text when no information about file name. If it is not defined the default value will be shown:
![image](https://user-images.githubusercontent.com/22093943/213426817-22ae87cb-16af-444b-8d3e-a953988b88ce.png)

#### Java API
The same as for `FileStorageUploadField` excluding example with put mode.

### Messages for fields:
```
fileStorageUploadField.fileNotSelected=File is not selected
fileStorageUploadField.upload.text=Upload
fileStorageUploadField.error.fileTooBig=File is too big
fileStorageUploadField.error.incorrectFileType=Incorrect file type
fileStorageUploadField.status.processing=Processing File...
fileStorageUploadField.status.connecting=Connecting...
fileStorageUploadField.remainingTime=remaining time:
fileStorageUploadField.remainingTime.unknown=unknown remaining time
fileStorageUploadField.uploadDialog.title=Uploading
fileStorageUploadField.uploadDialog.cancel.text=Cancel
fileStorageUploadField.uploadInternalError.notification.title=Uploading failed
fileStorageUploadField.uploadInternalError.notification.message=The error occurs while uploading '%s' file

fileUploadField.fileNotSelected=File is not selected
fileUploadField.upload.text=Upload
fileUploadField.error.fileTooBig=File is too big
fileUploadField.error.incorrectFileType=Incorrect file type
fileUploadField.status.processing=Processing File...
fileUploadField.status.connecting=Connecting...
fileUploadField.remainingTime=remaining time: 
fileUploadField.remainingTime.unknown=unknown remaining time
fileUploadField.uploadDialog.title=Uploading
fileUploadField.uploadDialog.cancel.text=Cancel
fileUploadField.noFileName=attachment (%s)
fileUploadField.uploadInternalError.notification.title=Uploading failed
fileUploadField.uploadInternalError.notification.message=The error occurs while uploading '%s' file
```

### QA
1. Check that XML attributes are applied for fields.
2. For FileStorageUploadField try example with MANUAL put mode.
3. Your cases.

**Comment by KremnevDmitry** [comment]
Visual bug detected:
![image](https://user-images.githubusercontent.com/75516667/219639014-4dde1808-5a5f-4b56-9b20-97f6873117c0.png)

_Reopened_

**Comment by Flaurite** [comment]
@rusiaikinat please, check case from @KremnevDmitry.
And in addition, check in the FormLayout that `FileUploadFIeld` on one line with another fields (e.g. TextField).

**Comment by rusiaikinat** [comment]
**env**
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4954-223
IntelliJ version: IntelliJ IDEA 2022.3.1 (Ultimate Edition)

bug is not reproduce

**env**
Jmix version: 1.5.0-RC1
bug is reproduce
