### ISSUE TITLE
Allow to remove required attributes for Entity Data Task

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#956]
For entity data task with "create" type required entity attributes are automatically added to the attributes table. These fields can't be removed. However there are cases when no value should be set for these fields, e.g. when values are filled in entity listener or `@PostConstruct` methods.

Remove actions should be enabled for any attribute:
![Screenshot 2022-08-17 at 14 51 12](https://user-images.githubusercontent.com/7888486/185101645-c4fadd9c-f86c-4046-9f5a-4fec4c2cb371.png)

**Comment by konyashkina** [comment]
Tested on 
Jmix version: 1.4.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4632-222
IntelliJ version: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
