### ISSUE TITLE
Change default format string for decimal datatype

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#967]
Currently it is `decimalFormat = #,##0.##`

It seems reasonable to change it to `decimalFormat = #,##0.00` in order to always display zeros in the fractional part.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.5.999-SNAPSHOT
Jmix Studio plugin version: 1.5.SNAPSHOT4937-223
IntelliJ version: IntelliJ IDEA 2022.3.2 (Ultimate Edition)
