### ISSUE TITLE
NPE when starting business process from process form

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#970]
NPE occurs if starting the process from the process form using the following command:

```java
        processFormContext.processStarting()
                .saveInjectedProcessVariables()
                .start();
```

See [forum](https://forum.jmix.io/t/bpm-start-process-npe-if-only-call-saveinjectedprocessvariables/1835)

**Comment by MaxKatyshev** [comment]
1.3.999-SNAPSHOT - verified
