### ISSUE TITLE
Source Code Editor component

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#972]
TODO: #1678 

TODO: Support focus-ring

**Comment by KremnevDmitry** [comment]
Consider implementing `com.vaadin.flow.component.textfield.HasPrefixAndSuffix`.

**Comment by m-shambarova** [comment]
Tested on:
Jmix version: 2.0.999-SNAPSHOT
Jmix Studio plugin version: 2.0.SNAPSHOT5243-231
IntelliJ version: IntelliJ IDEA 2023.1 (Ultimate Edition)
