### ISSUE TITLE
Add insertBefore administration to menu in Flow UI project template

### ISSUE THREAD

**Issue by Flaurite** [jmix-framework/jmix#978]
### Description
After added security, need to configure default position of `Application` menu.

Add:
```
<menu id="application" ... insertBefore="administration">
   ...
</menu>
```

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.4.SNAPSHOT4604-222
IntelliJ version: IntelliJ IDEA 2022.2.1 (Ultimate Edition)
