### ISSUE TITLE
Notifications indicator is not updated when a new message is sent to the current user

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#982]
Jmix version: 1.3.2

1. Create a project with Notifications add-on
1. Add notificationsIndicator component to the main screen as descried in the [documentation](https://docs.jmix.io/jmix/notifications/configuration.html#in-app-channel)
3. Create tow users, e.g. bob and alice
4. Login with both users in different browsers
5. Using the _Administration - Notifications_ screen send a new notification from alice to bob

ER:
Notifications counter at bob's screen will be increased

AR:
Notifications counter is the same

<img width="268" alt="Screenshot 2022-08-30 at 08 44 52" src="https://user-images.githubusercontent.com/7888486/187351198-5b4d272a-ef40-4365-823e-6649356cf2b4.png">

See [forum topic](https://forum.jmix.io/t/premium-notifications-add-on-a-few-questions/1861)

**Comment by Afanasevaa36** [comment]
Jmix version: 1.3.999-SNAPSHOT - Verified
