### ISSUE TITLE
Anonymous screens with OIDC add-on

### ISSUE THREAD

**Issue by gorbunkov** [jmix-framework/jmix#983]
It's not clear how to make Jmix screen available anonymously when using OIDC add-on.

With OIDC all non-authenticated requests are forbidden. We cannot just enable it with Spring security by permitting access to the screen URL like mvcPattern("/#some-anonymous-screen"). The problem is in Jmix routing mechanism and the "hash" symbol. Requests to such URLs are not recognized by Spring.

**Comment by adhawan325** [comment]
@gorbunkov - any thoughts on how we can have this prioritized by the Platform team?

**Comment by gorbunkov** [comment]
@adhawan325 We don't see any clear solution for this. It seems that this issue is not relevant for Vaadin Flow UI, and we don't have plans to fix it for Classic UI.
