### ISSUE TITLE
Inline icon overlaps field value for comboBox, entityPicker

### ISSUE THREAD

**Issue by lovtsovaik** [jmix-framework/jmix#984]
see #974

**Preconditions**

- Create an entity with strung, enum, many-to-one association
- Create screens
- In editor, add the icon and stylename attributes to all fields in form
  `icon="CHECK_CIRCLE" stylename="inline-icon"`

![image](https://user-images.githubusercontent.com/73226373/187678176-f824a4e9-66d2-41ea-888c-8ddabfb8457c.png)

**Steps**

- Run the app
- Start creating an instance of new entity
- Fill all fields

AR: Inline icon overlaps field value for comboBox, entityPicker
![image](https://user-images.githubusercontent.com/73226373/187677665-950c2336-1b83-45c2-90b8-560cc6dc7a65.png)

### QA
Check in Form and in VBox (or in HBox). Also apply general theme sizes: "small", "large". Pay attention, there is a ticket about self field styles: https://github.com/jmix-framework/jmix/issues/1163.
Test the following fields:
- [ ] ComboBox
- [ ] EntityComboBox
- [ ] EntityPicker
- [ ] ValuePicker
- [ ] ValuesPicker
- [ ] SuggestionField
- [ ] EntitySuggestionField
- [ ] TagField
- [ ] TimeField
- [ ] DateField

**Comment by lovtsovaik** [comment]
The same for date field, and maybe many else

**Comment by rusiaikinat** [comment]
**Reopened**

env
Google Chrome 107.0.5304.107
Yandex 22.9.5.710 (64-bit)
win10

Theme (Hallo, hover):
`<vbox/>` or `<hbox/>`  TagField, suggestionField - the cursor is behind the icon

![image](https://user-images.githubusercontent.com/114649487/201892825-7d7480a4-21f6-490d-beb2-4c26f47f1526.png)

`<form/>` (horizontal view) - dateField, timeField - different arrangement of elements
![image](https://user-images.githubusercontent.com/114649487/201895163-819d42d5-9ce6-4065-aae8-91477777f610.png)
