### ISSUE TITLE
View annotations renaming

### ISSUE THREAD

**Issue by glebfox** [jmix-framework/jmix#988]
* `@UiController` - `@ViewController`
* `@UiDescriptor` - `@ViewDescriptor`
* `@ComponentId` - `@ViewComponent`

---

`DataContext` must be injected with `@ViewComponent`. Need support from `UiContrellerDependencyInjector`.

**Comment by KremnevDmitry** [comment]
Related to Studio issue: https://youtrack.haulmont.com/issue/JST-3207

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4631-213
IntelliJ version: IntelliJ IDEA 2021.3.3 (Community Edition)
